### ISSUE TITLE
osgearth_pick: not work on win64 and MacOSX

### ISSUE THREAD

**Issue by remoe** [gwaldron/osgearth#1000]
tested with Windows: feature_draped_polygons.earth

https://github.com/gwaldron/osgearth/commit/4a1bc4827d980a0a7e7212e47a93ff96c0a87a31

![image](https://user-images.githubusercontent.com/804941/32672722-72e4d130-c64c-11e7-83b8-f0f74ab624b5.png)

on MacOSX:

https://github.com/gwaldron/osgearth/commit/fb3953a5743aefb643cba3bfd101d9b88d9b8c83

**Comment by gwaldron** [comment]
Fixed

**Comment by remoe** [comment]
Confirmed: Tested with Windows.

https://github.com/gwaldron/osgearth/commit/955cdb6e093758d89e22efc1eeefda4147afd793 solves the issue.
