### ISSUE TITLE
MGRS graticule sample defect

### ISSUE THREAD

**Issue by beachwalker** [gwaldron/osgearth#1006]
![image](https://user-images.githubusercontent.com/2715897/32898905-be4ed41c-cae9-11e7-9f91-2cc8e25f21a1.png)

... picture speaks for itself.

**Comment by gwaldron** [comment]
What are your configuration details?
osgearth_version --caps

**Comment by beachwalker** [comment]
osgEarth Library 2.9.0 DEVELOPMENT

[osgEarth]  [Capabilities] osgEarth Version: 2.9.0 DEVELOPMENT
[osgEarth]  [Capabilities] Detected hardware capabilities:
[osgEarth]  [Capabilities]   Vendor = NVIDIA Corporation
[osgEarth]  [Capabilities]   Renderer = GeForce GTX 770/PCIe/SSE2
[osgEarth]  [Capabilities]   Version = 4.5.0 NVIDIA 364.72
[osgEarth]  [Capabilities]   Max GPU texture units = 32
[osgEarth]  [Capabilities]   Max GPU texture coord indices = 8
[osgEarth]  [Capabilities]   Max GPU attributes = 16
[osgEarth]  [Capabilities]   Depth buffer bits = 24
[osgEarth]  [Capabilities]   Max texture size = 16384
[osgEarth]  [Capabilities]   Max lights = 8
[osgEarth]  [Capabilities]   GLSL = yes
[osgEarth]  [Capabilities]   GLSL Version = 450
[osgEarth]  [Capabilities]   Texture arrays = yes
[osgEarth]  [Capabilities]   3D textures = yes
[osgEarth]  [Capabilities]   Multitexturing = yes
[osgEarth]  [Capabilities]   draw instanced = yes
[osgEarth]  [Capabilities]   uniform buffer objects = yes
[osgEarth]  [Capabilities]   NPOT textures = yes
[osgEarth]  [Capabilities]   Texture buffers = yes
[osgEarth]  [Capabilities]   Texture buffer max size = 134217728
[osgEarth]  [Capabilities]   Transform feedback = yes
[osgEarth]  [Capabilities]   Compression = ARB S3 RG

**Comment by gwaldron** [comment]
I am unable to reproduce on osgEarth master branch.
