### ISSUE TITLE
Build failure with master, 20/11/2017

### ISSUE THREAD

**Issue by openscenegraph** [gwaldron/osgearth#1008]
I have just checked out osgearth master and attempted to run cmake but get a build error.  Looking at travis the build has been broken for the last five days:

    https://travis-ci.org/gwaldron/osgearth/builds

osgearth$ cmake .
-- Could not find ROCKSDB
-- Plugins will be installed under osgPlugins-3.5.9 directory.
CMake Error at src/osgEarthDrivers/CMakeLists.txt:40 (ADD_SUBDIRECTORY):
  The source directory

    /home/robert/3rdParty/osgearth/src/osgEarthDrivers/CMakeFiles

  does not contain a CMakeLists.txt file.

**Comment by gwaldron** [comment]
Thanks. I pushed a fix to repair a problem with in-source builds, so please retry with the latest.

Travis is busted for a different reason however -- still in the queue to fix that.
