### ISSUE TITLE
thread safety: use osgDB::readRef*File() in place of osgDB::read*File

### ISSUE THREAD

**Issue by filnet** [gwaldron/osgearth#1012]
See https://github.com/openscenegraph/OpenSceneGraph/commit/dd996a328979614d7c6b5778b2e4f9c8af37ecfd

That fix is in OSG since 3.5.1 and osgEarth was never adapted to do something similar.

I think it explains why I am seeing bursts of file not found errors when using the mp engine.

I did a quick grep and found ~70 problematic uses of osgDB::read*File()
But only a few are in core osgEarth files. I'll try to submit a PR for those.

Questions:
- I guess it is not acceptable to switch to using osgDB::readRef*File as this would make it mandatory to use osg 3.5.1 or up ?
- What would be an acceptable way to make it conditional ?

**Comment by filnet** [comment]
Here are some related changes: https://github.com/filnet/osgearth/commit/98bb8820c2f16e68e093188b763443ee401edd71

The changes are not conditional but should give you an idea of what we are talking about: https://github.com/filnet/osgearth/commit/98bb8820c2f16e68e093188b763443ee401edd71

**Comment by gwaldron** [comment]
Can you expound on why you think this is causing errors? Are you getting missing tiles, or just annoying console messages?

In any case, it does seem that moving to the new method will be the way to do. I think a polyfill approach is most sensible for retaining compatibility with 3.4. For example, we can replace instances of osgDB::readNodeFile with osgEarth::readNodeFile(), which is turn will include the appropriate "ifdefs".

**Comment by filnet** [comment]
I did not verify if the ref issue is causing the messages.
My approach is to fix the ref issue and see if the file not found goes away. The file not found is random and relatively rare (might happen more or less when under the debugger or not).

I did observe, a couple of times, missing tiles that formed a strange and interesting patterns.

My theory at this stage is that some cache thinks a tile was written to the file system but it was not because of some reason (a badly timed cancel triggering the ref issue ?). Later the cache goes to the file system and does not find it.
The osgDB::read call in  src/osgEarthDrivers/engine_mp/TilePagedLOD.cpp is a prime suspect.

I will try the polyfill approach.

**Comment by filnet** [comment]
Did some more research. The introduction of readRef*File() methods dates back to osg 2.3.0.
See https://github.com/openscenegraph/OpenSceneGraph/commit/256391c3b40ef800f9b53ab97cf6b1fd1a79a495#diff-6d9c36a0099655387baccbe27d87f22e

The commit mentioned (https://github.com/openscenegraph/OpenSceneGraph/commit/dd996a328979614d7c6b5778b2e4f9c8af37ecfd) in the first message is an improvement on this.
It allows to turn compilation of deprecated read*File() methods and adds a few convenience methods.
That commit is also in osg 3.4.0. See https://github.com/openscenegraph/OpenSceneGraph/commit/6a67be2e3254c5cc37e62770ffc0cd88f0cf83b7#diff-6d9c36a0099655387baccbe27d87f22e.

**Comment by gwaldron** [comment]
Thank for your research. Who knew? I'll put this on the 2.9 milestone list. There are bound to be additional changes (beyond just replacing the function) since the receiving return variables will need to be changed as well. 

Thanks for your offer to make the change -- however, I think we will do this internally so can also deal with the receiving result variable changes at the same time.

**Comment by filnet** [comment]
Ok. I have made some progress on my side. Will push it so you can have a look.

**Comment by gwaldron** [comment]
OK.
By the way, I just tried to build OSG 3.4.1 with OSG_PROVIDE_READFILE=OFF, and some of the projects fail..

**Comment by filnet** [comment]
Yes. Robert and I fixed the visible ones in 3.5.9 : https://github.com/openscenegraph/OpenSceneGraph/issues/386

You don't need to have osg compiled with this option unless you want to make sure you did not miss some osdDB:read*File() calls.

**Comment by filnet** [comment]
Code changes are done.

osgEarth will now use the "new" osgDB::readRef*File() methods if compiled against osg 3.4.0 and up.

osgEarth does not include osgDB::ReadFile anymore (except in osgEarth/Utils).

**Comment by gwaldron** [comment]
Thanks. I feel a little bad though -- my polyfill suggestion came before you discovered that the osgRef*File methods dated back to OSG 2.3. The current version of osgEarth requires OSG 3.4+ anyway, which means that we can probably use the readRef*File method without polyfill. Do you agree?

**Comment by filnet** [comment]
Don't feel bad... the polyfill part (in osgEarth/Utils) was little work. Most of the effort was to find and fix all the osgDB::read*() calls.

But note that removing the polyfill will change all the nice and short readObjectFile() calls to osgDB::readRefObjectFile(). I'll do whatever you feel is correct. Your call...

And the readFile() case remain opens. This method was introduced in osg 3.5.1.

Options are:
- keep polyfill as is
- simplify it to handle only osg 3.4.0+ (to keep the shorter name)
- keep it only for readFile()

What is your opinion about the location of polyfills (if they are kept and/or for readFile()).
Should they stay in osgEarth/Utils or be moved to a new osgEarth/ReadFile ?

**Comment by gwaldron** [comment]
Since osgEarth doesn't use the new osgDB::readFile template anyway, I suggest we just replace all the read*() calls with readRef*(), handle the return types properly, and do away with the polyfill.

**Comment by filnet** [comment]
I have edited my last message above. Please read the PS and PPS...

I'll drop the polyfill. Not a problem...

But readFile() is a special case that we need to discuss further.
It is used in a few places osg and has value.

Something that would be written like this:

```
osg::ref_ptr<osg::Object> object = osgDB::readRefObjectFile( driverExt, dbopt.get() );
osg::ref_ptr<TileSource> source = dynamic_cast<T*>(object.get());
```
Can be written like this with readRef():

```
osg::ref_ptr<TileSource> source = osgDB::readRefFile<TileSource>( driverExt, dbopt.get() );
```

Or like this with the polyfill/alias file:

```
osg::ref_ptr<TileSource> source = readFile<TileSource>( driverExt, dbopt.get() );
```

**Comment by filnet** [comment]
Ok. Here is what I suggest:

Do away with polyfill and readFile and target only the core files (and not the applications).
This will make it much easier to review and approve for 2.9.

And then we can reconsider introducing an alias header file (with readFile) for 2.10.

**Comment by gwaldron** [comment]
Works for me. Thanks.

**Comment by filnet** [comment]
New PR (https://github.com/gwaldron/osgearth/pull/1016) compiles fine with osg 3.4.0 and osg 3.5.9.

Will try to test is as much as possible with osg 3.5.9.

**Comment by gwaldron** [comment]
Thanks Phillipe. I merged your PR; I will do a bit of cleanup (to support implicit ref_ptr = off, for example) and then we can put this to rest.

**Comment by filnet** [comment]
Great! Note that all osgEarth calls to osgDB::Read*File() have been changed to osgDB::ReadRef*File() to the exceptions of:
- applications/**
- osgUtils/ExampleResources.cpp where there is a single call to 

In osgUtils/ExampleResources.cpp there is a single call to osgDB::readNodeFiles().
There is no osgDB::readRefNodeFiles() in osg 3.4.0 (only appeared in osg 3.5.1).
I should have put a #ifdef to call osgDB::readRefNodeFiles() if osg >= 3.5.1 but forgot to.

**Comment by emminizer** [comment]
I am building 3.4.1 now and I see osgDB::readRefNodeFiles() defined in osgDB/ReadFile.  It was not in 3.4.0.

**Comment by gwaldron** [comment]
Correct; it was backported to the 3.4 branch, but it's not in 3.4.0.
