### ISSUE TITLE
Load openstreetmap.earth leads memory leaks

### ISSUE THREAD

**Issue by tnt2pro** [gwaldron/osgearth#1015]
I write a MFC application to load openstreetmap.earth. After i close the application, the vs2015 output window shows there are memory leaks.

```
Detected memory leaks!
Dumping objects ->
{294608} normal block at 0x000000000785FD80, 16 bytes long.
Data: <                > 90 FC 85 07 00 00 00 00 00 00 00 00 00 00 00 00 
{294607} normal block at 0x000000000785FC90, 9 bytes long.
Data: <Pragma:  > 50 72 61 67 6D 61 3A 20 00 
{292519} normal block at 0x0000000007861590, 16 bytes long.
Data: <@               > 40 15 86 07 00 00 00 00 00 00 00 00 00 00 00 00 
{292518} normal block at 0x0000000007861540, 9 bytes long.
......
```
 I delete this line **## osg::ref_ptr\<osg::Node\> m_Model = osgDB::readNodeFile("openstreetmap.earth");**, there is no memory leak any more. I replace the openstreetmap.earth with cow.osg, there is no memory leak either. 

The version of OSGEarth is 2.8, OSG is 3.4.0

Here is source code :http://bbs.osgchina.org/forum.php?mod=attachment&aid=NzIwNnwzZWYxZDIyZjlhOGY1MWFjZjhiNGFiMWYwMTc5YmJlNXwxNTEyMzc5ODE2&request=yes&_f=.zip

**Comment by gwaldron** [comment]
Not enough information to investigate

**Comment by tnt2pro** [comment]
@gwaldron
 Here is source code :http://bbs.osgchina.org/forum.php?mod=attachment&aid=NzIwNnwzZWYxZDIyZjlhOGY1MWFjZjhiNGFiMWYwMTc5YmJlNXwxNTEyMzc5ODE2&request=yes&_f=.zip

**Comment by BrainyBeeLy** [comment]
mfc Application, I have the same mistake. load model and close the Application, window shows the information that memory leaks. How do you solve it? thanks.

**Comment by BrainyBeeLy** [comment]
@tnt2pro mfc Application, I have the same mistake. load model and close the Application, window shows the information that memory leaks. How do you solve it? thanks.
