### ISSUE TITLE
In case of paged feature source the contigous croped polygons lets a empty gap

### ISSUE THREAD

**Issue by JD31** [gwaldron/osgearth#1030]
To reproduce add in the earth feature_draped_polygons.earth

        <layout tile_size="500000" crop_features="true" paged="true">
            <level max_range="1e10"/>
        </layout>

on the Countries feature_model.

When looking at the east russia for example, we can see that there is a gap between polygons that should be perfectly contigous:

![image](https://user-images.githubusercontent.com/17981960/34871213-0f702ace-f78d-11e7-8cb0-4cb4b67739ac.png)

Note that if changing the max_polygon_tiling_angle to 45, the problem becomes more important:

![image](https://user-images.githubusercontent.com/17981960/34871528-4bd86ebc-f78e-11e7-9f36-2a5b9e332896.png)

**Comment by remoe** [comment]
which version of osgearth do you use?

**Comment by JD31** [comment]
Master 2 weeks ago
