### ISSUE TITLE
Can't use CMake create project of osgearth!!!

### ISSUE THREAD

**Issue by wangxiya** [gwaldron/osgearth#1033]
I use cmake 3.10.x create osgearth project, it has error------- 

CheckIncludeFile.c

C:\Work\C\osgEarth\Build-2013\CMakeFiles\CMakeTmp\CheckIncludeFile.c(1): fatal error C1083: can't open file: “pthread.h”: No such file or directory [C:\Work\C\osgEarth\Build-2013\CMakeFiles\CMakeTmp\cmTC_676d0.vcxproj]

What shall I do?

**Comment by jasonbeverage** [comment]
It's hard to say without some more information.  What platform are you
building on?

**Comment by wangxiya** [comment]
win10 pro, VS2013 SP5,
I download openthreads package, and copy pthread include file to vc\include, copy pthreadvc2.lib to vc\lib, then rename pthreadvc2.lib to pthread.lib, but I use cmake create osgearth project, the command 
Link:
  C:\Program Files (x86)\Microsoft Visual Studio 12.0\VC\bin\link.exe /ERRORREPORT:QUEUE /OUT:"C:\Work\C\osgEarth\Build-2013\CMakeFiles\CMakeTmp\Debug\cmTC_96503.exe" /INCREMENTAL /NOLOGO kernel32.lib user32.lib gdi32.lib winspool.lib shell32.lib ole32.lib oleaut32.lib uuid.lib comdlg32.lib advapi32.lib /MANIFEST /MANIFESTUAC:"level='asInvoker' uiAccess='false'" /manifest:embed /DEBUG /PDB:"C:/Work/C/osgEarth/Build-2013/CMakeFiles/CMakeTmp/Debug/cmTC_96503.pdb" /SUBSYSTEM:CONSOLE /TLBID:1 /DYNAMICBASE /NXCOMPAT /IMPLIB:"C:/Work/C/osgEarth/Build-2013/CMakeFiles/CMakeTmp/Debug/cmTC_96503.lib" /MACHINE:X86 /SAFESEH  /machine:X86 cmTC_96503.dir\Debug\CheckSymbolExists.obj

CheckSymbolExists.obj : error LNK2019: 无法解析的外部符号 __imp__pthread_create，该符号在函数 _main 中被引用 [C:\Work\C\osgEarth\Build-2013\CMakeFiles\CMakeTmp\cmTC_96503.vcxproj]

C:\Work\C\osgEarth\Build-2013\CMakeFiles\CMakeTmp\Debug\cmTC_96503.exe : fatal error LNK1120: 1 个无法解析的外部命令 [C:\Work\C\osgEarth\Build-2013\CMakeFiles\CMakeTmp\cmTC_96503.vcxproj]

已完成生成项目“C:\Work\C\osgEarth\Build-2013\CMakeFiles\CMakeTmp\cmTC_96503.vcxproj”(默认目标)的操作 - 失败。

生成失败。

it seems the link.exe lost pthreads.lib, but I don't know where I can write the code!
Someone can help me?

**Comment by jasonbeverage** [comment]
So definitely don't "download openthreads package".  OpenThreads is part of
OpenSceneGraph, so make sure you have it built properly first before you
try to build osgEarth.

**Comment by wangxiya** [comment]
The Error what I say, was happened on CMake configure the source code, not generate the project. so it's long way to build osgearth.
Now , I can't see the sln of visualstudio.

**Comment by wangxiya** [comment]
I create a new virtual machine, install win7 x64, and visual studio 2013, and osgearth 2.9 rc1, and cmake 3.10.2, I use cmake link source of osgearth, and configure, the error above also appear!
Someone have an answer?
thanks a lot!

**Comment by wangxiya** [comment]
cmake information : 

CMake Deprecation Warning at CMakeLists.txt:10 (cmake_policy):
  The OLD behavior for policy CMP0005 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.


The C compiler identification is MSVC 18.0.40629.0
The CXX compiler identification is MSVC 18.0.40629.0
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/bin/cl.exe
Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/bin/cl.exe -- works
Detecting C compiler ABI info
Detecting C compiler ABI info - done
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/bin/cl.exe
Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio 12.0/VC/bin/cl.exe -- works
Detecting CXX compiler ABI info
Detecting CXX compiler ABI info - done
Detecting CXX compile features
Detecting CXX compile features - done
Looking for pthread.h
Looking for pthread.h - not found
Found Threads: TRUE  
Found OpenGL: opengl32   
Could NOT find ZLIB (missing: ZLIB_LIBRARY ZLIB_INCLUDE_DIR) 
Could not find ROCKSDB
Could NOT find Protobuf (missing: Protobuf_LIBRARIES Protobuf_INCLUDE_DIR) 
Set GLCORE_ROOT as the parent of the directory containing the OpenGL core profile header. (missing: GLCORE_INCLUDE_DIR) 
Could NOT find Protobuf (missing: Protobuf_LIBRARIES Protobuf_INCLUDE_DIR) 
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
CURL_INCLUDE_DIR
   used as include directory in directory C:/Work/C/osgEarth/osgearth/src/osgEarth
   used as include directory in directory C:/Work/C/osgEarth/osgearth/src/osgEarth
   used as include directory in directory C:/Work/C/osgEarth/osgearth/src/osgEarth
CURL_LIBRARY
    linked by target "osgEarth" in directory C:/Work/C/osgEarth/osgearth/src/osgEarth
GDAL_INCLUDE_DIR
   used as include directory in directory C:/Work/C/osgEarth/osgearth/src/osgEarth
   used as include directory in directory C:/Work/C/osgEarth/osgearth/src/osgEarth
   used as include directory in directory C:/Work/C/osgEarth/osgearth/src/osgEarth
   used as include directory in directory C:/Work/C/osgEarth/osgearth/src/osgEarthAnnotation
   used as include directory in directory C:/Work/C/osgEarth/osgearth/src/osgEarthAnnotation
   used as include directory in directory C:/Work/C/osgEarth/osgearth/src/osgEarthAnnotation
   used as include directory in directory C:/Work/C/osgEarth/osgearth/src/osgEarthFeatures
   used as include directory in directory C:/Work/C/osgEarth/osgearth/src/osgEarthFeatures
   used as include directory in directory C:/Work/C/osgEarth/osgearth/src/osgEarthFeatures
   used as include directory in directory C:/Work/C/osgEarth/osgearth/src/osgEarthUtil
   used as include directory in directory C:/Work/C/osgEarth/osgearth/src/osgEarthUtil
   used as include directory in directory C:/Work/C/osgEarth/osgearth/src/osgEarthUtil
   used as include directory in directory C:/Work/C/osgEarth/osgearth/src/osgEarthDrivers/feature_ogr
   used as include directory in directory C:/Work/C/osgEarth/osgearth/src/osgEarthDrivers/feature_ogr
   used as include directory in directory C:/Work/C/osgEarth/osgearth/src/osgEarthDrivers/feature_ogr
   used as include directory in directory C:/Work/C/osgEarth/osgearth/src/osgEarthDrivers/feature_tfs
   used as include directory in directory C:/Work/C/osgEarth/osgearth/src/osgEarthDrivers/feature_tfs
   used as include directory in directory C:/Work/C/osgEarth/osgearth/src/osgEarthDrivers/feature_tfs
   used as include directory in directory C:/Work/C/osgEarth/osgearth/src/osgEarthDrivers/feature_wfs
   used as include directory in directory C:/Work/C/osgEarth/osgearth/src/osgEarthDrivers/feature_wfs
   used as include directory in directory C:/Work/C/osgEarth/osgearth/src/osgEarthDrivers/feature_wfs
   used as include directory in directory C:/Work/C/osgEarth/osgearth/src/osgEarthDrivers/feature_xyz
   used as include directory in directory C:/Work/C/osgEarth/osgearth/src/osgEarthDrivers/feature_xyz
   used as include directory in directory C:/Work/C/osgEarth/osgearth/src/osgEarthDrivers/feature_xyz
   used as include directory in directory C:/Work/C/osgEarth/osgearth/src/osgEarthDrivers/gdal
   used as include directory in directory C:/Work/C/osgEarth/osgearth/src/osgEarthDrivers/gdal
   used as include directory in directory C:/Work/C/osgEarth/osgearth/src/osgEarthDrivers/gdal
GDAL_LIBRARY
    linked by target "osgEarth" in directory C:/Work/C/osgEarth/osgearth/src/osgEarth
    linked by target "osgEarthAnnotation" in directory C:/Work/C/osgEarth/osgearth/src/osgEarthAnnotation
    linked by target "osgdb_osgearth_feature_ogr" in directory C:/Work/C/osgEarth/osgearth/src/osgEarthDrivers/feature_ogr
    linked by target "osgdb_osgearth_feature_tfs" in directory C:/Work/C/osgEarth/osgearth/src/osgEarthDrivers/feature_tfs
    linked by target "osgdb_osgearth_feature_wfs" in directory C:/Work/C/osgEarth/osgearth/src/osgEarthDrivers/feature_wfs
    linked by target "osgdb_osgearth_feature_xyz" in directory C:/Work/C/osgEarth/osgearth/src/osgEarthDrivers/feature_xyz
    linked by target "osgdb_osgearth_gdal" in directory C:/Work/C/osgEarth/osgearth/src/osgEarthDrivers/gdal
ZLIB_LIBRARY
    linked by target "osgEarth" in directory C:/Work/C/osgEarth/osgearth/src/osgEarth

Configuring incomplete, errors occurred!
See also "C:/Work/C/osgEarth/Build-2013/CMakeFiles/CMakeOutput.log".
See also "C:/Work/C/osgEarth/Build-2013/CMakeFiles/CMakeError.log".

**Comment by wangxiya** [comment]
@jasonbeverage 
Can you help me? thanks a lot!
I want learn osg and osgearth, but the question closed the doors on me！

**Comment by remoe** [comment]
@wangxiya
This issue is not a issue of osgEarth. Can you post such questions here http://forum.osgearth.org ?

Before you can build osgEarth you need to build OSG and all the dependencies of OSG and osgEarth. You find a lot of sites on web search engines:

http://www.openscenegraph.org/index.php/documentation/platform-specifics/windows/37-visual-studio
https://vicrucann.github.io/tutorials/osg-windows-quick-install/
https://github.com/OGStudio/openscenegraph-cross-platform-guide
or
http://forum.osgearth.org/Windows-Installation-td7500989.html#a7503026

And you need to learn something about CMake here:

https://cmake.org/cmake/help/v3.10/

For example, you need to understand how "find_package" works in CMake:
https://cmake.org/cmake/help/v3.10/command/find_package.html

or buy "Master CMake" Book: https://www.kitware.com/what-we-offer/#books

HTH

**Comment by wangxiya** [comment]
Sorry for everyone！My mistake！When I see the error, I think it in the makefile. 
In fact, the error try to tell me which options should to setup, when I fill the options, the error disappear!
thanks a lot！
@remoe @jasonbeverage
