### ISSUE TITLE
No array dispatchers defined for the multipass coords for MPGeometry

### ISSUE THREAD

**Issue by flocou** [gwaldron/osgearth#1039]
MPGeometry::createVertexArrayState method try to override non-virtual method defined in Drawable.
Since this method is never called, application crash when trying to access undefined dispatchers for multipass coords.

You just have to rename it to createVertexArrayStateImplementation for this code being reachable.

https://github.com/gwaldron/osgearth/blob/129b64a864a12b540cd817729101b44bc62e0141/src/osgEarthDrivers/engine_mp/MPGeometry.cpp#L569

**Comment by jasonbeverage** [comment]
What version of OpenSceneGraph are you using?

**Comment by flocou** [comment]
osg 3.5.9

**Comment by flocou** [comment]
In osg 3.5.9, createVertexArrayState method has been refactored to a non-virtual one. And implementation may call createVertexArrayStateImplementation which are virtual...
