### ISSUE TITLE
rex terrain engine doesn't work on MacOSX

### ISSUE THREAD

**Issue by remoe** [gwaldron/osgearth#1052]
I try to run osgearth_features.cpp sample on MacOSX. I don't see the images of world.tif on globe. But when i change the code to:

```c++
    osgEarth::Drivers::MPTerrainEngine::MPTerrainEngineOptions mp;

    MapNodeOptions mapNodeOptions;
    mapNodeOptions.enableLighting() = false;
    mapNodeOptions.setTerrainOptions(mp);
 ```

it works.

**Comment by filnet** [comment]
Could be related to https://github.com/gwaldron/osgearth/issues/853

**Comment by remoe** [comment]
I don't know why, but it doesn't call setMap here:

```c++
    _terrainEngine = TerrainEngineNodeFactory::create( terrainOptions );
    _terrainEngineInitialized = false;

    if ( _terrainEngine )
    {
       // HERE!
        _terrainEngine->setMap( _map.get(), terrainOptions );
    }
```

**Comment by remoe** [comment]
No, it's not related. I see the sky (not black), but no terrain texture.

**Comment by emminizer** [comment]
Agreed.  We're seeing the same problem with core profile on Windows.  Seeing sky, but no stars, and no terrain.  Turning on MP shows the terrain.  Also not related to #853 -- I did test the changes to TileRasterizer and it had no impact in our case.

**Comment by remoe** [comment]
@gwaldron 
Don't work with latest changes on MacOSX with readymap-rex.earth: https://github.com/gwaldron/osgearth/commit/408fe1f

But now i see no sky.

**Comment by emminizer** [comment]
Some more input from the GL CORE Windows side:
- We are now seeing earth with this latest push. Big improvement.  I do see earth on readymap-rex.earth.
- I see sky in day_night_rex.earth, but I see no stars.

There are also some weird fullscreen mode artifacts with screen dimming that I can reproduce in day_night_rex.

**Comment by remoe** [comment]
Sorry, it was a false alarm. Build issue on my side :/

It works on MacOSX rex. Tested with readymap-rex.earth

This was the commit for relevant changes: https://github.com/gwaldron/osgearth/commit/b0bc502
"rex: fix VAO support in GLCORE profile"
