### ISSUE TITLE
Queried elevation is lower resolution than rendered terrain, except with packaged data

### ISSUE THREAD

**Issue by torokati44** [gwaldron/osgearth#1053]
The elevation returned by `ElevationQuery` (in osgEarth 2.7.0) corresponds to a much lower LOD data than the rendered terrain if the elevation data is streamed from an online source. If it is an offline, packaged dataset, the elevation data exactly matches the rendered terrain.

#### Steps to reproduce:

- Take an `.earth` file with an elevation layer, and open it with the `osgearth_elevation` program. (I used this one: [online_source.earth](https://gist.github.com/torokati44/8f811dfa56059e5a248ecd03b1ad3ac0))
- Pick an area, zoom in very close, and wait for a while to allow the highest available resolution elevation data to be downloaded.
- Note down the reported elevation for a couple chosen points.
- Create an offline package from the same `.earth` file, with a sufficiently high max LOD on an area enclosing the chosen points. (I used this script: [tiledownloader.sh](https://gist.github.com/torokati44/1e0ab11f19860f93d7b2bd62b8021dd5))
- Open the resulting `.earth` file with `osgearth_elevation`.
- Check the elevation at the same points.
- Observe that they are different, even though the visible terrain geometries exactly match.

#### Illustration:

With the source `.earth` file, using an online data source:

[Point 1](https://user-images.githubusercontent.com/288816/36101583-10330a90-100a-11e8-9e77-e91a7159ee0d.png)
[Point 2](https://user-images.githubusercontent.com/288816/36101614-2198fab0-100a-11e8-8c26-fdf1e0ce86af.png)
[Point 3](https://user-images.githubusercontent.com/288816/36101618-23c493c6-100a-11e8-8ea2-7fd2d266c4f6.png)

The same points with the packaged data:

[Point 1](https://user-images.githubusercontent.com/288816/36101627-2837ebec-100a-11e8-8515-198dd1cee61c.png)
[Point 2](https://user-images.githubusercontent.com/288816/36101630-2a354b4c-100a-11e8-8290-5c436d0ec0a5.png)
[Point 3](https://user-images.githubusercontent.com/288816/36101634-2b9b914e-100a-11e8-9c26-7bc6fceeed18.png)

I tried to match the camera and the cursor as best as I could, so you can see that there is no real difference in the rendered terrain. Notice the different `elevation` and `resolution` values.

The reported "resolution" is much finer with the offline dataset, and I can confirm that the returned elevations are correct in that case. In our software integrating osgEarth, we have some objects placed at positions we compute using this elevation query, and they are glued to the ground when using the packaged dataset. With the "online" `.earth` file, they sometimes float above the ground, sometimes go underneath it, no matter how long I wait for background downloads, or how far I zoom in. If I then start to limit the max LOD of the streamed elevation data step by step, then the computed positions won't change, but at some point the ground "catches up" to their inaccuracy, such that the objects are again placed right on the (now much coarser) ground. It's like half of osgEarth's brain (ElevationQuery) isn't aware that there is a much better resolution data available now, only the other half is (terrain rendering).

I know that `ElevationQuery` is deprecated, and `ElevationPool` should be used instead, but the latter is not yet present in osgEarth 2.7.0 (AFAIK). I also know that osgEarth 2.7.0 isn't exactly new, but in the latest LTS Ubuntu release - which we intend to support -, the available version is 2.5.0 using the default repositories, and even after adding [the stable UbuntuGIS PPA](https://launchpad.net/~ubuntugis/+archive/ubuntu/ppa/+packages?field.name_filter=&field.status_filter=published&field.series_filter=xenial), the most recent version is 2.7.0. In Fedora 27, the current version is also 2.7.0.

If this is already fixed in more recent versions, or is not present at all when using `ElevationPool`, that's great, but is there perhaps a workaround we could implement to force osgEarth 2.7.0 to use the obviously present higher resolution elevation data in `ElevationQuery`?

**Comment by gwaldron** [comment]
The elevation query code has changed quite a bit since version 2.7. One quick place to look is in the ElevationQuery.cpp code, line 440, where it sets a tile size of 33. Try changing this to 257 (this is the tile size of the readymap 116 dataset) and see if that improves the situation.

Failing that, you will need to build the master version of osgEarth and see if the problem still exists. If it does not, you can attempt to analyze and back-port the code to a 2.7 branch. Hope this helps.

**Comment by torokati44** [comment]
Am I looking at it wrong, or is it actually setting it to 17 on line 434, in 2.7.0?
https://github.com/gwaldron/osgearth/blob/25ce0e1b7a47311d1c19f5e76f208d7cd4388f94/src/osgEarth/ElevationQuery.cpp#L434

Anyway, changing it to 257 indeed gave me very similar (presumably identical) results in the offline and the online case. Sadly it also made `osgearth_elevation` quite a bit more sluggish with the online map, which is not entirely surprising. Everything has a price I guess...

Finally, do you think that there is a way to propagate the _effects_ of this change (since the hard-coded value itself would be very hard to change in a binary, I suppose) to our users who would install osgEarth from the package repositories of their respective OS-es (like the UbuntuGIS PPA); by employing workarounds in our application? Or are we best off with simply copying the altered `ElevationQuery` class into our application, and using that? To me, the latter seems maybe not the most elegant, but the most efficient "solution".

It still baffles me though, that with a packaged dataset, the elevation matched up with the terrain, even with a `tileSize` of 17... Does this change during packaging?

**Comment by gwaldron** [comment]
The only thing I can recommend is to use the old lower-resolution elevation dataset:
http://readymap.org/readymap/tiles/1.0.0/9/

Those tiles are 32x32 so it might match up better.

**Comment by torokati44** [comment]
Alright. Thank you for your time, and answers!
