### ISSUE TITLE
SkyNode: Weird behavior when opening a viewer after first one was closed

### ISSUE THREAD

**Issue by ceranco** [gwaldron/osgearth#1055]
After a viewer with a SkyNode in its scene graph is completely closed, if another one is opened with a SkyNode in its scene graph then there are a number of problems:

- Atmosphere doesn't show the light effects, only a grey circle.
- A huge sphere shows behind the MapNode, always facing the lighted part of the MapNode, so maybe it has something to do with the sun.
- 'Warning: detected OpenGL error 'invalid value' at after RenderBin::draw(..)' is written in the console repeatedly 

Here is a sample code that shows the problem:

```
int main(int argc, char** argv) 
{ 
        while (true) 
        { 
                osg::ref_ptr<osg::Group> root = new osg::Group; 
                osg::ref_ptr<osgEarth::MapNode> mapNode = new osgEarth::MapNode; 
                osg::ref_ptr<osgEarth::Util::SkyNode> skyNode = osgEarth::Util::SkyNode::create(mapNode.get()); 

                osgEarth::Util::insertGroup(skyNode, mapNode); 
                root->addChild(mapNode.get()); 

                osg::ref_ptr<osgViewer::Viewer> viewer = new osgViewer::Viewer; 
                skyNode->attach(viewer.get()); 
                
                viewer->setSceneData(root.get()); 
                viewer->apply(new osgViewer::SingleWindow(50, 50, 1000, 1000)); 

                viewer->run(); 
        } 
        return 0; 
}
```
This is how it looks the first time, working as expected: 
![loop1](https://user-images.githubusercontent.com/22302978/36523626-317f1dee-17ab-11e8-8807-8d5f87f26863.png)

and here is how it looks the second time, with the errors: 
![loop2](https://user-images.githubusercontent.com/22302978/36523637-43ec415a-17ab-11e8-90b4-af8ce59a038d.png)

**Comment by ceranco** [comment]
Hi Glenn,
I've compiled the master osgEarth branch against OSG 3.6.0 on Windows 64-bit, and the following code still reproduces the issue:
```
int main(int argc, char** argv) 
{ 
	while(true)
	{
		osgViewer::Viewer viewer;
		viewer.apply(new osgViewer::SingleScreen)
		viewer.setCameraManipulator(new osgEarth::Util::EarthManipulator);

		auto root = new osg::Group;
		auto mapNode = new osgEarth::MapNode;
		root->addChild(mapNode);

		auto skyExtension = Extension::create("sky_simple", osgEarth::ConfigOptions());
		mapNode->addExtension(skyExtension);
		ExtensionInterface<osg::View>::get(skyExtension)->connect(&viewer);

		viewer.setSceneData(root);
		viewer.run();
	}
	return 0;
}
```
This code creates and attaches the SkyNode like the 'osgearth_viewer' application does.

**Comment by gwaldron** [comment]
The proper way to add a sky is:

SkyNode* sky = SkyNode::create(mapNode);
sky->addChild(mapNode);
root->addChild(sky);

**Comment by ceranco** [comment]
When I added the SkyNode like you said, it stopped the bug!

I tried to find the reason that using the Extension interface produces the bug, and I think I found the problem:
When the SimpleSkyExtension is added to the MapNode, it is stored in a vector of ref_ptr on line 559 in MapNode.cpp:
 `_extensions.push_back( extension ); `
On line 572 in MapNode.cpp, the SimpleSkyExtension interface's connect method is called: 
`extensionIF->connect( this );`
Line 58 in SimpleSkyExtension.cpp:
```
bool connect(MapNode* mapNode)
{
	_skynode = createSkyNode(mapNode->getMap()->getProfile());
	osgEarth::insertParent(_skynode.get(), mapNode);
	return true;
}
```
The SkyNode is inserted as the parent of the MapNode, so we have a circular reference:
**MapNode->SimpleSkyExtension ->SkyNode->MapNode**

The MapNode is never cleaned up, and for some reason that causes (at least on the 4 Windows computers that I've checked on) the bug with the atmosphere and the sun.

I've tried adding the following line to the code I sent in my previous comment:
`mapNode->removeExtension(skyExtension);`
and it seemed to fix the bug as well

Maybe line 61 in SimpleSkyExtension.cpp
`osgEarth::insertParent(_skynode.get(), mapNode);`
should be changed to:
`osgEarth::insertParent(_skynode.release(), mapNode);`

**Comment by ceranco** [comment]
Found another way to recreate the problem:
Reuse the scene graph between different Viewers:
```
int main(int argc, char** argv)
{
	ref_ptr<Group> root = new Group;
	auto mapNode = new osgEarth::MapNode;

	SkyNode* skyNode = SkyNode::create(mapNode);
	skyNode->addChild(mapNode);

	root->addChild(skyNode);

	for (size_t i = 0; i < 5; i++)
	{
		osgViewer::Viewer viewer;
		viewer.setCameraManipulator(new osgEarth::Util::EarthManipulator);

		viewer.setSceneData(root);
		viewer.run();
	}
	return 0;
}
```

I get the error message and the messed up atmosphere from the second iteration onward.

**Comment by gwaldron** [comment]
Please see #1142 and #1141
