### ISSUE TITLE
Shader failed to compile with osgEath 2.9 on macOS 11.12?

### ISSUE THREAD

**Issue by rhornig** [gwaldron/osgearth#1056]
I'm trying to compile osgEarth 2.9 on macOS and while the build was successful, trying out some .earth files (e.g. boston.earth) results in error messages:

VERTEX glCompileShader "main(vertex)" FAILED
VERTEX Shader "main(vertex)" infolog:
ERROR: 0:1: '' :  version '330' is not supported
WARNING: 0:4: extension 'GL_ARB_gpu_shader5' is not supported
ERROR: 0:38: ';' : syntax error: Uniform blocks may not have identifiers in GLSL 140

and the shaders/textures are incorrect. Is osgEarth 2.9 supposed to work on macOS.
I'm using OpenSceneGraph 3.4.1 (tested 3.5.9 too). My mac mini is fairly old with an intel 3000 graphics driver. I was able to get osg 3.2.1 and osgEarth 2.7 working fine, but I would love to have the latest 2.9 version if possible.

Is 2.9 supposed to work, or do I have to configure something?

**Comment by remoe** [comment]
You need to use OSG 3.5.9, latest osgEarth and OpenGL 4.1/3.3 core profile. 

https://support.apple.com/en-us/HT202823

**Comment by gwaldron** [comment]
GL 140 is insufficient; I recommend you update your driver.

**Comment by rhornig** [comment]
Thanks a lot. Appreciate the response. 
It seems to be working with 3.5.9 so I!m closing this now.
