### ISSUE TITLE
FindCurl.cmake is deprecated and should be deleted/replaced

### ISSUE THREAD

**Issue by remoe** [gwaldron/osgearth#1063]
FindCurl.cmake has issues with some environments which use CMAKE_PREFIX_PATH with multiple entries, because of this:
https://github.com/gwaldron/osgearth/blob/master/CMakeModules/FindCURL.cmake#L8

and this is also not updated:
https://github.com/gwaldron/osgearth/blob/master/CMakeModules/FindCURL.cmake#L38
On Windows, curl creates libcurl_imp.lib.

And such paths are not needed:
https://github.com/gwaldron/osgearth/blob/master/CMakeModules/FindCURL.cmake#L54
because one can use DCMAKE_FIND_ROOT_PATH and CMAKE_PREFIX_PATH. And CMAKE_PREFIX_PATH can contain multiple of entries.

Why not delete this file, because CMake has a right one included:

https://github.com/Kitware/CMake/blob/master/Modules/FindCURL.cmake

Or should we update it to the one of CMake?

**Comment by jasonbeverage** [comment]
Thanks a bunch Remo, I think you're right.  I've deleted the FindCurl.cmake in 635a5e38581c624e2b3489e2cb04768b80c64901.  OSG doesn't use their own custom FindCurl cmake anymore either, so we shouldn't have to either.
