### ISSUE TITLE
How to add text label has multiple line?

### ISSUE THREAD

**Issue by yakupc** [gwaldron/osgearth#1070]
I need to add text label has multiple line by using earth file. I tried '\n', '\D', '\A' characters to add line break but didn't help. Can you give me an idea how can I add multiple text lines?
```

text-content: "TEXT 
       " + [field_2] +"
          "+ [field_19] + "\n \r \A \D" + [field_6];

```

**Comment by gwaldron** [comment]
You need to use a script:

        </styles>
            <style type="text/css">              
                default {
                    text-content: getName();
                }     
            </style>
            <script language="javascript">
                function getName() {
                    return feature.properties.field_1 + "\n" + feature.properties.field_2;
                }
            </script>
        </styles>

**Comment by yakupc** [comment]
Thanks, it works.
