### ISSUE TITLE
Compile error in release version 2.9

### ISSUE THREAD

**Issue by ManiAm** [gwaldron/osgearth#1074]
I get the following error while compiling:

![2018-03-21_11-20-24](https://user-images.githubusercontent.com/5473998/37729342-f96cf7a0-2cf9-11e8-9d76-a932823a30fb.png)

**Comment by jasonbeverage** [comment]
What version of OpenSceneGraph are you trying to compile against?

**Comment by ManiAm** [comment]
I used OpenSceneGraph-3.2.3

**Comment by jasonbeverage** [comment]
You need to use at least osg 3.4 with the most recent osgearth.
