### ISSUE TITLE
fail to make osg2.8  !!!!

### ISSUE THREAD

**Issue by fereydoon031** [gwaldron/osgearth#1085]
.cpp.o
/home/fereydoon/examples/osgearth/src/osgEarth/Registry.cpp: In constructor ‘RegisterEarthTileExtension::RegisterEarthTileExtension()’:
/home/fereydoon/examples/osgearth/src/osgEarth/Registry.cpp:697:9: error: ‘setThreadSafeReferenceCounting’ is not a member of ‘osg::Referenced’
         osg::Referenced::setThreadSafeReferenceCounting( true );
         ^
[ 15%] Building CXX object src/osgEarth/CMakeFiles/osgEarth.dir/StateSetCache.cpp.o
src/osgEarth/CMakeFiles/osgEarth.dir/build.make:2043: recipe for target 'src/osgEarth/CMakeFiles/osgEarth.dir/Registry.cpp.o' failed
make[2]: *** [src/osgEarth/CMakeFiles/osgEarth.dir/Registry.cpp.o] Error 1
make[2]: *** Waiting for unfinished jobs....
CMakeFiles/Makefile2:165: recipe for target 'src/osgEarth/CMakeFiles/osgEarth.dir/all' failed
make[1]: *** [src/osgEarth/CMakeFiles/osgEarth.dir/all] Error 2
Makefile:149: recipe for target 'all' failed
make: *** [all] Error 2

**Comment by gwaldron** [comment]
osgEarth requires OSG 3.4 or newer.
