### ISSUE TITLE
Statistics display sometimes not shown properly

### ISSUE THREAD

**Issue by beachwalker** [gwaldron/osgearth#1094]
![image](https://user-images.githubusercontent.com/2715897/38504731-c2b6a28a-3c15-11e8-855e-10c3ec588700.png)

not working for feature_raster.earth
working for feature_rasterize.earth

![image](https://user-images.githubusercontent.com/2715897/38504816-00498752-3c16-11e8-8d6a-c0cfeb322021.png)

Seems there is a feature used in the  feature_raster.earth that makes this happen.

**Comment by plevy** [comment]
I believe Glenn pushed a fish for this on Friday.  If there was osgEarth controls text like your viewpoints list, it would cause a problem with osgText.  Can you update osgEarth and try again?

**Comment by gwaldron** [comment]
This is fixed
