### ISSUE TITLE
osgearth_pick on MacOSX: Image layer not visible 

### ISSUE THREAD

**Issue by remoe** [gwaldron/osgearth#1098]
After run `./osgearth_pick tests/feature_country_boundaries.earth` the image layer is not visible:

<img width="336" alt="screen shot 2018-04-10 at 12 43 33" src="https://user-images.githubusercontent.com/804941/38556048-97eed1ae-3cc8-11e8-9738-b8528450a588.png">

But it works if one run it with `osgearth_viewer`. Tested with `rex` and `mp`.

OSG: 3.6.0
osgearth: cc63ab23dbc97353b9cf46f1e93477278fb26076

**Comment by emminizer** [comment]
For what it's worth, I just tested on Windows with GL Core profile and current master and I can see the earth.  So like your PR does, I'm guessing it's an apple-specific issue.

**Comment by remoe** [comment]
Now, i can reproduce the issue with an OSG Sample:

https://github.com/remoe/osgsample-2

This works on Windows without any errors. On MacOSX it throws:

```ERROR: Active attribute aliasing. Slot 3 unavailable for 'osg_MultiTexCoord0' from BindAttributeLocation request.```

When one disable this:

https://github.com/remoe/osgsample-2/blob/master/main.cpp#L205

with "#if 0", Then it doesn't throw an error on MacOSX.

Tested with OSG 3.6.2 / GLCore.

**Comment by remoe** [comment]
The main issue is the following: OSG bind both vertex attribute arrays to the same index:

Linking osg::Program "osgEarth.engine_mp.TerrainNode" id=13 contextID=0
**Program's vertex attrib binding 4, oe_index_objectid_attr**
Program's vertex attrib binding 6, oe_terrain_attr
Program's vertex attrib binding 7, oe_terrain_attr2
State's vertex attrib binding 2, osg_Color
State's vertex attrib binding 12, osg_FogCoord
State's vertex attrib binding 3, osg_MultiTexCoord0
**State's vertex attrib binding 4, osg_MultiTexCoord1**
State's vertex attrib binding 5, osg_MultiTexCoord2
State's vertex attrib binding 6, osg_MultiTexCoord3
State's vertex attrib binding 7, osg_MultiTexCoord4
State's vertex attrib binding 8, osg_MultiTexCoord5
State's vertex attrib binding 9, osg_MultiTexCoord6
State's vertex attrib binding 10, osg_MultiTexCoord7
State's vertex attrib binding 1, osg_Normal
State's vertex attrib binding 11, osg_SecondaryColor
State's vertex attrib binding 0, osg_Vertex

Can someone please explain this behavior?

Thanks.

**Comment by emminizer** [comment]
This may not help much, but I did see a similar issue with vertex attrib binding duplicates.  I have it in my notes from a couple months back on our OSG / osgEarth Core Profile update.  It showed up once in an API Trace run, and I never saw it again.  I was unsure how to reproduce.  This is probably related.

I never came back to it to investigate because although I saw the warning, I didn't detect any bad behavior in our app.

**Comment by remoe** [comment]
It comes from this code block:

https://github.com/openscenegraph/OpenSceneGraph/blob/6cd00edd6c604dcb9156bf657560823cfdea07ec/src/osg/Program.cpp#L764

in combination with active state.getUseVertexAttributeAliasing(). and State::resetVertexAttributeAlias:

https://github.com/openscenegraph/OpenSceneGraph/blob/6cd00edd6c604dcb9156bf657560823cfdea07ec/src/osg/State.cpp#L1231

In this code one find a "slot" counter, but this doesn't lookup any custom vertex attributes.

**Comment by remoe** [comment]
@emminizer , yes on windows it gives a waring:

```
Linking osg::Program "osgEarth.engine_mp.TerrainNode" id=13 contextID=0
Program's vertex attrib binding 4, oe_index_objectid_attr
Program's vertex attrib binding 6, oe_terrain_attr
Program's vertex attrib binding 7, oe_terrain_attr2
State's vertex attrib binding 2, osg_Color
State's vertex attrib binding 12, osg_FogCoord
State's vertex attrib binding 3, osg_MultiTexCoord0
State's vertex attrib binding 4, osg_MultiTexCoord1
State's vertex attrib binding 5, osg_MultiTexCoord2
State's vertex attrib binding 6, osg_MultiTexCoord3
State's vertex attrib binding 7, osg_MultiTexCoord4
State's vertex attrib binding 8, osg_MultiTexCoord5
State's vertex attrib binding 9, osg_MultiTexCoord6
State's vertex attrib binding 10, osg_MultiTexCoord7
State's vertex attrib binding 1, osg_Normal
State's vertex attrib binding 11, osg_SecondaryColor
State's vertex attrib binding 0, osg_Vertex
Program "osgEarth.engine_mp.TerrainNode" link succeeded, infolog:
Link info
---------
warning:  two vertex attribute variables (named osg_MultiTexCoord1 and oe_index_objectid_attr) were assigned to the same generic vertex attribute

	Uniform "objectid_to_highlight" loc=0 size=1 type=uint
	Uniform "oe_ClipPlane_plane" loc=1 size=1 type=vec4
	Uniform "oe_index_objectid_uniform" loc=2 size=1 type=uint
	Uniform "oe_layer_attenuationRange" loc=3 size=1 type=float
	Uniform "oe_layer_maxRange" loc=4 size=1 type=float
	Uniform "oe_layer_minRange" loc=5 size=1 type=float
	Uniform "oe_layer_opacity" loc=6 size=1 type=float
	Uniform "oe_layer_order" loc=7 size=1 type=int
	Uniform "oe_layer_tex" loc=8 size=1 type=sampler2D
	Uniform "oe_layer_uid" loc=9 size=1 type=int
	Uniform "oe_terrain_color" loc=10 size=1 type=vec4
	Uniform "osg_ModelViewMatrix" loc=11 size=1 type=mat4
	Uniform "osg_ProjectionMatrix" loc=12 size=1 type=mat4
	Uniform "osg_ViewMatrixInverse" loc=13 size=1 type=mat4
	Attrib "oe_index_objectid_attr" loc=4 size=1
	Attrib "osg_Color" loc=2 size=1
	Attrib "osg_MultiTexCoord0" loc=3 size=1
	Attrib "osg_MultiTexCoord1" loc=4 size=1
	Attrib "osg_Vertex" loc=0 size=1
```

**Comment by gwaldron** [comment]
This article might shed some light.
https://stackoverflow.com/questions/20573235/what-are-the-attribute-locations-for-fixed-function-pipeline-in-opengl-4-0-cor

Basically it is saying that GLCORE prohibits the assumption that any particular attribute locations should be used for any specific data. (For example you cannot assume that Location 3 is always Color. They might make one exception: that Location 0 should be the Vertex.)

However, NVIDIA has always enforced specific bindings, and continues to do so, in order to maintain backwards compatibility with older hardware. The bindings are shown here:

https://www.opengl.org/sdk/docs/tutorials/ClockworkCoders/attributes.php

OSG follows this NVIDIA "standard" in its osg::Drawable::AttributeTypes enum. But, it's only really reliable on NVIDIA hardware. I am guessing that most vendors follow this pattern to be compatible, but MacOSX decided to break from the pack. 

Not sure what the solution is just yet but I suspect this is the problem.

**Comment by gwaldron** [comment]
Remo, I have a wacky idea. If you look at the osg::State::resetVertexAttributeAlias() function, it takes a paramter called "compactAliasing", which always defaults to true. This sets up the vertex attribute registers in the way that MacOSX is reporting. If we are able to call this method with compactAliasing=false, it should set things up according to the NVIDIA spec.

In osgEarth I would put this in GL3RealizeOperation -- not sure you use that in your app?

**Comment by remoe** [comment]
Glenn, I've tested this on MacOSX. It works!

```
Linking osg::Program "" id=8 contextID=0
Program's vertex attrib binding 4, oe_index_objectid_attr
Program's vertex attrib binding 6, oe_terrain_attr
Program's vertex attrib binding 7, oe_terrain_attr2
State's vertex attrib binding 3, osg_Color
State's vertex attrib binding 5, osg_FogCoord
State's vertex attrib binding 8, osg_MultiTexCoord0
State's vertex attrib binding 9, osg_MultiTexCoord1
State's vertex attrib binding 10, osg_MultiTexCoord2
State's vertex attrib binding 11, osg_MultiTexCoord3
State's vertex attrib binding 12, osg_MultiTexCoord4
State's vertex attrib binding 13, osg_MultiTexCoord5
State's vertex attrib binding 14, osg_MultiTexCoord6
State's vertex attrib binding 15, osg_MultiTexCoord7
State's vertex attrib binding 2, osg_Normal
State's vertex attrib binding 4, osg_SecondaryColor
State's vertex attrib binding 0, osg_Vertex
```

**Comment by gwaldron** [comment]
Excellent :) I will add this call to osgEarth's GL3RealizeOperation.
