### ISSUE TITLE
how can i draw a triangle on the osgearth with osg api

### ISSUE THREAD

**Issue by KhochkinNick** [gwaldron/osgearth#1125]
There is a question on the site in stackoverflow.

Could you answer.
Thank you in advance.

Link:
https://stackoverflow.com/questions/42413816/how-can-i-draw-a-triangle-on-the-osgearth-with-osg-api

**Comment by gwaldron** [comment]
Answered on SO.

**Comment by KhochkinNick** [comment]
Many thanks 23.05.2018, 15:56, "Glenn" <notifications@github.com>:Answered on SO.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or mute the thread.  -- С уважением, Хочкин Николай.
