### ISSUE TITLE
`visible` attribute in ModelLayer not used when loading a map

### ISSUE THREAD

**Issue by mathieu** [gwaldron/osgearth#1132]
To reproduce, add a `visible="false"` in the `feature_models.earth`  example here : 
https://github.com/gwaldron/osgearth/blob/f68e56479a5f34438bf74a22e4cd6b8f35c77b03/tests/feature_models.earth#L3

launching osgearth_viewer on this example and going to the viewpoint should not show the flags, instead they are shown :
![capture d ecran 2018-06-05 a 09 53 04](https://user-images.githubusercontent.com/17992/40962601-4462ff1a-68a6-11e8-8cc3-42f5e01e0403.png)
 
If by code I query the visible flag it is set to `false` and if I toggle it to `true` and then to `false` the flags get hidden like they should in the first place.

**Comment by gwaldron** [comment]
Thanks. Fixed in the master branch.
