### ISSUE TITLE
osgearthviewer carsh when earth file contain annotations and place node

### ISSUE THREAD

**Issue by TMwhuhan** [gwaldron/osgearth#1134]
the earth file "annotation.earth" is from tests directory

**Comment by gwaldron** [comment]
Cannot reproduce in osgEarth master, OSG 3.6 brach

**Comment by TMwhuhan** [comment]
That too  bad, I use vision 2.9 and osg 3.6. I tried  the application osgearth_3pv. It crashed too. I test the osgb_xxx_png  by open a  model with  png texture in osgviewer. It worker.  So I guess maybe other  important 3rdprty lib of placenode is missing. Could you give some advice to me?  
The env is  mingw7.3 in win10

**Comment by remoe** [comment]
This is not an issue of osgEarth. Please check your build.

see:
https://github.com/gwaldron/osgearth/issues/1033
