### ISSUE TITLE
Geodetic graticule edge labels do not display/position correctly when date line is shown

### ISSUE THREAD

**Issue by mk401** [gwaldron/osgearth#1137]
We've started displaying the edge labels using osgEarth::Util::GeodeticGraticuleOptions's new(ish) egdeLabelsVisible field. It looks great except whenever the international date line is in view. I'll attach some screenshots of the issue.
![date line shown 2](https://user-images.githubusercontent.com/5324181/41308045-d898b268-6e48-11e8-96be-c99cac16be53.PNG)
![date line shown](https://user-images.githubusercontent.com/5324181/41308046-d8b20d1c-6e48-11e8-8a48-f71b5d2a6ab3.PNG)
![date line not shown](https://user-images.githubusercontent.com/5324181/41308047-d8c82a7a-6e48-11e8-9ee6-ee8e3b36e6b9.PNG)

**Comment by jasonbeverage** [comment]
I pushed a fix for this in b5d9cce00bdb157369c21e73d070a7476b23ea00.  Should be good to go now.
