### ISSUE TITLE
Tiles with ImageSequence based textures don't animate in REX but they do in MP engine.

### ISSUE THREAD

**Issue by WojtekLewandowski** [gwaldron/osgearth#1139]
I have tried latest osgEarth github master (2.9) with WMS-T data. Initially I had some trouble with starting the sequence playback. But I overcame it (by forcing seq->start in WMS TileSource). And now tiles with ImageSequences animate. But only with MP engine. When I try the same with REX these sequences show only first static image.  After some digging I have found that  ImageSequence::update methods are not called. And I guess that REX ignores requiresUpdateTraverse flag set in TerrainTileModel and does not update ImageSequences. To prove this it the problem I hacked WMSTileSource to iterate elements of _sequenceCache and call ImageSequence::update from some external Update operation. It worked. So  this must be ImageSequence::update problem. 

Btw, while making above hack I encountered (and fixed) a compilation bug in ThreadSafeObserverSet<T> (Containers header)
Iterator used in ThreadSafeObserverSet<T>::iterate loop is declared as:
`std::set<T>::iterator`
but it should be declared as: 
`std::set<osg::observer_ptr<T>>::iterator` (ie the proper iterator for the _data member).

    template<typename T>
    struct ThreadSafeObserverSet
    {
      typedef void(*Functor)(T*);

      ...

      void iterate(const Functor& f)
      {
        osgEarth::Threading::ScopedWriteLock lock(_mutex);
      
      #if 0   // before 
        for (typename std::set<T>::iterator i = _data.begin(); i != _data.end();)
      #else   // now
        for (typename std::set<osg::observer_ptr<T>>::iterator i = _data.begin(); i != _data.end();)
      #endif
        {
          if (i->valid())
          {
            f(i->get());
            ++i;
          }
          else
          {
            i = _data.erase(i);
          }
        }
      }

**Comment by airscrat** [comment]
I have the same problem as you do.

**Comment by gwaldron** [comment]
Wojtek, I pushed your fix for the iterator type.

**Comment by gwaldron** [comment]
Pushed a fix for the update traversal ... please test and report back.

**Comment by WojtekLewandowski** [comment]
"I pushed your fix for the iterator type."
I see you only fixed iterate( ConstFunctor ). iterate( Functor ) has the same problem. Please fix it too.
Cheers,
WL

**Comment by WojtekLewandowski** [comment]
ImageSequences now update with REX. Disclaimer: I tested by cherry picking the #1139 fix changes to my branch. I could not test current master. Because when I pulled latest master, it did not build with my curl and triton versions. I presume some changes in Triton support and Curl requirements were made in master since the time I checked it out (roughly 3 days ago).
