### ISSUE TITLE
Need 2.9.x branch/release to build 2.9 against OSG 3.6 branch

### ISSUE THREAD

**Issue by filnet** [gwaldron/osgearth#1140]
Hi,

Some distributions like MSYS2/MinGW offer only the latest version of OSG (now 3.6.1).
This breaks the osgEarth 2.9 distribution because of the osgPlugins-3.6.1 directory...

This is usually fine and just recompiling osgEarth fixes the issue.
But this is not true currently as osgEarth 2.9 won't compile against OSG 3.6.1 (3.6.0 was ok).

So, my question is if there is a point release (a 2.9.1 compatible with OSG 3.6.1) in sight?

Cheers,
Philippe.

**Comment by gwaldron** [comment]
We don't have any sponsorship for this at the moment so it's not on the todo list. If someone wants to make it happen we can look at the possibility of a 2.9 branch.

**Comment by gwaldron** [comment]
Expiring b/c 2.10 works with OSG 3.6 branch.
