### ISSUE TITLE
GDAL error reporting

### ISSUE THREAD

**Issue by matthew-reid** [gwaldron/osgearth#1144]
The OCTNewCoordinateTransformation function in SpatialReference.cpp returns null if the Proj4 library isn't dynamically loaded or statically linked. This manifests as a message saying "SRS xform not possible", which gives no indication of the underlying reason for the failure. It would be helpful for the underlying reason to be reported with something like

```
if (!xform_handle)
	printf("ERROR: %s\n", CPLGetLastErrorMsg());
```

after this line:
https://github.com/gwaldron/osgearth/blob/master/src/osgEarth/SpatialReference.cpp#L1113

**Comment by jasonbeverage** [comment]
Good idea.  I pushed an implementation of this in bad8e7d9b6b5fcd64b4b907a17ae2ba4776ea9ed
