### ISSUE TITLE
doc: stroke-tessellation-segments and stroke-tessellation-size is not documented

### ISSUE THREAD

**Issue by remoe** [gwaldron/osgearth#1145]
see:

https://github.com/gwaldron/osgearth/blob/7922373a2c71facf229f6cbeeab8a3c3a7454b52/src/osgEarthSymbology/LineSymbol.cpp#L119
and
https://github.com/gwaldron/osgearth/blob/7922373a2c71facf229f6cbeeab8a3c3a7454b52/src/osgEarthSymbology/LineSymbol.cpp#L122

here is the current documentation:

https://github.com/gwaldron/osgearth/blob/b0a13dd6a17cb92326a1a54b61fdd88ac60a4af5/docs/source/references/symbology.rst

**Comment by gwaldron** [comment]
done
