### ISSUE TITLE
Dirty translucent color when used DrapeableNode/DrapingTechnique

### ISSUE THREAD

**Issue by KhochkinNick** [gwaldron/osgearth#1148]
When I use DrapeableNode the color of **translucent** texture is "dirty" (double alpha blend).
I found an error inside the code in my opinion.

In the method (class **DrapingTechnique**)
`void DrapingTechnique::setUpCamera(OverlayDecorator::TechRTTParams& params)`

there is a code whith using blend function

`blendFunc = new osg::BlendFunc(GL_SRC_ALPHA, GL_ONE_MINUS_SRC_ALPHA, GL_ONE, GL_ONE_MINUS_SRC_ALPHA);`

This code should be replaced on

`blendFunc = new osg::BlendFunc(GL_SRC_COLOR, GL_ONE_MINUS_SRC_COLOR, GL_ONE, GL_ONE_MINUS_SRC_ALPHA);`

I solve this problem using this patch.
Please check my solution.

**Comment by gwaldron** [comment]
Can you explain the problem (screenshot?) and why this is a good solution? It doesn't look right to me.

**Comment by OlaRune** [comment]
I can confirm that this is still a problem. In my application I let the user change draping technique in runtime, and that switches the color of semi-transparent polygons as in the screenshots.

**Comment by gwaldron** [comment]
Does the proposed fix above work for you as well?

**Comment by OlaRune** [comment]
> Does the proposed fix above work for you as well?

I don't have OSG Earth compiled from source on this computer, so I can't try it out yet.

**Comment by gwaldron** [comment]
I tried it and it looks decent - committed the fix
