### ISSUE TITLE
LineSymbol not rendring

### ISSUE THREAD

**Issue by MCA4213** [gwaldron/osgearth#1149]
Hi,
I noticed that there is no line rendering on ModelLyer in the last osgEarth ( since 1 month or more), only the polygon filling is shown as in this code:
        
```
osgEarth::Drivers::OGRFeatureOptions fo;
	fo.ogrDriver() = "ESRI Shapefile";
	fo.url() = "WORLD_POLY.shp";
	fo.openWrite() = false;
```
	FeatureGeomModelOptions  fgm_opt;
	StyleSheet* styleSheet = new StyleSheet();
	Style style;
	
        fgm_opt.featureOptions() = fo;
	AltitudeSymbol* alt = new AltitudeSymbol();
	alt->clamping() = AltitudeSymbol::CLAMP_TO_TERRAIN;
	alt->technique() = AltitudeSymbol::TECHNIQUE_MAP;
	style.add(alt);

	style.getOrCreate<PolygonSymbol>()->fill()->color() = Color::Green;
	LineSymbol* ls = style.getOrCreateSymbol<LineSymbol>();
	ls->stroke()->color() = Color::Yellow;
	ls->stroke()->width() = 5.0f;
        styleSheet->addStyle(style);
	fgm_opt.styles() = styleSheet;
	ModelLayer * lay = new ModelLayer("vector",  fgm_opt);
	map->addLayer(lay);

The same behavior is in the FeatureModelLayer in the osgEarth_features example.

**Comment by gwaldron** [comment]
osgEarth has a new line-rendering subsystem that uses shaders. You may need to call GLUtils::setGlobalDefaults on a camera's stateset to initialize the default uniforms. Most osgEarth examples that use MapNodeHelper do this automatically.

**Comment by MCA4213** [comment]
Indeed , you are right. It was my mistake.
By adding : `GLUtils::setGlobalDefaults(viewer.getCamera()->getOrCreateStateSet());`
the lines are now shown correctly.

For the osgEarth_features example, it was also my mistake, I commented the MapNodeHelper because it make the application crash. I did not know the utility of this.

So this is not an issue, sorry again.
