### ISSUE TITLE
[rex] crash in DrawTileCommand::draw caused by invalid _colorSamplers ptr

### ISSUE THREAD

**Issue by aroth-fastprotect** [gwaldron/osgearth#1180]
Hi,

in our software (Windows 32-bit, OSG 3.6.2, osgEarth master) we use the rex terrain engine. The rex sometimes crashes when a new layer was recently added and the RTT picker is enabled. 

The crash occurs in _DrawTileCommand::draw_ when accessing the __colorSamplers_ for a _LayerDrawable_ for the recently added layer. The __colorSamplers_ is non-zero but invalid and therefore it crashes.

I searched through the code and found that the _DrawTileCommand::_colorSamplers_ pointer are passed from _TerrainCuller::addDrawCommand_ as _&pass->samplers()_. The _samples is a vector in RenderingPass. In TileRenderModel a _vector<RenderingPass>_ is held and when _TileRenderModel::addPass()_, this vector is resized and a reference to the last element in the vector is returned. When a vector is resized all previous pointers to its elements become invalid (implementation allocates a new block of memory to hold all vector elements and the old block is freed). 

I've changed the 
`typedef std::vector<RenderingPass> RenderingPasses;`
to
`typedef std::vector<RenderingPass*> RenderingPasses;`
and change all the required code and this 'trick' fixes my crash. Effectively putting the RenderingPass on the heap instead of the stack and therefore avoiding the invalidation of the pointers by _resize()_.

My changeset is available [here](https://github.com/aroth-fastprotect/osgearth/commit/19b577eefd1092b5faa2e6923020835046bef6f0) and the entire branch is [here](https://github.com/aroth-fastprotect/osgearth/tree/rex_renderpass_ptr)

If tried to replicate the crash in our software with one of the osgEarth examples, but so far i haven't been successful. I don't the exact workings and mechanism in place which make the rex engine tick and it might be possible that i'm use the osgEarth not as it's intended. Nevertheless i hope someone familiar with the rex engine might take a look.

Thanks

**Comment by gwaldron** [comment]
Andreas,
I am struggling to understand how this invalidation occurs. As far as I can remember, addPass() is only called during an update traversal, whereas addDrawCommand will only happen during a cull traversal. So in theory there should be no pointers to _samplers to invalidate. But--- I haven't looked at this code in quite a while so I'm probably missing something.

**Comment by aroth-fastprotect** [comment]
Thanks Glenn for taking the time to look into this issue. I finally managed to find the cause of my issue.
The RTTPicker installs a slave camera when the first pick is done. The slave camera creates its own renderer, but the renderer is created with "_graphicsThreadDoesCull" set to true which triggers the corruption. The _graphicsThreadDoesCull is disabled for the "regular" view camera when the viewer threads are started (using the CullThreadPerCameraDrawThreadPerContext thread model). 

To "fix" this issue i now create the RTTPicker earlier and run a "dummy" pick at 0,0 before the viewer threads are started. With this "trick" the RTTPicker and the REX engine are working fine. Sorry for the noise.
