### ISSUE TITLE
osgearth_viewer display broken for minimal earth file sample with local file

### ISSUE THREAD

**Issue by beachwalker** [gwaldron/osgearth#1186]
![bug_earth](https://user-images.githubusercontent.com/2715897/44210611-7d861a00-a156-11e8-86cb-d711973db405.png)

The earth file I used is pretty simple. Just pointing to local file. Previous versions worked with that file.

```
<?xml version="1.0" encoding="UTF-8"?>
<map name="minimal" type="geocentric" version="2">
    <options>
        <cache driver="filesystem" path="./cache" />
    </options>
    <image driver="gdal" name="world-tiff">
        <url>data/TrueMarble.8km.5400x2700.tif</url>
    </image>
</map>
```

**Comment by beachwalker** [comment]
running on win10 x64 with osgearth-master, osg 3.6.2

**Comment by remoe** [comment]
The latest osgEarth use the REX terrain engine as default. Try to use ```OSGEARTH_TERRAIN_ENGINE=mp``` as environment variable.

**Comment by beachwalker** [comment]
so it seems REX is broken

**Comment by mk401** [comment]
You're on master, you say? I was seeing this issue yesterday, but after https://github.com/gwaldron/osgearth/commit/b51dfda49, the problem has disappeared.

**Comment by jasonbeverage** [comment]
Yeah grab the latest, I ended up pushing a bad change to the caching which I fixed yesterday.

**Comment by beachwalker** [comment]
ah, ok. i pull again. happens with both rex and mp.

**Comment by beachwalker** [comment]
yes, fixed now.
