### ISSUE TITLE
FeatureManipulator functionality is missing

### ISSUE THREAD

**Issue by beachwalker** [gwaldron/osgearth#1190]
The Editor for Features was removed but there is no current replacement for this functionality. So there is a loss of functionality.

**Comment by jasonbeverage** [comment]
As Glenn mentioned, the FeatureManipTool was more of an experiment, not widely used and was removed 3 years ago.  At some point we may write up a new tool, but for now it isn't going to be part of the core osgearth.

**Comment by beachwalker** [comment]
Ok, but a list of what is "core" and what is not would be nice. Otherwise the users of the sdk may run into serious trouble if taking the wrong decisions (like I did in this case).

**Comment by beachwalker** [comment]
… by the way for those who are interested and have the same problem: Revision: 9c8dd703fcbc5730e6df1bf17372423fadd7cb30
Date: 15.11.2017 20:08:00
removal of FeatureQueryTool etc.
