### ISSUE TITLE
2 Questions : Projection and World Coord to Screen coord

### ISSUE THREAD

**Issue by Tom-Henoch** [gwaldron/osgearth#1196]
Hello,

I have 2 questions related to your project.
- Is it possible to have 2 maps sharing the same layers with one in projected mode and the other on geocentric mode in the same time ? 
- I have seen you have the  `getWorldCoordsUnderMouse` function which convert screen coords to world coords. Do you have the function which do the opposite ? Taking the world coords and convert them in screen coords ?

Thanks,
Tom

**Comment by gwaldron** [comment]
Tom,

1. You should create a separate Layer object for each Map.

2. There's no function in osgEarth to convert world coords to screen coords, but it's just a matrix multiplication:

osg::Matrix VPW = viewMatrix * projectionMatrix * windowMatrix;
osg::Vec3d screenCoord = worldCoords * VPW;

**Comment by Tom-Henoch** [comment]
Ok thanks !
