### ISSUE TITLE
Unable to have more than one tms

### ISSUE THREAD

**Issue by beachwalker** [gwaldron/osgearth#1208]
The tms seems to have a problem if multiple layers are defined and the 2nd has only a part of the world. Only the first one is displayed.

**Comment by jasonbeverage** [comment]
Do you have an example earth file you could share that demonstrates the
issue?

**Comment by remoe** [comment]
We use a lot of TMS layers at same time. I don't see an issue. Do you run the lastest master of osgEarth? I'm also interested on an earth file ;)

**Comment by beachwalker** [comment]
We use together with geoserver. The full earth image works, but the smaller source files (e.g. tiles for a part of the country) with small boundary don't show up. The geoserver tms answers: coverage [minx,mint,max,maxy] is [33,24,33,24,5] ... Looks like the area does not fit to the tile scheme.

**Comment by beachwalker** [comment]
I think I found the issue. If the boundary of the tms is not defined for the whole earth (-180 +180 -90 +90) and has instead a smaller coverage, then osgearth seems to stop requesting tiles.
