### ISSUE TITLE
Draped features disappear with projected profile

### ISSUE THREAD

**Issue by plevy** [gwaldron/osgearth#1209]
Using osgearth_viewer annotation_flat.earth, the draped flag and polygon will disappear with a slight camera angle.

![image](https://user-images.githubusercontent.com/7724641/46104011-3dc44080-c1a0-11e8-9064-0f5fdad6ef84.png)

**Comment by gwaldron** [comment]
This in intentional. There's no "horizon distance" in a projected map, so we just simulate one based on what it would be in a geocentric map
