### ISSUE TITLE
Missing imagery on projected maps

### ISSUE THREAD

**Issue by plevy** [gwaldron/osgearth#1210]
Missing imagery on the right side of osgearth_viewer readymap_flat.earth

![image](https://user-images.githubusercontent.com/7724641/46104333-246fc400-c1a1-11e8-869e-eab225114b35.png)

**Comment by beachwalker** [comment]
I have similar issue. Projection does not even show an image anymore in my case (local file). However, unprojected geocentric 3d works without problems instead.

**Comment by gwaldron** [comment]
afaict this is only happening in the "plate-carre" profile

**Comment by gwaldron** [comment]
What version of OSG are you on? Reason the believe this was th result of an OSG change.

**Comment by beachwalker** [comment]
I'm using OSG 3.6.3. I'm gonna try to test if this still works with the 3.4.1 then.

**Comment by beachwalker** [comment]
![image](https://user-images.githubusercontent.com/2715897/46259679-e514e080-c4dc-11e8-9525-1d12076f5aa1.png)

With OSG 3.4.1 using readymap_flat.earth.
