### ISSUE TITLE
bug: Z-Values with altitude-clamping = "terrain"

### ISSUE THREAD

**Issue by remoe** [gwaldron/osgearth#1218]
"altitude-clamping" "terrain" should discard the z values:

http://docs.osgearth.org/en/latest/references/symbology.html#altitude

But this is not true in the current master.

**Comment by gwaldron** [comment]
Is this in the context of an annotation? FeatureNode? FeatureModelLayer?

**Comment by remoe** [comment]
FeatureModelLayer

**Comment by gwaldron** [comment]
altitude-technique:scene is only supported for annotations, not for feature layers. Use altitude-technique:map instead and it will work.

"map" is supposed to be the default -- I need to see why it's not applying when you omit the altitude-technique altogether -- looking into it now.

**Comment by remoe** [comment]
altitude-clamping: "terrain";
altitude-technique: "map";

does not discard the Z value on my test.

**Comment by gwaldron** [comment]
Remove the quotes:

altitude-clamping: terrain;
altitude-technique: map;

**Comment by gwaldron** [comment]
Should be fixed - please test

**Comment by remoe** [comment]
Glenn, thanks, but i don't see a commit :)

**Comment by gwaldron** [comment]
oops try now :)

**Comment by remoe** [comment]
Tested. Works ;)
