### ISSUE TITLE
osgearth_package white gap

### ISSUE THREAD

**Issue by ClarkBo** [gwaldron/osgearth#1219]
Hi guys,
    I'm currently using osgearth 2.7 now. I have more than 800 tiff images of the same resolution which consists of the whole moon (except for the polar regions).  I used the  osgearth_package to generate the tms files.  But there are many white gaps appears on the globe. How can I solve them?
![qq 20181009105710](https://user-images.githubusercontent.com/26448838/46644404-afde5180-cbb2-11e8-9d3a-36869eda3b67.png)
![qq 20181009105747](https://user-images.githubusercontent.com/26448838/46644425-c7b5d580-cbb2-11e8-814c-dbdb6d40cee3.png)

    Here is my earth file. 

![image](https://user-images.githubusercontent.com/26448838/46644501-1499ac00-cbb3-11e8-8325-81da86c54a95.png)

    And here is my osgearth_package command:
    `osgearth_package --tms moon5.earth --max-level 9 --verbose --out G:\tms4`
Clark

**Comment by remoe** [comment]
Try to use latest master with REX engine.

**Comment by ClarkBo** [comment]
> Try to use latest master with REX engine.

Thanks, remoe. I will try it.

**Comment by gwaldron** [comment]
Another suggestion is to use gdal_buildvrt to create a VRT file, and then reference that from your earth file. This will usually be more efficient and less error-prone than telling osgEarth to load a folder full of files.

**Comment by ClarkBo** [comment]
> Another suggestion is to use gdal_buildvrt to create a VRT file, and then reference that from your earth file. This will usually be more efficient and less error-prone than telling osgEarth to load a folder full of files.

Thanks for your advice, gwaldron. I used the VRT file but the white gaps still exist. Then I set the image interpolation to bilinear  (in earth file) ,the white gaps all gone but a long  black gap appears.  

![qq 20181011154914](https://user-images.githubusercontent.com/26448838/46788711-4bb3bd00-cd6d-11e8-9e31-df12a096df00.png)

Here are the two tiles of 0 level.  Both of them have one pixel black edge in their left/right.

![0](https://user-images.githubusercontent.com/26448838/46788453-aef11f80-cd6c-11e8-8d7e-3efd52a17265.png)
![0](https://user-images.githubusercontent.com/26448838/46788459-b4e70080-cd6c-11e8-8cde-ff3cfebffec2.png)
Is there a way to get rid of the black edge? I'm still use osgearth2.7 by the way. Thanks~

**Comment by gwaldron** [comment]
Clark, it's not possible for us to tell from pics whether the issue is with the source data, with GDAL's compositing, or with osgEarth. We would be interested to know if you experience the same issue in osgEarth 2.9 / GDAL 2.x. I'd also recommend analyzing the source data to look for missing pixels, or to see whether adjoining files have truly adjoining extents.

**Comment by ClarkBo** [comment]
Hi, gwaldron. I searched the earth file reference of osgEarth 2.7 and set the feather_pixels( which may be deleted in the new version) to true, then the gaps all gone. Well, I really think that I should use a newer version. Thanks a lot.
