### ISSUE TITLE
bug: FMG crash with stress test / latest master

### ISSUE THREAD

**Issue by remoe** [gwaldron/osgearth#1221]
Tested with Win64 / VS2017. osgEarth https://github.com/gwaldron/osgearth/commit/2c398d223d68ea93e7b54f25f270861908ef4c4c

The test loads/unloads hundreds of different maps and fly to multiple locations.

It's a release build crash. Don't know if the callstack correct:

```
osgEarth::Features::FeatureModelGraph::queryAndSortIntoStyleGroups + 0x161
osgEarth::Features::FeatureModelGraph::build + 0x1009
osgEarth::Features::FeatureModelGraph::buildTile + 0x1005
osgEarth::Features::FeatureModelGraph::load + 0x369
osgEarth::Features::FeatureMaskLayer::setFeatureSourceLayer + 0x1141
osgDB::Registry::destruct + 0x384
osgDB::Registry::read + 0x2619
osgDB::Registry::readImplementation + 0x1568
osgDB::Registry::readNodeImplementation + 0x131
osgDB::Registry::readNode + 0x353
osgDB::DatabasePager::DatabaseThread::run + 0x2889
OpenThreads::SetProcessorAffinityOfCurrentThread + 0x717
```

doesn't release the current master the same memory like some commits before? On my stress test i had someting around 2GB memory usage. But now i have 4.2GB. 

And when i close the app it doesn't close ?! it hangs with ~3gb not released memory.

This behavior was not with https://github.com/gwaldron/osgearth/commit/47f1c8e1916335e3e1cd4fa09840e67baeb2fbdb

**Comment by gwaldron** [comment]
Remo, unfortunately, a release-mode stack trace like cannot help us find a problem -- the code path it describes is not possible.

**Comment by remoe** [comment]
ok, i reopen it when i can reproduce it.

**Comment by remoe** [comment]
The latest master from today does not eat so much memory like before ;)
