### ISSUE TITLE
Investigate usage of GDAL_SCOPED_LOCK

### ISSUE THREAD

**Issue by jasonbeverage** [gwaldron/osgearth#1223]
Can we loosen the requirements for GDAL_SCOPED_LOCK in certain situations to provide better concurrency?  For example can we rework the gdal driver so each thread has it's own GDALDataset instead of sharing it across threads to avoid locking?

**Comment by damiandixon** [comment]
This was the approach we took to avoid locking in each thread (last place I worked at).

Works quite well as long as you don't create too many GDALDatasets. The only concern we had was memory use with regards to caching but there are ways to limit the amount used.

**Comment by gwaldron** [comment]
31ab038c
