### ISSUE TITLE
Can't access to TritonContext

### ISSUE THREAD

**Issue by sirehna-openlab** [gwaldron/osgearth#1226]
And by extension, cannot access to osgEarth::Triton::Environment and osgEarth::Triton::Ocean classes.
We can't access TritonContext from TritonNode (it's defined as "protected"), and so we cannot configure Triton rendering from code.
Is there any particulary reason for this encapsulation?

**Comment by gwaldron** [comment]
There was a reason; I cannot recall exactly but it had something to do with linkage. In any case the Triton extension is being phased out in favor of the new TritonLayer which is part of the Triton nodekit. It will be easier to expose the API through the TritonLayer as we move forward.

**Comment by sirehna-openlab** [comment]
Ok, so we should move on to the new TritonLayer. But from what I know, the problem is the same with TritonLayer (at this time at least), no?

**Comment by gwaldron** [comment]
Correct you are.

**Comment by sirehna-openlab** [comment]
Hi,

So we play a little with the new Layer implementation of Triton plugin, and we have exactly the same problem as before, but were able to get around by adding two new functions to `TritonLayer`: 

```
osg::Drawable* getTritonDrawable() const;
TritonContext* getTritonContext() const;
```

This way, we can call directly Triton's SDK functions we need, and also inject planar reflection textures and transform matrix into `TritonDrawable` (using an upcast for this one). Do you think that such change could be added to osgearth main code base?

FYI, here the code of the 2 functions implementations (provided as a diff patch):

```
diff --git a/src/osgEarthTriton/TritonLayer b/src/osgEarthTriton/TritonLayer
index 8a4ea41ea..557d7a58a 100644
--- a/src/osgEarthTriton/TritonLayer
+++ b/src/osgEarthTriton/TritonLayer
@@ -29,6 +29,8 @@
 
 namespace osgEarth { namespace Triton
 {
+    // Pre-declaration.
+    class TritonContext;
 
     /**
      * Serializable options for initializing the TritonLayer.
@@ -149,6 +151,10 @@ namespace osgEarth { namespace Triton
 
         virtual osg::Node* getNode() const;
 
+        osg::Drawable* getTritonDrawable() const;
+
+        TritonContext* getTritonContext() const;
+
     protected: // Layer
 
         virtual void init();
diff --git a/src/osgEarthTriton/TritonLayer.cpp b/src/osgEarthTriton/TritonLayer.cpp
index 9e3ad3df9..5a48dc848 100644
--- a/src/osgEarthTriton/TritonLayer.cpp
+++ b/src/osgEarthTriton/TritonLayer.cpp
@@ -239,6 +239,28 @@ TritonLayer::getNode() const
     return _root.get();
 }
 
+osg::Drawable*
+TritonLayer::getTritonDrawable() const
+{
+    TritonDrawable* tritonDrawable = 0;
+    TritonLayerNode* tritonNode = static_cast<TritonLayerNode*>(_tritonNode.get());
+    if(tritonNode)
+        return tritonNode->_drawable;
+    else
+        return 0;
+}
+
+TritonContext*
+TritonLayer::getTritonContext() const
+{
+    TritonContext* tritonContext = 0;
+    TritonLayerNode* tritonNode = static_cast<TritonLayerNode*>(_tritonNode.get());
+    if (tritonNode)
+        return tritonNode->_TRITON;
+    else
+        return 0;
+}
+
 void
 TritonLayer::setMaskLayer(const osgEarth::ImageLayer* maskLayer)
 {
```

**Comment by sirehna-openlab** [comment]
Hi, 
I need tu use Triton Ship Wakes in osgEarth2.10
I can see ship wakes in my app with osgEarth before commit 7fbeedb4e9dbcbec63a935ae0846670db41b412f
But, I can't see the ship wakes in osgEarth since commit b480040e0ce95ab67b5e7cb3d3d541dacb375689

How can I use Triton Ship Wakes in osgEarth 2.10 ?


here, a diff patch for osgEarthTriton

[dev-7fbeedb4e9dbcbec63a935ae0846670db41b412f.txt](https://github.com/gwaldron/osgearth/files/2733425/dev-7fbeedb4e9dbcbec63a935ae0846670db41b412f.txt)

**Comment by gwaldron** [comment]
If still needed submit a PR
