### ISSUE TITLE
Default glsl shaders error

### ISSUE THREAD

**Issue by kostinio** [gwaldron/osgearth#1227]
ShaderFactory creates invalid shader when OSG_GL3_AVAILABLE set by osg library.

in src/osgEarth/ShaderFactory.cpp

> #if defined(OSG_GL3_AVAILABLE) || defined(OSG_GL4_AVAILABLE)
>#define GLSL_400 "400"
>#else
>#define GLSL_400 "400 compatibility"
>#endif
>
>    // use GLSL 400 if it's avaiable since that will give the developer
>   // access to double-precision types.
>    bool use400 = 
>        Registry::instance()->hasCapabilities() &&
>        Registry::capabilities().getGLSLVersionInt() >= 400;
>
>    std::string tcs_glsl_version(GLSL_400);
>    std::string tes_glsl_version(GLSL_400);
>
>    std::string vs_glsl_version = use400 ? GLSL_400 : GLSL_330;
>    std::string fs_glsl_version = use400 ? GLSL_400 : GLSL_330;
>    std::string gs_glsl_version = use400 ? GLSL_400 : GLSL_330;

Further usage of glsl variables gl_Vertex, gl_Normal, etc.. is impossible in a core profile and shader wont compile. 
Because of this there is nothing draws.

**Comment by gwaldron** [comment]
OSG and osgEarth work under the GL CORE profile. There is more to it than just setting OSG_GL3_AVAILABLE. Did you get the osgsimplegl3 example working?

**Comment by kostinio** [comment]
OSG library works fine with option OSG_GL3_AVAILABLE.
There is a problem with osgEarth built with OSG GL3. (this definition comes to osgEarth through osg/GL header)
shaderFactory from the code above produces glsl shader like this
>#version 400
>void main(void) {
>            vp_Vertex = gl_Vertex
>...
>}

For this shader version definition MUST contain compatibility option because gl_Vertext unavailable in core profile.
But in src/osgEarth/ShaderFactory.cpp compatibility option lacks for 4+ context and OSG_GL3_AVAILABLE definition.

**Comment by gwaldron** [comment]
Kostinio,
If you look at the GL3 [support instructions located here](https://github.com/openscenegraph/OpenSceneGraph/blob/master/examples/osgsimplegl3/osgsimplegl3.cpp#L121) it says that GL3 support requires you to disable a set of CMake variables. One of these is OSG_GL_FIXED_FUNCTION_AVAILABLE. When you disable that, OSG automatically enables vertex attribute aliasing. This feature in turn replaces occurances of legacy GLSL built-ins like "gl_Vertex" with modern attributes like "osg_Vertex" and passes them into the shader.

My understanding -- which may or may be correct -- is that trying to mix GL3 support with fixed-function pipeline support is ... not officially supported :) Granted it is a murky topic. You might want to ask for clarification on the osg-users mailing list.

In the meantime, I cobbled together a GL CORE help page [here](https://gist.github.com/gwaldron/a56b0e77e7fa8587b698717d21f9366d).

**Comment by kostinio** [comment]
Thanks a lot! It works. 
It could be a proper cmakeLists configuration which disables incompatible variables if OPENGL_PROFILE set to GL3 or OSG_GL3_AVAILABLE enabled.

**Comment by remoe** [comment]
@gwaldron, it would be great when this GL CORE help page goes to the official osgEarth documentation ;)
