### ISSUE TITLE
osgEarth::Annotation::ImageOverlay doesn't work with osgViewer::GraphicsWindowEmbedded 

### ISSUE THREAD

**Issue by kostinio** [gwaldron/osgearth#1234]
ImageOverlay works fine with GraphicsWindowX11, but it makes scene empty with GraphicsWindowEmbedded. Im running this code: https://pastebin.com/aP9pHVwU. Result is empty scene with correct clear color. I can keep default x11 context by commenting line 58 and it works, but it is a separate window.. If i dont add imageOverlay in line 75 its also ok, but when i add it in paintGL at 
arbitrary time, scene disappears.

**Comment by gwaldron** [comment]
There are known problems with QOpenGLWidget and using OSG render-to-texture cameras (which ImageOverlay uses) because QOpenGLWidget itself is an RTT implementation, IIRC. Consider using the older QGLWidget instead, or better yet use the osgQt library.

**Comment by kostinio** [comment]
Thank you, it works again :)
