### ISSUE TITLE
ImageOverlay can't be drawn over whole globe

### ISSUE THREAD

**Issue by kostinio** [gwaldron/osgearth#1235]
When I try to set longitude range more then 180 degrees (no matter throug Bounds, Corners or East/West), ImageOverlay no longer draws.

My primary purpose is to generate texture on each frame and draw it over whole Earth with respect to elevation layers. 
First problem is ImageLayer data format. It is a Image, not texture. I believe that this object has underlying GL_TEXTURE object but there should be some GPU<->CPU data exchanges when GL_TEXTURE becomes osg::Image. I use offscreen camera with attached Image to render and ImageLayers to wrap this over Earth. I think that there performs next copy operations: 
1) After native offscreen rendering with offscreen Camera underlying FBO, GL_TEXTURE data copies into attached to camera osg::Image: GPU->CPU
2) ImageLayer converts osg::Image to GL_TEXTURE to render it: CPU->GPU

If there was a way to attach texture, not an osg::Image to ImageLayer, it could be faster (I could attach texture, not osg::Image to offscreen Camera).
But now anyway i have to do trick to split Image by 2 parts to wrap it over whole Earth.

Do i do my task correct?
___
Sorry if it's not bugtracker format but i was tried to grant access to post on http://forum.osgearth.org/, and feedback forms seems to be broken, or i was just ignored.

**Comment by gwaldron** [comment]
Kostinio,

The ImageOverlay works by using a projected texture, so indeed it will only be able to cover 1/2 the globe (and the extremes will probably be a bit distorted in that case).

There's a fairly recent API addition to support this -- I am actually working it as we speak with the hope of squeezing it into version 2.10 before release. You have to inherit a class from ImageLayer and implement createTexture() to return a texture given a TileKey. How you create or update that texture is up to you.

**Comment by kostinio** [comment]
OK, Thank you.

**Comment by gwaldron** [comment]
I pushed an update; you can see the usage of createTexture in the osgearth_map example.

BTW, what is your forum ID? We must not have seen it come through.

**Comment by kostinio** [comment]
Nickname is "kostinio", email is "shkil-k@mail.ru". I didn't see any ID mentions.

**Comment by gwaldron** [comment]
I don't see it in the system. Try registering again.
