### ISSUE TITLE
How can I display online maps such as google  satellite images by osgearth?

### ISSUE THREAD

**Issue by zcwbnu** [gwaldron/osgearth#1239]
I want to show online map resources when connecting to the internet, does osgearth provides such a function ？

**Comment by gwaldron** [comment]
osgEarth supports streamed maps in open tiles formats such as TMS and WMS. You can find examples of how to use these in the tests folder in the repository.

Many commercial services, including Google, restrict access to users of their own products.

**Comment by zcwbnu** [comment]
Thank you! 
<image name="osm_mapnik" driver="xyz">
        <url>http://[abc].tile.openstreetmap.org/{z}/{x}/{y}.png</url>
        <profile>spherical-mercator</profile>
        <cache_policy usage="none"/>
    </image>
