### ISSUE TITLE
build osgearth_viewerIOS failed

### ISSUE THREAD

**Issue by showzh20** [gwaldron/osgearth#1241]
Xcode version:8.2
osg version:3.4.1 and 3.6.1
osgearth version:osgearth3.4.1 osgearth2.9 osgearth-master
When I've compiled all the libs successful,I tried build target  application_osgearth_viewer_ios and faied
<img width="1400" alt="wx20181115-153832 2x" src="https://user-images.githubusercontent.com/17865282/48540528-4cec8280-e8f5-11e8-9acd-99eee6bfc07d.png">
this is my building setting
<img width="851" alt="wx20181115-153900 2x" src="https://user-images.githubusercontent.com/17865282/48540538-5544bd80-e8f5-11e8-9e51-c57a8ab8a4f8.png">
<img width="878" alt="wx20181115-153945 2x" src="https://user-images.githubusercontent.com/17865282/48540542-58d84480-e8f5-11e8-99bb-175f4d1e18d8.png">

I tried osgearth2.9 osgearth2.8 and master it seems to have the same problem.
Did someone Experienced the same problems？
It would be appreciated if you could give me some advice

**Comment by EdYao** [comment]
Looks like a 3rdParty issue. Did you link to the 3rdParty lib property?
