### ISSUE TITLE
ON_DEMAND does not work with the REX engine

### ISSUE THREAD

**Issue by AlexGolyakov** [gwaldron/osgearth#1245]
OSG's ON_DEMAND frame scheme does not work with the REX engine on master and osgEarth 2.10. ON_DEMAND  work correctly with the MP engine.
viewer.setRunFrameScheme(viewer.ON_DEMAND);

**Comment by gwaldron** [comment]
74e0d56 addresses this.

**Comment by AlexGolyakov** [comment]
Thanks Glen. It is works.
