### ISSUE TITLE
a bug about osgEarthScreenSpaceLayoutRenderBin and DeclutterSourt

### ISSUE THREAD

**Issue by angribaby** [gwaldron/osgearth#1247]
Sorry for being not good at English.
OpenSceneGraph create RenderBin by call RenderBin::clone(in osgUtil::RenderBin::createRenderBin),but osgEarthScreenSpaceLayoutRenderBin just copy a pointer to SortCallback in that function,These cause several osgearthScreenSpaceLayoutRenderBins to have same pointer to one SortCallback (actually DeclutterSort), and when several osgearthScreenSpaceLayoutRenderBins simultaneously call DeclutterSort::SortImplementation, an access violation of DeclutterSort::_perCam will occur.

**Comment by gwaldron** [comment]
This is unexpected because DeclutterSort::_perCam is protected by a mutex.
Please post a debug stack trace.

**Comment by angribaby** [comment]
![osgearth](https://user-images.githubusercontent.com/15900340/48878129-0e991b00-ee41-11e8-8d37-9b6f3b3f6199.jpg)
the format of .dmp file is vs2015.I don't think you can debug it without .pdb file.so I uploaded a screenshot of conflict.The version of OSG is 3.6.0 and the version of osgEarth is 2.9.0

**Comment by angribaby** [comment]
Also I am wondering about the mutex you mentioned. Where is it?

**Comment by gwaldron** [comment]
The mutex is in the PerObjectFastMap class itself, in osgEarth/Containers.

**Comment by angribaby** [comment]
I don't think the mutex you mentioned can work. The variable named local(in osgEarth/ScreenSpaceLayout.cpp line 290) is a reference to an element inside the _perCam container. When a thread manipulates the local variable (the action is not protected by mutex)  and another thread call _perCam::get(will call vector::pushback) which will cause memory redistribution, the reference will be invalidated.

**Comment by gwaldron** [comment]
It's true that the internal member access is unprotected. But that access happens on a per-camera copy of the data structure. This code runs in the CULL traversal, and unless you are culling the same render stage twice at the same time in 2 separate threads (which I assumed was not possible) you will not get a conflict. Am I wrong? Are you using some kind of multi-camera or multi-window setup?

**Comment by angribaby** [comment]
Yes,you're right.I am using a CompositeViewer that contains two Viewers. One of the MapNode used has a coordinate system of CSTYPE_GEOCENTRIC, and the other uses a coordinate system of CSTYPE_PROJECTED. The Maps used by the two mapnodes are different, but the layers in the two maps are the same (via otherMap.AddLayer(map.GetLayerAt(i))), The ThreadedModel of CompositeViewer  is CullThreadPerCameraDrawThreadPerContext,  so both cameras are simultaneously CULL Tranversal.
I want to know what I need to do to achieve my above requirements(two Maps with different coordinate systems) if current practice is wrong,Should I copy the layers deeply?

**Comment by angribaby** [comment]
It  works well if the ThreadModel of CompositeViewer is DrawThreadPerContext.

I don't think the perCam can be used safely.
Thread1: in DeclutterSort::sortImplementation
                   PerCamInfo& local=_perCam::get(camera1) //local is reference to a variable in _perCam::_data::_data(type is vector)
                                 _mutex.lock()
                   use local to do something(will crash)

Thread2: in DeclutterSort::sortImplementation
                   PerCamInfo& local=_perCam::get(camera2)
                                  _mutex.lock()
                                  return _data[camera2] //fast_map::operator[]
                                            _data.push_back(entry(camera2,DATA())) //vector::push_back(cause memory redistribution, Thread1::local will be invalid)

The mutex in PerObjectFastMap only serialize the call to _perCam::get. Thread1 will get a variable named local after calling _perCam::get, but the variable will be invalid if thread2 call _perCam::get(cause memory redistribution).

**Comment by angribaby** [comment]
It works well if the ThreadModel of CompositeViewer is DrawThreadPerContext.

I don't think the perCam can be used safely.(please see the picture）
![222](https://user-images.githubusercontent.com/15900340/49781606-5e874580-fd4e-11e8-90ce-8e203770c120.jpg)



The mutex in PerObjectFastMap only serialize the call to _perCam::get. Thread1 will get a variable named local after calling _perCam::get, but the variable will be invalid if thread2 call _perCam::get(cause memory redistribution).

**Comment by angribaby** [comment]
That's my fault, I didn't check the latest version of OSGEARTH.

I will cherry-pick the fix into my local repository.Sorry to bother you. Thanks a lot.
