### ISSUE TITLE
Rex engine displays not sufficiently detailed level

### ISSUE THREAD

**Issue by Vic-Min** [gwaldron/osgearth#1248]
Rex engine displays the tiles of the wrong level, is not sufficiently detailed in comparison with the mp engine (rex – left picture, mp – right picture):
![diff](https://user-images.githubusercontent.com/35421250/48854807-d9021c80-edc3-11e8-82b6-4d8be2929dc4.png)

earth-file:
<map name="OpenStreetMap" type="geocentric" version="2">

    <image name="osm_mapnik" driver="xyz">
        <url>http://[abc].tile.openstreetmap.org/{z}/{x}/{y}.png</url>
        <profile>spherical-mercator</profile>
        <cache_policy usage="none"/>
        <attribution>&#169;OpenStreetMap contributors</attribution>
    </image>

    <options>
        <lighting>false</lighting>
        <terrain
            driver = "mp"
            min_tile_range_factor = "8"
        />
    </options>

    <viewpoints time="1.0">
        <viewpoint name="Boston" heading="0" height="0" lat="42.34425" long="-71.076262" pitch="-90" range="10000"/>
    </viewpoints>

</map> 

In the figures - the view from the viewpoint "Boston"

I used osg-3.6.3 and osgEarth-2.10

**Comment by gwaldron** [comment]
Resolution: adjust min_tile_range_factor or LOD scale as necessary. Comparison of MP and REX display characteristics is OBE
