### ISSUE TITLE
Bounds check in RTTPicker::pick is incomplete

### ISSUE THREAD

**Issue by 10110111** [gwaldron/osgearth#1250]
Currently, in `RTTPicker::pick` I see the [following code](https://github.com/gwaldron/osgearth/blob/master/src/osgEarthUtil/RTTPicker.cpp#L306):
```
    // check the bounds:
    if ( u < 0.0f || u > 1.0f || v < 0.0f || v > 1.0f )
        return false;
```
This misses the cases when `u==1 || v==1`. When this happens, in particular, for `v`, `SpiralIterator` will read past the end of the image data, because `_offsetY` will be equal to `h`, while the largest possible offset is `h-1` since it's indexed from 0.

This in particular happens with OpenSceneGraph before its [commit abd2fa53c4acede9acbca536c11922cfd9fcb00f](https://github.com/openscenegraph/OpenSceneGraph/commit/abd2fa53c4acede9acbca536c11922cfd9fcb00f), which sometimes lets `GUIEventAdapter::getY()` return height (when mouse cursor is at the topmost pixel).

The result is that we sometimes (when the data read appears >0 in `RTTPicker::checkForPickResult`) get garbage `ObjectID` in the `Callback::onHit()` implementation, which could also potentially collide with an existing id, resulting in false pick.

Same could happen for `u` coordinate. I don't how to reproduce this case, since there hasn't been any off-by-one bug in OSG (due to X coordinate not being inverted), but this is possible in `RTTPicker` anyway and should be fixed.

**Comment by gwaldron** [comment]
Can you please submit a PR? Thanks
