### ISSUE TITLE
Filter layers terrainshader are applied to

### ISSUE THREAD

**Issue by sirehna-openlab** [gwaldron/osgearth#1251]
When using terrainShader extension, the shader code is applied to all the layers of the map .

For example, we use terrainShader extension to render caustics on terrain which is below water level, and we do not want to apply such effect on the water layer itself.

It would be great to be able to filter (by name or type?) the layers shaders are applied on.

One other issue we have with the terrain shader is that input samplers filtering and texture size are hardcoded in the extension (but it's not a blocking behavior for us), and ideally, should be configurable in the earth file directly.

**Comment by gwaldron** [comment]
Sirehna,
You did not say with version of osgEarth you are using, but in version 2.10 you can apply a shader per-layer. Please see tests/glsl.earth for an example. (You can also do this is version 2.9 with the rex terrain engine.)

**Comment by sirehna-openlab** [comment]
Hello,

Good point, we recently switch from 2.9 to 2.10, I was not aware of this new feature, thanks for the highlight!

So, indeed, Layer have now on optionnal `<shader>` markup, but it's not as powerful as `<terrainShader>` is: it's not possible to specify `samplers` nor `uniforms` to be used by it. It would be great if those `<terrainShader>` features would be added to the layer `<shader>` markup!

**Comment by gwaldron** [comment]
Added this with the LayerShader construct
