### ISSUE TITLE
What is the difference between REX engine and MP engine?

### ISSUE THREAD

**Issue by zcwbnu** [gwaldron/osgearth#1259]
I'm using osgearth 2.5 now, and I want to update to latest version, I want to know what is the difference between REX engine and MP engine? Is the lastest version stable?  Can you help me ?Thank you!

**Comment by gwaldron** [comment]
osgEarth 2.10 is the latest stable release. REX is just our internal name for the default terrain engine. (MP is just the previous implementation and is still available only in legacy mode -- which means it will be there, but we will not be making any further improvements to it.)
