### ISSUE TITLE
WMS driver not working after updating to 2.10

### ISSUE THREAD

**Issue by omaralvarez** [gwaldron/osgearth#1264]
I was using osgEarth 2.8 and my WMS source was working properly. I have updated to osgEarth 2.10 and OSG 3.6.3 and my source is no longer working:

```xml
    <image name="PNOA-MA" driver="wms" visible="true">
        <url>http://www.ign.es/wms-inspire/pnoa-ma</url>
        <srs>EPSG:4326</srs>
        <layers>OI.OrthoimageCoverage</layers>
        <format>jpeg</format>
    </image>
```
I can see the GDAL elevation layer, but no aerial imagery.

I am using the REX terrain engine.

Am I doing something wrong? Have there been any changes to the WMS driver?

**Comment by gwaldron** [comment]
Not sure when this broke, but I pushed a patch to the 2.10 branch.

**Comment by omaralvarez** [comment]
This is indeed fixed with your patch. Thanks for the quick response.
