### ISSUE TITLE
Need help for Triton Ship Wakes in osgEarth2.10

### ISSUE THREAD

**Issue by sirehna-openlab** [gwaldron/osgearth#1265]
Hi,
I need tu use Triton Ship Wakes in osgEarth2.10
I can see ship wakes in my app with osgEarth before commit 7fbeedb
But, I can't see the ship wakes in osgEarth since commit b480040

How can I use Triton Ship Wakes in osgEarth 2.10 ?

here, a diff patch for osgEarthTriton
[dev-7fbeedb4e9dbcbec63a935ae0846670db41b412f.txt](https://github.com/gwaldron/osgearth/files/2733433/dev-7fbeedb4e9dbcbec63a935ae0846670db41b412f.txt)

**Comment by gwaldron** [comment]
Please submit code changes using a Pull Request -- thanks!
