### ISSUE TITLE
WCS driver HTTP request failed

### ISSUE THREAD

**Issue by omaralvarez** [gwaldron/osgearth#1267]
I have been testing the following elevation layer in osgEarth 2.10:

```xml
    <elevation name="MDT-200" driver="wcs">
        <url>http://www.ign.es/wcs-inspire/mdt</url>
        <identifier>Elevacion4258_200</identifier>
        <format>tiff</format>
    </elevation>
```

I'm getting the following error:

```
[osgEarth]* [osgEarth::WCS1.1] WARNING: HTTP request failed
```

Service info:

```
http://www.ign.es/wcs-inspire/mdt?version=2.0.1&request=GetCapabilities&service=WCS
```

I think it has to do with the fact that the service is using WCS 2.0.1, but not sure why it is not working.

**Comment by gwaldron** [comment]
The WCS driver is *very* old and very rarely used, so unfortunately it's no surprise that it doesn't work with a newer service. Wish I could offer more help.

**Comment by omaralvarez** [comment]
No problem. Thanks for the response, I would like to pick your brain on a subject related to this.

Right now I have a pretty big DEM (250 GB), I could maybe get by using a smaller DEM (9GB). Its made up of thousands of GeoTIFFs. When using it with:

```xml
    <elevation name="PNOA-MDT25" driver="gdal">
        <url>/mnt/data/MDT_25</url>
    </elevation>
```

DEM loading is extremely slow even when dealing with small parts of the terrain. I have tried to create a TMS with the elevation data using `osgearth_package`, but the resulting TMS has no elevation data. I have also tried to use `osgearth_cache --seed` with no luck, the resulting cache has no elevation data (although cache works fine using a custom viewer, don't know what is happening with elevation). Both of these work well for imagery.

My question:

How to deal with precise DEMs? Any way to speed up elevation loading? Is there any issue with elevation data and these tools?

If needed I can provide data samples.

**Comment by gwaldron** [comment]
Don't use the "load everything from a folder" feature -- it's slow, it's limited, and it's going away in the next version.

I suggest that you (a) use GDAL to construct a VRT that combines all your elevation TIFFs; and then (b) use [osgearth_conv ](http://docs.osgearth.org/en/latest/data.html#tips-for-preparing-your-own-data) to tile the data into either an MBTiles database (local use) or a TMS repository (server use).
