### ISSUE TITLE
Intel video adapter mesa driver 13.0.6, error: GLSL 3.30 is not supported

### ISSUE THREAD

**Issue by oldbay** [gwaldron/osgearth#1270]
Question based on:
https://embeddeddevelop.blogspot.com/2018/07/intel-gpu-building-osg-and-osgearth-for.html
https://embeddeddevelop.blogspot.com/2018/07/linux-osgearth-opengl-coreprofile.html
https://embeddeddevelop.blogspot.com/2018/07/linux-osgearth-and-qt-with-coreprofile.html

Described error:
VERTEX glCompileShader "oe_LineDrawable_VS_VIEW" FAILED
VERTEX Shader "oe_LineDrawable_VS_VIEW" infolog:
0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.00 ES, 3.00 ES, 3.10 ES, and 3.20 ES

Error for my, if start osgearth_viewer (ver 2.10) on intel video adapter.

Will it help me only "cmake ../OpenSceneGraph -DOPENGL_PROFILE=GLCORE -DCMAKE_PREFIX_PATH=/opt/Qt/5.6.3/gcc_64/lib/cmake" or need redact code and add string "osg::DisplaySettings::instance()->setGLContextVersion("4.5");" to osgearth_viewer.cpp?

P.S: I'm little sign with C++. I'm trying to work with osgEarth in my Python project. Sorry for my English :).

**Comment by gwaldron** [comment]
Building with GLCORE support requires some additional steps. Here's a quick guide that we typed up to assist in the process:
https://gist.github.com/gwaldron/a56b0e77e7fa8587b698717d21f9366d

Also make sure you do have the latest drivers of course!

**Comment by oldbay** [comment]
Thank You for response!
