### ISSUE TITLE
Instancing.vert.glsl: explane decoding the ObjectID

### ISSUE THREAD

**Issue by KhochkinNick** [gwaldron/osgearth#1275]
file path: **osgearth-2.10\src\osgEarth\Instancing.vert.glsl**

Part of code:	
```
void oe_di_setInstancePosition(inout vec4 VertexMODEL)
{ 
    int index = 4 * gl_InstanceID;

    vec4 m0 = texelFetch(oe_di_postex_TBO, index);
    vec4 m1 = texelFetch(oe_di_postex_TBO, index+1); 
    vec4 m2 = texelFetch(oe_di_postex_TBO, index+2); 
    vec4 m3 = texelFetch(oe_di_postex_TBO, index+3);

    // decode the ObjectID from the last column:
    
    oe_index_objectid = uint(m3[0]) + (uint(m3[1]) << 8u) + (uint(m3[2]) << 16u) + (uint(m3[3]) << 24u);
    
    // rebuild positioning matrix and transform the vert. (Note, the matrix is actually
```
Question the following line
`oe_index_objectid = uint(m3[0]) + (uint(m3[1]) << 8u) + (uint(m3[2]) << 16u) + (uint(m3[3]) << 24u);`
Does variable `vec4 m3` contain a color in format (RGBA) or in "inversing" format (ABGR)?
In my opinion here is using decoding of ObjectID from "inversing" format (ABGR).
But in other osgEarth 2.10 code ObjectID-coding to color `vec4` is doing in format (RGBA)
(examples in 
	**osgEarthUtil\RTTPicker.glsl**:

```
// encode the objectID as a vec4 (color)
#ifdef USE_BITWISE_MATH
        uint u0 = (oe_index_objectid & 0xff000000u) >> 24u;
        uint u1 = (oe_index_objectid & 0x00ff0000u) >> 16u;
        uint u2 = (oe_index_objectid & 0x0000ff00u) >> 8u;
        uint u3 = (oe_index_objectid & 0x000000ffu);
#else
        uint u0 = (oe_index_objectid / 16777216u);
        uint u1 = (oe_index_objectid / 65536u) - (u0 * 256u);
        uint u2 = (oe_index_objectid / 256u) - (u1 * 256u) - (u0 * 65536u);
        uint u3 = (oe_index_objectid) - (u2 * 256u) - (u1 * 65536u) - (u0 * 16777216u);
#endif
```

**osgEarthUtil\RTTPicker.cpp**:

```
ObjectID id = (ObjectID)(
            ((unsigned)(value.r()*255.0) << 24) +
            ((unsigned)(value.g()*255.0) << 16) +
            ((unsigned)(value.b()*255.0) <<  8) +
            ((unsigned)(value.a()*255.0)));
).
```
Is it bug of decoding of `ObjectID`?
Or has `vec4 m3` an "inversing" format (i.e. ABGR)?

**Comment by gwaldron** [comment]
I will say there is no error. The picking examples that rely on this encoded appear to be working fine. Are you seeing otherwise?

**Comment by KhochkinNick** [comment]
If the selection `void oe_di_setInstancePosition(inout vec4 VertexMODEL)` works, then the feature is how the `m3` values ​​are written.
Сomparing line
`oe_index_objectid = uint(m3[0]) + (uint(m3[1]) << 8u) + (uint(m3[2]) << 16u) + (uint(m3[3]) << 24u);`
and line
```
ObjectID id = (ObjectID)(
            ((unsigned)(value.r()*255.0) << 24) +
            ((unsigned)(value.g()*255.0) << 16) +
            ((unsigned)(value.b()*255.0) <<  8) +
            ((unsigned)(value.a()*255.0)));
```
I think that
`m3[0] == value.a()*255.0`
`m3[1] == value.b()*255.0`
`m3[2] == value.g()*255.0`
`m3[3] == value.r()*255.0`
It seemed to me that by default **OpenGL** color `vec4` coding in **RGBA**. But `vec4 m3` coding in **ABGR** (
it seems to me).
I think that data `vec4 m3` stored in `texelFetch` 
(`vec4 m3 = texelFetch(oe_di_postex_TBO, index+3);`)
in that inverse format **ABGR (Alpha-Blue-Green-Red)**.

I do not approve that the code is not working (`void oe_di_setInstancePosition(inout vec4 VertexMODEL)`).
I can’t understand exactly when it is called.
**I trust your statement about its work well**.
