### ISSUE TITLE
can not open PostGIS database by version 2.10

### ISSUE THREAD

**Issue by jonaydy** [gwaldron/osgearth#1277]
I updated the program form osgEarth 2.9(osg 3.4) to osgEarth 2.10(osg 3.6.1), however the connection to postgis is no longer working:

    _<feature_model name="roadnet" driver="feature_geom">
	    <features driver="ogr">
		<connection>PG:dbname=earth-chengdu host=localhost port=5432 user=postgres 
                    password=ydy831128</connection>
		<layer>roadrednet</layer>
	    </features>
    </feature_model>_ 

the command line said: 
    _Resource unavailable :Failed to open"PG:dbname=earth-chengdu host=localhost port=5432 user=postgres password=ydy831128"_

**Comment by gwaldron** [comment]
Were you able to resolve? We don't have a PG test environment (PG access goes through GDAL) so cannot repro this one.

**Comment by dengzengjian** [comment]
Hi！Have u solve it ?this problem is happened  to me
