### ISSUE TITLE
osgearth2.10.0 white earth

### ISSUE THREAD

**Issue by zcwbnu** [gwaldron/osgearth#1279]
I used vcpkg building osgearth 2.10.0 successfully. However earth displays white globe when loading tms data.
`<image name="world-l5"  driver="tms">
      <url>world\tms.xml</url>
  </image>`

my tms.xml as follows：
[tms.zip](https://github.com/gwaldron/osgearth/files/2825222/tms.zip)
![oe1](https://user-images.githubusercontent.com/18117662/52173235-60eca580-27bb-11e9-95dd-44cc1491709a.PNG)

![oe2](https://user-images.githubusercontent.com/18117662/52174498-8e434e80-27cf-11e9-86f6-26525a1eada3.PNG)
![oe3](https://user-images.githubusercontent.com/18117662/52174524-1cb7d000-27d0-11e9-9336-b730df23e98b.PNG)

**Comment by zcwbnu** [comment]
I use osgearth2.5 add same data ,the map can be displayed normally

**Comment by gwaldron** [comment]
Make sure proj4.dll (or similar) is in your path; and make sure you don't have multiple versions or instances of GDAL and its DLL's in your path.

**Comment by zcwbnu** [comment]
@gwaldron Thank you! This problem is solved. vcpkg  generated directory “installed ” does not have osgPlugins dll ,so can't handle png/jpg file.
