### ISSUE TITLE
No translation for an empty SRS to PROJ.4

### ISSUE THREAD

**Issue by zcwbnu** [gwaldron/osgearth#1283]
I build osgearth2.10 by vcpkg. It can add .tif file normal，but can’t add shp file. I use osgearth_viewer feature_geom.earth, it can't load usa.shp. Sometimes it always Unable to load PROJ.4 library,but I have the proj_4_9.dll.
![1](https://user-images.githubusercontent.com/18117662/52789213-3396d600-309e-11e9-9137-911e26a2c14e.PNG)

![default](https://user-images.githubusercontent.com/18117662/52789951-46120f00-30a0-11e9-96b4-44dbcb235f33.PNG)

**Comment by gwaldron** [comment]
Make sure that the vcpkg `installed/x86-windows/bin` folder is in your path, and that your GDAL_DATA environment variable is set to `installed/x86-windows/share/gdal`.

**Comment by zcwbnu** [comment]
@gwaldron ，Extremely grateful！it works! Thank you and your great work osgearth！
