### ISSUE TITLE
 Is AnnotationEventHandler removed?

### ISSUE THREAD

**Issue by zcwbnu** [gwaldron/osgearth#1284]
I implemented placeNode click event function in osgearth2.5, now  I can't find AnnotationEventHandler after  upgrade osgearth2.5 to 2.10.  Is AnnotationEventHandler removed? I found osgearth_annotation application has removed placeNode click function. How can I implement this function in osgearth2.10？

**Comment by gwaldron** [comment]
Yes, long gone. Please refer to the osgearth_pick example for a newer approach.
