### ISSUE TITLE
How was  

### ISSUE THREAD

**Issue by petersadro** [gwaldron/osgearth#1287]
I am looking at running the splat examples, but the file is missing as shown in a previous bug submission ( closed by the author )

I founfd the original source of the file here: http://due.esrin.esa.int/files/GLOBCOVER_L4_200901_200912_V2.3.tif

I was wondering what you used to generate the tiled version of the file ( i.e. which gdal commands )

Pete

**Comment by gwaldron** [comment]
[Take a look here](http://docs.osgearth.org/en/latest/data.html#tips-for-preparing-your-own-data), at the section entitled "building internal tiles".
