### ISSUE TITLE
LineDrawable shaders missing GLES precision qualifiers

### ISSUE THREAD

**Issue by gwaldron** [gwaldron/osgearth#1290]
Like it says. Won't work on GLES because of this.

**Comment by EdYao** [comment]
@gwaldron I'd like to provide some help to solve this problem, but don't know what can I do. Can you give me some advice?

**Comment by EdYao** [comment]
To make LineDrawable shaders work, What should I do?

**Comment by gwaldron** [comment]
Fixed in 55c2709.
