### ISSUE TITLE
Crash in glDrawElements when rendering text (e.g. of PlaceNode) using core GL context

### ISSUE THREAD

**Issue by Himbeertoni** [gwaldron/osgearth#1294]
I'm using the current osgEarth master with current OSG 3.6.4 on Linux Debian (Nvidia proprietary driver). osgEarth is rendered as part of a QML application using  QQuickFramebufferObject, OSG is configured to use a core GL context ("GLCORE"). 
Rendering works (osgEarth globe gets rendered), until I add a PlaceNode/LabelNode with Text, this results in a segfault in glDrawElements: 
![callstack_crash_gldrawelements](https://user-images.githubusercontent.com/2862477/53640254-116b8f00-3c2c-11e9-9723-c4f9caa78346.png)

I found this post via Google: http://forum.openscenegraph.org/viewtopic.php?t=17481, which suggests setting the node to DYNAMIC but I did that (placeNode->setDynamic(true);) without effect. If I configure 
OSG to use a legacy/compatibility context it works, i.e. the text gets rendered without any crash

**Comment by gwaldron** [comment]
Alexander,
There's not a whole lot we can say about this - are you able to reproduce the issue with a minimal osgEarth example?
