### ISSUE TITLE
How to get image layer's geoExtent?

### ISSUE THREAD

**Issue by zcwbnu** [gwaldron/osgearth#1295]
I  want to implement a function that the earth can manipulated to  a fixed viewpoint automatically where is the center of image when adding a new layer.
I need to get the geoextent of a layer at run time, however I found layer->getProfile() always return null. How can I get layer's center positon?
This is my code:
   GDALOptions gdal;
   gdal.url() = "c:/data/srtm.tif";
   ImageLayer* layer = new ImageLayer( "img", gdal );
   map->addImageLayer( layer ); 
   layer->getPfofile();//reuturn null
   layer->getExtent();//return null

**Comment by gwaldron** [comment]
This works in newer versions of osgEarth -- consider upgrading.

**Comment by zcwbnu** [comment]
My osgearth was built with vcpkg. Vcpkg always use osgearth version "gwaldron-osgearth-osgearth-2.10.tar.gz" .  I downloaded a new version of osgearth-master and replaced the old version with the latest version , however vcpkg always reported an error :
Building package osgearth failed with: BUILD_FAILED
Please ensure you're using the latest portfiles with .\vcpkg update, then
submit an issue at https://github.com/Microsoft/vcpkg/issues including:
Vcpkg version: 2018.11.23-nohash.

So how can I upgrading my osgearth with vcpkg?

**Comment by gwaldron** [comment]
I can't answer your vcpkg question; but the getExtent should work with osgEarth 2.10.

**Comment by zcwbnu** [comment]
Thank you! I found vcpkg download url is https://github.com/gwaldron/osgearth/archive/osgearth-2.10.tar.gz, I can't open it in browser，Is it the lastest？

**Comment by gwaldron** [comment]
2.10 is the latest release.
