### ISSUE TITLE
ElevationLayer createHeightField with nodata_policy=NODATA_MSL

### ISSUE THREAD

**Issue by AJarrier** [gwaldron/osgearth#1297]
There is a crash, when we load an .earth file containing an elevation part with `nodata_policy="msl"` option.

Example : [multiple_heightfields.earth](https://github.com/gwaldron/osgearth/files/2935543/multiple_heightfields.earth.txt)

### Code
If we look at the [code](https://github.com/gwaldron/osgearth/blob/master/src/osgEarth/ElevationLayer.cpp#L673), `hf` is never set if `result` is valid and with `nodata_policy="msl"` option we try to access to this (null) pointer.

**Comment by gwaldron** [comment]
Thanks for this. Fixed in the master.
However-- we haven't revisited this property in a long time and I'm not sure setting it has an effect. :)
