### ISSUE TITLE
Visual defects with two OSG views

### ISSUE THREAD

**Issue by Himbeertoni** [gwaldron/osgearth#1300]
Hi, I am using the current osgEarth, rendered into a QQuickFramebufferObject inside a QML application. I use two osgViewer::Views with separate camera manipulators  in the osgViewer and blit the color buffer of the second view into the lower left corner. I somehow get the following visual defects:  
![osgEarth_rendering_issues](https://user-images.githubusercontent.com/2862477/54222450-bc662d80-44f5-11e9-9be1-46bad4093a1f.png)
Also, sometimes parts of the globe geometry is missing in either view. The issue seems to be related to the horizon culling because the effect varies based on the camera movement and the visibility of the PlaceNode. Do you have any idea what could cause such an issue?

**Comment by Himbeertoni** [comment]
Unfortunately the issue is still current, with current osgEarth 2.10 and OSG 3.7. I even tested running the osgEarth 3.0 branch, no difference.  In the attached GIF, you see the globe rotating and depending on the view, the map imagery layer becomes completely pixelated/low resolution. In other cases, parts of the globe become invisible.
  
![test2](https://user-images.githubusercontent.com/2862477/62475178-d48c6100-b7a4-11e9-841b-0a979ff14640.gif)

(Note that there is another window which shows the same scene, however I am unable to show both windows in the same gif)

Currently, there is a custom osg::Geometry node under a osgEarth::Annotation::GeoPositionNode, but the error occurs with any "Icon"/Annotation (e.g. PlaceNode with an osgImage). 
I tried using separate GL contexts and shared GL contexts, separate osgEarth map instances and a shared map instance between the views, CompositeViewers and regular Viewers. I tried 24-bit and 32-bit float depth/stencil formats for the FBO. I tried all kinds of REX terrain options, none seemed to have an effect. There are _no_ OpenGL errors. 
I am completely at loss what could be creating this error. 

Browsing the forum I found some other unadressed/unsolved threads which seem to refer to the same issue, which makes me think this issue exists for a long time:
"Strange effect with multiple views" (http://forum.osgearth.org/Strange-effect-with-multiple-views-td7591185.html) and 
"Texture disappears when more than two earth are created using CompositeViewer" (http://forum.osgearth.org/Texture-disappears-when-more-than-two-earth-are-created-using-CompositeViewer-td7592213.html)

What happens during horizon culling of annotations that could cause the switch to the low resolution? Does osgEarth use some kind of global state that is shared between multiple views? 

Any hint for something else I could try would be very much appreciated!

**Comment by gwaldron** [comment]
I don't know whether it's the same problem, but perhaps this will help:
http://forum.osgearth.org/solved-black-screen-with-drape-mode-in-a-QOpenGLWidget-td7592420.html#a7592421

Basically OSG needs to know if Qt is rendering to an FBO, otherwise the OpenGL state will get messed up. Hope this helps.

**Comment by Himbeertoni** [comment]
Thank you for the quick response. I have seen this thread before, and it did fix the issue I also encountered when using osgEarth styles with draping (if any annotation used a style with draping technique, the rendering would not update, therefore the application seemed to be "frozen"). After restoring the FBO, the rendering would update and I could see the draped geometry. 

However, unfortunately that seems unrelated to the aforementioned issue.  For the geometry shown in the GIF, I don't use draping and I even removed all usages from the code. The call to setDefaultFboId() is being made before calling frame() on the viewer. But calling setDefaultFboId() or not has no effect on the issue.

To me, it seems that if annotations are visible in two views the culling state "becomes confused" and thinks it can lower the resolution because the current view is not visible although it is? Is there a way to never "cache" the horizon culling result between calls to frame()? Calling setHorizonCulling(false) on the geometry/annotation did not help with the issue. I am not aware of the internals of neither OSG nor osgEarth, so I am just guessing.

**Comment by gwaldron** [comment]
Horizon culling is a cull-time calculation and so the result will be different for each camera. There should be nothing shared between views..

Perhaps you can modify the osgearth_windows example to demonstrate the problem? That would at least give us a way to reproduce it. Let me know if you think this is a viable option.

**Comment by Himbeertoni** [comment]
I could not reproduce it with the osgearth_windows example, I suspect it has to to something with the fact that an externally created window is used to render into. However, I created a reproducer application with Qt5, which can be cloned from https://github.com/Himbeertoni/QmlOsgEarthTest
The reproducer requires Qt5, OSG and osgEarth and can be build with CMake. This screenshot shows the window after application launch:
![osge](https://user-images.githubusercontent.com/2862477/63040004-cb964080-bec4-11e9-8261-664f7aa85e90.gif)
The application creates a window with two separate OSG views with separate osgEarth maps and a single PlaceNode annotation. Depending on the view the graphic defects are visible. The occurrence of the  defects seem to correlate with the visibility of the PlaceNode. It would be great if you could have a look at it. Thank you!

**Comment by Himbeertoni** [comment]
I'm happy to report that the issue seems to have been fixed for a few months now. The cause of the actual issue remains unknown to us. Currently, we're using OSG master bd50af117bed340b14b5bf13da6a8efe893f4ce7 and osgEarth master 5c0c2a322d3db432a8dac73cac34dc21c6b2e1d6, and we have not yet encountered any graphical glitches since then.

**Comment by JasonStepan** [comment]
I have the same problem as you, the osg version I use is 3.6.5, and the osgEarth version is 3.2, I don't know how to solve it now, can you give me some ideas?
