### ISSUE TITLE
Visual defects when using LODBlending and BrightnessContrastColorFilter together

### ISSUE THREAD

**Issue by farz4d** [gwaldron/osgearth#1301]
When adding LODBlending effect to terrain engine and BrightnessContrastColorFilter to an image layer, the BrightnessContrastColorFilter does not work properly.

**Comment by gwaldron** [comment]
The LODBlending class is obsolete now as blending is built into the osgEarth 2.10 terrain engine. The ColorFilters are also deprecated with the advent of layer shaders.
