### ISSUE TITLE
2.10: Crashes in GraphicsContext::runOperations() while we unload/load maps

### ISSUE THREAD

**Issue by remoe** [gwaldron/osgearth#1305]
We have sometimes crashes here:

```c++
void GraphicsContext::runOperations()
{
    // sort the cameras into order
    typedef std::vector<Camera*> CameraVector;
    CameraVector camerasCopy;
    std::copy(_cameras.begin(), _cameras.end(), std::back_inserter(camerasCopy));
    std::sort(camerasCopy.begin(), camerasCopy.end(), CameraRenderOrderSortOp());

    for(CameraVector::iterator itr = camerasCopy.begin();
        itr != camerasCopy.end();
        ++itr)
    {
        osg::Camera* camera = *itr;
>>>>>>>        if (camera->getRenderer()) (*(camera->getRenderer()))(this);
    }
```

when we unload/load maps. The camera pointer is invalid:

  | Name | Value | Type
-- | -- | -- | --
◢ | camera | 0x000001e824247350 {_dataChangeMutex={_prvData=0xdddddddddddddddd _mutexType=MUTEX_RECURSIVE \| -572662308 (-572662307) } ...} | osg::Camera *
  | ▶ osg::Transform | {_referenceFrame=ABSOLUTE_RF \| -572662308 (-572662307) } | osg::Transform
  | ▶ osg::CullSettings | {_inheritanceMask=-572662307 _inheritanceMaskActionOnAttributeSetting=DO_NOT_MODIFY_INHERITANCE_MASK \| -572662308 (-572662307) ...} | osg::CullSettings
  | ▶ _dataChangeMutex | {_prvData=0xdddddddddddddddd _mutexType=MUTEX_RECURSIVE \| -572662308 (-572662307) } | OpenThreads::Mutex
  | ▶ _view | 0xdddddddddddddddd {_stats={_ptr=??? } _lightingMode=??? _light={_ptr=??? } ...} | osg::View *
  | ▶ _stats | {_ptr=0xdddddddddddddddd {_name={...} _mutex={_prvData=??? _mutexType=??? } _baseFrameNumber=??? ...} } | osg::ref_ptr<osg::Stats>
  | _allowEventFocus | true (221) | bool
  | ▶ _displaySettings | {_ptr=0xdddddddddddddddd {_displayType=??? _stereo=??? _stereoMode=??? ...} } | osg::ref_ptr<osg::DisplaySettings>
  | _clearMask | 3722304989 | unsigned int
  | ▶ _clearColor | {_v=0x000001e8242474dc {-1.99839716e+18, -1.99839716e+18, -1.99839716e+18, -1.99839716e+18} } | osg::Vec4f
  | ▶ _clearAccum | {_v=0x000001e8242474ec {-1.99839716e+18, -1.99839716e+18, -1.99839716e+18, -1.99839716e+18} } | osg::Vec4f
  | _clearDepth | -1.4568159901474629e+144 | double

**Comment by gwaldron** [comment]
Remo, unfortunately there is not enough information here for debugging. Can you discover which Camera is at fault? Are you destroying and creating Views?

**Comment by remoe** [comment]
I don't destroy any views. It has 9 cameras in the "camerasCopy" and 7 are invalid. I'm not sure which camera, because it's invalid. But it cloud be such a camera:


  | Name | Value | Type
-- | -- | -- | --
◢ | [1] | 0x0000012bb14c4370 {_dataChangeMutex={_prvData=0x0000012bc5c9b3e0 _mutexType=MUTEX_NORMAL (0) } _view=...} | osg::Camera *
  | ▶ osg::Transform | {_referenceFrame=ABSOLUTE_RF_INHERIT_VIEWPOINT (2) } | osg::Transform
  | ▶ osg::CullSettings | {_inheritanceMask=2147082238 _inheritanceMaskActionOnAttributeSetting=DISABLE_ASSOCIATED_INHERITANCE_MASK_BIT (0) ...} | osg::CullSettings
  | ▶ _dataChangeMutex | {_prvData=0x0000012bc5c9b3e0 _mutexType=MUTEX_NORMAL (0) } | OpenThreads::Mutex
  | ▶ _view | 0x0000012bbc59acc0 {_viewerBase={_reference={_ptr=0x0000012bb14ca8e0 {_mutex={_prvData=0x0000012bb16bd450 ...} ...} } ...} ...} | osg::View * {osg158-osgViewerd.dll!osgViewer::View}
  | ▶ _stats | {_ptr=0x0000000000000000 <NULL> } | osg::ref_ptr<osg::Stats>
  | _allowEventFocus | true | bool
  | ▶ _displaySettings | {_ptr=0x0000000000000000 <NULL> } | osg::ref_ptr<osg::DisplaySettings>
  | _clearMask | 16640 | unsigned int
  | ▶ _clearColor | {_v=0x0000012bb14c44fc {1.00000000, 1.00000000, 1.00000000, 0.000000000} } | osg::Vec4f
  | ▶ _clearAccum | {_v=0x0000012bb14c450c {0.000000000, 0.000000000, 0.000000000, 1.00000000} } | osg::Vec4f
  | _clearDepth | 1.0000000000000000 | double
  | _clearStencil | 0 | int
  | ▶ _colorMask | {_ptr=0x0000000000000000 <NULL> } | osg::ref_ptr<osg::ColorMask>
  | ▶ _viewport | {_ptr=0x0000012bc7e1e310 {_x=0.00000000000000000 _y=0.00000000000000000 _width=2048.0000000000000 ...} } | osg::ref_ptr<osg::Viewport>
  | _transformOrder | PRE_MULTIPLY (0) | osg::Camera::TransformOrder
  | _projectionResizePolicy | HORIZONTAL (1) | osg::Camera::ProjectionResizePolicy
  | ▶ _projectionMatrix | {_mat=0x0000012bb14c4548 {0x0000012bb14c4548 {2.1786431914662856e-06, 0.00000000000000000, 0.00000000000000000, ...}, ...} } | osg::Matrixd
  | ▶ _viewMatrix | {_mat=0x0000012bb14c45c8 {0x0000012bb14c45c8 {-0.14389402537557094, -0.71902151993906394, 0.67992835161194243, ...}, ...} } | osg::Matrixd
  | _renderOrder | PRE_RENDER (0) | osg::Camera::RenderOrder
  | _renderOrderNum | 0 | int
  | _drawBuffer | 1028 | unsigned int
  | _readBuffer | 1028 | unsigned int
  | _renderTargetImplementation | FRAME_BUFFER_OBJECT (0) | osg::Camera::RenderTargetImplementation
  | _renderTargetFallback | PIXEL_BUFFER_RTT (1) | osg::Camera::RenderTargetImplementation
  | ▶ _bufferAttachmentMap | { size=1 } | std::map<enum osg::Camera::BufferComponent,osg::Camera::Attachment,std::less<enum osg::Camera::BufferComponent>,std::allocator<std::pair<enum osg::Camera::BufferComponent const ,osg::Camera::Attachment> > >
  | _implicitBufferAttachmentRenderMask | 0 | int
  | _implicitBufferAttachmentResolveMask | 0 | int
  | _attachmentMapModifiedCount | 0 | unsigned int
  | ▶ _affinity | {activeCPUs={ size=0 } } | OpenThreads::Affinity
  | ▶ _cameraThread | {_ptr=0x0000000000000000 <NULL> } | osg::ref_ptr<osg::OperationThread>
  | ▶ _graphicsContext | {_ptr=0x0000012bb1738c80 {_currentCursor=0x0000000000010003 {unused=??? } _windowProcedure=0x0000000000000000 ...} } | osg::ref_ptr<osg::GraphicsContext>
  | ▶ _renderer | {_ptr=0x0000000000000000 <NULL> } | osg::ref_ptr<osg::GraphicsOperation>
  | ▶ _renderingCache | {_ptr=0x0000012bc5f93850 {_mutex={_prvData=0x0000012bc5ca0310 _mutexType=MUTEX_NORMAL (0) } _renderStageMap=...} } | osg::ref_ptr<osg::Object>
  | ▶ _initialDrawCallback | {_ptr=0x0000000000000000 <NULL> } | osg::ref_ptr<osg::Camera::DrawCallback>
  | ▶ _preDrawCallback | {_ptr=0x0000000000000000 <NULL> } | osg::ref_ptr<osg::Camera::DrawCallback>
  | ▶ _postDrawCallback | {_ptr=0x0000000000000000 <NULL> } | osg::ref_ptr<osg::Camera::DrawCallback>
  | ▶ _finalDrawCallback | {_ptr=0x0000000000000000 <NULL> } | osg::ref_ptr<osg::Camera::DrawCallback>

**Comment by remoe** [comment]
Glenn, I reset the mapnode (unloading maps). I don't destroy mapview.

**Comment by remoe** [comment]
It doesn't crash when I call viewer->stopThreading(), replace the mapnode and add all handlers and run viewer->startThreading(). Is it because of this:

https://github.com/gwaldron/osgearth/blob/c145e17fa8800d161be3de8a8f9cea7a68f26ada/src/osgEarthUtil/RTTPicker#L37

?

**Comment by gwaldron** [comment]
I am closing this since RTTPicker has been superceded by ObjectIDPicker which does not use slave cameras.
If the problem persists you can re-open or open a new issue.
