### ISSUE TITLE
As a support of omnet++，there are some problem when make

### ISSUE THREAD

**Issue by github-xudwei** [gwaldron/osgearth#1306]
problem1:FeatureNode
problem2:getModelLayerGroup

![image](https://user-images.githubusercontent.com/44045912/55388432-dc719580-5565-11e9-8d7d-6b82de5383ba.png)
![image](https://user-images.githubusercontent.com/44045912/55388469-f612dd00-5565-11e9-910f-0fc044105cfa.png)
Thank you for your time!

**Comment by gwaldron** [comment]
Replace the first with FeatureNode(Feature*); replace the second with mapNode->addChild(...)
