### ISSUE TITLE
ImageOverlay didn't draw on iPhone

### ISSUE THREAD

**Issue by EdYao** [gwaldron/osgearth#1309]
I user those codes to display a ImageOverlay on the map, just like the example code:
`
void BigeMapPlaceNode::addImg(std::string imgPath)

{

    ImageOverlay* imageOverlay = 0L;

    osg::ref_ptr<osg::Image> image = osgDB::readRefImageFile( imgPath );

    if (image.valid())

    {

        imageOverlay = new ImageOverlay(_cyMapNode, image.get());

        imageOverlay->setBounds( Bounds( getPosition().x() - 1, getPosition().y() - 1, getPosition().x() + 1, getPosition().y() + 1) );

        _parentGroup->addChild( imageOverlay );
    }
}
`

I'm pretty sure that the imgPath was correct, and have step over those codes, didn't find any problem. the console didn't show any problem either. 

the version I am using:
osgearth:2.10.
osg:3.6.1
xcode: 10.2
iOS: 12.2

Thanks to anyone could offer some help:)

**Comment by gwaldron** [comment]
Unable to help since we do not have an iOS devel environment - sorry!
