### ISSUE TITLE
Cannot load tiff on Android

### ISSUE THREAD

**Issue by EdYao** [gwaldron/osgearth#1311]
This is my code to load a tiff object:
`osg::Object* img =   osgDB::readObjectFile("/storage/emulated/0/BiGeMap/0.tiff");`
but the img ptr was  NULL. And the saw those out put in console:

`TIFF rader: inputstream: Seek error accessing TIFF directory`
`TIFF rader: Failed to read directory at offset 8`
`TIFF loader: Error opening file`
`Warning: dynamic library 'osgPlugins-3.6.1/osgdb_tiff.so' does not exist (or isn't readable):`
`dlopen failed: library "osgPlugins-3.6.1/osgdb_tiff.so" not found`
`DynamicLibrary::failed loading "osgPlugins-3.6.1/osgdb_tiff.so"`
`Error reading file /storage/emulated/0/BiGeMap/0.tiff: file not handled`

I checked the libtiff(which is a osgPlugin) source code, and found out that the `Seek error accessing TIFF directory` was defined there.  `Seek error accessing TIFF directory` means `An error occurred while positioning to the location of the directory `, see here [click](http://www.libtiff.org/man/TIFFReadDirectory.3t.html) . but I'm sure the directory `/storage/emulated/0/BiGeMap/0.tiff` was correct. I also tried to load a png object by `osg::Object* img =   osgDB::readObjectFile("/storage/emulated/0/BiGeMap/test.png");`, and the img object was correct.

I also tried to rebuild libtiff(stable release libtiff-Release-v4-0-9), which didn't help.

The osg vertion:3.6.1
osgEarth version: 2.10

**Comment by gwaldron** [comment]
This error is common when your TIFF is bigger than 2GB. IIRC you would need to build the TIFF library especially to handle larger files, but I don't know the details.

**Comment by EdYao** [comment]
@gwaldron The TIFF file size was only 5kb, which was successfully loaded on iOS. and the ElevationLayer also works fine on iOS.

**Comment by gwaldron** [comment]
OK. Recommend trying to run `osgviewer --image 0.tiff` and if that fails your problem is definitely not an osgEarth issue.

**Comment by EdYao** [comment]
@gwaldron Hi, I have run `osgviewer --image 0.tiff` on windows cmd, it succeeded. 
 This problem looks like a libtiff plugin issue. I don't know if others loaded tiff on Android, did they meet the problem I have.
Thanks for reply :)

**Comment by leedejun** [comment]
@EdYao  Hi,  Did you solved your problem ? Could share your method for me? Thanks.

@gwaldron
