### ISSUE TITLE
Blank osg::Geodes when using osgEarth::Annotation::AnnotationUtils::createImageGeometry on 3D Geodetic Maps only

### ISSUE THREAD

**Issue by B1anky** [gwaldron/osgearth#1314]
osgEarth::Annotation::AnnotationUtils::createImageGeometry(osg::Image* img) used to work for both the Projected and Geodetic maps in osgEarth 2.9. Something changed that affected its appearance in osgEarth 2.10. osgEarth::Annotation::PlaceNodes still work as intended on both map types with the same file paths. The actual use case for this was using an osgEarth::GeoTransform and adding an osg::Geode as a child to it who then added an osg::Drawable generated from the osgEarth::Annotation::AnnotationUtils::createImageGeometry(osg::Image* img) function.

[main.txt](https://github.com/gwaldron/osgearth/files/3129694/main.txt)
[2d.txt](https://github.com/gwaldron/osgearth/files/3129696/2d.txt)
[3d.txt](https://github.com/gwaldron/osgearth/files/3129697/3d.txt)

**Comment by gwaldron** [comment]
The shader is missing. I don't actually know why it is present on the 2D map since you didn't generate one. If you run this the 3D version will display correctly:

`osgEarth::Registry::shaderGenerator().run(_3DGeode);`

**Comment by B1anky** [comment]
How come this seemed to work in osgEarth2.9 without that requirement? Did something change regarding the shaderGenerator?

**Comment by gwaldron** [comment]
No idea.
Whenever you create geometry and place it under the osgEarth scene graph, it needs shaders in order to render properly if you are doing anything beyond basic colors. FFP rendering is not supported under the MapNode or any other osgEarth node. So I would expect shader generation to be necessary in all cases.
