### ISSUE TITLE
OE_COMMENT(STR) causes QtCreator to fire wrong errors. osgEarth 3.0

### ISSUE THREAD

**Issue by kefir** [gwaldron/osgearth#1318]
Greetings fellow developers! Here is the problem i've experienced while porting my code to osgearth 3.0...

I'm using:
- Qt Creator 4.9.0-rc1 (4.8.84) Based on Qt 5.12.2 (MSVC 2017, 32 bit)
- Desktop Qt 5.11.2 MSVC2017 64bit
- Windows 10

I have noticed that following line in: include\osgEarth\Common:42
`// expandable comment for macros (only works in MSVC)`
`#ifdef _MSC_VER`
`#define OE_COMMENT(STR) / ## ** #STR * ## /`
`#else`
`#define OE_COMMENT(STR)`
`#endif`

causes QtCreator to mark this code:
`TMSElevationLayer* elevation = new TMSElevationLayer();`
`elevation->setName("Elevation");`
`elevation->setURL("http://readymap.org/readymap/tiles/1.0.0/116/");`
`ui->mapWidgetArea->getMap()->addLayer( elevation );`

with errors:
`mainwindow.cpp:109: error: no matching constructor for initialization of 'osgEarth::TMSElevationLayer'`
`mainwindow.cpp:111: error: 'setURL' is a protected member of 'osgEarth::TMSElevationLayer'`

My solution to this was simply to replace
 `#ifdef _MSC_VER`
with
`#if defined(_MSC_VER) && undefined(QT_VERSION)`

I assume this behavior can only be experienced in Qt environment since osgearth itself has compiled ok through cmake.

So the question is: did I do something wrong and there is perhaps some define that I should make to avoid these errors or maybe I should create a pull request.

Thanks.

**Comment by gwaldron** [comment]
I have not the faintest idea. What gave you the idea of using `undefined(QT_VERSION) ` ? This likely points to some more insidious problem in the `OE_COMMENT `macro. I am inclined to just disable it completely instead of testing `QT_VERSION `without knowing why.

**Comment by kefir** [comment]
> I have not the faintest idea. What gave you the idea of using `undefined(QT_VERSION) ` ? This likely points to some more insidious problem in the `OE_COMMENT `macro.

Actually my first instinct was to just replace
`#define OE_COMMENT(STR) / ## ** #STR * ## /`
with
`#define OE_COMMENT(STR) /* ## ** #STR * ## */`

But then i thought that such a solution may screw up folks who use VisualStudio and want their extended comments...

> I am inclined to just disable it completely instead of testing `QT_VERSION `without knowing why.

Good call, thanks. So should I close the issue or leave it be while things are resolved?

**Comment by gwaldron** [comment]
Thanks. I will close it out and push a patch shortly.
