### ISSUE TITLE
Can we remove the compute_levels option on mbtiles?

### ISSUE THREAD

**Issue by jasonbeverage** [gwaldron/osgearth#1324]
The levels are only really necessary to get the min_level if an mbtiles dataset doesn't start at lod 0 so it can return an empty image so osgearth will continue subdividing (which is only necessary for the MP engine).  Since REX is the default driver now do we actually need to compute the levels at all?  Computing the levels takes a very long time at startup for large mbtiles files so it would be nice to just get rid of it.

**Comment by gwaldron** [comment]
Agreed -- suggest we default to false in the 2.10 branch, and get rid entirely in the 3.0 branch

**Comment by gwaldron** [comment]
done
