### ISSUE TITLE
Crash with sky and annotation

### ISSUE THREAD

**Issue by JD31** [gwaldron/osgearth#1334]
The osgearth_viewer application crashes with the following earth file and with --sky argument:

```
<map name="test" type="geocentric" version="2">
	<options lighting = "true">
		<terrain color="#415564"/>
	</options>
	<!-- Annotation test -->
    <annotations name="Annotations Group">
        <label text="GPU-Clamped Line" lat="44" long="-115">
            <style type="text/css">
                text-align:             center_center;
                text-geographic-course: 45.0;
                text-bbox-fill: #FFFF0033;
                text-bbox-margin: 8;
                text-bbox-border: #FFFF00;
                text-bbox-border-width: 0.5;
                render-lighting:    false;
            </style>
        </label>
	</annotations>
</map>

```

OsgEarth 2.10.1
Osg 3.6.3
MSVC 2017 64 bits

The console provides the following trace:
```
glLinkProgram 000002B4C3A302D0"VisibleLayer" FAILED
glLinkProgram 000002B4C3A30490"osgEarth::Text" FAILED
```

**Comment by gwaldron** [comment]
I cannot reproduce this crash. Please set OSGEARTH_NOTIFY_LEVEL=INFO and post the output.

**Comment by JD31** [comment]
Here is the trace with level to DEBUG:
(I updated to 2.10.2 but still have the same issue).

C:\PROJECTS\osg_and_gdal\bin>osgearth_viewer.exe C:\PROJECTS\osg_and_gdal\testCountries.earth --sky --screen 0

[osgEarth]  [Earth Plugin] Forced load: osgEarthUtil.dll
[osgEarth]  [Map] cache=none; policy=read-write; bin=no
[osgEarth]  [Capabilities] Realized graphics window for OpenGL operations.
[osgEarth]  [Capabilities] osgEarth Version: 2.10.2
[osgEarth]  [Capabilities] OSG Version:      3.6.3
[osgEarth]  [Capabilities] GDAL Version:     2.4.0
[osgEarth]  [Capabilities] Detected hardware capabilities:
[osgEarth]  [Capabilities]   Vendor = Intel
[osgEarth]  [Capabilities]   Renderer = Intel(R) HD Graphics 520
[osgEarth]  [Capabilities]   Version = 4.4.0 - Build 20.19.15.4457
[osgEarth]  [Capabilities]   Core Profile = no
[osgEarth]  [Capabilities]   Max GPU texture units = 32
[osgEarth]  [Capabilities]   Max GPU texture coord indices = 8
[osgEarth]  [Capabilities]   Max GPU attributes = 16
[osgEarth]  [Capabilities]   Depth buffer bits = 24
[osgEarth]  [Capabilities]   Max texture size = 16384
[osgEarth]  [Capabilities]   GLSL = yes
[osgEarth]  [Capabilities]   GLSL Version = 440
[osgEarth]  [Capabilities]   Texture arrays = yes
[osgEarth]  [Capabilities]   draw instanced = yes
[osgEarth]  [Capabilities]   Texture buffers = yes
[osgEarth]  [Capabilities]   Texture buffer max size = 134217728
[osgEarth]  [Capabilities]   Compression = ARB S3
[osgEarth]  [GeoPoint] ILLEGAL: called GeoPoint::createLocalToWorld with AltitudeMode = RELATIVE_TO_TERRAIN
[osgEarth]  [ObjectIndex] Insert 11; size = 1
[osgEarth]  [engine_rex] Activated!
[osgEarth]  [Map] Map profile is: [srs=WGS 84, min=-180,-90 max=180,90 lod0=2,1 vdatum=geodetic]
[osgEarth]  [PagerLoader] Merges per frame = 20
[osgEarth]  [TerrainResources] Texture unit 0 reserved for Terrain Color
[osgEarth]  [TerrainResources] Texture unit 1 reserved for Terrain Elevation
[osgEarth]  [TerrainResources] Texture unit 2 reserved for Terrain Normals
[osgEarth]  [TerrainResources] Texture unit 3 reserved for Terrain Parent Color
[osgEarth]  [RexTerrainEngineNode] Render Bindings:
[osgEarth]  [RexTerrainEngineNode]  > Bound "oe_layer_tex" to unit 0
[osgEarth]  [RexTerrainEngineNode]  > Bound "oe_layer_texParent" to unit 3
[osgEarth]  [RexTerrainEngineNode]  > Bound "oe_tile_elevationTex" to unit 1
[osgEarth]  [RexTerrainEngineNode]  > Bound "oe_tile_normalTex" to unit 2
[osgEarth]  LOD 19 TY=524288 minAR=0.305263 minTY=51771 maxTY=472516 (+/-72.226 deg)
[osgEarth]  LOD 18 TY=262144 minAR=0.289474 minTY=24505 maxTY=237638 (+/-73.1741 deg)
[osgEarth]  LOD 17 TY=131072 minAR=0.273684 minTY=11566 maxTY=119505 (+/-74.1172 deg)
[osgEarth]  LOD 16 TY=65536 minAR=0.257895 minTY=5441 maxTY=60094 (+/-75.0572 deg)
[osgEarth]  LOD 15 TY=32768 minAR=0.242105 minTY=2551 maxTY=30216 (+/-75.9897 deg)
[osgEarth]  LOD 14 TY=16384 minAR=0.226316 minTY=1191 maxTY=15192 (+/-76.9208 deg)
[osgEarth]  LOD 13 TY=8192 minAR=0.210526 minTY=553 maxTY=7638 (+/-77.8601 deg)
[osgEarth]  LOD 12 TY=4096 minAR=0.194737 minTY=256 maxTY=3839 (+/-78.772 deg)
[osgEarth]  LOD 11 TY=2048 minAR=0.178947 minTY=117 maxTY=1930 (+/-79.7607 deg)
[osgEarth]  LOD 10 TY=1024 minAR=0.163158 minTY=53 maxTY=970 (+/-80.7715 deg)
[osgEarth]  LOD 9 TY=512 minAR=0.147368 minTY=24 maxTY=487 (+/-81.7383 deg)
[osgEarth]  LOD 8 TY=256 minAR=0.131579 minTY=11 maxTY=244 (+/-82.6172 deg)
[osgEarth]  LOD 7 TY=128 minAR=0.115789 minTY=5 maxTY=122 (+/-83.6719 deg)
[osgEarth]  LOD 6 TY=64 minAR=0.1 minTY=2 maxTY=61 (+/-85.7813 deg)
[osgEarth]  [RexTerrainEngineNode] Creating 2 root keys.
[osgEarth]  [TileNode] notify (create) key 0/0/0
[osgEarth]  [TerrainTileModelFactory] No HF at key 0/0/0, making placeholder
[osgEarth]  [LoadTileData] apply 0/0/0
[osgEarth]  [TileNode] notify (create) key 0/1/0
[osgEarth]  [TerrainTileModelFactory] No HF at key 0/1/0, making placeholder
[osgEarth]  [LoadTileData] apply 0/1/0
[osgEarth]  [MapNode] Adding node from layer "Annotations Group" to the scene graph
[osgEarth]  [SimpleSkyNode] Using O'Neil atmospheric lighting
[osgEarth]  [MapNode] Added extension "sky_simple"
[osgEarth]  [EarthManip] setViewpoint:
    from x=0, y=90, z=-6.35675e+06, h=0, p=-90, d=1m, xo=0, yo=0, zo=0
    to   x=-90, y=0, z=0, h=0, p=-89, d=1.91344e+07m, xo=0, yo=0, zo=0
[osgEarth]  [EarthManip] setViewpoint:
    from x=-90, y=0, z=-9.31323e-10, h=0, p=-89, d=1.91344e+07m, xo=0, yo=0, zo=0
    to   x=-90, y=0, z=0, h=0, p=-89, d=1.91344e+07m, xo=0, yo=0, zo=0
[osgEarth]  [GeoTransform] Discovered terrain.
[osgEarth]  [TileNode] notify (create) key 1/0/0
[osgEarth]  [TileNode] notify (create) key 1/1/0
[osgEarth]  [TileNode] notify (create) key 1/0/1
[osgEarth]  [TileNode] notify (create) key 1/1/1
[osgEarth]  [TileNode] notify (create) key 2/0/0
[osgEarth]  [TileNode] notify (create) key 2/1/0
[osgEarth]  [TileNode] notify (create) key 2/0/1
[osgEarth]  [TileNode] notify (create) key 2/1/1
[osgEarth]  [TileNode] notify (create) key 3/0/0
[osgEarth]  [TileNode] notify (create) key 3/1/0
[osgEarth]  [TileNode] notify (create) key 3/0/1
[osgEarth]  [TileNode] notify (create) key 3/1/1
[osgEarth]  [TileNode] notify (create) key 3/2/0
[osgEarth]  [TileNode] notify (create) key 3/3/0
[osgEarth]  [TileNode] notify (create) key 3/2/1
[osgEarth]  [TileNode] notify (create) key 3/3/1
[osgEarth]  [TileNode] notify (create) key 3/0/2
[osgEarth]  [TileNode] notify (create) key 3/1/2
[osgEarth]  [TileNode] notify (create) key 3/0/3
[osgEarth]  [TileNode] notify (create) key 3/1/3
[osgEarth]  [TileNode] notify (create) key 3/2/2
[osgEarth]  [TileNode] notify (create) key 3/3/2
[osgEarth]  [TileNode] notify (create) key 3/2/3
[osgEarth]  [TileNode] notify (create) key 3/3/3
[osgEarth]  [TileNode] notify (create) key 2/2/0
[osgEarth]  [TileNode] notify (create) key 2/3/0
[osgEarth]  [TileNode] notify (create) key 2/2/1
[osgEarth]  [TileNode] notify (create) key 2/3/1
[osgEarth]  [TileNode] notify (create) key 3/4/0
[osgEarth]  [TileNode] notify (create) key 3/5/0
[osgEarth]  [TileNode] notify (create) key 3/4/1
[osgEarth]  [TileNode] notify (create) key 3/5/1
[osgEarth]  [TileNode] notify (create) key 3/6/0
[osgEarth]  [TileNode] notify (create) key 3/7/0
[osgEarth]  [TileNode] notify (create) key 3/6/1
[osgEarth]  [TileNode] notify (create) key 3/7/1
[osgEarth]  [TileNode] notify (create) key 3/4/2
[osgEarth]  [TileNode] notify (create) key 3/5/2
[osgEarth]  [TileNode] notify (create) key 3/4/3
[osgEarth]  [TileNode] notify (create) key 3/5/3
[osgEarth]  [TileNode] notify (create) key 3/6/2
[osgEarth]  [TileNode] notify (create) key 3/7/2
[osgEarth]  [TileNode] notify (create) key 3/6/3
[osgEarth]  [TileNode] notify (create) key 3/7/3
[osgEarth]  [TileNode] notify (create) key 2/0/2
[osgEarth]  [TileNode] notify (create) key 2/1/2
[osgEarth]  [TileNode] notify (create) key 2/0/3
[osgEarth]  [TileNode] notify (create) key 2/1/3
[osgEarth]  [TileNode] notify (create) key 3/0/4
[osgEarth]  [TileNode] notify (create) key 3/1/4
[osgEarth]  [TileNode] notify (create) key 3/0/5
[osgEarth]  [TileNode] notify (create) key 3/1/5
[osgEarth]  [TileNode] notify (create) key 3/2/4
[osgEarth]  [TileNode] notify (create) key 3/3/4
[osgEarth]  [TileNode] notify (create) key 3/2/5
[osgEarth]  [TileNode] notify (create) key 3/3/5
[osgEarth]  [TileNode] notify (create) key 3/0/6
[osgEarth]  [TileNode] notify (create) key 3/1/6
[osgEarth]  [TileNode] notify (create) key 3/0/7
[osgEarth]  [TileNode] notify (create) key 3/1/7
[osgEarth]  [TileNode] notify (create) key 3/2/6
[osgEarth]  [TileNode] notify (create) key 3/3/6
[osgEarth]  [TileNode] notify (create) key 3/2/7
[osgEarth]  [TileNode] notify (create) key 3/3/7
[osgEarth]  [TileNode] notify (create) key 2/2/2
[osgEarth]  [TileNode] notify (create) key 2/3/2
[osgEarth]  [TileNode] notify (create) key 2/2/3
[osgEarth]  [TileNode] notify (create) key 2/3/3
[osgEarth]  [TileNode] notify (create) key 3/4/4
[osgEarth]  [TileNode] notify (create) key 3/5/4
[osgEarth]  [TileNode] notify (create) key 3/4/5
[osgEarth]  [TileNode] notify (create) key 3/5/5
[osgEarth]  [TileNode] notify (create) key 3/6/4
[osgEarth]  [TileNode] notify (create) key 3/7/4
[osgEarth]  [TileNode] notify (create) key 3/6/5
[osgEarth]  [TileNode] notify (create) key 3/7/5
[osgEarth]  [TileNode] notify (create) key 3/4/6
[osgEarth]  [TileNode] notify (create) key 3/5/6
[osgEarth]  [TileNode] notify (create) key 3/4/7
[osgEarth]  [TileNode] notify (create) key 3/5/7
[osgEarth]  [TileNode] notify (create) key 3/6/6
[osgEarth]  [TileNode] notify (create) key 3/7/6
[osgEarth]  [TileNode] notify (create) key 3/6/7
[osgEarth]  [TileNode] notify (create) key 3/7/7
[osgEarth]  [TileNode] notify (create) key 1/2/0
[osgEarth]  [TileNode] notify (create) key 1/3/0
[osgEarth]  [TileNode] notify (create) key 1/2/1
[osgEarth]  [TileNode] notify (create) key 1/3/1
[osgEarth]  [TileNode] notify (create) key 2/4/0
[osgEarth]  [TileNode] notify (create) key 2/5/0
[osgEarth]  [TileNode] notify (create) key 2/4/1
[osgEarth]  [TileNode] notify (create) key 2/5/1
[osgEarth]  [TileNode] notify (create) key 2/6/0
[osgEarth]  [TileNode] notify (create) key 2/7/0
[osgEarth]  [TileNode] notify (create) key 2/6/1
[osgEarth]  [TileNode] notify (create) key 2/7/1
[osgEarth]  [TileNode] notify (create) key 2/4/2
[osgEarth]  [TileNode] notify (create) key 2/5/2
[osgEarth]  [TileNode] notify (create) key 2/4/3
[osgEarth]  [TileNode] notify (create) key 2/5/3
[osgEarth]  [TileNode] notify (create) key 2/6/2
[osgEarth]  [TileNode] notify (create) key 2/7/2
[osgEarth]  [TileNode] notify (create) key 2/6/3
[osgEarth]  [TileNode] notify (create) key 2/7/3
[osgEarth]  [ScreenSpaceLayout] Decluttering VP installed
glLinkProgram 0000025E3960A560"VisibleLayer" FAILED
[osgEarth]  getShader, mask = 11, location = 2
[osgEarth]  getShader, mask = 11, location = 1
[osgEarth]  getShader, mask = 11, location = 1
[osgEarth]  getShader, mask = 11, location = 1
[osgEarth]  getShader, mask = 11, location = 1
[osgEarth]  getShader, mask = 11, location = 1
[osgEarth]  getShader, mask = 11, location = 1
[osgEarth]  getShader, mask = 11, location = 1
[osgEarth]  getShader, mask = 11, location = 1
[osgEarth]  getShader, mask = 11, location = 1
[osgEarth]  getShader, mask = 11, location = 1
[osgEarth]  [VirtualProgram] Program link failure!
glLinkProgram 0000025E3960C320"osgEarth::Text" FAILED
[osgEarth]  getShader, mask = 11, location = 1
[osgEarth]  getShader, mask = 11, location = 1
[osgEarth]  getShader, mask = 11, location = 1
[osgEarth]  [VirtualProgram] Program link failure!

**Comment by gwaldron** [comment]
Maybe it is something particular to the Intel 520 driver. First I would try updating the driver. Next I would generate an OSG log (by using OSG_NOTIFY_LEVEL) and look for shader compiler/linker errors. (Please don't post the entire OSG log here though..use pastebin instead). Good luck.

**Comment by gwaldron** [comment]
Any resolution on this?
