### ISSUE TITLE
error: GLSL 3.30 is not supported.

### ISSUE THREAD

**Issue by SupremeDing1996** [gwaldron/osgearth#1336]
**### When I type "osgearth_viewer  glsl.earth" in terminal of Ubuntu18.04, the osgearth_viewer not work well, the error message is as follow:
How should I do?**

VERTEX glCompileShader "oe_ClipPlane_VS" FAILED
VERTEX Shader "oe_ClipPlane_VS" infolog:
0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.00 ES, and 3.00 ES

VERTEX glCompileShader "main(vertex)" FAILED
VERTEX Shader "main(vertex)" infolog:
0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.00 ES, and 3.00 ES

FRAGMENT glCompileShader "main(fragment)" FAILED
FRAGMENT Shader "main(fragment)" infolog:
0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.00 ES, and 3.00 ES

glLinkProgram 0x7f49ac043b50"HorizonClipPlane" FAILED
Program "HorizonClipPlane" infolog:
error: linking with uncompiled/unspecialized shadererror: linking with uncompiled/unspecialized shadererror: linking with uncompiled/unspecialized shader
VERTEX glCompileShader "RexEngine.SDK.vert.glsl_VERTEX" FAILED
VERTEX Shader "RexEngine.SDK.vert.glsl_VERTEX" infolog:
0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.00 ES, and 3.00 ES

FRAGMENT glCompileShader "RexEngine.SDK.vert.glsl_FRAGMENT" FAILED
FRAGMENT Shader "RexEngine.SDK.vert.glsl_FRAGMENT" infolog:
0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.00 ES, and 3.00 ES

VERTEX glCompileShader "oe_rexEngine_vert" FAILED
VERTEX Shader "oe_rexEngine_vert" infolog:
0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.00 ES, and 3.00 ES

VERTEX glCompileShader "oe_rex_setTexCoords" FAILED
VERTEX Shader "oe_rex_setTexCoords" infolog:
0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.00 ES, and 3.00 ES

VERTEX glCompileShader "oe_rexEngine_elevation" FAILED
VERTEX Shader "oe_rexEngine_elevation" infolog:
0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.00 ES, and 3.00 ES

VERTEX glCompileShader "oe_normalMapVertex" FAILED
VERTEX Shader "oe_normalMapVertex" infolog:
0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.00 ES, and 3.00 ES

FRAGMENT glCompileShader "oe_normalMapFragment" FAILED
FRAGMENT Shader "oe_normalMapFragment" infolog:
0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.00 ES, and 3.00 ES

VERTEX glCompileShader "oe_rexEngine_morph" FAILED
VERTEX Shader "oe_rexEngine_morph" infolog:
0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.00 ES, and 3.00 ES

FRAGMENT glCompileShader "oe_rexEngine_frag" FAILED
FRAGMENT Shader "oe_rexEngine_frag" infolog:
0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.00 ES, and 3.00 ES

VERTEX glCompileShader "oe_VisibleLayer_initOpacity" FAILED
VERTEX Shader "oe_VisibleLayer_initOpacity" infolog:
0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.00 ES, and 3.00 ES

VERTEX glCompileShader "main(vertex)" FAILED
VERTEX Shader "main(vertex)" infolog:
0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.00 ES, and 3.00 ES

FRAGMENT glCompileShader "main(fragment)" FAILED
FRAGMENT Shader "main(fragment)" infolog:
0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.00 ES, and 3.00 ES

glLinkProgram 0x7f49ac02d250"Layer shader" FAILED
Program "Layer shader" infolog:
error: linking with uncompiled/unspecialized shadererror: linking with uncompiled/unspecialized shadererror: linking with uncompiled/unspecialized shadererror: linking with uncompiled/unspecialized shadererror: linking with uncompiled/unspecialized shadererror: linking with uncompiled/unspecialized shadererror: linking with uncompiled/unspecialized shadererror: linking with uncompiled/unspecialized shadererror: linking with uncompiled/unspecialized shadererror: linking with uncompiled/unspecialized shadererror: linking with uncompiled/unspecialized shadererror: linking with uncompiled/unspecialized shadererror: linking with uncompiled/unspecialized shader
VERTEX glCompileShader "main(vertex)" FAILED
VERTEX Shader "main(vertex)" infolog:
0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.00 ES, and 3.00 ES

FRAGMENT glCompileShader "main(fragment)" FAILED
FRAGMENT Shader "main(fragment)" infolog:
0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.00 ES, and 3.00 ES

glLinkProgram 0x7f49ac0806b0"Control::geomStateSet" FAILED
Program "Control::geomStateSet" infolog:
error: linking with uncompiled/unspecialized shadererror: linking with uncompiled/unspecialized shader
VERTEX glCompileShader "oe_Text_VS" FAILED
VERTEX Shader "oe_Text_VS" infolog:
0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.00 ES, and 3.00 ES

FRAGMENT glCompileShader "oe_Text_FS" FAILED
FRAGMENT Shader "oe_Text_FS" infolog:
0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.00 ES, and 3.00 ES

VERTEX glCompileShader "main(vertex)" FAILED
VERTEX Shader "main(vertex)" infolog:
0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.00 ES, and 3.00 ES

FRAGMENT glCompileShader "main(fragment)" FAILED
FRAGMENT Shader "main(fragment)" infolog:
0:1(10): error: GLSL 3.30 is not supported. Supported versions are: 1.10, 1.20, 1.30, 1.40, 1.00 ES, and 3.00 ES

glLinkProgram 0x7f49ac058710"osgEarth::Text" FAILED
Program "osgEarth::Text" infolog:
error: linking with uncompiled/unspecialized shadererror: linking with uncompiled/unspecialized shadererror: linking with uncompiled/unspecialized shadererror: linking with uncompiled/unspecialized shader

**Comment by gwaldron** [comment]
OsgEarth requires OpenGL 3.3 or better. It is likely that your system does not have a supported GPU or driver. Please run `osgearth_version --caps` and post the output.

**Comment by SupremeDing1996** [comment]
The output is following. How can I fix this problem? 

osgEarth Library 2.10.0 

[osgEarth]  [Capabilities] osgEarth Version: 2.10.0 
[osgEarth]  [Capabilities] Detected hardware capabilities:
[osgEarth]  [Capabilities]   Vendor = X.Org
[osgEarth]  [Capabilities]   Renderer = AMD CAICOS (DRM 2.50.0 / 5.0.0-21-generic, LLVM 8.0.1)
[osgEarth]  [Capabilities]   Version = 3.1 Mesa 19.2.0-devel (git-9d5beab 2019-08-02 bionic-oibaf-ppa)
[osgEarth]  [Capabilities]   Core Profile = no
[osgEarth]  [Capabilities]   Max GPU texture units = 16
[osgEarth]  [Capabilities]   Max GPU texture coord indices = 8
[osgEarth]  [Capabilities]   Max GPU attributes = 16
[osgEarth]  [Capabilities]   Depth buffer bits = 24
[osgEarth]  [Capabilities]   Max texture size = 16384
[osgEarth]  [Capabilities]   GLSL = yes
[osgEarth]  [Capabilities]   GLSL Version = 140
[osgEarth]  [Capabilities]   Texture arrays = yes
[osgEarth]  [Capabilities]   draw instanced = yes
[osgEarth]  [Capabilities]   Texture buffers = yes
[osgEarth]  [Capabilities]   Texture buffer max size = 1503238553
[osgEarth]  [Capabilities]   Compression = ARB S3 RG

**Comment by gwaldron** [comment]
Try to find an AMD OpenGL driver for your platform. Failing that, you need a version of Mesa that supports GL3/GLCORE. With that, you will need to compile OSG and osgEarth to use GL CORE profile. [There are some instructions here](https://gist.github.com/gwaldron/a56b0e77e7fa8587b698717d21f9366d). Good luck!

**Comment by SupremeDing1996** [comment]
Thank you very much。I decide to replace the graphic card of my computer, since it is a bit too old to work with some new software。
