### ISSUE TITLE
Crash on Android while setting DatabasePager HttpThreads or GeneralThreads number greater than 1 .

### ISSUE THREAD

**Issue by EdYao** [gwaldron/osgearth#1350]
As the title said, and iOS platform works just fine. On android, the app will crash at any time, and there was not a certain operation could cause the crash. Sometimes the app could run 3 secends, sometimes crashed just at the begining. 
here is the crash log.

[click pic](https://github.com/EdYao/YFPMusicPlayer/blob/master/crash.png?raw=true)

The version info:
OSGEarth 2.10.2 or 2.10.1 or 2.10
OSG: 3.6.4 or 3.6.1

**Comment by remoe** [comment]
Can you please upload the image here (github) and not on a google account?

**Comment by EdYao** [comment]
@remoe of cource yes, I  edited the issue. you can click it now...

**Comment by remoe** [comment]
sorry, the image has a 404 error ...

**Comment by EdYao** [comment]
@remoe I edit the issue again, this time should working properly.....  :)

**Comment by remoe** [comment]
yes, works. your crash is in this method:

https://github.com/openscenegraph/OpenSceneGraph/blob/master/src/osgDB/DatabasePager.cpp#L1607

do you have tried the environment variable OSGEARTH_NOTIFY_LEVEL=DEBUG or OSG_NOTIFY_LEVEL=DEBUG ?

**Comment by remoe** [comment]
Or try: OSGEARTH_HTTP_DEBUG

**Comment by EdYao** [comment]
Yes and nothing related to the issue. The log info says that application want to dereference a null pointer.  I guess this means that one object was released by two threads at the same time, which was a classic multi-thread issue, and only appears on Android this time.

**Comment by gwaldron** [comment]
Closing this b/c there is nothing in the trace to indicate it's an osgEarth issue -- please try the osg-users mailing list
