### ISSUE TITLE
MGRSGraticule 2.9 and 2.10.2+ issues 

### ISSUE THREAD

**Issue by Kyeiv** [gwaldron/osgearth#1361]
OS: Ubuntu 18.04.3 LTS
- osgEarth 2.10.2+ (head on commit: "rex:small sector re-use optimization") with OSG 3.6.4:
when launching osgearth_graticule --mgrs graticules.earth there are only labels visible. I cannot see any grids of the graticule.

- osgEarth 2.9 (https://launchpad.net/ubuntu/bionic/+source/osgearth) OSG (https://packages.ubuntu.com/bionic/openscenegraph)
the same program as above but other issue. While launching 
osgearth_graticule --mgrs graticules.earth i get: 
[osgEarth]* [MGRSGraticule] sqid bin file is corrupt.. abort!
The file I am using is the one from this github repository.

My --caps:
`
[osgEarth]  [Capabilities] Detected hardware capabilities:

[osgEarth]  [Capabilities]   Vendor = NVIDIA Corporation

[osgEarth]  [Capabilities]   Renderer = GeForce GTX 470/PCIe/SSE2

[osgEarth]  [Capabilities]   Version = 4.6.0 NVIDIA 390.129

[osgEarth]  [Capabilities]   Max GPU texture units = 32

[osgEarth]  [Capabilities]   Max GPU texture coord indices = 8

[osgEarth]  [Capabilities]   Max GPU attributes = 16

[osgEarth]  [Capabilities]   Depth buffer bits = 24

[osgEarth]  [Capabilities]   Max texture size = 16384

[osgEarth]  [Capabilities]   Max lights = 8

[osgEarth]  [Capabilities]   GLSL = yes

[osgEarth]  [Capabilities]   GLSL Version = 460

[osgEarth]  [Capabilities]   Texture arrays = yes

[osgEarth]  [Capabilities]   3D textures = yes

[osgEarth]  [Capabilities]   Multitexturing = yes

[osgEarth]  [Capabilities]   draw instanced = yes

[osgEarth]  [Capabilities]   uniform buffer objects = yes

[osgEarth]  [Capabilities]   NPOT textures = yes

[osgEarth]  [Capabilities]   Texture buffers = yes

[osgEarth]  [Capabilities]   Texture buffer max size = 134217728

[osgEarth]  [Capabilities]   Transform feedback = yes

[osgEarth]  [Capabilities]   Compression = ARB S3 RG

`

**Comment by gwaldron** [comment]
Not been able to reproduce either issue in 2.10.x master or 3.0 branch
