### ISSUE TITLE
Default User Agent on HTTPClient wrong

### ISSUE THREAD

**Issue by remoe** [gwaldron/osgearth#1363]
s_userAgent on HTTPClient has this value:

"osgearthOSGEARTH_MAJOR_VERSION.OSGEARTH_MINOR_VERSION"

https://github.com/gwaldron/osgearth/blob/b928fa754bb64170566e2ce053186f7c6fac750c/src/osgEarth/HTTPClient.cpp#L377

Platform: Win64

**Comment by gwaldron** [comment]
Fixed in 3.0 branch
