### ISSUE TITLE
about getHeightField

### ISSUE THREAD

**Issue by jamesjinlv** [gwaldron/osgearth#1373]
I used to getHeightField from osgEarth::Map;
But int the new version, there is no getHeightField function in the class of osgEarth::Map.
Who can tell me how to change the old code,such as: getMap()->getHeightField(tilekey,true,pHF);
Thank you.

**Comment by gwaldron** [comment]
Try this:
```
ElevationLayerVector layers;
map->getLayers(layers);
layers.populateHeightFieldAndNormalMap(...);
```
Good luck.
