### ISSUE TITLE
Can't compile with GEOS 3.8.0

### ISSUE THREAD

**Issue by lbartoletti** [gwaldron/osgearth#1378]
GEOS 3.8.0 was release 3 weeks ago.

osgEarth can't compile with it. Here an error log:
http://package18.nyi.freebsd.org/data/120amd64-default-PR238988/2019-10-22_05h46m02s/logs/errors/osgearth-2.10.1_3.log

Thank you.

**Comment by sgarfinkel** [comment]
@gwaldron Is there a workaround to this? Both VCPKG and Homebrew currently link to GEOS 3.8.0 which makes building OSGEarth irritating.

**Comment by bosth** [comment]
Been a while since I did any work in C++, but I knocked this patch together: https://git.slackbuilds.org/slackbuilds/tree/gis/osgEarth/geos-3_8-support.patch

**Comment by lbartoletti** [comment]
@bosth Thanks. LGTM

**Comment by gwaldron** [comment]
GEOS 3.8.x works
