### ISSUE TITLE
osgearth_package_qt: When using multiple processes the path to the generated earth file is sometimes invalid.

### ISSUE THREAD

**Issue by damiandixon** [gwaldron/osgearth#1379]
If I run osgearth_package_qt with an earth file as follows:
```
osgearth_package_qt5 openseamap.earth
```
I then select multiprocessing option and start the processing I get the following error:
```
Error reading file /~1804289383.earth: file not found
Failed to load a valid .earth file
```
The problem is that root in TMSExporter.cpp is empty.
```
            if (!earthFilePath.empty())
            {
                std::string root = osgDB::getFilePath(earthFilePath);
                root += "/";
                tmpEarth = getTempName(root, ".earth");
            }
```
Workaround is to pass the full path to the earth file.

**Comment by gwaldron** [comment]
I'm afraid that osgearth_package_qt is no longer supported (or available) in the current version of osgEarth. If you find it useful and discover a bug fix you can apply it to your working fork.

**Comment by gwaldron** [comment]
deprecated
