### ISSUE TITLE
Did osgearth isn't support WKT?

### ISSUE THREAD

**Issue by sltruman** [gwaldron/osgearth#1380]
Why it is not working that I trying to set WKT into srs of profile of earth file? 
Can somebody tell me where is wrong please.
![Screenshot from 2019-11-04 11-26-31](https://user-images.githubusercontent.com/12881971/68098226-906d4180-fef6-11e9-8ee1-c53cf01bc501.png)

**Comment by gwaldron** [comment]
If you are using osgEarth 2.x (or the current master) an SRS is not supported; you must specify the location like `<location x="longitude" y="latitude" z="altitude"/>` where the lat/long are in degrees.

osgEarth 3.0 (not yet released as of this writing) will have full SRS support for your model location.

**Comment by sltruman** [comment]
@gwaldron Thanks!
