### ISSUE TITLE
CXX11 Check Fails with AppleClang

### ISSUE THREAD

**Issue by sgarfinkel** [gwaldron/osgearth#1388]
The issue is that since Cmake 3.0, the Apple-native Clang compiler has a compiler ID of `AppleClang`, which fails the check (in CXX11.cmake):
```
CMAKE_CXX_COMPILER_ID STREQUAL "Clang"
```
An alternative solution is to instead use

```cmake
include(CheckCXXCompilerFlag)

CHECK_CXX_COMPILER_FLAG("-std=c++11" COMPILER_SUPPORTS_CXX11)

if((MSVC AND NOT ${MSVC_VERSION} VERSION_LESS 1900) OR 
    (COMPILER_SUPPORTS_CXX11))
    ...
else()
    ...
endif()
```

Not compiling with C++11 will cause a fatal linking error when linking with GDAL, as GDAL now requires C++11. See https://trac.osgeo.org/gdal/wiki/rfc68_cplusplus11.

**Comment by gwaldron** [comment]
Can you generate a PR please? Feel free to perform the GDAL/GEOS checks as well -- I don't recall in what version GDAL went C++11 only.

**Comment by remoe** [comment]
@sgarfinkel it's fixed on 2.10 branch. Could you please check this? Thanks.

**Comment by gwaldron** [comment]
Are we good here? Can we close this?

**Comment by remoe** [comment]
@gwaldron, yes I had build a MacOSX version of osgEarth 2.10 without any issues.

**Comment by gwaldron** [comment]
What about master branch (3.0)?

**Comment by remoe** [comment]
VS2017 - no issue. Haven't tested with MacOSX.

**Comment by sgarfinkel** [comment]
Sorry I'm no longer working the project that had the need for OSGEarth so I'll let others chime in on this.

**Comment by remoe** [comment]
I've build osgEarth on MacOSX always with following flags:

```
                - -DCMAKE_CXX_STANDARD:STRING=11
                - -DCMAKE_CXX_STANDARD_REQUIRED:BOOL=ON
                - -DCMAKE_CXX_EXTENSIONS:BOOL=OFF 
```

I've build latest 3.0 master with XCode 11.4. No build issues.

**Comment by sgarfinkel** [comment]
@remoe What PR resolved this? If it’s in master I see no reason this can be closed but it’d be good to have that traceability.

**Comment by remoe** [comment]
@sgarfinkel https://github.com/gwaldron/osgearth/pull/1405/commits/46253454b3eb2037e90e637fc98f6bf8b21bf89b . But it's long time ago :)
