### ISSUE TITLE
osgearth_viewer Exception loading OSM

### ISSUE THREAD

**Issue by whwlei** [gwaldron/osgearth#1394]
PS D:\c-workspace\OSGEarth\osgearth\build\bin\Release> .\osgearth_viewer.exe .\openstreetmap.earth
Error reading file .\openstreetmap.earth: file not handled
[osgEarth]* [MapNodeHelper] Loaded scene graph does not contain a MapNode - aborting
[osgEarth]
Usage: D:\c-workspace\OSGEarth\osgearth\build\bin\Release\osgearth_viewer.exe file.earth
  --sky                         : add a sky model
  --kml <file.kml>              : load a KML or KMZ file
  --kmlui                       : display a UI for toggling nodes loaded with --kml
  --coords                      : display map coords under mouse
  --ortho                       : use an orthographic camera
  --logdepth                    : activates the logarithmic depth buffer
  --logdepth2                   : activates logarithmic depth buffer with per-fragment interpolation
  --shadows                     : activates model layer shadows
  --out-earth [file]            : write the loaded map to an earth file
  --uniform [name] [min] [max]  : create a uniform controller with min/max values
  --define [name]               : install a shader #define
  --path [file]                 : load and playback an animation path
  --extension [name]            : loads a named extension
  --ocean                       : add a simple ocean model (requires bathymetry)

**Comment by whwlei** [comment]
<map name="OpenStreetMap" type="geocentric" version="2">

    <image name="osm_mapnik" driver="xyz">
        <url>http://[abc].tile.openstreetmap.org/{z}/{x}/{y}.png</url>
        <profile>spherical-mercator</profile>
        <cache_policy usage="none"/>
        <attribution>&#169;OpenStreetMap contributors</attribution>
    </image>

    <options>
        <lighting>false</lighting>
        <terrain>
            <min_tile_range_factor>8</min_tile_range_factor>
        </terrain>
    </options>

</map>

**Comment by jasonbeverage** [comment]
Is .\openstreetmap.earth actually in your D:\c-workspace\OSGEarth\osgearth\build\bin\Release directory?  If not, pass in the full path to the openstreetmap.earth file, usually in the osgearth tests directory.

**Comment by whwlei** [comment]
I have copied the file to the current directory

**Comment by jasonbeverage** [comment]
Closing this as there isn't enough info to duplicate.

**Comment by Alexabc3000** [comment]
I have the same question in win10, VS2019
