### ISSUE TITLE
How to realize infowindow in osgearth?

### ISSUE THREAD

**Issue by liyihongcug** [gwaldron/osgearth#1398]
We know infowindow is popup-window in Google map/Google earth. It can show up one window dialog when we click one POI or one feaure in osgearth. 
I can't find the example in osgearth2.8 osg3.4.  I need realize mutile infowindow in osgearth so that I can compare them about information when I move 3D earth view. Each infowindow is binding to one fixed geodetic position. 
I know com can provide this. But I still am puzzled with it. I want know how to code to solve it.

**Comment by gwaldron** [comment]
This is outside the scope of osgEarth. Google uses an embedded HTML renderer, and you can do the same -- I suggest searching for "html rendering engine C++" and see what you find. Good luck.
