### ISSUE TITLE
EarthManipulator no longer recalculates center pt on zoom

### ISSUE THREAD

**Issue by geissel1** [gwaldron/osgearth#1399]
When the zoomToMouse functionality was added to the EarthManipulator, it removed the call to recalculateCenterFromLookVector() in the zoom() method. Was this intentional? The focal point altitude no longer recalculates when zooming, so the max zoom is no longer at ground level. Is the expectation is that now users of the class should manage the focal point altitude themselves?

**Comment by gwaldron** [comment]
Fixed.
