### ISSUE TITLE
HTTP2: Content type string doesn't match the HTTP/2 specification

### ISSUE THREAD

**Issue by remoe** [gwaldron/osgearth#1410]
All header keys in HTTP2 are lowercase:

https://http2.github.io/http2-spec/#rfc.section.8.1.2

The following static string is not correct with a HTTP2 connection:

https://github.com/gwaldron/osgearth/blob/2.10/src/osgEarth/IOTypes.cpp#L28

**Comment by gwaldron** [comment]
fixed by forcing http header names to be all lower case (in 3.0)
