### ISSUE TITLE
emscripten

### ISSUE THREAD

**Issue by tantan580** [gwaldron/osgearth#1413]
osgearth能否支持webassembly技术？

**Comment by remoe** [comment]
It's not official supported, but you can try to compile OSG with GLES3 and then osgEarth. Use Linux or Windows WSL and CLang. It's complicated to build all dependencies, but it's possible.
Try to port osgEarth and post your findings here.
It's a huge amount of work, so no one do this for free here :)

**Comment by tantan580** [comment]
I've tried it, but osgearth's own architecture doesn't support it。so I hope osgearth can support emscripten 。

**Comment by remoe** [comment]
osgEarth support GLES3 and some part of osgEarth (like HTTPClient) need to be changed to fully support WASM build. First try out OSG:
https://github.com/Kurdakov/emscripten_OSG/wiki/Introduction

**Comment by tantan580** [comment]
thanks , I've done that.I have deleted HTTP client,but Osgearth still has some problems. It can't create GC.

**Comment by remoe** [comment]
Ok, build OSG with the following flags:

```
                - -DCMAKE_CXX_STANDARD:STRING=11
                - -DCMAKE_CXX_STANDARD_REQUIRED:BOOL=ON
                - -DOSG_CPP_EXCEPTIONS_AVAILABLE=ON
                - -DBUILD_OSG_EXAMPLES=OFF
                - -DOSG_GL1_AVAILABLE=OFF
                - -DOSG_GL2_AVAILABLE=OFF
                - -DOSG_GLES2_AVAILABLE=OFF
                - -DOSG_GLES3_AVAILABLE=ON
                - -DEGL_LIBRARY=GL
                - -DBUILD_OSG_APPLICATIONS=OFF
                - -DOSG_WINDOWING_SYSTEM=None
                - -DDYNAMIC_OPENTHREADS=OFF
                - -DDYNAMIC_OPENSCENEGRAPH=OFF
                - -O3 
                - -s USE_SDL=2
                - -s USE_PTHREADS=1 
```

and use my osgEarth gles300es branch https://github.com/remoe/osgearth/commits/gles300es with:

```
                - -DCMAKE_CXX_STANDARD:STRING=11
                - -DCMAKE_CXX_STANDARD_REQUIRED:BOOL=ON
                - -DCMAKE_CXX_EXTENSIONS:BOOL=OFF 
                - -DCMAKE_POLICY_DEFAULT_CMP0063=NEW
                - -DAPPEND_OPENSCENEGRAPH_VERSION:BOOL=FALSE
                - -DDYNAMIC_OSGEARTH:BOOL=OFF
                - -DOSGEARTH_ENABLE_FASTDXT=OFF
                - -DBUILD_APPLICATIONS=FALSE
                - -DBUILD_TESTS=FALSE
                - -DOSGEARTH_USE_GLES300ES=ON
                - -O3 
                - -s USE_WEBGL2=1 
                - -s FULL_ES3=1
                - -s USE_SDL=2
                - -s USE_PTHREADS=1
                - -s ERROR_ON_MISSING_LIBRARIES=0
```

**Comment by tantan580** [comment]
Ok,thanks.I ‘ll try it.

**Comment by tantan580** [comment]
If I use the - s use U pthreads = 1 flag, I will be prompted:
ReferenceError:Atomics is not defined.

**Comment by tantan580** [comment]
If I use the -s USE_PTHREADS=1 flag, I will be prompted:
ReferenceError:Atomics is not defined

**Comment by remoe** [comment]
I haven't tested since months, but do you use latest Chrome and latest LLVM? I've used latest master of LLVM https://github.com/llvm/llvm-project.

**Comment by tantan580** [comment]
I use OSG emscripten only
Emscripten 1.39.1 I use，openscenegraph 3.6.3。
If you don't add the -s USE_PTHREADS = 1 flag, there is no problem。

**Comment by tantan580** [comment]
Yes, enable it in Chrome browser:
chrome://flags/# enable-webassembly-threads

**Comment by tantan580** [comment]
Yes, enable it in Chrome browser:
chrome：// flags /＃enable-webassembly-threads
But Firefox doesn't support it。

**Comment by tantan580** [comment]
Yes, enable it in Chrome browser:
chrome：// flags /＃enable-webassembly-threads ，use osg only chrome browser can display .
But browsers don't support atomic features.Atomic is used in osgeearth.

**Comment by remoe** [comment]
Yes, some parts of osgEarth threading code is not supported. Can you show us which part you found, please? I found parts in elevation code.

**Comment by tantan580** [comment]
There are many, such as graphicwindow, compositeview, singlewindow, databasepager, imagepager, etc

**Comment by remoe** [comment]
Hm, but it is possible to run osgEarth with a single world.tif. So try to build and run first only simple things.

**Comment by tantan580** [comment]
The simple demo of OSG is OK, but the demo of osgearth is not. It cannot be compiled.

Tips:

'atomics' feature is disallowed........Use --no-check-features to suppress etc

**Comment by remoe** [comment]
yes, no stock osgEarth samples work. One need to write own code with SDL.

**Comment by tantan580** [comment]
That's what I do. I use SDL to display osgearth。
But compilation failed。Tips:
'atomics' feature is disallowed........Use --no-check-features to suppress etc

**Comment by remoe** [comment]
Here is my working (08.2019) sample: https://gist.github.com/remoe/2afaabbd2c47c62c19762f2a14d99d2a

**Comment by tantan580** [comment]
Do you have a wechat account？So I can communicate with you easily

**Comment by remoe** [comment]
I've not defined "-s USE_PTHREADS" on the sample application. So the main application have not included PTHREADS.

**Comment by tantan580** [comment]
I use "OSG_GLES3_AVAILABLE =ON" to compile OSG. osgemscripten demo can display blue windows in chrome, but the data can't be displayed. Therefore, I use "-s USE_PTHREADS=1", "OSG_GLES2_AVAILABLE =ON" to compile OSG. osgemscripten demo can display data in chrome normally, but osgearth_wasm demo compilation fails whether "-s USE_PTHREADS=1" is used or not：
error:Target feature 'atomics' used in Async.cpp is disallowd .......etc

**Comment by tantan580** [comment]
wasm-ld: error: Target feature 'atomics' used in GraphicsWindow_2d9fc294.cpp.o is disallowed by vsi_pcidsk_io_3fb5555b.o. Use --no-check-features to suppress.
wasm-ld: error: Target feature 'atomics' used in PanoramicSphericalDisplay_0567879a.cpp.o is disallowed by vsi_pcidsk_io_3fb5555b.o. Use --no-check-features to suppress.
wasm-ld: error: Target feature 'atomics' used in Scene_a3c9c035.cpp.o is disallowed by vsi_pcidsk_io_3fb5555b.o. Use --no-check-features to suppress.
wasm-ld: error: Target feature 'atomics' used in CompositeViewer_11b80770.cpp.o is disallowed by vsi_pcidsk_io_3fb5555b.o. Use --no-check-features to suppress.
wasm-ld: error: Target feature 'atomics' used in Renderer_b4383ee1.cpp.o is disallowed by vsi_pcidsk_io_3fb5555b.o. Use --no-check-features to suppress.
wasm-ld: error: Target feature 'atomics' used in StatsHandler_7dc9ea94.cpp.o is disallowed by vsi_pcidsk_io_3fb5555b.o. Use --no-check-features to suppress.
wasm-ld: error: Target feature 'atomics' used in Keystone_ba34d40c.cpp.o is disallowed by vsi_pcidsk_io_3fb5555b.o. Use --no-check-features to suppress.
wasm-ld: error: Target feature 'atomics' used in SingleWindow_efc4d17d.cpp.o is disallowed by vsi_pcidsk_io_3fb5555b.o. Use --no-check-features to suppress.
wasm-ld: error: Target feature 'atomics' used in SingleScreen_8162eb67.cpp.o is disallowed by vsi_pcidsk_io_3fb5555b.o. Use --no-check-features to suppress.
wasm-ld: error: Target feature 'atomics' used in AcrossAllScreens_d743747f.cpp.o is disallowed by vsi_pcidsk_io_3fb5555b.o. Use --no-check-features to suppress.
wasm-ld: error: Target feature 'atomics' used in SphericalDisplay_304ce8c4.cpp.o is disallowed by vsi_pcidsk_io_3fb5555b.o. Use --no-check-features to suppress.
wasm-ld: error: Target feature 'atomics' used in WoWVxDisplay_fdf1d6d3.cpp.o is disallowed by vsi_pcidsk_io_3fb5555b.o. Use --no-check-features to suppress.
wasm-ld: error: Target feature 'atomics' used in View_f1143995.cpp.o is disallowed by vsi_pcidsk_io_3fb5555b.o. Use --no-check-features to suppress.
wasm-ld: error: Target feature 'atomics' used in Viewer_fa64136c.cpp.o is disallowed by vsi_pcidsk_io_3fb5555b.o. Use --no-check-features to suppress.
wasm-ld: error: Target feature 'atomics' used in ViewerBase_b5fa5bed.cpp.o is disallowed by vsi_pcidsk_io_3fb5555b.o. Use --no-check-features to suppress.
wasm-ld: error: Target feature 'atomics' used in DatabasePager_4a2d7958.cpp.o is disallowed by vsi_pcidsk_io_3fb5555b.o. Use --no-check-features to suppress.
wasm-ld: error: Target feature 'atomics' used in ImagePager_d26a682c.cpp.o is disallowed by vsi_pcidsk_io_3fb5555b.o. Use --no-check-features to suppress.
wasm-ld: error: Target feature 'atomics' used in ObjectCache_8a69497c.cpp.o is disallowed by vsi_pcidsk_io_3fb5555b.o. Use --no-check-features to suppress.
wasm-ld: error: Target feature 'atomics' used in fstream_a788c7dc.cpp.o is disallowed by vsi_pcidsk_io_3fb5555b.o. Use --no-check-features to suppress.
wasm-ld: error: too many errors emitted, stopping now (use -error-limit=0 to see all errors)

**Comment by tantan580** [comment]
Maybe this error means that SDL was compiled with threads disabled，I‘ll try it.

**Comment by tantan580** [comment]
[https://github.com/emscripten-core/emscripten/issues/9973](url)
