### ISSUE TITLE
Model texture error

### ISSUE THREAD

**Issue by sxsim** [gwaldron/osgearth#1419]
In some cases, the external model loaded by osgearth2.10.2 has a texture error, and the case data is as follows.

[http://forum.osgearth.org/file/n7593004/test.zip](url)

The same model shows no problems in OSG.

**Comment by gwaldron** [comment]
Which forum thread are you referring to?

**Comment by sxsim** [comment]
> Which forum thread are you referring to?

http://forum.osgearth.org/Bug-reports-osgearth-share-the-model-texture-td7593004.html

**Comment by gwaldron** [comment]
It almost looks like the texture state is "bleeding" from one level to the next, as if the child tile is trying to inherit a texture from the parent, but the association is getting lost, and it's inheriting a random texture from elsewhere in the draw. 

Sorry - I don't know what is happening after a quick glance.
