### ISSUE TITLE
MaskLayer error

### ISSUE THREAD

**Issue by HerediaLuis** [gwaldron/osgearth#1431]
I have a terrain model in which it includes a hole. The hole is introduced by adding a FeatureMaskLayer layer. The problem arises when representing it. It seems to work perfectly, but at certain zoom levels it represents the hole badly.
[sample.zip](https://github.com/gwaldron/osgearth/files/4091011/sample.zip)

**Comment by gwaldron** [comment]
Ref: http://forum.osgearth.org/MaskLayer-display-error-td7593051.html

**Comment by gwaldron** [comment]
Works now in master branch.

**Comment by gwaldron** [comment]
False alarm ... still broken

**Comment by gwaldron** [comment]
@plevy Please re-tests with the new TerrainConstraint implementation, thanks

**Comment by plevy** [comment]
Try this, but it is setup for osgEarth 3.X:

<map name="MyMap">
    <options> 
    	<profile>
			<srs>+proj=utm +zone=31 +ellps=WGS84 +datum=WGS84 +units=m +no_defs</srs>
			<xmin>264655.437</xmin>
			<xmax>269763.687</xmax>
			<ymin>4642818.244</ymin>
			<ymax>4647140.994</ymax>
		</profile>
    </options> 		 
    
	<image name="image" driver="gdal">
        <url>monzon.tif</url>
    </image>

    <elevation name="elevation" driver="gdal">
        <url>cotas.tif</url>
    </elevation>	
	
    <TerrainConstraint name="mask" remove_interior="true" has_elevation="true" enabled="true" min_level=0>	
        <OGRFeatures>

			<profile>+proj=utm +zone=31 +ellps=WGS84 +datum=WGS84 +units=m +no_defs</profile>
            <geometry>
                POLYGON((267005.447000 4645049.999911 291.183000, 267005.615145 4645049.820811 291.268000, 267005.711854 4645049.612139 291.322000, 267005.805655 4645049.395785 291.378000, 267005.896093 4645049.171518 291.436000, 267005.983673 4645048.938954 291.498000, 267006.066889 4645048.698014 291.562000, 267006.146176 4645048.448300 291.629000, 267006.221910 4645048.189302 291.700000, 267006.305483 4645048.094780 291.753000, 267006.617225 4645047.738391 291.956000, 267006.961452 4645047.338052 292.186000, 267007.341073 4645046.886482 292.446000, 267007.765489 4645046.372328 292.745000, 267008.243662 4645045.782116 293.089000, 267008.790863 4645045.096313 293.492000, 267009.419143 4645044.293237 293.966000, 267009.995880 4645043.442117 294.437000, 267010.302349 4645042.699020 294.773000, 267010.449022 4645042.433272 294.910000, 267011.012681 4645041.406067 295.444000, 267011.657416 4645040.209878 296.071000, 267012.403656 4645038.799880 296.815000, 267013.287625 4645037.106318 297.717000, 267014.349531 4645035.039147 298.824000, 267014.464510 4645033.792897 299.738000, 267013.427703 4645033.821282 300.203000, 267012.391387 4645033.929442 300.691000, 267011.342898 4645034.143263 301.222000, 267011.096890 4645034.146809 301.319000, 267010.253246 4645034.171663 301.647000, 267009.443481 4645034.206935 301.953000, 267008.663261 4645034.254900 302.239000, 267007.918284 4645034.299642 302.497000, 267007.240573 4645034.262661 302.671000, 267006.578254 4645034.235333 302.832000, 267005.918499 4645034.248089 303.002000, 267005.269524 4645034.283789 303.169000, 267004.670838 4645034.210262 303.242000, 267004.506278 4645034.172909 303.249000, 267003.928373 4645034.049524 303.269000, 267003.349876 4645033.935446 303.280000, 267002.770452 4645033.829504 303.282000, 267002.189875 4645033.728593 303.274000, 267001.607382 4645033.630621 303.255000, 267001.021293 4645033.543552 303.228000, 267000.431336 4645033.465517 303.193000, 266999.836963 4645033.395692 303.150000, 266999.237632 4645033.336322 303.099000, 266999.065753 4645033.320035 303.083000, 266998.459146 4645033.271707 303.021000, 266997.845330 4645033.225711 302.945000, 266997.219727 4645033.162900 302.843000, 266996.584096 4645033.109853 302.732000, 266995.939717 4645033.075113 302.616000, 266995.285814 4645033.055448 302.494000, 266994.618071 4645033.038263 302.356000, 266993.927287 4645033.003170 302.187000, 266993.220868 4645032.980322 302.007000, 266993.017076 4645032.977495 301.954000, 266992.292218 4645032.977651 301.763000, 266991.550072 4645032.991224 301.559000, 266990.813446 4645033.062860 301.375000, 266990.078863 4645033.178689 301.200000, 266989.330693 4645033.309704 301.014000, 266988.563420 4645033.450018 300.808000, 266987.781937 4645033.609798 300.591000, 266986.990551 4645033.796107 300.367000, 266986.181736 4645034.001292 300.127000, 266985.944304 4645034.058518 300.051000, 266985.095731 4645034.272050 299.775000, 266985.040246 4645035.307622 298.943000, 266988.845131 4645039.804724 296.015000, 266989.898926 4645041.412525 295.088000, 266990.967984 4645042.863660 294.215000, 266992.113526 4645044.216128 293.349000, 266992.449453 4645044.868821 293.024000, 266992.755332 4645045.447978 292.737000, 266993.037917 4645045.966592 292.482000, 266992.873415 4645045.968126 292.553000, 266989.465589 4645044.529691 294.394000, 266990.146966 4645045.324579 293.912000, 266990.745822 4645046.009118 293.498000, 266991.275771 4645046.603590 293.140000, 266991.751565 4645047.125253 292.827000, 266992.180183 4645047.585700 292.551000, 266992.571653 4645047.995573 292.306000, 266992.928277 4645048.361657 292.089000, 266993.255904 4645048.690666 291.894000, 266993.271384 4645048.764982 291.880000, 266993.328358 4645049.021503 291.831000, 266993.392963 4645049.272105 291.783000, 266993.463845 4645049.516574 291.736000, 266993.542643 4645049.754970 291.690000, 266993.625013 4645049.987072 291.647000, 266993.714611 4645050.212979 291.604000, 266993.810105 4645050.432581 291.562000, 266994.122977 4645050.623352 291.414000, 266993.584845 4645050.914326 291.700000, 266993.594539 4645050.979926 291.700000, 266993.633842 4645051.209201 291.700000, 266993.681349 4645051.436918 291.700000, 266993.787257 4645051.649438 291.673000, 266993.946134 4645051.842251 291.623000, 266994.105049 4645052.027773 291.576000, 266994.265632 4645052.205738 291.531000, 266994.426686 4645052.376791 291.489000, 266994.587098 4645052.541719 291.449000, 266994.749406 4645052.699610 291.411000, 266994.809153 4645052.736411 291.393000, 266995.013926 4645052.861721 291.334000, 266995.215778 4645052.979107 291.277000, 266995.407897 4645053.093589 291.228000, 266995.502486 4645053.270532 291.240000, 266995.644814 4645053.412581 291.226000, 266995.881724 4645053.472582 291.153000, 266996.111258 4645053.525468 291.084000, 266996.333420 4645053.572055 291.019000, 266996.589524 4645053.643892 290.955000, 266996.736960 4645053.747362 290.944000, 266996.886152 4645053.846520 290.934000, 266997.037639 4645053.940617 290.924000, 266997.190710 4645054.030458 290.916000, 266997.345316 4645054.116087 290.908000, 266997.501927 4645054.196687 290.901000, 266997.659933 4645054.273119 290.895000, 266997.819302 4645054.345418 290.890000, 266998.027314 4645054.429486 290.884000, 266998.192432 4645054.485379 290.878000, 266998.357993 4645054.537963 290.872000, 266998.524996 4645054.584455 290.867000, 266998.692672 4645054.626744 290.864000, 266998.861006 4645054.664857 290.860000, 266999.029985 4645054.698814 290.858000, 266999.199765 4645054.727645 290.857000, 266999.370102 4645054.752330 290.856000, 266999.542903 4645054.752963 290.847000, 266999.590197 4645054.773333 290.855000, 266999.762288 4645054.774979 290.850000, 266999.933941 4645054.772435 290.846000, 267000.105149 4645054.765732 290.843000, 267000.275848 4645054.753896 290.840000, 267000.446021 4645054.737945 290.839000, 267000.615664 4645054.717892 290.838000, 267000.784607 4645054.692754 290.838000, 267000.952940 4645054.663528 290.839000, 267001.116656 4645054.613685 290.833000, 267001.167979 4645054.618498 290.841000, 267001.334398 4645054.578401 290.844000, 267001.499756 4645054.533252 290.847000, 267001.664286 4645054.484002 290.851000, 267001.827591 4645054.429697 290.855000, 267001.989967 4645054.371258 290.861000, 267002.151390 4645054.308648 290.867000, 267002.311355 4645054.240946 290.874000, 267002.470242 4645054.169019 290.882000, 267002.616129 4645054.074304 290.880000, 267002.672506 4645054.069888 290.894000, 267002.827279 4645053.986026 290.903000, 267002.980677 4645053.897867 290.913000, 267003.132011 4645053.804585 290.923000, 267003.282460 4645053.707689 290.935000, 267003.430659 4645053.605596 290.948000, 267003.576452 4645053.498320 290.961000, 267003.721160 4645053.387220 290.975000, 267003.863237 4645053.270862 290.990000, 267003.975006 4645053.127621 290.988000, 267003.666171 4645052.824352 290.773000, 267003.824575 4645052.733392 290.810000, 267003.982766 4645052.635750 290.847000, 267004.143915 4645052.533352 290.888000, 267004.306242 4645052.424690 290.930000, 267004.469567 4645052.309423 290.975000, 267004.635491 4645052.188065 291.022000, 267004.802028 4645052.059297 291.072000, 267004.969841 4645051.923149 291.124000, 267005.084807 4645051.760545 291.150000, 267005.159453 4645051.727470 291.180000, 267005.222931 4645051.542588 291.182000, 267005.280748 4645051.355623 291.185000, 267005.333821 4645051.166922 291.189000, 267005.380143 4645050.976155 291.193000, 267005.421613 4645050.783851 291.198000, 267005.456200 4645050.589827 291.203000, 267005.485828 4645050.394472 291.209000, 267005.509447 4645050.197786 291.216000, 267005.447000 4645049.999911 291.183000, 267060.325000 4645050.000109 288.297000, 267060.958689 4645052.189470 287.960000, 267061.521065 4645054.424934 287.619000, 267062.010590 4645056.704601 287.273000, 267062.423771 4645059.026304 286.923000, 267062.757179 4645061.387605 286.568000, 267063.006488 4645063.785592 286.211000, 267062.477870 4645066.039897 286.207000, 267063.095226 4645068.636323 285.564000, 267063.655380 4645071.314094 284.895000, 267062.807430 4645071.747441 285.226000, 267063.411409 4645074.539192 284.462000, 267062.930003 4645076.988156 284.223000, 267062.358470 4645079.436077 283.981000, 267061.696189 4645081.879779 283.736000, 267061.643214 4645084.710520 283.087000, 267060.589717 4645087.042549 282.951000, 267059.502993 4645089.379926 282.782000, 267058.322945 4645091.684462 282.615000, 267057.052212 4645093.953566 282.449000, 267056.672527 4645094.592598 282.403000, 267055.339987 4645096.855798 282.203000, 267053.913927 4645099.077110 282.006000, 267052.396490 4645101.253296 281.811000, 267050.789198 4645103.380548 281.618000, 267049.193821 4645105.568176 281.352000, 267047.639867 4645107.871688 280.980000, 267045.993670 4645110.148025 280.600000, 267044.254698 4645112.393855 280.212000, 267042.423082 4645114.606596 279.814000, 267041.883999 4645115.230874 279.700000, 267039.715544 4645117.029402 279.503000, 267037.473135 4645118.758530 279.306000, 267035.158432 4645120.414409 279.107000, 267032.774581 4645121.995918 278.907000, 267030.322296 4645123.496575 278.706000, 267027.805717 4645124.917246 278.504000, 267024.951226 4645125.420770 278.739000, 267022.162366 4645126.042117 278.856000, 267019.478823 4645127.026101 278.734000, 267018.705813 4645127.288461 278.700000, 267015.986162 4645128.235335 278.533000, 267013.239215 4645129.185777 278.317000, 267010.444809 4645130.041283 278.099000, 267007.605698 4645130.794696 277.883000, 267004.725796 4645131.444901 277.668000, 267001.808944 4645131.989939 277.454000, 266998.859099 4645132.425996 277.242000, 266995.880490 4645132.751417 277.032000, 266992.877420 4645132.964714 276.824000, 266992.017697 4645133.002951 276.766000, 266989.036575 4645132.716498 276.739000, 266986.067408 4645132.313081 276.717000, 266983.115102 4645131.793269 276.700000, 266980.147536 4645131.309392 276.610000, 266977.212034 4645130.650307 276.555000, 266974.322801 4645129.808987 276.540000, 266971.491146 4645128.790813 276.564000, 266968.728250 4645127.600858 276.627000, 266966.025368 4645126.288675 276.703000, 266965.252298 4645125.924283 276.710000, 266962.124839 4645125.474591 276.237000, 266959.343262 4645124.243708 276.136000, 266956.839197 4645122.510612 276.267000, 266954.412938 4645120.684486 276.404000, 266952.068816 4645118.768086 276.547000, 266949.808713 4645116.767613 276.695000, 266947.635879 4645114.686826 276.847000, 266945.553398 4645112.529623 277.003000, 266943.563492 4645110.300753 277.164000, 266943.015001 4645109.651379 277.211000, 266940.815427 4645107.660432 277.145000, 266938.692868 4645105.581625 277.083000, 266936.650263 4645103.418847 277.026000, 266934.693466 4645101.173573 276.975000, 266932.824399 4645098.850708 276.929000, 266931.046308 4645096.453961 276.889000, 266929.363974 4645093.986126 276.853000, 266927.779550 4645091.451865 276.824000, 266926.412585 4645088.793826 276.866000, 266926.067477 4645088.014070 276.893000, 266925.104619 4645085.169773 277.088000, 266924.268604 4645082.297713 277.294000, 266923.555756 4645079.405784 277.507000, 266922.970364 4645076.498323 277.729000, 266922.508024 4645073.582844 277.959000, 266922.169635 4645070.664646 278.196000, 266921.985131 4645067.742505 278.456000, 266922.328939 4645064.754209 278.929000, 266922.809250 4645061.810057 279.415000, 266922.970624 4645060.979880 279.555000, 266924.547380 4645058.004233 280.521000, 266926.134248 4645055.163298 281.436000, 266927.763500 4645052.448856 282.320000, 266929.532142 4645049.858184 283.225000, 266932.747358 4645047.449058 284.809000, 266935.789310 4645045.251814 286.266000, 266937.966216 4645043.166668 287.255000, 266940.266890 4645041.240099 288.273000, 266942.522999 4645039.451084 289.241000, 266943.158170 4645038.965230 289.508000, 266947.337630 4645037.800134 291.431000, 266952.627149 4645037.217737 293.926000, 266956.671871 4645036.623308 295.786000, 266959.470770 4645035.875165 296.999000, 266961.136083 4645034.870351 297.607000, 266962.840959 4645033.975418 298.226000, 266964.589246 4645033.197316 298.862000, 266966.343135 4645032.522901 299.497000, 266965.926778 4645030.723443 300.319000, 266965.809127 4645030.192307 300.563000, 266964.829998 4645027.902148 301.911000, 266963.525127 4645025.212926 303.620000, 266963.018241 4645022.878298 304.794000, 266962.619647 4645020.465525 305.980000, 266962.248588 4645017.905758 307.253000, 266962.488875 4645015.716009 308.098000, 266962.654837 4645013.322471 309.116000, 266962.876210 4645010.824733 310.200000, 266963.160095 4645008.217635 311.356000, 266963.312967 4645007.524140 311.637000, 266965.414147 4645006.921842 311.049000, 266967.466113 4645006.356846 310.510000, 266969.474786 4645005.826858 310.016000, 266971.444025 4645005.329268 309.565000, 266973.378696 4645004.863700 309.155000, 266975.280979 4645004.426021 308.784000, 266977.156007 4645004.017740 308.449000, 266979.005926 4645003.635555 308.150000, 266980.869924 4645003.366168 307.823000, 266981.345175 4645003.165416 307.828000, 266983.137783 4645002.804772 307.631000, 266984.916384 4645002.462531 307.468000, 266986.684327 4645002.138677 307.339000, 266988.444348 4645001.831613 307.243000, 266990.207622 4645001.581191 307.153000, 266991.980301 4645001.433580 307.036000, 266993.746589 4645001.316879 306.942000, 266995.507686 4645001.229351 306.871000, 266997.266603 4645001.198381 306.805000, 266997.765500 4645001.158980 306.814000, 266999.521817 4645001.300239 306.688000, 267001.266234 4645001.461405 306.590000, 267003.000514 4645001.651909 306.514000, 267004.725887 4645001.872365 306.459000, 267006.443580 4645002.122551 306.426000, 267008.154816 4645002.402416 306.414000, 267009.860801 4645002.712075 306.423000, 267011.562716 4645003.051806 306.454000, 267013.261700 4645003.422050 306.506000, 267013.745586 4645003.533348 306.525000, 267015.486538 4645003.812032 306.696000, 267017.237404 4645004.123362 306.892000, 267019.001534 4645004.463371 307.114000, 267020.779605 4645004.835866 307.363000, 267022.567831 4645005.252753 307.631000, 267024.370995 4645005.706973 307.923000, 267026.205261 4645006.175103 308.261000, 267028.029382 4645006.730136 308.590000, 267029.871170 4645007.325762 308.946000, 267030.399967 4645007.502727 309.054000, 267030.197175 4645010.837029 307.188000, 267029.996946 4645013.857532 305.533000, 267029.798635 4645016.611527 304.055000, 267029.603089 4645019.135869 302.730000, 267029.408604 4645021.463415 301.538000, 267029.210787 4645023.623703 300.458000, 267031.569904 4645023.487173 297.846000, 267033.504754 4645023.854214 297.210000, 267035.515821 4645024.281242 296.534000, 267036.102688 4645024.415328 296.335000, 267038.149059 4645024.972284 295.646000, 267040.268057 4645025.603205 294.918000, 267042.465300 4645026.312576 294.147000, 267044.741009 4645027.108667 293.331000, 267047.099400 4645027.997921 292.467000, 267049.546261 4645028.986917 291.550000, 267052.080592 4645030.085913 290.580000, 267055.963004 4645030.873991 288.889000, 267057.006852 4645032.776085 288.683000, 267057.149395 4645033.369287 288.700000, 267057.910186 4645035.380559 288.596000, 267058.470924 4645037.452772 288.558000, 267058.978120 4645039.542752 288.510000, 267059.407544 4645041.653410 288.464000, 267059.758357 4645043.781746 288.419000, 267060.030834 4645045.924657 288.375000, 267060.223380 4645048.079217 288.332000, 267060.325000 4645050.000109 288.297000, 267005.447000 4645049.999911 291.183000)) 
            </geometry>
        </OGRFeatures>
    </TerrainConstraint>
</map>
