### ISSUE TITLE
Remove MapNodeObserver in 3.0 branch

### ISSUE THREAD

**Issue by jasonbeverage** [gwaldron/osgearth#1433]
MapNodeObserver isn't functioning in the 3.0 branch and it looks like most things that implement it have been updated to look for the MapNode in the update traversal by calling:
MapNode* mapNode = osgEarth::findInNodePath<MapNode>(nv);

We should just remove MapNodeObserver completely.

**Comment by gwaldron** [comment]
For now there are a few "known users" of the classes out there. Suggest we leave it intact for now but keep an eye on it.
