### ISSUE TITLE
Setting model pitch using an earth file

### ISSUE THREAD

**Issue by rheirman** [gwaldron/osgearth#1441]
I would like to set a custom pitch for my models, but there's currently no option available that can be passed to the model symbol in the earth file. Is there any other way to set the model pitch through the earth file? I've looked into setting it using JavaScript, but I can't figure out if it's possible to set model symbol attributes that way.

**Comment by gwaldron** [comment]
You could try the OSG "rot" pseudoloader; Check the docs in the [source code here](https://github.com/openscenegraph/OpenSceneGraph/blob/master/src/osgPlugins/rot/ReaderWriterROT.cpp).
