### ISSUE TITLE
Uninitialized numPoints variable

### ISSUE THREAD

**Issue by emminizer** [gwaldron/osgearth#1450]
I'm on the 3.0 branch and noticed that there's an uninitialized variable in one of the switch statements in `OgrUtils::createGeometry()`:

https://github.com/gwaldron/osgearth/blob/3.0/src/osgEarth/OgrUtils.cpp#L207

I'm not familiar enough with the API to suggest a fix, but I'm pretty confident the variable is uninitialized when it gets passed to `new PointSet`.

**Comment by gwaldron** [comment]
Thanks. Correct solution is to use the default ctor for PointSet instead

**Comment by gwaldron** [comment]
fixed
