### ISSUE TITLE
cannot find operator < in DrawTileCommand

### ISSUE THREAD

**Issue by hankern** [gwaldron/osgearth#1451]
in DrawTileCommand line 88-93
`bool operator < (const DrawTileCommand& rhs) const
        {
            if (_key->getLOD() > rhs._key->getLOD()) return true;
            if (_key->getLOD() < rhs._key->getLOD()) return false;
            return _geom < rhs._geom;
        }`
cannot find operator < of _geom?

**Comment by gwaldron** [comment]
It's just a pointer comparison.
