### ISSUE TITLE
(GEOS 3.8) Geos function mismatch when building osgEarthSymbology/GEOS.cpp

### ISSUE THREAD

**Issue by paul-jewell** [gwaldron/osgearth#1455]
I am receiving the error shown below when building with release 2.10.1. Geos version installed is 3.8.0-r1. I have replicated this on two different computer systems, both running Gentoo. Have you seen any errors similar to this? 

I appreciate your comments!

Error message:
`[ 28%] Building CXX object src/osgEarthSymbology/CMakeFiles/osgEarthSymbology.dir/GeometryRasterizer.cpp.o
cd /var/tmp/portage/sci-geosciences/osgearth-2.10.1/work/osgearth-2.10.1_build/src/osgEarthSymbology && /usr/bin/x86_64-pc-linux-gnu-g++ -DOSGEARTHSYMBOLOGY_LIBRARY -DOSGEARTH_CXX11 -DOSGEARTH_HAVE_GEOS -DosgEarthSymbology_EXPORTS -I/var/tmp/portage/sci-geosciences/osgearth-2.10.1/work/osgearth-osgearth-2.10.1/src -I/var/tmp/portage/sci-geosciences/osgearth-2.10.1/work/osgearth-osgearth-2.10.1   -DNDEBUG -march=native -O2 -pipe -fPIC   -std=gnu++11 -o CMakeFiles/osgEarthSymbology.dir/GeometryRasterizer.cpp.o -c /var/tmp/portage/sci-geosciences/osgearth-2.10.1/work/osgearth-osgearth-2.10.1/src/osgEarthSymbology/GeometryRasterizer.cpp
/var/tmp/portage/sci-geosciences/osgearth-2.10.1/work/osgearth-osgearth-2.10.1/src/osgEarthSymbology/GEOS.cpp: In function ‘geos::geom::CoordinateSequence* {anonymous}::vec3dArray2CoordSeq(const osgEarth::Symbology::Geometry*, bool, const geos::geom::CoordinateSequenceFactory*)’:
/var/tmp/portage/sci-geosciences/osgearth-2.10.1/work/osgearth-osgearth-2.10.1/src/osgEarthSymbology/GEOS.cpp:67:56: error: cannot convert ‘std::unique_ptr<geos::geom::CoordinateSequence>’ to ‘geos::geom::CoordinateSequence*’ in initialization
   67 |         geom::CoordinateSequence* seq = factory->create( coords );
      |                                         ~~~~~~~~~~~~~~~^~~~~~~~~~
      |                                                        |
      |                                                        std::unique_ptr<geos::geom::CoordinateSequence>
/var/tmp/portage/sci-geosciences/osgearth-2.10.1/work/osgearth-osgearth-2.10.1/src/osgEarthSymbology/GEOS.cpp: In function ‘geos::geom::Geometry* {anonymous}::import(const osgEarth::Symbology::Geometry*, const geos::geom::GeometryFactory*)’:
/var/tmp/portage/sci-geosciences/osgearth-2.10.1/work/osgearth-osgearth-2.10.1/src/osgEarthSymbology/GEOS.cpp:158:65: error: no matching function for call to ‘geos::geom::GeometryFactory::createPolygon(geos::geom::LinearRing*&, std::vector<geos::geom::Geometry*>*&) const’
`

**Comment by paul-jewell** [comment]
Building with geos 3.7.2 doesn't exhibit this error. It builds without any issues.

**Comment by gwaldron** [comment]
Please update, or confirm that this works now in 3.x. Otherwise I will close the issue

**Comment by paul-jewell** [comment]
Good afternoon - the package now compiles correctly. osgearth version 3.1, and geos version 3.9. Many thanks!
