### ISSUE TITLE
PrimitiveIntersector::Intersection copy constructor is not exported

### ISSUE THREAD

**Issue by Moohasha** [gwaldron/osgearth#1458]
The PrimiritiveIntersector::Intersection struct is defined entirely inline _except_ for the copy constructor.  Since it's defined in the cpp file, this limits the use of the struct outside of the osgEarth, such as copying hits to another container.  The easiest thing would be to define the copy constructor inline like the other methods, or just export the copy constructor.  Unless this was done intentionally.

https://github.com/gwaldron/osgearth/blob/88512ab5eea80c4fc0ddfb7e9d332f5173b6bc37/src/osgEarth/PrimitiveIntersector#L49

**Comment by Moohasha** [comment]
I thought about just fixing this and putting up a pull request, but A) I don't know what branch to target, and B) I don't know the process for submitting code changes.

**Comment by gwaldron** [comment]
Hi. Please target the 3.0 branch. A PR is the best way to submit changes. Thanks!
