### ISSUE TITLE
[3.0]Geocoder can't link correctly to osgearth.dll

### ISSUE THREAD

**Issue by TMwhuhan** [gwaldron/osgearth#1460]
error LNK2019: 无法解析的外部符号 OGRGeocodeCreateSession，该符号在函数 "public: __cdecl osgEarth::Geocoder::Geocoder(void)" (??0Geocoder@osgEarth@@QEAA@XZ) 中被引用
2>Geocoder.obj : error LNK2019: 无法解析的外部符号 OGRGeocodeDestroySession，该符号在函数 "public: __cdecl osgEarth::Geocoder::Geocoder(void)" (??0Geocoder@osgEarth@@QEAA@XZ) 中被引用

envirament: vs2019 64bit 
                    gdal 3.0.3  + proj 6.0.2
                    osg 3.6.4 + osgearth3.0

**Comment by mylxiaoyi** [comment]
Hi, @TMwhuhan , I have the same problem, how did you solve it? Thanks.

**Comment by gwaldron** [comment]
Disable the geocoder in CMAKE with 
OSGEARTH_ENABLE_GEOCODER=OFF

**Comment by mylxiaoyi** [comment]
@gwaldron  Thanks
