### ISSUE TITLE
(GDAL3/PROJ6) ModelSymbol are not loaded vertically to the terrain (on polygons and lines)!

### ISSUE THREAD

**Issue by MCA4213** [gwaldron/osgearth#1472]
Hi,
I an running on the lates master osgEarth (26/03/202), and I am facing some troubles in loading trees on polygon shapefile (same with lines, but points are ok). my problem is that the trees are loaded inclined (not vertical to terrain) as in the image.

![Capture](https://user-images.githubusercontent.com/7198569/77643636-08004380-6f60-11ea-805c-bdec7ccccf62.PNG)

my code is as follow:
```
        OGRFeatureSource* data = new OGRFeatureSource();
        data->setURL(path.toStdString());
        data->options().buildSpatialIndex() = true;
        data->open();
        Style style;
        style.setName("parks");

        ModelSymbol* model = style.getOrCreate<ModelSymbol>();
        model->url()->setLiteral(modelPath);
        model->placement() = model->PLACEMENT_RANDOM;
        model->density() = densite;
        model->scale() = scale;

        AltitudeSymbol* alt = style.getOrCreate<AltitudeSymbol>();
        alt->clamping() = alt->CLAMP_TO_TERRAIN;
        //alt->clampingResolution() = 0;
        RenderSymbol* render = style.getOrCreate<RenderSymbol>();
        render->transparent() = true;
        render->minAlpha() = 0.15f;
        FeatureDisplayLayout layout;
        layout.tileSizeFactor() = tilesize;
        layout.addLevel(FeatureLevel(minRange, maxRange, "parks"));
        FeatureModelLayer* layer = new FeatureModelLayer();
        layer->setFeatureSource(data);
        layer->options().layout() = layout;
        layer->setStyleSheet(new StyleSheet());
        layer->getStyleSheet()->addStyle(style);
        map->addLayer(layer);
```

Any help please to fix the angle of the trees to be normal to the terrain?
Thanks.

**Comment by gwaldron** [comment]
Can you reproduce the error with an earth file? And if so can you post it here? Thanks.

**Comment by MCA4213** [comment]
yes, same with the earth file,  but in boston.earth the spotlights are correctly loaded where the parks are not loaded at all.
I create a similar earth file on my region and same things: trees are inclined and not vertical!

![Capture](https://user-images.githubusercontent.com/7198569/77666428-3c382c00-6f81-11ea-9484-ddc005994061.PNG)

![Capture2](https://user-images.githubusercontent.com/7198569/77666508-570aa080-6f81-11ea-945a-6994e1291cc9.PNG)


the code:

```
<map name="Boston Demo">
    <GDALImage name="nearest">
        <url>loopix/world_image.tif</url>
        <max_data_level_override>19</max_data_level_override>
        <interpolation>nearest</interpolation>
    </GDALImage>
    <GDALImage name="bilinear">
        <url>GhazOrtho_tiled.tif</url>
        <interpolation>bilinear</interpolation>
        <max_data_level_override>19</max_data_level_override>
    </GDALImage>
    <GDALElevation name="elev">
        <url>GhazMNT_tiled.tif</url>
    </GDALElevation>
	
    <FeatureModel name="Parks" enabled="true">
        <OGRFeatures name="parks">
            <url>Veg_poly/veg_poly.shp</url>
        </OGRFeatures>            
        <feature_indexing enabled="false"/>
        <styles>
            <style type="text/css">
                default {
                   model:                  "loopix/tree4.osgb";
		   model-scale:            2 + 0.1*Math.random();
                   model-placement:        random;
                   model-density:          300;
		   model-heading:          Math.random() * 360.0;
                   altitude-clamping:      terrain;
                   render-transparent:     true;
                   render-min-alpha:       0.15;
                }
            </style>
        </styles>        
    </FeatureModel>
</map>
```

**Comment by gwaldron** [comment]
Hmm, I cannot reproduce this in the master branch.

![image](https://user-images.githubusercontent.com/326618/77667876-20209480-6f59-11ea-80d4-17e072bb9e85.png)

Earth file:

`<map name="Demo">
    <FeatureModel name="Parks" enabled="true">
        <OGRFeatures name="parks">
            <url>../data/parks.shp</url>
        </OGRFeatures>            
        <feature_indexing enabled="false"/>
        <styles>
            <style type="text/css">
                default {
                   model:                  "../data/loopix/tree4.osgb";
		           model-scale:            2 + 0.1*Math.random();
                   model-placement:        random;
                   model-density:          300;
		           model-heading:          Math.random() * 360.0;
                   altitude-clamping:      terrain;
                   render-transparent:     true;
                   render-min-alpha:       0.15;
                }
            </style>
        </styles>        
    </FeatureModel>
</map>`

**Comment by MCA4213** [comment]
I tested your file with  the same data and same things, always inclined.

******BUT when I removed my PROJ_LIB variable of my proj6 library, I cannot charge my tif files (logic) but I got the trees with the correct normal!!!!!
![Capture3](https://user-images.githubusercontent.com/7198569/77671813-693c0d00-6f88-11ea-8306-27d499f98d9f.PNG)

I think that the problem is linked to the proj6 library (perhaps because of axis inversion or ....)? 
Are you using the same proj6 or the old proj4????

**Comment by gwaldron** [comment]
Ah...yes, we have noticed various problems with GDAL 3 + PROJ 6.
We use GDAL 2.4.1 (from vcpkg).

**Comment by plevy** [comment]
I want to try and reproduce this issue.  How are you building gdal 3 and proj 6? Or using gisinternals pre-built?

**Comment by MCA4213** [comment]
Hi, usually I used the gisinternals pre-built version for "MSVC 2017 x64" but this time I used the third-party from the gisinternals, and I compiled the GDAL with a newer version of geos (3.7.3 for QGIS compatibility).

But I think that the gisinternals pre-built version should **WORK** because I use the same Proj version 6.1.

Thank you.

**Comment by plevy** [comment]
Last time I built gdal 3.0, it just worked with osgEarth.  Now I am getting some unresolved symbols on the new out-of-tree drivers such as:
Out-of-tree drivers:
* GDALDataset::GetProjectionRef() made non-virtual.
  Replaced by GetSpatialRef() virtual method.
  Compatibility emulation possible by defining:
    const char* _GetProjectionRef() override; // note leading underscore
    const OGRSpatialReference* GetSpatialRef() const override {
        return GetSpatialRefFromOldGetProjectionRef();
    }

Did you make any changes to the gdal driver?  Just wondering if my gdal build is off or I forgot to do something.  I don't remember getting or fixing unresolved symbols last time.  It was an earlier version of gdal, maybe 3.0 or 3.0.1

**Comment by MCA4213** [comment]
No, I did not do any change. I am also on an earlier version of GDAL 3.0.1 ( compiled on 28/09/2019), so I did not find any problems.

**Comment by plevy** [comment]
OK, let me try that again..that was around the same time I last built osgearth and gdal 3.

**Comment by plevy** [comment]
OK, I see the same, with PROJ_LIB set, the trees are rotated, mine are underground.  Without PROJ_LIB set, trees look correct.

**Comment by MCA4213** [comment]
It depends on the location, for Boston as example it is underground, for north Africa (my example) it is rotated with that angle as in the previous images.

**Comment by plevy** [comment]
Can you try this file.  Rename your parks.prj, rename this file to parks.prj and see of the trees look normal
[parks.prj.txt](https://github.com/gwaldron/osgearth/files/4411234/parks.prj.txt)

**Comment by MCA4213** [comment]
Yes I confirm, with your parks.prj I can see the trees loaded correctly on the map.

**Comment by plevy** [comment]
Just going through the tests and data with osgEarth, Proj6 seems to have issues with some datums.  parks.prj and parks-boston.prj need the datum to be D_NAD83 and then it works.  Perhaps this was part of reducing redundancy in the new proj.db.  Seems odd that D_NAD83 would work but not NAD83.  In most cases, if OSGEARTH_NOTIFY_LEVEL is set to INFO, there should be an error message showing the two coordinate systems and an error saying [osgEarth]* [SpatialReference] SRS xform not possible

Are you using libprotobuf?  Gisinternals has a libprotobuf but looks to be compiled static as is the default now on libprotobuf.

**Comment by MCA4213** [comment]
Hi, first thanks for your work,
For libprotobuf I am using a dynamic one,. As I said: I compile my GDAL on my own, I use almost all 3rdParty from Gisinternals  except Geos, TileDB and protobuf.

For the projection problem, re-projecting my shapefile with a proj5 in Grass 3.10 give me the correct results, even if it will force me to do many changes to my data. 

BUT looking on GDAL folder, I found the **old Proj still exists** with the new one. 
My question is it possible to use one of them automatically depending on the the projection string in osgEarth?

**Comment by plevy** [comment]
From the way I read it, no.  There is only a single proj.db now which is a cleaned-up version of the old files.  From the notes it says:

WKT1, WKT2, ESRI WKT, PROJ strings import and export is now delegated to PROJ. The same holds for import of CRS from the EPSG database, that now relies on proj.db SQLite database. Consequently all the data/*.csv files that contained CRS related information have been removed from GDAL. 

Just curious, why did you switch to GDAL 3? Just testing or is there new functionality you needed?

Thank you

**Comment by MCA4213** [comment]
Hi, after digging in the code and searching on the internet, and as we discuss here: the problem was related to the Proj lib.
In osgEarth the Proj string is always favorized against others projection definitions, so if we change the SpatialReference.cpp file by replacing all the Proj string with EPSG as example, and make WKT preferable before the Proj this will fix the problem of the vertical symbols.
Also you need to add 
    `CPLSetConfigOption("OGR_CT_FORCE_TRADITIONAL_GIS_ORDER", "YES");` to the Registry.cpp to fix inverted coordinates.

I have put the files that make this work for me on this link: [https://github.com/MCA4213/osgEarth-Fix-GDAL3](https://github.com/MCA4213/osgEarth-Fix-GDAL3)

Note: in the SpatialReference.cpp file, I didn't take all cases (I focused only on wgs84), so it still need some works. As example: for the utm transformation: different datum=> different EPSG and I did not fix that.

**Comment by MCA4213** [comment]
Hi, I confirm that this issue is resolved. thanks
