### ISSUE TITLE
The rex engine doesn't render terrain on Mali GPU (Huawei phone) with release 2.10.2,but MP engine works well.

### ISSUE THREAD

**Issue by cooljil** [gwaldron/osgearth#1476]
Hi,
The rex engine doesn't render terrain on Mali GPU (Android system, Huawei phone,GPU of ARM) with release 2.10.2, but MP engine works well.

**Comment by gwaldron** [comment]
Thanks. We do not generally develop on GLES systems, and rely on the community to support them as needed. Feel free to submit PRs for GLES fixes.
