### ISSUE TITLE
3dTiles model have no texture

### ISSUE THREAD

**Issue by 1753592** [gwaldron/osgearth#1478]
GLTFReader.h:376   i think the geometry should use setTextureAttributeAndModes,if else ShaderGenerator's state capture nothing.

**Comment by jasonbeverage** [comment]
Do you have a sample model that is showing the issue that we could test with?

**Comment by jasonbeverage** [comment]
Actually I remembered seeing this issue in non GL3/GLcore builds awhile ago and you're correct, we should be calling setTextureAttributeAndModes.  I've pushed a fix in b40c7193e34f2cb77b16321f203a1420371c0bd7.
