### ISSUE TITLE
WIP: upgrading from osgEarth 2.x to osgEarth 3.x - hints

### ISSUE THREAD

**Issue by remoe** [gwaldron/osgearth#1481]
- some include paths are different (Symbology, Annotations, Features)
- fast_map replaced with UnorderedMap
- TerrainEffects removed.
- getProfile() -> getTilingProfile()
- MapNode::getOverlayDecorator removed (osgEarth::Util::findTopMostNodeOfType<OverlayDecorator>() ? )
- new ImageLayer -> ImageLayer::create
- ImageLayerOptions -> ImageLayer::Options (prevent forward declare :/ )
- ModelLayerOption -> ModelLayer::Options
- MapOptions -> Map::Options
- MapNodeOptions -> MapNode::Options
- MapFrame removed (https://github.com/gwaldron/osgearth/commit/66323ed058f34a7703df4f7e2d94a83e53bddb89#diff-d8a1d7c2f3a0882ff635d1e978abdc49)
- LabelSource removed (https://github.com/gwaldron/osgearth/commit/bae24a5b051517aa61f5e8c31cc7b380c77885ac)
- FeatureSourceFactory / OGRFeatureOptions removed ->OGRFeatureSource (osgearth_callouts sample)  
- Map::isGeocentric() ->MapNode::isGeocentric()
- TerrainLayer -> TileLayer ( no getTileSource ) (https://github.com/gwaldron/osgearth/issues/1414)
- GeometryCompilerOptions::useGPUScreenSpaceLines() removed
- earth file: ```<sky>``` -> ```<sky_simple>```

**Comment by remoe** [comment]
osgearth_pagingtest
osgearth_sharedlayer
osgearth_featuretiler

Are removed, why?

can't find this includes "osgEarthDrivers/feature_ogr/OGRFeatureOptions"

**Comment by remoe** [comment]
Can't find an alternative for GeometryCompilerOptions::useGPUScreenSpaceLines(). Is it not needed in 3.0?

**Comment by remoe** [comment]
Does anyone know why it could get this error:

```
[osgEarth]* [ShaderLoader] Inline source for "RexEngine.Morphing.vert.glsl" is empty, and no external file could be found.
[osgEarth]* [ShaderLoader] Failed to load shader source from "RexEngine.Morphing.vert.glsl"
```

**Comment by plevy** [comment]
Remo, Glenn fixed the "RexEngine.Morphing.vert.glsl" issue earlier today

**Comment by remoe** [comment]
How one can convert this earth file fragment to osgEarth 3.0 ?

```xml
<sky driver="simple" hours="12.0" ambient="0.3"/>
```

**Comment by Himbeertoni** [comment]
* The color filters (Gamma, RGB, BrightnessContrast) for the image layers are gone in 3.0
* I had to call osgEarth::MapNode::open() after creating the osgEarth::Map, otherwise osgEarth::MapNode::getTerrainEngine() would return a nullptr. Apparently this was done internally in versions prior to 3.0?
* I had to add ${CMAKE_CURRENT_BINARY_DIR}/build/build_include to the list of osgEarth include directories, due to the new BuildConfig.h
