### ISSUE TITLE
Powerlines: lines can dip below ground on long run

### ISSUE THREAD

**Issue by gwaldron** [gwaldron/osgearth#1484]
On a long run, the lines can dip below the ground. Perhaps limit the sag to a percentage of the tower height?

![image](https://user-images.githubusercontent.com/326618/78911181-f9338980-7a53-11ea-866e-6844b9c74440.png)

**Comment by timoore** [comment]
Fixed by e9cb7e030944e46366995469b16f1790723c7f13
