### ISSUE TITLE
MapBox Vector Tile  problem

### ISSUE THREAD

**Issue by 1753592** [gwaldron/osgearth#1489]
MVT.cpp:713  i see the setFirstLevel has changed to minLevel, i have a line data which has 6 levels, pagelod's minRange set to 0, they all become visiable. i can not figure out a proper solution.
![2020-04-15_111300](https://user-images.githubusercontent.com/16001348/79294977-1a8bee00-7f0a-11ea-9744-e68a347529d7.jpg)

**Comment by remoe** [comment]
Do you have an earth file to reproduce this?

**Comment by 1753592** [comment]
[mvt.zip](https://github.com/gwaldron/osgearth/files/4492054/mvt.zip)    at lo:-149.3 la:60.3

**Comment by jasonbeverage** [comment]
The FeatureModelGraph in osgEarth doesn't support non-additive feature datasets.  There is another layer called TiledFeatureModel that supports both additive and non-additive datasets.  Your example was very helpful in finding a small bug in TiledFeatureModel, so thanks for providing it.

You can do something like this with your dataset
`
    <TiledFeatureModel name="railway" enabled="true" additive="false">
		
        <MVTFeatures name="railway_source">
            <url>D:\\tmp\\mvt\\railway.mbtiles</url>
            <profile>spherical-mercator</profile>
        </MVTFeatures>

		<Styles>
			<style type="text/css">
		    default {
                fill:               #00000000;
                stroke:             #00ff00;
                stroke-width:       1.0;
                altitude-clamping:  terrain;
                altitude-technique: drape;
                render-lighting:    false;
            }
			</style>
		</Styles>
        
	</TiledFeatureModel>
`
