### ISSUE TITLE
ThreeDTileNode has a cull trouble

### ISSUE THREAD

**Issue by 1753592** [gwaldron/osgearth#1492]
if a tile has region boundingVolume，the _content is effected by transform matrix which is defined in tileset.json， but _boundingBox  is effected by both the _boundingBoxLocalToWorld and transform, in my data the two matrix is same basically. so the cullvisitor culled my model in ThreeDTileNode::traverse. in the jpg, white model's boundingbox is the green one.
![2020-04-17_103150](https://user-images.githubusercontent.com/16001348/79527709-dda33100-809a-11ea-8fb9-139d4d0a2a6a.jpg)

**Comment by jasonbeverage** [comment]
Do you have a sample 3d tiles we can test against?

**Comment by 1753592** [comment]
[shptest.zip](https://github.com/gwaldron/osgearth/files/4493321/shptest.zip)
you may have to change the result of computeScreenSpaceError to a large number to make sure this tile not be pass by.

**Comment by 1753592** [comment]
if (tile->transform().isSet()) {
		_boundingBoxLocalToWorld = osg::Matrixd::identity();
	}
add this after computeBoundingVolume works fine, but i do not think its a good idea.

**Comment by jasonbeverage** [comment]
Thanks for the test file, it's so useful when we get data to help reproduce a bug.  I just pushed a fix for it in af4241d55fb8ea287958079e125583456c65b7b9
