### ISSUE TITLE
How to Tether A Node in 2.10.2?

### ISSUE THREAD

**Issue by Simon-Wong** [gwaldron/osgearth#1503]
How can I tether a node to make the camera follow it while there is no method named setTetherNode in OsgEarth 2.10.2?
All I can find is setTetherMode and setTetherCallback.
Help!

**Comment by gwaldron** [comment]
Viewpoint vp;
vp.setNode(...);
manip->setViewpont (vp);

**Comment by Simon-Wong** [comment]
Thanks.
It works well when the node is just a osg::Node,but failed when osgEarth::Annotation::ModelNode.
Does it need additional settings?

**Comment by gwaldron** [comment]
ModelNode's transforms are children of the node itselg, so you will need to access one of them and tether to it instead:

ModelNode::getGeoTransform()
ModelNode::getPositionAttitudeTransform()

Good luck.

**Comment by Simon-Wong** [comment]
Thanks a lot.
I have put a matrixtransform without any model resource which has the same Lon-Lat-Alt & Heading-Pitch-Roll as the ModelNode.
HAHA.It seems that I have a lot to learn.

**Comment by Simon-Wong** [comment]
Thank you very much.
