### ISSUE TITLE
Feature: LineString  cannot be shown 

### ISSUE THREAD

**Issue by BoyChan** [gwaldron/osgearth#1506]
I update osgEarth2.10.1 and osg3.4.0. I find that LineString cannot be rendered ,but Point and Polygon can be render. I use the example of osgearth_annotation by .earth file , it's okay.Can you how to solve it?Thanks :)

**Comment by Simon-Wong** [comment]
Try this code:
osgEarth::GLUtils::setGlobalDefaults(refptrVeiwer->getCamera()->getOrCreateStateSet());

**Comment by BoyChan** [comment]
> Try this code:
> osgEarth::GLUtils::setGlobalDefaults(refptrVeiwer->getCamera()->getOrCreateStateSet());

thanks. I found that the line must be child of the MapNode, otherwise, the line cannot be drawn ,the function of FeatureNode::setMapNode is invalid.

**Comment by gwaldron** [comment]
If you want your features outside the MapNode, then in addition to ```setGlobalDefaults``` mentioned by @Simon-Wong , you will also need to call ```addCullCallback(new InstallCameraUniform());``` on one of your nodes, likely a top-level group node. 
Placing your features under a MapNode automatically does both of these things. Hope this helps.

**Comment by BoyChan** [comment]
> If you want your features outside the MapNode, then in addition to `setGlobalDefaults` mentioned by @Simon-Wong , you will also need to call `addCullCallback(new InstallCameraUniform());` on one of your nodes, likely a top-level group node.
> Placing your features under a MapNode automatically does both of these things. Hope this helps.

Oh,thanks. You are excellent:)
