### ISSUE TITLE
(GDAL3/PROJ6) ModelSymbol not getting elevation from projected elevationLayer

### ISSUE THREAD

**Issue by MCA4213** [gwaldron/osgearth#1516]
Hi, I am facing another problem with osgEarth and GDAL3/PROJ6. 
I have two Elevation layers:
1- World: 
`GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AXIS["Latitude",NORTH],AXIS["Longitude",EAST],AUTHORITY["EPSG","4326"]]`
and 
2-UTM30N (high resoltion): 
`PROJCS["WGS 84 / UTM zone 30N",GEOGCS["WGS 84",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AUTHORITY["EPSG","4326"]],PROJECTION["Transverse_Mercator"],PARAMETER["latitude_of_origin",0],PARAMETER["central_meridian",-3],PARAMETER["scale_factor",0.9996],PARAMETER["false_easting",500000],PARAMETER["false_northing",0],UNIT["metre",1,AUTHORITY["EPSG","9001"]],AXIS["Easting",EAST],AXIS["Northing",NORTH],AUTHORITY["EPSG","32630"]]`

The layers are loaded correctly in the viewer with correct elevation, but when I add modelSymbols they takes the elevation of the first one, the second one is ignored!!!
Even if I load the second one only, they are at 0m elevation, so not taken also.

![Capture](https://user-images.githubusercontent.com/7198569/81482076-5033a680-922c-11ea-88af-fa8280316eb4.PNG)

**Comment by MCA4213** [comment]
Hi I am trying to figure out how to fix this problem. I am trying to understand the call hierarchy for this. This what I found till now, perhaps it will help someone.

In this example I will use only one elevation layer for a region of 2*2 degrees with UTM30N (wgs84) on a geocentric maps with Epsg:4326 as SRS:

1. The projected elevation gives a correct terrain rendering, but symbols elevation are wrong;
2. Following the different calls I attend the AltitudeFilter.cpp file, and at ```void AltitudeFilter::pushAndClamp( FeatureList& features, FilterContext& cx )``` function you can find `eq.getElevations( geom->asVector(), featureSRS.get(), elevations, _maxRes ) )` that is returning always 0
3. Testing elevationQuery alone gives same results: always 0.
4. Trying to understand more, I took the same file but in 4326 srs:
-  when the projected layer is loaded it gives maxLevel of lod equal to 2.
-  For the same layer with 4326 srs, it gives a maxLevel lods equal to 12.
-  If I force the `lodToUse = osg::minimum(_lod, i->maxLevel().get());` in the ```bool ElevationEnvelope::sample(..) ``` function in the ElevationPool.cpp file with a value of 12 (as for the layer with 4326 srs) for the projected layer (that return lodToUse=2) I will be able to get the correct elevation and everything will work. (but every layer has its own max lod)
- The tile returned by the lodToUse=2 is perhaps invalid, but something is sure: the elevation is always 0 (set to nodata).

So at this level I don't know how to continue, I cannot understand why for the same region and same data with different srs we have different lod (perhaps srs extents?)???
Why with a max lod=2 the rendering is working and the ElevationQuery is failing???

Perhaps some explanation will help me to find a fix.
Thanks.

**Comment by MCA4213** [comment]
Hi, after testing I found that if I add `layer->setMaxDataLevel(20);` to my code, the elevation will works and the the trees are draped correctly. 
So as I mentioned before, the problem is with how a maxlod is calculated for a projected ElevationLayer, but I can not see any relation with GDAL3/Proj6!

Can someone tried an UTM ElevationLayer on GDAL2 just to confirm if it is a problem related to GDAL version, or it is a general problem, so I can orient my work.

Thanks.

**Comment by gwaldron** [comment]
There are some GDAL3 fixes in the master branch / 3.1 release. Can you please re-test?

**Comment by MCA4213** [comment]
Hi, this issue it is not resolved yet. 
This happen when I load a projected DEM (utm30N in my case) on a geocentric Maps. Till now, I am forcing my application to generate a vrt to convert my DEM to WGS to be able to get the correct elevation. 
The problem is with the maxLevel  of the projected dem (elevationQuery always return 0 for maxLevel=2), if I force the maxLevel  to a higher value the elevationQuery will work . 
So, I am wondering if this can happen on gdal2 also, perhaps someone can confirm that to find the exact problem!

**Comment by plevy** [comment]
Are you still seeing the original problem with the floating trees?

**Comment by MCA4213** [comment]
I tested your data and it looks for the first time that is working, but if you **remove the "readymap_elevation.xml"** from your earth file you will find that the models will not get their elevation anymore. 
So please can you exclude the "readymap_elevation.xml"  from your earth file and try again?

**Comment by plevy** [comment]
OK, I see it, trees are underground and not floating.  Looking into it.  Thank you
