### ISSUE TITLE
the Texture of 3DTiles is not recognised

### ISSUE THREAD

**Issue by BoyChan** [gwaldron/osgearth#1519]
osgEarth load 3DTiles ,but the texture is white, and no error,I don't know the trouble.  osg version is 3.6.2

**Comment by jasonbeverage** [comment]
What version of osgEarth are you using?  I pushed a fix a couple of weeks ago to help with texture loading in non-gl3 builds that might help you.  I'd recommend trying the master osgEarth if you're not already.

**Comment by BoyChan** [comment]
> What version of osgEarth are you using? I pushed a fix a couple of weeks ago to help with texture loading in non-gl3 builds that might help you. I'd recommend trying the master osgEarth if you're not already.

osgearth-3.0rc2. some 3DTiles is OKay ,but one model is white.

**Comment by jasonbeverage** [comment]
If you can send us the model we can take a look, might be a missing texture or a format that we don't support for some reason.

**Comment by BoyChan** [comment]
> If you can send us the model we can take a look, might be a missing texture or a format that we don't support for some reason.

Okay,thanks. but it is too large, so I upload a b3dm file
[test.zip](https://github.com/gwaldron/osgearth/files/4622371/test.zip)

**Comment by BoyChan** [comment]
> If you can send us the model we can take a look, might be a missing texture or a format that we don't support for some reason.

hello. I find tinygltf can read the image, but the b3dm file lack the the attribute of ‘baseColorTexture’. so I add the default texture, and it is Okay....

**Comment by gwaldron** [comment]
Is this a bug in the loader, or a problem with the file?

**Comment by BoyChan** [comment]
> Is this a bug in the loader, or a problem with the file?

I am not sure that. because the file is customized by others,but set default texture do can solve the missing texture.
