### ISSUE TITLE
bug about imageControl

### ISSUE THREAD

**Issue by enigma19971** [gwaldron/osgearth#1522]
i have a LayerControl which is normal in osgearth2.8, when i  update OE to  3.0 .     the last imagecontrol 's   texture will override  all previous controls texture.   the detail code is as below:

void createControls(osgViewer::Viewer* viewer)
{
	// create a surface to house the controls
	ControlCanvas* cs = ControlCanvas::getOrCreate(viewer);
	int y = viewer->getCamera()->getViewport()->height() - 100;
	// a container centered on the screen, containing an image and a text label.
	{
		HBox* center = new HBox();
		center->setBorderColor(0, 0, 0, 0);
		center->setPadding(1);
		center->setHorizAlign(Control::ALIGN_CENTER);
		center->setVertAlign(Control::ALIGN_CENTER);
		center->setPosition(1, y);
		center->setWidth(265);
		center->setName("center");
		// Add an image:
		osg::ref_ptr<osg::Image> image = osgDB::readImageFile("view-pan-64x64.png");
		if (image.valid())
		{
			s_imageControl = new ImageControl(image.get());
			s_imageControl->setImage(image.get());
			s_imageControl->setName("pan-button");
			s_imageControl->setHorizAlign(Control::ALIGN_LEFT);
			s_imageControl->setFixSizeForRotation(true);
			center->addControl(s_imageControl);
			center->setHorizAlign(Control::ALIGN_CENTER);
		}
		VBox* dummy = new VBox();
		dummy->setName("dummy");
		dummy->setHorizAlign(Control::ALIGN_LEFT);
		HBox* row0 = new HBox();
		HBox* row1 = new HBox();
		row0->setName("row0");
		row1->setName("row1");	
		osg::ref_ptr<osg::Image> zoom_in_image = osgDB::readImageFile("view-zoom-in-32x32.png");
		if (zoom_in_image.valid())
		{
			view_zoom_in_imageControl = new ImageControl(zoom_in_image.get());
			row0->addControl(view_zoom_in_imageControl);
			view_zoom_in_imageControl->addEventHandler(new ZoomInHandler(viewer));
			view_zoom_in_imageControl->setName("zoomin");
		}

		osg::ref_ptr<osg::Image> view_heading_left_image = osgDB::readImageFile("view-heading-left-32x32.png");
		if (view_heading_left_image.valid())
		{
			view_heading_left_imageControl = new ImageControl(view_heading_left_image.get());
			row0->addControl(view_heading_left_imageControl);
			view_heading_left_imageControl->setName("heading-left");
		}
		osg::ref_ptr<osg::Image> view_pitch_up_image = osgDB::readImageFile("view-pitch-up-32x32.png");
		if (view_pitch_up_image.valid())
		{
			view_pitch_up_imageControl = new ImageControl(view_pitch_up_image.get());
			row0->addControl(view_pitch_up_imageControl);
			view_pitch_up_imageControl->setName("pitch-up");
		}
		osg::ref_ptr<osg::Image> view_elevation_up_image = osgDB::readImageFile("view-elevation-up-32x32.png");
		if (view_elevation_up_image.valid())
		{
			view_elevation_up_imageControl = new ImageControl(view_elevation_up_image.get());
			row0->addControl(view_elevation_up_imageControl);
			view_elevation_up_imageControl->addEventHandler(new VerticalHandler);
			view_elevation_up_imageControl->setName("elevation-up");
		}
		
		osg::ref_ptr<osg::Image> zoom_out_image = osgDB::readImageFile("view-zoom-out-32x32.png");
		if (zoom_out_image.valid())
		{
			view_zoom_out_imageControl = new ImageControl(zoom_out_image.get());
			row1->addControl(view_zoom_out_imageControl);
			view_zoom_out_imageControl->addEventHandler(new ZoomInHandler(viewer));
			view_zoom_out_imageControl->setName("zoomout");
		}
		osg::ref_ptr<osg::Image> view_heading_right_image = osgDB::readImageFile("view-heading-right-32x32.png");
		if (view_heading_left_image.valid())
		{
			view_heading_right_imageControl = new ImageControl(view_heading_right_image.get());
			row1->addControl(view_heading_right_imageControl);
			view_heading_right_imageControl->setName("heading-right");
		}
		osg::ref_ptr<osg::Image> view_pitch_down_image = osgDB::readImageFile("view-pitch-down-32x32.png");
		if (view_pitch_down_image.valid())
		{
			view_pitch_down_imageControl = new ImageControl(view_pitch_down_image.get());
			row1->addControl(view_pitch_down_imageControl);
			view_pitch_down_imageControl->setName("pitch-down");
		}
		osg::ref_ptr<osg::Image> view_elevation_down_image 
			= osgDB::readImageFile("view-elevation-down-32x32.png");
		if (view_elevation_down_image.valid())
		{
			view_elevation_down_imageControl = new ImageControl(view_elevation_down_image.get());
			row1->addControl(view_elevation_down_imageControl);
			view_elevation_down_imageControl->addEventHandler(new VerticalHandler);
			view_elevation_down_imageControl->setName("elevation-down");
		}
		dummy->addChild(row0);
		dummy->addChild(row1);
		center->addControl(dummy);
		cs->addControl(center);
	}
}

![image-control-bug](https://user-images.githubusercontent.com/910108/82151900-860e0600-9890-11ea-9058-376964cf78fc.PNG)

the png file is borrowed from nasa worldwind .  all image controls display the last view-elevation-down-32x32.png.

**Comment by gwaldron** [comment]
The Controls package is no longer under active development.
