### ISSUE TITLE
How can i create MapNode nonblock?

### ISSUE THREAD

**Issue by labdong801** [gwaldron/osgearth#1523]
I found that create a MapNode will block and no timeout  when the network unreachable .
and i can not cancel the thread.

**Comment by gwaldron** [comment]
The terrain engine will always try to load the first set of tiles before displaying them. If there are network issues, it may take a while to return. You can try setting an HTTP timeout by calling one or both of
```
#include <osgEarth/HTTPClient>
...
HTTPClient::setTimeout(seconds);
HTTPClient::setConnectTimout(seconds);
```

**Comment by labdong801** [comment]
Thanks

**Comment by labdong801** [comment]
After  i setting  timeout:
HTTPClient::setTimeout(1)
HTTPClient::setConnectTimout(1)

APP will crash when i change mapnode, and  I don't know if it's relevant ?



2020-05-27 23:34:29.146 3455-3455/? A/DEBUG: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x19
2020-05-27 23:34:29.146 3455-3455/? A/DEBUG: Cause: null pointer dereference

(osg::Referenced::unref() const+4) (BuildId: b683a7a03a6eeea9a8ab93a871ac9a6ad978115d)
(osg::ref_ptr<osg::IndexArray>::~ref_ptr()+10) (BuildId: b683a7a03a6eeea9a8ab93a871ac9a6ad978115d)
(osg::TriangleMesh::~TriangleMesh()+24) (BuildId: b683a7a03a6eeea9a8ab93a871ac9a6ad978115d)
(osg::TriangleMesh::~TriangleMesh()+4) (BuildId: b683a7a03a6eeea9a8ab93a871ac9a6ad978115d)
(osgEarth::Drivers::RexTerrainEngine::RexTerrainEngineNode::setMap(osgEarth::Map const*, osgEarth::TerrainOptions const&)+422) (BuildId: b68
(osgEarth::MapNode::init()+656) (BuildId: b683a7a03a6eeea9a8ab93a871ac9a6ad978115d)
(osgEarth::MapNode::MapNode(osgEarth::Map*)+182) (BuildId: b683a7a03a6eeea9a8ab93a871ac9a6ad978115d)
(MapFactory::createFromXYZDriver(std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>> const&, std::
(XYZMapScene::XYZMapScene(osg::Vec2f const&, std::__ndk1::basic_string<char, std::__ndk1::char_traits<char>, std::__ndk1::allocator<char>>&)
(_ZNSt6__ndk120__shared_ptr_emplaceI11XYZMapSceneNS_9allocatorIS1_EEEC2IJRN3osg5Vec2fERNS_12basic_stringIcNS_11char_traitsIcEENS2_IcEEEEEEES
(_ZNSt6__ndk110shared_ptrI11XYZMapSceneE11make_sharedIJRN3osg5Vec2fERNS_12basic_stringIcNS_11char_traitsIcEENS_9allocatorIcEEEEEEES2_DpOT_+4
(OsgMainApp::createScene()+88) (BuildId: b683a7a03a6eeea9a8ab93a871ac9a6ad978115d)

**Comment by labdong801** [comment]
crash not everytime

**Comment by gwaldron** [comment]
Please open a new issue for a new problem. (And your crash is in OSG code so you may want to post on the osg-users group.)
