### ISSUE TITLE
ImageControl not displaying image on osgearth 3.0

### ISSUE THREAD

**Issue by MCA4213** [gwaldron/osgearth#1526]
Hi, I have noticed that ImageControl is displaying a white rectangle in the 3.0 version (no image).
Comparing the Controls.cpp file with older version 2.10 (that works) show that removing "g->setStateSet(getGeomStateSet());" in "void ImageControl::draw( const ControlContext& cx )" function **will fix the problem**.

**Comment by gwaldron** [comment]
If you have a fix please submit a PR, thx
