### ISSUE TITLE
How to load Cesium 3d  tiles ?

### ISSUE THREAD

**Issue by liyihongcug** [gwaldron/osgearth#1527]
My 3d tiles isn't cesiumIon. It is below
var tileset = viewer.scene.primitives.add(new Cesium.Cesium3DTileset({
                url: 'http://localhost/sg/b3dm/shanghai4dml.400063/tileset.json',
                //maximumScreenSpaceError: 2,
                //maximumNumberOfLoadedTiles: 100,
            }));

The url is my data in my web server. Its data is *.b3dm
Can you provide the driver to deal with that？

**Comment by gwaldron** [comment]
You just say
```
<ThreeDTiles>
    <url>http://localhost/sg/b3dm/shanghai4dml.400063/tileset.json</url>
</ThreeDTiles>
```
