### ISSUE TITLE
ImageOverlay perspective distortion

### ISSUE THREAD

**Issue by jtaibo** [gwaldron/osgearth#1530]
When using osgEarth::Annotation::ImageOverlay is used with coorner coordinates that don't form a rectangular shape projected vertically (i.e., a trapezoid viewed in the vertical direction), texture coordinates are computed in a "non-perspective-correct" way. It seems that a linear interpolation between the vertices of two triangles are computed, without taking into consideration the perspective. I am attaching an image illustrating this effect. The image in the upper-right corner is projected onto the terrain through an ImageOverlay, with the noticeable distortion in the two triangles that the image is divided into.

This is the configuration I am using:

$ osgearth_version --caps
osgEarth Library 2.10.1 

[osgEarth]  [Capabilities] osgEarth Version: 2.10.1 
[osgEarth]  [Capabilities] OSG Version:      3.4.0
[osgEarth]  [Capabilities] GDAL Version:     2.2.3
[osgEarth]  [Capabilities] Detected hardware capabilities:
[osgEarth]  [Capabilities]   Vendor = NVIDIA Corporation
[osgEarth]  [Capabilities]   Renderer = GeForce GTX 760/PCIe/SSE2
[osgEarth]  [Capabilities]   Version = 4.6.0 NVIDIA 440.64.00
[osgEarth]  [Capabilities]   Core Profile = no
[osgEarth]  [Capabilities]   Max GPU texture units = 32
[osgEarth]  [Capabilities]   Max GPU texture coord indices = 8
[osgEarth]  [Capabilities]   Max GPU attributes = 16
[osgEarth]  [Capabilities]   Depth buffer bits = 24
[osgEarth]  [Capabilities]   Max texture size = 16384
[osgEarth]  [Capabilities]   GLSL = yes
[osgEarth]  [Capabilities]   GLSL Version = 460
[osgEarth]  [Capabilities]   Texture arrays = yes
[osgEarth]  [Capabilities]   draw instanced = yes
[osgEarth]  [Capabilities]   Texture buffers = yes
[osgEarth]  [Capabilities]   Texture buffer max size = 134217728
[osgEarth]  [Capabilities]   Compression = ARB S3 RG

![Screenshot from 2020-06-05 17-12-40](https://user-images.githubusercontent.com/4067243/83894002-049fea00-a751-11ea-9759-c7be86b7624a.png)

**Comment by jasonbeverage** [comment]
ImageOverlay is really only meant as a simple way to place rectangular images on the earth, it doesn't do any type of smart warping or anything like that.

**Comment by jtaibo** [comment]
Ok. Thanks for the clarification, Jason.
