### ISSUE TITLE
tag:2.10.1 day of datetime for --sky param bug at src\osgEarthUtil\ExampleResources.cpp #822

### ISSUE THREAD

**Issue by RedBoneZhang** [gwaldron/osgearth#1536]
file: src\osgEarthUtil\ExampleResources.cpp
line: 822
bug:
`ui::HSliderControl* skyDaySlider = grid->setControl(1, r, new ui::HSliderControl( 1, 31, dt.hours() ));`

should be on the following line:
`ui::HSliderControl* skyDaySlider = grid->setControl(1, r, new ui::HSliderControl( 1, 31, dt.day() ));`

**Comment by gwaldron** [comment]
Fixed in master branch
