### ISSUE TITLE
Can't compile osgEarth on AppleClang

### ISSUE THREAD

**Issue by PetrBo** [gwaldron/osgearth#1541]
- **osg 3.7.0**: the latest commit [63bb537132bab1f8b077838f7550e26405e5fa35](https://github.com/openscenegraph/OpenSceneGraph/commit/63bb537132bab1f8b077838f7550e26405e5fa35)
- **osgEarth 3.0**: the latest commit [b8f1fe67e17f7285f8b16d3d04a251147cbffd2c](https://github.com/gwaldron/osgearth/commit/b8f1fe67e17f7285f8b16d3d04a251147cbffd2c)

> In file included from /Users/petr/projects/research/osg/osgearth-src-new/src/osgEarth/CacheSeed.cpp:23:
> In file included from /Users/petr/projects/research/osg/osgearth-src-new/src/osgEarth/CacheSeed:28:
> In file included from /Users/petr/projects/research/osg/osgearth-src-new/src/osgEarth/TileVisitor:26:
> In file included from /Users/petr/projects/research/osg/osgearth-src-new/src/osgEarth/TileHandler:27:
> /Users/petr/projects/research/osg/osgearth-src-new/src/osgEarth/Map:43:9: error:
>       __cannot initialize return object of type 'osg::Object *' with an rvalue of
>       type 'osgEarth::Map *'__
>         META_Object(osgEarth, Map);
>         ^~~~~~~~~~~~~~~~~~~~~~~~~~
> /usr/local/include/osg/Object:47:57: note: expanded from macro 'META_Object'
>         virtual osg::Object* cloneType() const { return new name (); } \
>                                                         ^~~~~~~~~~~
> /Users/petr/projects/research/osg/osgearth-src-new/src/osgEarth/Map:43:9: error:
>       __cannot initialize return object of type 'osg::Object *' with an rvalue of
>       type 'osgEarth::Map *'__
>         META_Object(osgEarth, Map);
>         ^~~~~~~~~~~~~~~~~~~~~~~~~~
> /usr/local/include/osg/Object:48:78: note: expanded from macro 'META_Object'
>   ...osg::CopyOp& copyop) const { return new name (*this,copyop); } \
>                                          ^~~~~~~~~~~~~~~~~~~~~~~

> In file included from /Users/petr/projects/research/osg/osgearth-src-new/src/osgEarth/CacheSeed.cpp:23:
> In file included from /Users/petr/projects/research/osg/osgearth-src-new/src/osgEarth/CacheSeed:26:
> In file included from /Users/petr/projects/research/osg/osgearth-src-new/src/osgEarth/Common:25:
> /usr/local/include/osg/ref_ptr:41:32: error: __cannot initialize object parameter
>       of type 'const osg::Referenced' with an expression of type
>       'osgEarth::ElevationPool'__
>         ~ref_ptr() { if (_ptr) _ptr->unref();  _ptr = 0; }
>                                ^~~~
> /Users/petr/projects/research/osg/osgearth-src-new/src/osgEarth/Map:178:9: note:
>       in instantiation of member function
>       'osg::ref_ptr<osgEarth::ElevationPool>::~ref_ptr' requested here
>         Map(const Map& rhs, const osg::CopyOp& copy) { }
>         ^
> /usr/local/include/osg/ref_ptr:37:49: error: __cannot initialize object parameter
>       of type 'const osg::Referenced' with an expression of type
>       'const osgEarth::Map'__
>         ref_ptr(T* ptr) : _ptr(ptr) { if (_ptr) _ptr->ref(); }
>                                                 ^~~~
> /Users/petr/projects/research/osg/osgearth-src-new/src/osgEarth/CacheSeed.cpp:35:1: note:
>       in instantiation of member function 'osg::ref_ptr<const
>       osgEarth::Map>::ref_ptr' requested here
> _map( map )
> ^
> /usr/local/include/osg/ref_ptr:41:32: error: __cannot initialize object parameter
>       of type 'const osg::Referenced' with an expression of type
>       'const osgEarth::Map'__
>         ~ref_ptr() { if (_ptr) _ptr->unref();  _ptr = 0; }
>                                ^~~~

Any idea what's wrong?

[UPDATED] Just found out that the problem is probably in commit [1ca7b813a37130f35090e4898b40c1e98a34aeef](https://github.com/gwaldron/osgearth/commit/1ca7b813a37130f35090e4898b40c1e98a34aeef), after this osgEarth can't compile.

 Thanks.

**Comment by gwaldron** [comment]
Does it build against an official OSG release like 3.6.5?

**Comment by PetrBo** [comment]
Unfortunately, it does **not** build against an official OSG (3.6.5) — precisely the same errors as with OSG 3.7.0.

**Comment by remoe** [comment]
The latest master build with OSG 3.7.0 and XCode 11.7 successfully.
