### ISSUE TITLE
Problem with driver="xyz"

### ISSUE THREAD

**Issue by Vigoss2333** [gwaldron/osgearth#1542]
Hi,

I'm experiencing problems with imagery. And it could possibly be problem with PROJ 6.
I have the same problem like this ：http://forum.osgearth.org/Solved-Problem-with-driver-quot-xyz-quot-td7592880.html#a7592887
If I use imagery sources with driver="xyz" - I have whitened parts of the globe,too.
This is my code:
	XYZImageLayer* osm = new XYZImageLayer();
	osm->setURL("http://[abc].tile.openstreetmap.org/{z}/{x}/{y}.png");
	osm->setProfile(Profile::create("spherical-mercator"));
	osm->setOpacity(0.5f);
And  I use OSG 3.6.3, osgearth 3.0, GDAL 3.1.0,PROJ 6.2.0.

**Comment by plevy** [comment]
We do not support gdal 3.x at this time.  I am guessing it is the profile,
set OSGEARTH_NOTIFY_LEVEL=INFO and look at the profile, usually there is an
unknown.  Proj4 had many aliases for srs but Proj6 removed many so it takes
a little bit of time to find the Proj6 entry.

--
Paul Levy : Pelican Mapping

**Comment by Vigoss2333** [comment]
I got it.  Thank you for your help!
