### ISSUE TITLE
Elevation data is not visible

### ISSUE THREAD

**Issue by Vigoss2333** [gwaldron/osgearth#1546]
Hi
I'm a learner of OSGEarth.I have a problem. Can I look for help here？
I want to load an elevation data， though it's slow，I can load it through the earth file, but I was wrong when loading the code.
This is my earth file:
 <map name="MapBox">

    <XYZImage name="mapbox_satellite" driver="xyz">
        <url>http://a.tiles.mapbox.com/v4/mapbox.satellite/{z}/{x}/{y}.jpg?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4M29iazA2Z2gycXA4N2pmbDZmangifQ.-g_vE53SD2WrJ6tFX7QHmA</url>
        <profile>spherical-mercator</profile>
    </XYZImage>

    <XYZElevation name="mapbox_terrain" driver="xyz" max_data_level="14">
        <url>http://api.mapbox.com/v4/mapbox.terrain-rgb/{z}/{x}/{y}.pngraw?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4M29iazA2Z2gycXA4N2pmbDZmangifQ.-g_vE53SD2WrJ6tFX7QHmA</url>
        <profile>spherical-mercator</profile>
        <elevation_encoding>mapbox</elevation_encoding>
    </XYZElevation>

  <options>
    <cache path="cache_dir" type="filesystem" />
  </options>
    
</map>

And this is my code:
osgEarth::XYZImageLayer *imagery= new osgEarth::XYZImageLayer;
imagery->setURL("http://a.tiles.mapbox.com/v4/mapbox.satellite/{z}/{x}/{y}.jpg?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4M29iazA2Z2gycXA4N2pmbDZmangifQ.-g_vE53SD2WrJ6tFX7QHmA");
	imagery->setProfile(osgEarth::Profile::create("spherical-mercator"));
	imagery->setName("mapbox_satellite");
XYZElevationLayer *elevation= new XYZElevationLayer;
	elevation->setURL("http://api.mapbox.com/v4/mapbox.terrain-rgb/{z}/{x}/{y}.pngraw?access_token=pk.eyJ1IjoibWFwYm94IiwiYSI6ImNpejY4M29iazA2Z2gycXA4N2pmbDZmangifQ.-g_vE53SD2WrJ6tFX7QHmA");
	elevation->setProfile(osgEarth::Profile::create("spherical-mercator"));
	elevation->setMaxDataLevel(14);
	elevation->setName("mapbox_terrain");	
	elevation->setElevationEncoding("mapbox");
        map->addLayer(imagery);
	map->addLayer(elevation);

I can't see elevation data when I load it with code.I don't know how to do
Thanks!

**Comment by plevy** [comment]
Vigoss2333 I do not think it is your code, there seems to be an issue in the Mapbox elevation driver.  Can you use another elevation source such as ReadyMap for now?

**Comment by Vigoss2333** [comment]
Thanks, plevy.I can load ReadyMap elevation data successfully.
