### ISSUE TITLE
 An error (osgEarth/ThreadingUtils: No such file or directory compilation terminated) occurred while building

### ISSUE THREAD

**Issue by luckystar360** [gwaldron/osgearth#1549]
[ 52%] Building CXX object src/osgEarthDrivers/cache_rocksdb/CMakeFiles/osgdb_osgearth_cache_rocksdb.dir/RocksDBCache.cpp.o
In file included from /home/nhatdn1/Desktop/osg/osgearth/src/osgEarthDrivers/cache_rocksdb/RocksDBCache:23:0,
                 from /home/nhatdn1/Desktop/osg/osgearth/src/osgEarthDrivers/cache_rocksdb/RocksDBCache.cpp:19:
/home/nhatdn1/Desktop/osg/osgearth/src/osgEarthDrivers/cache_rocksdb/Tracker:23:35: fatal error: osgEarth/ThreadingUtils: No such file or directory
compilation terminated.
src/osgEarthDrivers/cache_rocksdb/CMakeFiles/osgdb_osgearth_cache_rocksdb.dir/build.make:62: recipe for target 'src/osgEarthDrivers/cache_rocksdb/CMakeFiles/osgdb_osgearth_cache_rocksdb.dir/RocksDBCache.cpp.o' failed
make[2]: *** [src/osgEarthDrivers/cache_rocksdb/CMakeFiles/osgdb_osgearth_cache_rocksdb.dir/RocksDBCache.cpp.o] Error 1
CMakeFiles/Makefile2:552: recipe for target 'src/osgEarthDrivers/cache_rocksdb/CMakeFiles/osgdb_osgearth_cache_rocksdb.dir/all' failed
make[1]: *** [src/osgEarthDrivers/cache_rocksdb/CMakeFiles/osgdb_osgearth_cache_rocksdb.dir/all] Error 2
Makefile:138: recipe for target 'all' failed
make: *** [all] Error 2

Thank you in advance for any help you can provide

**Comment by nmielcarek** [comment]
I'm seeing several new errors in the latest code:

src/osgEarth/Threading:211:41: error: redeclaration of ‘typedef class std::function<void(T*)> osgEarth::Threading::Future<T>::Callback’
(fix: remove line 211)

src/osgEarth/Profile.cpp: In static member function ‘static const osgEarth::Profile* osgEarth::Profile::create(const osgEarth::SpatialReference*, double, double, double, double, unsigned int, unsigned int)’:
src/osgEarth/Profile.cpp:150:45: error: expected ‘;’ before ‘__FUNCTION__’
(not sure about this one, I removed WHERE in the OE_SOFT_ASSERT_AND_RETURN macros to make it work)

**Comment by gwaldron** [comment]
Should all be fixed -- thanks

**Comment by Kyeiv** [comment]
is it fixed? cause building branch master gives me this error.

**Comment by emminizer** [comment]
I am able to build the current master on MSVC 2015, 2017, 2019, and g++ 8.3.1.

**Comment by Kyeiv** [comment]
i still get the fatal error: osgEarth/ThreadingUtils: No such file or directory and cannot find the ThreadingUtils by my own in the osgearth directory

**Comment by emminizer** [comment]
It does look like there are still some old file nuggets left around referencing ThreadingUtils.  Just over 20.  I spot checked most in the osgEarth/ subdirectory and none were actually being built though.

I'm not building with rocksdb support, that could be the difference in our configurations.

**Comment by Kyeiv** [comment]
i dont use rocksdb either. maybe it's worth to mention that i am using ubuntu 20.04,  GDAL 2.4.4, released 2020/01/08 from sources

my errors:
In file included from /home/krzysztof/osgearth/src/osgEarthDrivers/cache_leveldb/LevelDBCache:23,
                 from /home/krzysztof/osgearth/src/osgEarthDrivers/cache_leveldb/LevelDBCache.cpp:19:
/home/krzysztof/osgearth/src/osgEarthDrivers/cache_leveldb/Tracker:23:10: fatal error: osgEarth/ThreadingUtils: No such file or directory
   23 | #include <osgEarth/ThreadingUtils>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [src/osgEarthDrivers/cache_leveldb/CMakeFiles/osgdb_osgearth_cache_leveldb.dir/build.make:63: src/osgEarthDrivers/cache_leveldb/CMakeFiles/osgdb_osgearth_cache_leveldb.dir/LevelDBCache.cpp.o] Error 1


In file included from /home/krzysztof/osgearth/src/osgEarthDrivers/cache_leveldb/LevelDBCacheBin:22,
                 from /home/krzysztof/osgearth/src/osgEarthDrivers/cache_leveldb/LevelDBCacheBin.cpp:19:
/home/krzysztof/osgearth/src/osgEarthDrivers/cache_leveldb/Tracker:23:10: fatal error: osgEarth/ThreadingUtils: No such file or directory
   23 | #include <osgEarth/ThreadingUtils>
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
make[2]: *** [src/osgEarthDrivers/cache_leveldb/CMakeFiles/osgdb_osgearth_cache_leveldb.dir/build.make:76: src/osgEarthDrivers/cache_leveldb/CMakeFiles/osgdb_osgearth_cache_leveldb.dir/LevelDBCacheBin.cpp.o] Error 1

**Comment by Kyeiv** [comment]
commenting out includes with ThreadingUtils did the job and it builds successfully.

**Comment by nmielcarek** [comment]
I created a pull request to fix this, I'm not sure how anyone else can compile the master branch without these changes. Leftover osgEarth 2.x files in a system include directory maybe?
