### ISSUE TITLE
problem in tilenode.cpp _tileKeyValue

### ISSUE THREAD

**Issue by hankern** [gwaldron/osgearth#1555]
_tileKeyValue.set(
        (float)fmod(x, m),
        (float)fmod(y, m),
        (float)_key.getLOD(),
        -1.0f);
why use fmod? it cannot get right key value in glsl!!!

**Comment by hankern** [comment]
it cannot get right key value in glsl when x>65535 or y>65535.

**Comment by gwaldron** [comment]
IIRC, this is by design because the algorithm that uses this value fails with large values due to floating point precision limitations.

What are you trying to do?

**Comment by hankern** [comment]
I want get tile key value in glsl, but i find when lod level over 16 i cannot get right value. For level 19，max key value is 2^19=524288, the value not exceeds the of floating point precision. You can mod 999999 regard of precision.

**Comment by gwaldron** [comment]
Not a bug. _tileKeyValue uniform is not designed for this purpose
