### ISSUE TITLE
Fontconfig error

### ISSUE THREAD

**Issue by showintime** [gwaldron/osgearth#1566]
![image](https://user-images.githubusercontent.com/29477247/91120326-fa461a00-e6c7-11ea-833b-e19740c95428.png)
`Fontconfig error: Cannot load default config file
Error reading file C:\Windows\Fonts\arial.ttf: file not handled`
so how to solve it, and is it because of using vcpkg to install osgearth?

**Comment by virtuozo007** [comment]
I installed osgearth using vcpkg,  same error.

**Comment by romezxy** [comment]
I have got the same error also via vcpkg, but how to solve the problem?

**Comment by howe1110** [comment]
I installed osgearth using vcpkg, same error.

**Comment by howe1110** [comment]
I fixed the error by install the osgdb_freetype.dll plugin.

**Comment by SpaceView** [comment]
I used vcpkg to install
vcpkg install osg:x64-windows
and I checked that in my system the plugin is there,
D:\vs3D\vcpkg\installed\x64-windows\tools\osg\osgPlugins-3.6.5\osgdb_freetype.dll
I even add this path to env path, but it doesn't work,
any further suggestion?
