### ISSUE TITLE
Demonstrate the classified rendering function of features in code form

### ISSUE THREAD

**Issue by ZhengYongHe** [gwaldron/osgearth#1570]
I wonder where there's an example to classifying the features' styles in code instead of in earth file?
any help will be grateful

**Comment by ZhengYongHe** [comment]
I've found a way that seems can solve my issue:
http://forum.osgearth.org/Set-feature-style-class-for-each-category-programmatically-td5342169.html#a5342245
however,the function and members are too old to my current edition...I just want to know how to use it now.
any help will be appreciated.

**Comment by nmielcarek** [comment]
A good example of programmatic styles and features can be found in src/applications/osgearth_annotation/

**Comment by ZhengYongHe** [comment]
> A good example of programmatic styles and features can be found in src/applications/osgearth_annotation/

I‘m sorry for explain my issue unclearly...I want to render features in FeatureSource with different styles.
However,thanks for ur advice and it seems that I've found a way to use with the code followed:

`  StyleSelector selector5;
  selector5.name() = style1name;
  selector5.query()->expression() = "shape_leng>1000";

  styleSheet->getSelectors().insert({ style1name,selector5 });

  StyleSelector selector;
  selector.name() = style2name;
  selector.query()->expression() = "shape_leng<=1000";


  styleSheet->getSelectors().insert({ style2name, selector });`
what's more,I also want to find a way to render features with unique values of one field,any help will be grateful!

**Comment by gwaldron** [comment]
He,
If you want to pick styles on a per-feature basis, you can use scripting. The script can return either a style name or a full style definition. There is an earth file example in the tests folder called "feature_style_selector.earth" that demonstrates this.

**Comment by ZhengYongHe** [comment]
> 他，
> 如果您想按功能选择样式，则可以使用脚本。该脚本可以返回样式名称或完整的样式定义。在tests文件夹中有一个名为“ feature_style_selector.earth”的Earth文件示例，可以证明这一点。

Hi,gwaldron.I've seen such earth files,however I want to do it in code instead of using earth file and I don't know how to code the content described in earth file

**Comment by gwaldron** [comment]
I just added a code-based example [here](https://github.com/gwaldron/osgearth/blob/master/src/applications/osgearth_features/osgearth_features.cpp#L195). Hope this helps. You activate it with the --script argument.

**Comment by ZhengYongHe** [comment]
thank you @gwaldron !
