### ISSUE TITLE
Bad tesselation for some very large polygons (lands)

### ISSUE THREAD

**Issue by JD31** [gwaldron/osgearth#1571]
[ne_10m_land.zip](https://github.com/gwaldron/osgearth/files/5150473/ne_10m_land.zip)

Given the shapefile attached to the email.
When loading it to map most of the polygons are well tesselated (and tesselation goes prety fast) but we can see also some bad tesselation.
See screenshot (red is the expected boundary, grey is the tesselated land polygon).

![image](https://user-images.githubusercontent.com/17981960/91724848-308b0a00-eb9e-11ea-9876-d3049cc00ece.png)

OsgEarth 2.10.2 (with tesselation algorithm updated from 3.0)

**Comment by jasonbeverage** [comment]
I can reproduce the issue here.  Have you ever been able to display this shapefile with osgearth and have it tesselated properly?  Is this specific to the use of earcut in 3.0 or has this always been an issue?

**Comment by JD31** [comment]
I can make it working if I ask a max_polygon_tiling_angle of 45.
However I want to avoid this because:
- the process is longer
- the process uses GEOS for croping and i need a OsgEarth without GEOS

Any ideas or directions ?

**Comment by jasonbeverage** [comment]
Why do you need osgEarth without GEOS?  A good majority of the feature operations require geos so they won't be available unless you build against it.

**Comment by JD31** [comment]
Geos is strict LGPL v3 and thus is not usable with a closed source software on iOS.
In the case of this issue, using a tiling angle is rather a workaround. Having this tesselation working directly would be also better for performance.

Side discussion : we are evaluating boost.geometry for replacing Geos. With good results so far 🙂. The code is available on our fork. For the moment it is not enough mature nor exhaustive to be pushed to the master...

**Comment by gwaldron** [comment]
I pushed some changes to the tessellator if you want to give it a try. Doesn't use GEOS, and renders your poly correctly.
