### ISSUE TITLE
2.10.2 geodetic graticule not scaling on zoom

### ISSUE THREAD

**Issue by Kyeiv** [gwaldron/osgearth#1572]
i am using tag osgearth 2.10.2 ;  ubuntu 20 ; geos 3.7.3 ; gdal 2.4.4 ; OSG  3.6.4

osgearth_graticule --geodetic doesn't work on zooming, the lines stay the same and are not getting more precise.

**Comment by gwaldron** [comment]
Cannot reproduce in 3.0/master.
