### ISSUE TITLE
Windows x86 and x64 build failures (with vcpkg)

### ISSUE THREAD

**Issue by ankurverma85** [gwaldron/osgearth#1574]
src\osgEarthDrivers\lerc\ReaderWriterLERC.cpp(144): error C2065: 'GL_RGB32F': undeclared identifier
src\osgEarthDrivers\lerc\ReaderWriterLERC.cpp(145): error C2065: 'GL_RGBA32F': undeclared identifier
src\osgEarthDrivers\lerc\ReaderWriterLERC.cpp(156): error C2065: 'GL_RGB32F': undeclared identifier
src\osgEarthDrivers\lerc\ReaderWriterLERC.cpp(157): error C2065: 'GL_RGBA32F': undeclared identifier

https://github.com/microsoft/vcpkg/pull/13385

**Comment by ankurverma85** [comment]
https://github.com/gwaldron/osgearth/commit/29476ff6407711ea7b4bea6fbf00af77149a3eca

**Comment by ankurverma85** [comment]
Paging in @jasonbeverage to see if there's a quick fix available for the issue.
We would like to move osgearth vcpkg to move the newer commit that fixes issue with geos api usage but the newer commits have this build issue on windows

**Comment by jasonbeverage** [comment]
I just pushed a hopeful fix for this in 9237cea6f978f25b4bc58b4f5404f6ae5dcc3aa1, that should get rid of the undeclared identifier issues.  Give it a try in vcpkg and let me know.
