### ISSUE TITLE
How to get the ObjectID from a feature

### ISSUE THREAD

**Issue by ZhengYongHe** [gwaldron/osgearth#1582]
Now I can get a feature by ObjectID ,the example file "osgearth_pick.cpp" show it perfectly.
but how to get the specified ObjectID from a feature that I've got?
any help will be grateful.

**Comment by gwaldron** [comment]
You have to find the `FeatureSourceIndexNode` holding the mappings for your feature. This will be in the scene graph under your feature layer. You can call `FeatureSourceIndexNode::get(node)` to locate it. After that you can call `FeatureSourceIndexNode::getObjectID(feature->getFID())` to get the ObjectID.

**Comment by ZhengYongHe** [comment]
Thank you, @gwaldron .
