### ISSUE TITLE
modelsymbol  clamp the added terrain failed in featuremodellayer

### ISSUE THREAD

**Issue by ZhengYongHe** [gwaldron/osgearth#1583]
I have a point shapefile added to the earth,when I use  `ModelSymbol`  in `FeatureModelLayer` to render my shapefile,and add a terrain file into the earth,it works not so well.For example,if I add a shapefile to earth and created a modelsymbol in it's style after adding a terrain file,some features in the shapefile will fall into the ground, seems that it clamp the added terrain  unperfectly.
  Instead, when I use the same style in `ModelNode` ,It work perfect and can clamp the terrain if a terrain is displayed,or it will clamp the default terrain of the earth while I set the added-terrain Invisibled.

 style code of  a featuremodellayer as followed:
```
...
Style style;
ModelSymbol *ms = style.getOrCreate<ModelSymbol>();
string modelReplacePath = symbolArray.at(7);
ms->url()->setLiteral(modelReplacePath);

AltitudeSymbol *alt = style.getOrCreate<AltitudeSymbol>();
alt->clamping() = alt->CLAMP_TO_TERRAIN;
alt->technique() = alt->TECHNIQUE_MAP; 
...
```
style code of  a modelnode as followed:
```
...
Style style;
style.getOrCreate<ModelSymbol>()->url()->setLiteral(path);
osg::ref_ptr<osgEarth::ModelNode> modelNode = new ModelNode(_mosg->GetMapNode(), style);
modelNode->setName(modelname);
modelNode->setPosition(GeoPoint(Srs, Longitude, Latitude, Altitude, AltitudeMode::ALTMODE_RELATIVE));
...
```
and I found that only when setting  the mode ` AltitudeMode::ALTMODE_RELATIVE` when create a position for modelnode can work well.

  So I want to know if there's a way to make the modelsymbol work perfect in featuremodellayer as good as in the modelnode?

**Comment by gwaldron** [comment]
FeatureModelLayer is for static feature data, and does not support dynamic clamping.
