### ISSUE TITLE
How to reduce the drawing map image quality to improve the frame rate

### ISSUE THREAD

**Issue by fansmit** [gwaldron/osgearth#1584]
Hi 

I want to run my osgearth(2.6.0) application with an old fashioned GPU. The frame rate is only about 10 fps on my PC at present.  I've tried to reduce the resolution to 640x360 on my ubuntu OS, the frame rate can be improved to 40~50fps as expected. But this resolution(640x360) has not been supported on the most mainstream monitors. So if I can reduce the drawing map image qulity or resolution without changing the resolution of OS. Or if there is any other method to improve the frame rate?

**Comment by gwaldron** [comment]
There are a couple ways to decrease the amount of geometry being drawn. You can increase the LOD scale (higher means lower resolution) on the camera. (osg::Camera::setLODScale). You can experiment with this at runtime by pressing * (asterisk) multiple times to increase the LOD scale. Press / (slash) to decrease again.

In osgEarth you can set a "min_tile_range_factor" that will require the camera to get closer to tiles before they come in; for example:
```
<map>
  <options>
    <terrain min_tile_range_factor="3" ...
```
Your osgEarth version is very old, so I might be off on the exact details, but give it a try.

**Comment by fansmit** [comment]
> osg::Camera::setLODScale

It works! Both methods are very effective，now I can increase the frame rate to at least 30fps with 1280x720 resolution.

Thanks for your help!

**Comment by fansmit** [comment]
> There are a couple ways to decrease the amount of geometry being drawn. You can increase the LOD scale (higher means lower resolution) on the camera. (osg::Camera::setLODScale). You can experiment with this at runtime by pressing * (asterisk) multiple times to increase the LOD scale. Press / (slash) to decrease again.
> 
> In osgEarth you can set a "min_tile_range_factor" that will require the camera to get closer to tiles before they come in; for example:
> 
> ```
> <map>
>   <options>
>     <terrain min_tile_range_factor="3" ...
> ```
> 
> Your osgEarth version is very old, so I might be off on the exact details, but give it a try.

It works! Both methods are very effective，now I can increase the frame rate to at least 30fps with 1280x720 resolution.

Thanks for your help!
