### ISSUE TITLE
Impossible to blend an image layer with terrain color

### ISSUE THREAD

**Issue by JD31** [gwaldron/osgearth#1589]
When using a shader on an image layer, if a fragement is discarded or set to fully transparent, we expect to see terrain color at this pixel. Instead, nothing is drawn, making like a hole in the globe.

Terrain color :
![image](https://user-images.githubusercontent.com/17981960/95963261-be961980-0e07-11eb-8752-b468a6c8f6b6.png)

Image Layer:
![image](https://user-images.githubusercontent.com/17981960/95963432-f9984d00-0e07-11eb-852d-21a0c48e9b1f.png)

With GLSL:
The expected behaviour of the shader is set to full white all colors which are already bright, and discarding the others.
But instead of discarding the color and revealing the terrain color, it complety discard the tile drawing (displaying thus the glclearcolor).
![image](https://user-images.githubusercontent.com/17981960/95963827-71667780-0e08-11eb-8153-17688b25749a.png)
Expected result is:
![image](https://user-images.githubusercontent.com/17981960/95964432-15502300-0e09-11eb-9083-20784f8790fa.png)

OsgEarth 2.10.2
[testGlsl.zip](https://github.com/gwaldron/osgearth/files/5376770/testGlsl.zip)

**Comment by gwaldron** [comment]
Sorry for replying so late.
Shader overrides the rendering pathway for that layer. So if you discard the fragment, you get nothing if no layer was drawn underneath. You would have to manually write the terrain color instead of discard.
