### ISSUE TITLE
How to compile osgearth with GLES2 and run it on PC ubuntu.

### ISSUE THREAD

**Issue by fansmit** [gwaldron/osgearth#1590]
Hi

I'd like to run osgearth with GLES2 on ubuntu. I changed OSG configuration to GLES2 and compiled, then compiled osgearth immediately or added OSG_GLES2_AVAILABLE argument additionally. Neither of them could work normally. So what can I do?

**Comment by gwaldron** [comment]
@fansmit Unfortunately there's not enough information here for us to offer guidance. You will need to elaborate a lot on the problems you are seeing.

That said, the osgEarth team does not actively maintain GLES builds, so we rely on the user base to find and track down GLES issues.

**Comment by the-best-ever** [comment]
I was under the impression that older versions supported GLES2 but newer ones only support core GL 3.3 (desktop) and maybe GLES3.

**Comment by Astral-Yang** [comment]
> I was under the impression that older versions supported GLES2 but newer ones only support core GL 3.3 (desktop) and maybe GLES3. My attempts to run recent 2.x versions with GLES2 were met with failure.我的印象是旧版本支持 GLES2，但较新的版本仅支持核心 GL 3.3（桌面），也许还支持 GLES3。我尝试使用 GLES2 运行最近的 2.x 版本，但失败了。
> 
> Also: the in-built OpenSceneGraph nodes tend to break when you change the default OSG/OpenGL configuration in the CMake options. Even with the default `GL2` profile they break when informed that GL3+ is available.此外：当您在 CMake 选项中更改默认 OSG/OpenGL 配置时，内置的 OpenSceneGraph 节点往往会中断。即使使用默认的 `GL2` 配置文件，当被告知 GL3+ 可用时，它们也会中断。

Could you please tell me which specific version of osgEarth supports OpenGL ES 2? Thanks!
