### ISSUE TITLE
Support for Linear Workflow Rendering (sRGB <-> linear)

### ISSUE THREAD

**Issue by Himbeertoni** [gwaldron/osgearth#1593]
It would be nice if osgEarth created its tile textures with an internal format of GL_SRGB8_ALPHA8 instead of GL_RGBA8 (see https://www.khronos.org/registry/OpenGL/extensions/EXT/EXT_texture_sRGB.txt). This would allow for correct blending operations inside the shaders. Currently all computations on color are done in sRGB space instead of linear color space which is technically not quite correct. 
Maybe the fact which texture format is used could be made configurable e.g. via the TerrainOptions or MapNode Options, e.g. terrainOptions.sRGBTextures() = true;

**Comment by gwaldron** [comment]
Thank you for your thoughts. We've looked into this a couple times over the years. One issue here is incomplete support in OSG itself. For example, OSG's JPEG and PNG readers don't support sRGB as an internal format. Another topic is that osgEarth doesn't have control over the framebuffer (that's up to the application). So your suggestion would be a blanket "override" of RGB8 to sRGB8 when the user asks for an sRGB framebuffer, which might be OK, though we'd have to determine what complexities this would introduce into the various shaders and CPU-based image processing pipelines.
