### ISSUE TITLE
Some questions about triton ocean in osgearth

### ISSUE THREAD

**Issue by cll131421** [gwaldron/osgearth#1594]
Recent projects require the use of triton library to achieve marine effects
When I use osgearth to load triton, there are some problems. It may not be a bug, but a problem with my own use.
I use the code in Sample osgearth_triton, the sample that comes with osgearth, and the loaded data file is triton_drop_shader.earth
The generated ocean effect is perfect from a distance, but when I zoomed in, some undesirable things happened. It looked like a piece of area, the dividing line was very obvious, and one side was the ocean. One side is an image of land. When I move the position of the camera, the boundary line will also change randomly. In most cases, land will become ocean.
![image](https://user-images.githubusercontent.com/20762035/97836380-2a88e500-1d17-11eb-8996-0ec6a5b28c0c.png)
![image (1)](https://user-images.githubusercontent.com/20762035/97836382-2c52a880-1d17-11eb-88ef-37c0d465e0f2.png)
![image (2)](https://user-images.githubusercontent.com/20762035/97836386-2e1c6c00-1d17-11eb-9aa3-236b4ca8fe09.png)

In addition, the scope of ocean rendering also has a certain deviation, and there are also obvious dividing lines.
The strangest thing is that when I am at a certain height, when the camera's field of view height is changed slightly, I will get completely different rendering results, as shown in the figure:
Now the height of our camera is slightly higher
![image (3)](https://user-images.githubusercontent.com/20762035/97836448-4e4c2b00-1d17-11eb-9997-e1095179d9a4.png)

When I lower the camera height slightly
![image (4)](https://user-images.githubusercontent.com/20762035/97836476-60c66480-1d17-11eb-9dcc-2a48e17daa3b.png)

There will be such a scene
![image (5)](https://user-images.githubusercontent.com/20762035/97836521-73d93480-1d17-11eb-8a59-d8459a6675a5.png)

I found some methods on the Internet, using osgearth's LogarithmicDepthBuffer, and copying the shader files in the osgearth_triton directory to the triton resources directory
The console prompts that an error is reported when loading the glsl file. After modifying the configuration file of triton, more detailed error information is obtained:

TRITON: GLSL error detected in: user-vert-functions.glsl

TRITON: 0(98): error C7532: global function inverse requires "#version 140" or later
0(98): error C0000: ... or #extension GL_ARB_gpu_shader5: enable
----This problem can be solved by putting #extension GL_ARB_gpu_shader5: enable in the first line

GLSL error detected in: user-vert-functions.glsl
TRITON: Failed to link shader program for OpenGL.
TRITON: GLSL error detected in: user-vert-functions.glsl

TRITON: 0(284): error C1038: declaration of "trit_projection" conflicts with previous declaration at 0(41)
0(292): error C7011: implicit cast from "f64mat4" to "mat4"

GLSL error detected in: user-vert-functions.glsl
TRITON: Failed to link shader program for OpenGL.

I'm sorry I don't know anything about shader programming
If anyone can provide usable examples, I would be very grateful.
Or suggest a possible solution, ingredients thanks!

**Comment by gwaldron** [comment]
Looks like you solved the first error. 
Did you try replacing the "trit_projection" declaration with this?
```uniform f64mat4 trit_projection;```

**Comment by cll131421** [comment]
> Looks like you solved the first error.
> Did you try replacing the "trit_projection" declaration with this?
> `uniform f64mat4 trit_projection;

I tried to modify it to uniform f64mat4 trit_projection; the error message is as follows:

0(91): error C0000: syntax error, unexpected identifier, expecting'{' at token "trit_projection"

0(97): error C1503: undefined variable "trit_projection"

0(99): error C1503: undefined variable "trit_projection"

It seems to say that f64mat4 is not a valid type, but I checked some glsl documents, f64mat4 should be a correct type

**Comment by cll131421** [comment]
The ocean rendering effect I want to achieve is as follows:
![Uploading 2018-12-25_164358.jpg…]()
If anyone can provide usable example code or point to a feasible solution, I would like to express my great thanks

**Comment by cll131421** [comment]
This problem is solved, the main reason is that the elevation data used is problematic. Triton requires that the depth data of the ocean is also smooth and gradual in order to render perfect results.
The problem was solved after I changed my elevation data.

**Comment by Mario-Yao** [comment]
1

**Comment by Mario-Yao** [comment]
I have encountered the same problem as you. Could you please tell me how to adjust the ocean elevation data? Thank you very much!

**Comment by cll131421** [comment]
You need a smoother elevation data



At 2023-07-10 16:36:06, "Mario-Yao" ***@***.***> wrote:

I have encountered the same problem as you. Could you please tell me how to adjust the ocean elevation data? Thank you very much!

**Comment by Mario-Yao** [comment]
> You need a smoother elevation data At 2023-07-10 16:36:06, "Mario-Yao" ***@***.***> wrote: I have encountered the same problem as you. Could you please tell me how to adjust the ocean elevation data? Thank you very much! — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***>

Is it to find smoother elevation data directly? Where did you get such high quality data? Some of the data we have found so far have some problems with the ocean elevation. Or do you have a way to smooth out the elevation data? Thank you very much!

**Comment by cll131421** [comment]
I have no idea to smooth out the elevation data.
The point of the elevation data is the elevatin should be smooth,like 1.0 2.0 3.0 4.0
The data like 1.0 1.0 1.0 10.0 10.0 10.0 is not available for us.
















At 2023-07-11 14:30:47, "Mario-Yao" ***@***.***> wrote:

You need a smoother elevation data At 2023-07-10 16:36:06, "Mario-Yao" @.> wrote: I have encountered the same problem as you. Could you please tell me how to adjust the ocean elevation data? Thank you very much! — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: @.>

Is it to find smoother elevation data directly? Where did you get such high quality data? Some of the data we have found so far have some problems with the ocean elevation. Or do you have a way to smooth out the elevation data? Thank you very much!

**Comment by Mario-Yao** [comment]
> I have no idea to smooth out the elevation data. The point of the elevation data is the elevatin should be smooth,like 1.0 2.0 3.0 4.0 The data like 1.0 1.0 1.0 10.0 10.0 10.0 is not available for us. At 2023-07-11 14:30:47, "Mario-Yao" ***@***.***> wrote: You need a smoother elevation data At 2023-07-10 16:36:06, "Mario-Yao" @.> wrote: I have encountered the same problem as you. Could you please tell me how to adjust the ocean elevation data? Thank you very much! — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: @.> Is it to find smoother elevation data directly? Where did you get such high quality data? Some of the data we have found so far have some problems with the ocean elevation. Or do you have a way to smooth out the elevation data? Thank you very much! — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you modified the open/close state.Message ID: ***@***.***>

Ok, thank you for your reply!
