### ISSUE TITLE
Stricter API and ABI versioning?

### ISSUE THREAD

**Issue by torokati44** [gwaldron/osgearth#1596]
Unfortunately the somewhat lenient approach to API/ABI stability of osgEarth development has led to the Debian maintainers giving up on the project and no longer including it in their package archives. Similarly, the QGIS developers dropped the osgEarth-related functionality from their project for the same reason. See: https://lists.debian.org/debian-gis/2020/11/msg00003.html
This means that osgEarth can no longer be obtained as effortlessly on Ubuntu either, as before.
Perhaps the recent 3.0 release could provide a nice milestone for this to change?
I don't mean this in a bad way, I just wish that osgEarth, being a rather nice and useful project, would remain as accessible to as many users as possible. I hope this is among your goals as well.

**Comment by gwaldron** [comment]
Where can one find the actual guidelines?

**Comment by torokati44** [comment]
Since I'm not a Debian package maintainer myself, I doubt I know any more about this than you. I was simply seeing the results of the issue described, and tried to initiate some sort of cooperation between you and the package maintainers for our mutual benefit.

With a bit of looking around the interwebs, I could find lots of guides on this, but most target the packagers, not the developers. This section here seems to be an exception: https://www.netfort.gr.jp/~dancer/column/libpkg-guide/libpkg-guide.html#sonamenomodify

This article is also meant explicitly for upstream library developers: https://wiki.debian.org/UpstreamGuide#Libraries

I think #898 might also have been an effort in this direction.

Since osgEarth is written in C++, this could also help: http://syrcose.ispras.ru/2009/files/02_paper.pdf
This one also has a number of references that might provide additional information.

I feel kind of a middle-man here, perhaps direct communication between you and the Debian packagers would be more effective?

**Comment by gwaldron** [comment]
Version 3.1, which is due to release this month, will have proper SONAME support!

You can try the 3.1 branch and see if it works for you.

Thanks for pointing this out and hopefully the Debian folks will be able to pick it back up.

**Comment by torokati44** [comment]
This is great to hear, thanks!
Yeah, let's hope for Debian to take osgEarth back...

**Comment by gwaldron** [comment]
Version 3.1 / master has SONAME support -- should be OK moving forward.
