### ISSUE TITLE
3.1: VS2017 x64 compile / GLCore 

### ISSUE THREAD

**Issue by remoe** [gwaldron/osgearth#1602]
Can't compile it with osgEarth 3.0 CMake configurations:

Why is GLCore not needed?

include\osg/GL(114): fatal error C1083: Cannot open include file: 'GL/glcorearb.h': No such file or directory

https://github.com/gwaldron/osgearth/commit/91a2af27f835136cb3ba3720a46766201fe48e60

**Comment by gwaldron** [comment]
Remo, try adding your GLCORE folder to the CMAKE_INCLUDE_PATH and let me know if that works

**Comment by remoe** [comment]
It's a bit too general. But i found osgEarth use now "OSGEARTH_GLCORE_INCLUDE_DIR". I will try it, thanks.

**Comment by remoe** [comment]
Version https://github.com/gwaldron/osgearth/commit/db92b803126ec0949525a43edaf44d7080baa6b2 compiles with ```OSGEARTH_GLCORE_INCLUDE_DIR```
