### ISSUE TITLE
Is readymap.org unavailable in some countries?

### ISSUE THREAD

**Issue by 10110111** [gwaldron/osgearth#1605]
I'm trying to access `readymap.org` from Saint-Petersburg, Russia. From multiple places with different ISPs I was able to resolve the IP address of the host, but not ping it. This makes e.g. the `osgearth_map` demo hang at startup while trying to connect to the imagery&elevation data provider.

OTOH, if I connect through HotSpot Shield VPN extension for Chromium (via a US server I suppose), the website does respond and redirects me to a page at `web.pelicanmapping.com`, which has Live Preview that works unless I stop HotSpot Shield (in which case there's no globe at all).

Is access to `readymap.org` restricted in Russia? I've not been able to google anything relevant, but maybe you could answer.

**Comment by jasonbeverage** [comment]
Indeed we do have Russia as well as quite a few other countries blocked.  We've had problems with people bulk downloading downloading and putting a strain on the server so we've put some pretty aggressive firewall policies in place.
