### ISSUE TITLE
3.1/2.10: Bug in CascadeDrapingDecorator ?

### ISSUE THREAD

**Issue by remoe** [gwaldron/osgearth#1607]
The function objectDeleted in https://github.com/gwaldron/osgearth/blob/3.1/src/osgEarth/CascadeDrapingDecorator.cpp#L504  is called as well when someone else remove another rtt-camera from different code. And then osgEarth crashes here:

https://github.com/gwaldron/osgearth/blob/3.1/src/osgEarth/CascadeDrapingDecorator.cpp#L1121

```c++
>	osgEarthd.dll!osgEarth::CascadeDrapingDecorator::CameraLocal::objectDeleted(void * ptr) Line 507	C++
 	osg158-osgd.dll!osg::ObserverSet::signalObjectDeleted(void * ptr) Line 79	C++
 	osg158-osgd.dll!osg::Referenced::signalObserversAndDelete(bool signalDelete, bool doDelete) Line 286	C++
 	osg158-osgd.dll!osg::Referenced::unref() Line 194	C++
 	!osg::ref_ptr<osg::Camera>::~ref_ptr<osg::Camera>() Line 41
```

because the StateSet is null.

Right?

**Comment by gwaldron** [comment]
What do you mean by "someone else removes another rtt-camera from different code"? Do you have any sample code to reproduce this?

**Comment by remoe** [comment]
Currently I don't have a simple sample. I can do when you need it. It is for example when an operation is released which has a camera reference in it:

```c++
struct TestOp : public osg::Operation
{
  osg::ref_ptr<osg::Camera> _camera;

  ~TestOp() {
    // this calls: CascadeDrapingDecorator::CameraLocal::objectDeleted
  }
}
```

**Comment by gwaldron** [comment]
Is your operation _camera pointing to one of the decorator's internal cameras??

**Comment by remoe** [comment]
No, I do a screenshot with a RTT-Camera:

```c++
struct RTTPrintScreenOp : public osg::Operation
{
	void update()
	{
          ...
          if (group->removeChild(_camera)) {
              _camera->removeChild(0, 1);
          }
          _camera->getGraphicsContext()->getCameras().remove(_camera);
          ...
	}
};
```
```c++
osg::Group* scene_root = dynamic_cast<osg::Group*>(view->getSceneData());
_i->_rttCamera->addChild(scene_root->getChild( 0 ) );
scene_root->addChild( _i->_rttCamera );
RTTPrintScreenOp* rpso = new RTTPrintScreenOp(_i->_rttCamera, _i->_rttImage ...);
gc->add(rpso);
viewer->addUpdateOperation(rpso);
```

**Comment by gwaldron** [comment]
Did you ever resolve this? If so I will close it.

**Comment by remoe** [comment]
No, it's not resolved. I haven't looked into it.
