### ISSUE TITLE
osgearth_viewer Entry Point Not Found On "osgEarth.dll"

### ISSUE THREAD

**Issue by shanto462** [gwaldron/osgearth#1610]
Hello Guys,
I am getting a dll error on osgEarth.dll
After following every build instructions and dependency setup for osgearth, I have successfully complied and installed osgearth.

But I am getting this dll error every time I try to launch osgearth_viewer.

> **The Procedure entry point ?GetArea@MessageLite@protobuf@google@QWBAPEAVArena@23@XZ could not be located in the dynamic link library
> Path To osgEarth Binaries\osgEarth.dll**

**protobuf is installed via vcpkg

I tried same steps on my another desktop and I can run osgEarth binaries without any problem.

Later I tried to install osgEarth from vcpkg and issue remained.
Even I reinstalled windows and tried the documented steps again but the issue remained.

It would be great if you guys can help me. :P

**Comment by gwaldron** [comment]
Is the protobuf DLL in your path?
You could try running [this dependency walker](https://lucasg.github.io/Dependencies/) to see if there's a missing DLL somewhere.

**Comment by shanto462** [comment]
Thank you.
Adding protobuf to path saved my day :P
