### ISSUE TITLE
vector layer flashed with classifing and extruding

### ISSUE THREAD

**Issue by ZhengYongHe** [gwaldron/osgearth#1616]
with osg3.6.3 and osgearth3.0,I add shpfile on the earth and make some render. classifing is fine and extuding also done well,but when I put them together,the layer start to flash anytime when I move the viewpoint.anyone can help me?
![lALPBFuNcAyDCmHNAxLNBRY_1302_786](https://user-images.githubusercontent.com/45898487/101470331-d2ca4300-3980-11eb-9a6e-c0d4ea7829a1.png)
![1607421191694_8733E78D-B872-4939-B0FB-D48B2FA0D487](https://user-images.githubusercontent.com/45898487/101470344-d6f66080-3980-11eb-8b39-5334d6606b47.png)

**Comment by gwaldron** [comment]
The second screenshot looks like you have a z-fighting problem, and the geometry is rendering twice. So it is likely that either you are drawing the layer multiple times, or your source data has duplicate features. Earth file?

**Comment by ZhengYongHe** [comment]
sorry I can't get the code right now.I make it with C++ code instead of using Earth file.I'll show you the code later

**Comment by gwaldron** [comment]
Not necessary (and please don't post large chunks of code here). Just make sure you are not rendering or adding twice and make sure your source data does not have duplicate features (which is pretty common in GIS data).

**Comment by ZhengYongHe** [comment]
Ok,I‘ll check it later.thank you!

**Comment by YHLpuyu** [comment]
when add a featuremodellayer with earth file, the layer rendered has effected by light, but when add featuremodellayer directly through code, it doesn't effect by light. what's the different between two ways. i use boston.earth and osgearth_city.cpp.
Is there some setting i should mention?

**Comment by hejustbrave** [comment]
您好，您的邮件本人已经收到，谢谢！
