### ISSUE TITLE
osgearth fails to compile with C++20

### ISSUE THREAD

**Issue by ankurverma85** [gwaldron/osgearth#1623]
error at osgEarth/Threading : 605
```c++
 // std::invoke workaround for c++11
    // https://stackoverflow.com/questions/38288042/c11-14-invoke-workaround
    template<typename Fn, typename... Args>
    constexpr auto cpp11invoke(Fn&& f, Args&&... args)
        noexcept(noexcept(std::forward<Fn>(f)(std::forward<Args>(args)...)))
        -> typename std::result_of<Fn(Args...)>::type
    {
```

It complains about result_of not being found, which was deprecated in c++17 but removed from the stl in c++20

A prospective fix can be found in the vcpkg pull request
https://github.com/microsoft/vcpkg/pull/15375

**Comment by gwaldron** [comment]
Quick research suggests that referencing `_HAS_CXX17` is not a sufficient solution across platforms and compiler versions. A more robust check is needed as discussed [here ](https://stackoverflow.com/questions/52379233/is-has-cxx17-marco-usable-in-custom-project-headers-to-enable-c17-language)and [here](https://stackoverflow.com/questions/2324658/how-to-determine-the-version-of-the-c-standard-used-by-the-compiler). If you want to tackle this we are happy to review a PR.

**Comment by ankurverma85** [comment]
Using 
https://en.cppreference.com/w/cpp/feature_test

```diff
+#if defined(__cpp_lib_is_invocable) && __cpp_lib_is_invocable >= 201703
+        -> typename std::invoke_result<Fn(Args...)>::type
+#else
         -> typename std::result_of<Fn(Args...)>::type
+#endif
```

**Comment by gwaldron** [comment]
FYI, I have a pending commit that removes the need for cpp11invoke. So stand by for that.

**Comment by ankurverma85** [comment]
Thanks
For fixing vcpkg osgearth builds

https://github.com/microsoft/vcpkg/pull/15375

Do you recommend I abandon the PR and attempt to migrate to a newer osgearth commit (that includes your fixes) ?
Or are we OK 
Merging that for now into vcpkg repository and then remove the patch once we move to a newer commit with the fixes

**Comment by JackBoosY** [comment]
@gwaldron Ping for response.

**Comment by gwaldron** [comment]
You can abandon; cpp11invoke is gone as of c3d3b4fc3.

**Comment by ankurverma85** [comment]
> You can abandon; cpp11invoke is gone as of [c3d3b4f](https://github.com/gwaldron/osgearth/commit/c3d3b4fc3cef6229f32ff13871305e70e1639662).

Could you please update vcpkg to that commit?

**Comment by gwaldron** [comment]
Well, that I cannot do, not until we get to a 3.2 release. There are too many other dependent commits. If you absolutely need it in vcpkg immediately you'll need to create a patch that works on the 3.1 branch and PR it there. Sorry for the confusion

**Comment by ankurverma85** [comment]
Can you then maybe approve the vcpkg PR
https://github.com/microsoft/vcpkg/pull/15375
So we can have a working vcpkg build

The fix works with the commit and we can pull it out when 3.2 is ready to replace it.

**Comment by gwaldron** [comment]
Yep we will run a build/test on this end, then approve. Thanks
