### ISSUE TITLE
How Can I Render the FeatureModelLayer different color By name or other fields?

### ISSUE THREAD

**Issue by GISerliang** [gwaldron/osgearth#1624]
I rendered the FeatureModelLayer's color by PolygonSymbol, but I only use one color to rendering. Could I render the FeatureModelLayer different color by name or other fileds ?
Like GIS categorized symbol, like this picture
![image](https://user-images.githubusercontent.com/11342604/104399454-aa3ef580-558b-11eb-8b23-a1ea022893e7.png)

**Comment by gwaldron** [comment]
You can use JavaScript to select or construct a style based on the Feature's properties. There are a couple example earth files in the repo. [This one](https://github.com/gwaldron/osgearth/blob/master/tests/feature_scripted_styling_2.earth) selects a Style by name; [this one](https://github.com/gwaldron/osgearth/blob/master/tests/feature_scripted_styling.earth) constructs a unique Style for each feature.

In code, this would mean adding several Styles to the StyleSheet; then setting your script using StyleSheet::setScript; and then setting a selector using StyleSheet::addSelector that specifies the JavaScript function to execute.

Good luck!

**Comment by GISerliang** [comment]
> You can use JavaScript to select or construct a style based on the Feature's properties. There are a couple example earth files in the repo. [This one](https://github.com/gwaldron/osgearth/blob/master/tests/feature_scripted_styling_2.earth) selects a Style by name; [this one](https://github.com/gwaldron/osgearth/blob/master/tests/feature_scripted_styling.earth) constructs a unique Style for each feature.
> 
> In code, this would mean adding several Styles to the StyleSheet; then setting your script using StyleSheet::setScript; and then setting a selector using StyleSheet::addSelector that specifies the JavaScript function to execute.
> 
> Good luck!

Thank you!
