### ISSUE TITLE
bug-3.1: osgearth_pick doesn't pick features ?

### ISSUE THREAD

**Issue by remoe** [gwaldron/osgearth#1625]
Build 3.1 and run 
```osgearth_pick.exe tests\feature_draped_polygons.earth```

using osg 3.6.3, gdal 2.4.2:

![image](https://user-images.githubusercontent.com/804941/105051771-6195a980-5a6f-11eb-9017-fdb1d76b666a.png)

**Comment by gwaldron** [comment]
You need to add this to the feature model layer to enable picking:
`<feature_indexing enabled="true"/>`
Hope this helps.

**Comment by remoe** [comment]
oh - no comment, sorry :D
