### ISSUE TITLE
OsgImGuiHandler.hpp not included in CMakeLists.txt/LIB_PUBLIC_HEADERS ?

### ISSUE THREAD

**Issue by remoe** [gwaldron/osgearth#1627]
**OsgImGuiHandler.hpp** is not included in osgearth-installer:

https://github.com/gwaldron/osgearth/blob/master/src/osgEarth/CMakeLists.txt
LIB_PUBLIC_HEADERS

**Comment by jasonbeverage** [comment]
Hey Remo, the OsgImGuiHandler and the related osgEarth imgui support isn't really intended for public consumption yet and just used internally in that one demo so we have avoided adding it to the public libs at the moment.
