### ISSUE TITLE
RTTPicker fails to locate annotations added by the MapNode object

### ISSUE THREAD

**Issue by walidchaker** [gwaldron/osgearth#1630]
Hi,

When I use predefined  annotations in a .earth file, all is going well with the RTTPicker but when I insert them by the api with the MapNode object (of course before start rendering) I can see them on the map but I can not locate them by RTTPicker. Did I forget something? 

Thank you in advance for your help!

**Comment by gwaldron** [comment]
You have to insert it into the object index by calling

`Registry::objectIndex()->tagNode(node, object);`

where `object` is the data you want returned when you look up the picked object ID later. (node and object can be the same.)

**Comment by walidchaker** [comment]
It works !
Thank you so much
