### ISSUE TITLE
stretch terrain

### ISSUE THREAD

**Issue by yuhubuxi** [gwaldron/osgearth#1637]
Dear gwaldron：
I am a student developer of osgearth, thank you very much for your contribution to the estimated project. I have a trouble and want to know whether the version of 3.1 support stretching terrain. I used .earth to achieve stretching terrain in the version of 2.8. However,  the version of 2.10 have changed terrain engine and haven't support  stretching terrain. I wonder whether other function can achieve stretching terrain. If not,  I wonder whether will achieve stretching terrain in the future.

Best wishes,
Ying Ma

**Comment by gwaldron** [comment]
Are you referring to vertical scaling? If so, that feature is no longer in the SDK. It caused too many inconsistencies and problems, so we decided to remove it until a better solution becomes apparent.

**Comment by yuhubuxi** [comment]
Thanks very much.


Best wishes,
Ying Ma




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "gwaldron/osgearth"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年2月2日(星期二) 晚上9:14
收件人:&nbsp;"gwaldron/osgearth"<osgearth@noreply.github.com&gt;;
抄送:&nbsp;"中国海洋大学-计算机系-马颖"<895896656@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [gwaldron/osgearth] stretch terrain (#1637)





 
Are you referring to vertical scaling? If so, that feature is no longer in the SDK. It caused too many inconsistencies and problems, so we decided to remove it until a better solution becomes apparent.

**Comment by yuhubuxi** [comment]
Dear gwaldron： 
I wonder whether other methods can achieve vertical scaling. If not, I wonder whether will achieve vertical scaling in the future. If possible, I would like to know when you plan to implement the function.

Best wishes,
Ying Ma

**Comment by gwaldron** [comment]
There is nothing on the roadmap at this time.
However, you can use a shader like this to achieve GPU vertical scaling:
https://gist.github.com/gwaldron/e60c7ce2b0eb1ebb7418249caaebb5ba

**Comment by GouShiQuan** [comment]
unsubscribe



在 2021-04-20 05:12:22，"Glenn" ***@***.***> 写道：

Closed #1637.

**Comment by horrzs** [comment]
> 目前路线图上没有任何内容。但是，您可以使用这样的着色器来实现 GPU 垂直缩放： https://gist.github.com/gwaldron/e60c7ce2b0eb1ebb7418249caaebb5ba

Can I implement this function in the source code? I want to dynamically adjust the scale of vertical scaling when oegearth is running. Osgearth 3.5
