### ISSUE TITLE
Null dereference in TerrainTileModelFactory.cpp

### ISSUE THREAD

**Issue by emminizer** [gwaldron/osgearth#1641]
Ran a Cppcheck on osgEarth code today and found a null dereference that should be investigated.  Take a look at TerrainTileModelFactory.cpp, line 793.  The variable `tex` is guaranteed to be `nullptr`.

https://github.com/gwaldron/osgearth/blob/master/src/osgEarth/TerrainTileModelFactory.cpp#L793

**Comment by jasonbeverage** [comment]
Thanks Dan, this should be fixed in 86a8c54672669409d607f125a493236f0758e295.
