### ISSUE TITLE
github actions: it currently use 3.1 tag 

### ISSUE THREAD

**Issue by remoe** [gwaldron/osgearth#1644]
Please check the github actions, it use the 3.1 tag:

https://github.com/gwaldron/osgearth/blob/master/.github/workflows/linux.yml#L46
https://github.com/gwaldron/osgearth/blob/master/.github/workflows/windows.yml#L29
https://github.com/gwaldron/osgearth/blob/master/.github/workflows/macos.yml#L36

It should be the master branch?

**Comment by gwaldron** [comment]
It should be whichever branch triggered the action ... do you know how to specify this?

**Comment by remoe** [comment]
Sorry, no. I haven't tested/checked this. But here are the docs: https://github.com/actions/checkout

**Comment by remoe** [comment]
@gwaldron need to merge https://github.com/gwaldron/osgearth/pull/1646 for linux fix.

**Comment by remoe** [comment]
@jasonbeverage now linux compiles. Exampleresources.cpp doesn't compile with Macosx. When I find time tomorrow I can try on MacOSX.

**Comment by remoe** [comment]
@gwaldron , @jasonbeverage I've added a fix for this build issue: https://github.com/gwaldron/osgearth/pull/1647

This could be cleaner, but it compiles with XCode 11.7  and it shows what the problem is.

**Comment by remoe** [comment]
I've tried to fix a master compiling issue on Linux with: https://github.com/gwaldron/osgearth/pull/1648 . The current github action use the correct commit. So this is solved.
