### ISSUE TITLE
VerticalScale 3.1 Doesn't work

### ISSUE THREAD

**Issue by l1uw3n** [gwaldron/osgearth#1650]
I added the VerticalScale file in version 2.10 to version 3.1. I want version 3.1 to support dynamic terrain changes. My code runs without any errors, but nothing changes in the results. What function did I add less?Or how should I implement this feature?

**Comment by gwaldron** [comment]
You can use a shader like this to achieve GPU vertical scaling:
https://gist.github.com/gwaldron/e60c7ce2b0eb1ebb7418249caaebb5ba
