### ISSUE TITLE
abnormal of show model on more than one screen

### ISSUE THREAD

**Issue by x1244** [gwaldron/osgearth#1653]
I have tow screen，when not define `OSG_SCREEN`，scale factor 500 looks normal for cessna.
```  
  {
        Style style;
        style.getOrCreate<ModelSymbol>()->autoScale() = true;
        style.getOrCreate<ModelSymbol>()->url()->setLiteral("../data/cessna.osg.500.scale");
        ModelNode* modelNode = new ModelNode(mapNode, style);
        cessna = modelNode;
        modelNode->setPosition(GeoPoint(geoSRS, -100, 52));
        annoGroup->addChild(modelNode);
    }
```
but，when define `OSG_SCREEN=0`，scale factor 1 is looks normal for cessna.
```
  {
        Style style;
        style.getOrCreate<ModelSymbol>()->autoScale() = true;
        style.getOrCreate<ModelSymbol>()->url()->setLiteral("../data/cessna.osg.1.scale");
        ModelNode* modelNode = new ModelNode(mapNode, style);
        cessna = modelNode;
        modelNode->setPosition(GeoPoint(geoSRS, -100, 52));
        annoGroup->addChild(modelNode);
    }
```
I also run `osgearth_annotation simple.earth`，the same thing occurrence.
when not define `OSG_SCREEN`, got `red_flag`, by define `OSG_SCREEN=0`, the `red_flag`  disappeared.
how to work with model more than 1 screen?
how to fix it?

**Comment by gwaldron** [comment]
Is your display spanning both screens when you see the problem? Or is the difference apparent with OSG_SCREEN=0 versus OSG_SCREEN=1? Are your screens different resolutions?

**Comment by x1244** [comment]
The two screens has the same resolutions with 1920*1080.When not set OSG_SCREEN，the display spanning both screens.At that time, the same results are obtained regardless of whether OSG_SCREEN=0 or OSG_SCREEN=1 is set.

But I can't go back to the problem. Now I use code like this to view the model.
```
style.getOrCreate<ModelSymbol>()->url()->setLiteral("../data/cessna.osg.1000.scale");
```
This is not the reason of OSG_SCREEN setting. It seems that some random factor is causing the problem. I will keep testing.
Thanks.
