### ISSUE TITLE
How to turn off the Frustum of the version of 3.6.5 OSG?

### ISSUE THREAD

**Issue by yuhubuxi** [gwaldron/osgearth#1661]
This question in the following figure will appear after vertical scaling, is it the reason for the Frustum?  I want to know how to solve this problem. Could you guide me？
![1da111cf610a4071e49b76916eff862](https://user-images.githubusercontent.com/28517837/111409796-955d1a80-8712-11eb-90b6-72f98d37b867.png)

**Comment by gwaldron** [comment]
I cannot tell what the problem is by looking at your picture. Can you explain it please?
