### ISSUE TITLE
osgearth_collecttriangles fix

### ISSUE THREAD

**Issue by nmielcarek** [gwaldron/osgearth#1662]
Linux build error on this new application code due to a const missing on the Observer class (I assume this is what was intended). Here is the simple fix, let me know if you want it as a pull request instead.

```
--- a/src/applications/osgearth_collecttriangles/osgearth_collecttriangles.cpp
+++ b/src/applications/osgearth_collecttriangles/osgearth_collecttriangles.cpp
@@ -74,7 +74,7 @@ public:
     {
     }
 
-    Observer(osg::BoundingSphered& bounds):
+    Observer(const osg::BoundingSphered& bounds):
         _bounds(bounds)
     {
     }
```

Thanks,
Nathan

**Comment by gwaldron** [comment]
Fixed in 8183af39e2ce7606298364de09356f5fa5b9892a
thanks
