### ISSUE TITLE
camera's near and far plane cropping abnormally occurr when I use GPU vertical scaling

### ISSUE THREAD

**Issue by yuhubuxi** [gwaldron/osgearth#1664]
The version of osgearth is 3.1, when I use GPU vertical scaling, the camera's near and far plane cropping abnormally occurr. The main manifestation is that when I put the camera close to the ground, the camera's far plane will be cropped. In other words, I can't see the terrain in the distance. Currently, I use osgEarth::Util::AutoClipPlaneCullCallback(mapNode) to automatically calculate the near and far plane, and use osg::CullSettings::NO_CULLING for the camera. How can I solve my problem?
The following two pictures show my problem. My camera is in this position, I look into the distance when the pitch angle is not large. However, when I tilt the camera up, it will automatically crop the far terrain.
![b06e1d6d6a5d39fe6a1ee1e09572467](https://user-images.githubusercontent.com/28517837/112928648-95fda400-9149-11eb-966a-ad9f36479840.png)
![16add9e7c95e79646302b405e29bdca](https://user-images.githubusercontent.com/28517837/112928652-972ed100-9149-11eb-9ded-4b649cae7043.png)

The following picture shows that this phenomenon will be more serious if my camera continues to push to the ground.
![8521af50d7664c65472919b446e7404](https://user-images.githubusercontent.com/28517837/112929510-28eb0e00-914b-11eb-9fe8-8ecd96ea7c54.png)

**Comment by gwaldron** [comment]
It happens because the OpenSceneGraph culling does not know about vertices moving in the GPU vertex shader. The AutoClipPlaneCullCallback does not know about them either. This is why we don't do shader-based vertical scaling.

**Comment by yuhubuxi** [comment]
Excuse me, is there any way to alleviate my current situation?

**Comment by gwaldron** [comment]
Not within the scope of the osgEarth API, no.
In the future we could consider adding a static vertical scaling option to the ElevationLayer class; if this is of interest, you can open a github ticket to request the feature.
