### ISSUE TITLE
Crash: profile is nullptr when creating elevation layer

### ISSUE THREAD

**Issue by gwaldron** [gwaldron/osgearth#1665]
See:
http://forum.osgearth.org/issue-with-removing-gdal-elevation-layer-td7593749.html#a7593761

**Comment by jasonbeverage** [comment]
I pushed some basic fixes in 06b8af750d827b2ad66d6d54cb475766c7c73719.  If we continue to see crashes when removing layers we may want to add some read/write mutex to prevent a layer from being removed from a layer while it's actively being used in a background job.
