### ISSUE TITLE
How to Clamp Feature on Model

### ISSUE THREAD

**Issue by mingweiLIU** [gwaldron/osgearth#1670]
As we see, we could clamp FeatureModelLayer on the terrain through a combination of clamping and technique, while is there any way to clamp feature or node on the model? I have tried the OverlayNode from OSG while it has no effect.

**Comment by gwaldron** [comment]
The easiest way to clamp a Node to the terrain is to put it under an `osgEarth::GeoTransform` and make sure it's somewhere under the MapNode. Please refer to the `osgearth_transform.cpp` example for more information. Hope this helps!

**Comment by mingweiLIU** [comment]
well，thanks for reply，you may miss understand me.what i want to do is drape the featue on model surface， not clamp on terrain------------------&nbsp;原始邮件&nbsp;------------------
***@***.***&gt;
发送时间:&nbsp;2021年4月9日(星期五) 晚上9:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [gwaldron/osgearth] How to Clamp Feature on Model (#1670)

**Comment by gwaldron** [comment]
I see. No, that capability is not available in osgEarth.
