### ISSUE TITLE
how to achieve an egocentric 3D globe, in the version of osgearth 3.1 and osg3.6.5.

### ISSUE THREAD

**Issue by yuhubuxi** [gwaldron/osgearth#1675]
Now, the globe is 3D exocentric globe, where the user’s viewpoint is outside the globe. Namely, it is formed by bending inward from 180°.  We only see at most one hemisphere without the inability to show the entire surface. 

In order to  show the entire surface, we want to  show an egocentric 3D globe, with the viewpoint inside the globe. Namely, it is formed by bending outward from 180°.  People stand inside the egocentric 3D globe and can see the entire surface. 

I want to know how to achieve an egocentric 3D globe, could you give me some guidance?

**Comment by gwaldron** [comment]
The closest thing available to an egocentric view is the SkyView layer type and the osgearth_skyview example. Its intent was to render a sky image, but you can run it with a land image as well though it will be reversed. It will not properly render things like annotations and features however. But, it might be a start if you want try writing some code. Good luck.

**Comment by yuhubuxi** [comment]
Thank you gwaldron. As you said, I tried to run SkyView. The earth was indeed rendered as the sky. Of course, the final map was also reversed. Is there any better solution?

**Comment by jasonbeverage** [comment]
SkyView is really the closest solution we have at the moment.    That code
is actively being used in a planetarium environment so it should work
pretty well for you I'd think.
