### ISSUE TITLE
Leftover GEOS dependency in osgearth_viewer?

### ISSUE THREAD

**Issue by robspearman** [gwaldron/osgearth#1676]
The 3.1 release notes say that GEOS is no longer used, however on master I get the following linker error:

```
/usr/gdal30/lib/libgdal.so: undefined reference to `GEOSMakeValid_r'
collect2: error: ld returned 1 exit status
make[2]: *** [src/applications/osgearth_viewer/CMakeFiles/application_osgearth_viewer.dir/build.make:108: bin/osgearth_viewer] Error 1
make[1]: *** [CMakeFiles/Makefile2:1785: src/applications/osgearth_viewer/CMakeFiles/application_osgearth_viewer.dir/all] Error 2
```

**Comment by gwaldron** [comment]
GEOS is still in use. We however replaced the C++ API with the C API, as this was the recommendation of the project maintainers.

**Comment by robspearman** [comment]
Is gdal 3.1 now required then?  This error is with gdal 3.0.4.

**Comment by robspearman** [comment]
Nevermind, looks like I have two GEOS lib versions and need to correct which one is being linked by cmake.
