### ISSUE TITLE
Some TMS/Composite layers doesn't show/work on current master 05/21

### ISSUE THREAD

**Issue by remoe** [gwaldron/osgearth#1688]
The current master doesn't work with some TMS layers. It does not throw any error but it doesn't show the layers. I've ported a large app to osgEarth 3.x in the past with this commit (2/21):

c5dc70df7de85e49078e774fbc704c3b204a5d04

(works as well: 28a59a97ee90d9188a63fc2dd186b57877d512ec )

Using OSG 3.6.3 and GDAL 2.4. This version works!

After porting to this commit:

40d46cf6e7af36e28e8b83e276e9e9fb5e722066

I have this issue. The diffs between this commits are large and I don't have an idea which changes are create this issue.

**Comment by gwaldron** [comment]
Hi Remo -- please provide a sample case so we can repro.

**Comment by remoe** [comment]
Sorry Glenn, I don't have a sample but I tried a lot of commits and found it's this commit:

9c2e7611534433b4f2afe8d4b674fa25280af898

**Comment by remoe** [comment]
This is solved on commit: db3cd7fc8b16cc9b231b8eb917dec7199e76be06 . But I think the main issue was:

https://github.com/gwaldron/osgearth/commit/e2895043bba9716e33a25dfe002ae2abb526ffb1
