### ISSUE TITLE
Multiple problems with POINTSET geometries

### ISSUE THREAD

**Issue by MCA4213** [gwaldron/osgearth#1691]
Hello, I have noticied at two problems with POINTSET geometrie:
1: The first one is related to the AnotationNode, it draw only one point at the centroid, even if a have 10!!!
I am using this code:
```
 osgEarth::Style style;
       style.getOrCreate<IconSymbol>()->url() = osgEarth::StringExpression("../data/images/pin.png");
       style.getOrCreate<IconSymbol>()->placement() = osgEarth::IconSymbol::PLACEMENT_VERTEX;
       osg::ref_ptr <osgEarth::Feature> feature = new osgEarth::Feature(observer->geom, srsWgs);
       observerZone->setFeature(feature);
       observerZone->setStyle(style);
       observerZone->dirty();
```
If I change to modelSymbol, it will display all the points correctly. **(I don't knew how to fix this first problem)**

2: All GEOS operations with POINTSET fails. This because `GEOS::importGeometry` is failling, and this is caused by the manner that you create the geometry.
At `GEOSGeometry*  import(GEOSContextHandle_t handle, const Geometry* input) ` in **GEOS.cpp**, you are creating a pointset with the same manner as you do for point using GEOSGeom_createPoint_r, but this fonction can create only one point and fail if you give more than one!
So as a quick solution, you can create a multiple points geometries, than add them to a collection, and this will make it work.
 ```
case Geometry::TYPE_POINT:
                seq = vec3dArray2CoordSeq(handle, input, false);
                if (seq) output = GEOSGeom_createPoint_r(handle, seq);
                break;
```

```
case Geometry::TYPE_POINTSET:
                geomsList=new GEOSGeom[input->size()];
                for (int i = 0; i < input->size(); i++)
                {
                    seq = GEOSCoordSeq_create_r(handle, 1, 3);
                    {
                        GEOSCoordSeq_setX_r(handle, seq, 0, input->at(i).x());
                        GEOSCoordSeq_setY_r(handle, seq, 0, input->at(i).y());
                        GEOSCoordSeq_setZ_r(handle, seq, 0, input->at(i).z());
                    }
                    geomsList[i] = GEOSGeom_createPoint_r(handle, seq);
                }
                output = GEOSGeom_createCollection_r(handle, GEOS_MULTIPOINT, geomsList, input->size());
                delete geomsList;
                break;
```
**(This could be a solution for problem 2)**

I am on the lates osgearth 3.1.0 build 109, GDAL 3.4.0dev, Geos 3.9.0, and osg 3.7.0 on windows 10.
Thank you.

**Comment by gwaldron** [comment]
Please create a PR with the GEOS-related fix and we'll merge it. Thanks.

**Comment by gwaldron** [comment]
The first problem (IconSymbol with per_vertex placement only renders to the centroid) is a discrepancy in the BuildTextFilter code. I will create a new defect for that and close this one.
