### ISSUE TITLE
Picker does not work with current master

### ISSUE THREAD

**Issue by remoe** [gwaldron/osgearth#1695]
Tested with https://github.com/gwaldron/osgearth/commit/551b43c16e40194d03f1f23b946961f20e76a1ba Win64

osgearth_pick.exe tests\feature_draped_polygons.earth

![image](https://user-images.githubusercontent.com/804941/118266791-61f0ff00-b4bb-11eb-9531-89a11a4a7f11.png)

**Comment by remoe** [comment]
@gwaldron sorry Glenn, I tested the fix, but it doesn't solve the issue. And the globe "jumps" ...

**Comment by gwaldron** [comment]
Doesn't solve which issue? The picking is working again on my side. Remember to enable feature_indexing on the earth file to get any picks.

Yes the screen jumps -- I opened a separate ticket for this.
