### ISSUE TITLE
ImGui: osgearth_pick causes GUI tab headers to disappear while mouse is moving

### ISSUE THREAD

**Issue by gwaldron** [gwaldron/osgearth#1696]
Run osgearth_pick osm.earth. GUI headers do not display while mouse moves.

**Comment by jasonbeverage** [comment]
The reason for this is the OsgImGuiHandler::newFrame function is getting called from the CallHostCameraPreDrawCallback in the RTTPicker.  We want the predraw callback to be called so the log depth buffer can update the far plane uniform, but we don't want the imgui new frame to be called from here.  Maybe we can rework the imgui stuff to not use camera callbacks to avoid this.

**Comment by gwaldron** [comment]
Fixed
