### ISSUE TITLE
Problem:windows7 can not found "setThreadDescription" from kernel32.dll

### ISSUE THREAD

**Issue by tangxiaodao** [gwaldron/osgearth#1700]
**[Description]**
 osgEarth compiled under 64-bit windows10, when running on 64-bit window7, an error occurred: the function "setThreadDescription" could not be found in the Kernel32.dll.
**[Analysis]**
 By comparing the export functions of windows7 kernel32.dll  and windows10 kernel32.dll , windows7 kernel32dll not exists"setThreadDescription".
**[Conclusion]**
Not sure where the function of setThreadDescription is called. OpenThreads? OpenSceneGraph? Or osgEarth?If there is a way to optimize it to make osgEarth more compatible in the end.

Best regards.

**Comment by remoe** [comment]
Do you have tried latest master?

**Comment by jasonbeverage** [comment]
Remo is right, I pushed a hopeful fix for this awhile back.  Give the master a shot and report back if it works.

**Comment by tangxiaodao** [comment]
Thx,Remoe && Jason,I find the changed from latest code:
=========================================
  //::SetThreadDescription(::GetCurrentThread(), buf);
  // Look up the address of the SetThreadDescription function rather than using it directly.
    typedef ::HRESULT(WINAPI* SetThreadDescription)(::HANDLE hThread, ::PCWSTR lpThreadDescription);
    auto set_thread_description_func = reinterpret_cast<SetThreadDescription>(::GetProcAddress(::GetModuleHandle("Kernel32.dll"), "SetThreadDescription"));
    if (set_thread_description_func)
    {
        set_thread_description_func(::GetCurrentThread(), buf);
    }
==========================================
I'll try it.
Best regards.
