### ISSUE TITLE
Help:osg::Billboard cannot be loaded into osgEarth correctly

### ISSUE THREAD

**Issue by tangxiaodao** [gwaldron/osgearth#1701]
**[Description]**
Try to use osg::Billboard in osgEarth and let it be placed at a certain point(lon, lat, alt).
**[Question]**
Is there a substitute in osgEarth to achieve the effect of Billboard?

=========================================
Best regards.

**Comment by gwaldron** [comment]
You can put your osg::Billboard under a GeoTransform to place it on the map.

**Comment by tangxiaodao** [comment]
Thx,gwaldron.I'll try it.
