### ISSUE TITLE
Problem:win7 compatible with win10 API(GetSystemTimePreciseAsFileTime)

### ISSUE THREAD

**Issue by tangxiaodao** [gwaldron/osgearth#1705]
**[Description]**
win7 kernel32.dll can not found GetSystemTimePreciseAsFileTime.
**[Analysis]**
The function is called by Plugin_osgearth_scriptengine_javascript.From file duktape.c
;----------------------------------------------
From:docs.microsoft.com Fragment.

Minimum supported client | Windows 8 [desktop apps \| UWP apps]
Minimum supported server | Windows Server 2012 [desktop apps \| UWP apps]
Target Platform | Windows
Header | sysinfoapi.h (include Windows.h)
Library | Kernel32.lib
DLL | Kernel32.dll
;--------------------------------------------------------------------------
Best regards.

**Comment by tangxiaodao** [comment]
This is really troublesome. The two functions of GetSystemTimePreciseAsFileTime and GetSystemTimeAsFileTime are not completely compatible. GetSystemTimePreciseAsFileTime has an additional parameter FILTTIME, and GetSystemTimeAsFileTime does not have this parameter, so it cannot be replaced simply. If you just replace GetSystemTimePreciseAsFileTime with GetSystemTimeAsFileTime , the osgEarth will crash.

**Comment by jasonbeverage** [comment]
Thanks for the report, but I don't think we can support a fix for this.  Windows 7 reached end of life Jan 2020 and this is an issue in the duktape engine which we are just using the code directly with no modifications on our side.  You may want to reach out to the duktape developers and see if they are interested in fixing it, but supporting Windows 7 issues isn't a priority for us.

**Comment by mirh** [comment]
See https://github.com/svaarala/duktape/issues/1663
