### ISSUE TITLE
Problem:Test osgearth under windows7-x64 is incorrect.

### ISSUE THREAD

**Issue by tangxiaodao** [gwaldron/osgearth#1706]
**[Description]**
Made a test Demo for osgearth_annoation.exe.
Testing osgearth_annoation.exe under winodws7 is incorrect.
;------------------------------------------Test config--------------------------------------------
osgEarth Version:Latest master.Compiled under windows10-x64.
Test Demo:osgearth_annoation.exe.
Test Environment:windows7-x64.
The error screenshot is as follows:
![image](https://user-images.githubusercontent.com/12289997/119114914-2c1ebe00-ba59-11eb-86b4-3a5310afb14f.png)
![image](https://user-images.githubusercontent.com/12289997/119115036-4a84b980-ba59-11eb-9d3f-f1608904f6b9.png)
;----------------------------------------------------------------------------------------------------
**[Analysis]**
According to error：Version number not supported by OGL driver, it may be a problem with OpenGL driver.

Best regards.

**Comment by gwaldron** [comment]
Please post the output to `osgearth_version --caps`

**Comment by tangxiaodao** [comment]
I think I found the problem. The Laptop is an integrated graphics card Intel HD Graphics 3000. The driver only supports up to OpenGL 3.1 and GLSL 1.40, while OpenGL 3.2 and GLSL 1.50 just support GL_ARB_GPU_Shader5. Shortly after I‘ll switched to another Laotop with a discrete graphics card and tested it again.

**Comment by tangxiaodao** [comment]
I tested osgEarth on a laptop with a discrete graphics card. The driver of the discrete graphics card is OpenGL 4.0 && GLSL  full support.But osgEarth_annotation.exe is crash and no error message found.It maybe a problem with driver(Graphics card with OpenGL).
The osgEarth_version caps screenshots of the two tests are as follows：

***1.Laptop with  integrated graphics card with Intel HD Graphics 3000.***

![image](https://user-images.githubusercontent.com/12289997/119223227-c4d13e80-bb2a-11eb-8b31-91b5869ee727.png)
![image](https://user-images.githubusercontent.com/12289997/119223261-efbb9280-bb2a-11eb-9266-c64fa4b6105f.png)

***2. laptop with a discrete graphics card with Intel HD Graphics 4000(NVIDIA GeForce 610M)***

![image](https://user-images.githubusercontent.com/12289997/119223237-d3b7f100-bb2a-11eb-9477-1adc4fc85595.png)
![image](https://user-images.githubusercontent.com/12289997/119223243-d87ca500-bb2a-11eb-9e44-9032e8ff0727.png)
![image](https://user-images.githubusercontent.com/12289997/119223246-dc102c00-bb2a-11eb-9966-b3be7f58c66d.png)


Best regards.

**Comment by jasonbeverage** [comment]
Try forcing the use of the nvidia discrete card instead of the intel card and see if that helps.  The intel drivers are notoriously terrible and have issues with osgearth.
