### ISSUE TITLE
using osgEarth master (built 06/08/2021), osgearth_conv produces strange results when tiling imagery with jpg...

### ISSUE THREAD

**Issue by keince** [gwaldron/osgearth#1724]
I run the following application to create an MBTiles file:

osgearth_conv --in driver GDALImage --in url N3600W11500.tif --out driver MBTilesImage --out filename N3600W11500.mbtiles --out format jpg

and load it in the simple.earth file using:
```
<map>
    <GDALImage name="World GeoTIFF">
        <url>../data/world.tif</url>
    </GDALImage>

  <MBTilesImage name="Vegas" visible="true">
    <url>E:/Imagery/GeoTiff/LasVegas/N3600W11500.mbtiles</url>
  </MBTilesImage>
</map>
```
I get the following incorrect result in osgearth_viewer:

![image](https://user-images.githubusercontent.com/80072561/122252514-a5f36d00-ce88-11eb-86d3-4c8da957ca76.png)

If I reissue "osgearth_conv" but change "--out format jpg" to "--out format png" and re-run osgearth_viewer, I get the following result which looks correct:

![image](https://user-images.githubusercontent.com/80072561/122253840-c7a12400-ce89-11eb-8a22-ab4ee6cdbf2e.png)

For some reason tiling to jpg format internally creates black regions around the image inset at all zoom levels whereas png format does not.

I have sent the GeoTiff file I used to reproduce the problem via mytransfer to support@pelicanmapping.com...

**Comment by gwaldron** [comment]
That's because JPEG does not support transparency.

**Comment by keince** [comment]
So...the option "-out format jpg" should be avoided when converting hi-res imagery insets to mbtiles?

**Comment by gwaldron** [comment]
Correct you are. Use PNG to ensure a proper alpha channel for blending.
