### ISSUE TITLE
ImGui Map Layers tool has checkbox set on startup for non-visible layers...

### ISSUE THREAD

**Issue by keince** [gwaldron/osgearth#1725]
I have the following earth file:
```
<map>
    <GDALImage name="World GeoTIFF">
        <url>../data/world.tif</url>
    </GDALImage>

  <MBTilesImage name="Vegas" visible="false">
    <url>E:/Imagery/GeoTiff/LasVegas/N3600W11500.mbtiles</url>
  </MBTilesImage>
</map>
```

If I run the osgearth_imgui application and open the "Map Layers" tool, it has the "Vegas" image layer checked as visible even though I have the layer set to "visible=false" in the earth file by default. The image is correct (no layer visible) but the Map Layers tool thinks it's visible which is incorrect.

![image](https://user-images.githubusercontent.com/80072561/122258416-3da78a00-ce8e-11eb-88ca-e9da68088a7a.png)

If I uncheck the "Vegas" layer via the check box and then re-enable the check box, then the layer behaves as expected as I toggle the check box on and off. It appears the problem is on start up with layers that are marked as not visible by default in the earth file.

**Comment by jasonbeverage** [comment]
Right now that checkbox is tied to the "enabled" state of the layer which completely opens and closes a layer vs the visible state of a layer.  At some point we might change the gui to have separate toggles for opening/closing and the visibility of a layer.

**Comment by keince** [comment]
Is there any way that I can start up the application using ImGui so that those checkboxes are NOT enabled? I need to have the layers present in the earth file but disabled.

**Comment by jasonbeverage** [comment]
Use enabled="false" instead and it should work.

**Comment by keince** [comment]
Thanks Jason.
