### ISSUE TITLE
ImGui Terrain tool disables left mouse button throwing in EarthManipulator

### ISSUE THREAD

**Issue by keince** [gwaldron/osgearth#1728]
In our application, we enable the throwing feature in the EarthManipulator as follows...
```
EarthManipulator* em = new EarthManipulator(arguments);
em->getSettings()->setThrowingEnabled(true);
```
This works as expected until we open the Terrain tool in the ImGui "tools" menu. When the Terrain tool is being used, the throwing feature in EarthManipulator gets disabled for the left mouse button panning. The middle mouse button still works with throwing.

Even if we close the ImGui Terrain tool, the throwing for the left mouse button is still disabled.

**Comment by gwaldron** [comment]
fixed in 4c93fbf
