### ISSUE TITLE
Compile error on Ubuntu 20.04

### ISSUE THREAD

**Issue by Conan42** [gwaldron/osgearth#1729]
Hello,

I am on Ubuntu 20.04. All dependencies are installed, see the cmake output:

mich@ticonderoga:~$ cd Downloads/

mich@ticonderoga:~/Downloads$ cd gwaldron-osgearth-342fcad/

mich@ticonderoga:~/Downloads/gwaldron-osgearth-342fcad$ cd build

mich@ticonderoga:~/Downloads/gwaldron-osgearth-342fcad/build$ cmake ..

CMake Deprecation Warning at CMakeLists.txt:10 (cmake_policy):
  The OLD behavior for policy CMP0005 will be removed from a future version
  of CMake.

  The cmake-policies(7) manual explains that the OLD behaviors of all
  policies are deprecated and that a policy should be set to OLD only under
  specific short-term circumstances.  Projects should be ported to the NEW
  behavior and not rely on setting a policy to OLD.

CMake Warning (dev) at /usr/local/share/cmake-3.20/Modules/FindOpenGL.cmake:315 (message):
  Policy CMP0072 is not set: FindOpenGL prefers GLVND by default when
  available.  Run "cmake --help-policy CMP0072" for policy details.  Use the
  cmake_policy command to set the policy and suppress this warning.

  FindOpenGL found both a legacy GL library:

    OPENGL_gl_LIBRARY: /usr/lib/x86_64-linux-gnu/libGL.so

  and GLVND libraries for OpenGL and GLX:

    OPENGL_opengl_LIBRARY: /usr/lib/x86_64-linux-gnu/libOpenGL.so
    OPENGL_glx_LIBRARY: /usr/lib/x86_64-linux-gnu/libGLX.so

  OpenGL_GL_PREFERENCE has not been set to "GLVND" or "LEGACY", so for
  compatibility with CMake 3.10 and below the legacy GL library will be used.
Call Stack (most recent call first):
  CMakeLists.txt:126 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Warning (dev) at /usr/local/share/cmake-3.20/Modules/FindPackageHandleStandardArgs.cmake:438 (message):
  The package name passed to `find_package_handle_standard_args` (LibZip)
  does not match the name of the calling package (LIBZIP).  This can lead to
  problems in calling code that expects `find_package` result variables
  (e.g., `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  /usr/local/share/cmake-3.20/Modules/FindLIBZIP.cmake:39 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)
  CMakeLists.txt:148 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

-- Found libzip: /usr/lib/x86_64-linux-gnu/libzip.so
-- Found GDAL 3.2.1
-- Plugins will be installed under osgPlugins-3.7.0 directory.
-- Creating /home/mich/Downloads/gwaldron-osgearth-342fcad/build/build_include/osgEarth/BuildConfig.h
-- Building osgEarth as a SHARED library
-- Configuring done
-- Generating done
-- Build files have been written to: /home/mich/Downloads/gwaldron-osgearth-342fcad/build

mich@ticonderoga:~/Downloads/gwaldron-osgearth-342fcad/build$ make

[ 0%]
...

[ 98%] Linking CXX executable ../../../bin/osgearth_mvtindex
/usr/bin/ld: CMakeFiles/application_osgearth_mvtindex.dir/osgearth_mvtindex.cpp.o: in function `main':
osgearth_mvtindex.cpp:(.text+0x600): undefined reference to `osgEarth::MVTFeatureSource::setURL(osgEarth::URI const&)'
/usr/bin/ld: osgearth_mvtindex.cpp:(.text+0xe2b): undefined reference to `osgEarth::MVTFeatureSource::iterateTiles(int, int, int, osgEarth::GeoExtent const&, void (*)(osgEarth::TileKey const&, std::__cxx11::list<osg::ref_ptr<osgEarth::Feature>, std::allocator<osg::ref_ptr<osgEarth::Feature> > > const&, void*), void*)'
/usr/bin/ld: CMakeFiles/application_osgearth_mvtindex.dir/osgearth_mvtindex.cpp.o: in function `osgEarth::MVT::MVTFeatureSourceOptions::MVTFeatureSourceOptions()':
osgearth_mvtindex.cpp:(.text._ZN8osgEarth3MVT23MVTFeatureSourceOptionsC2Ev[_ZN8osgEarth3MVT23MVTFeatureSourceOptionsC5Ev]+0x20): undefined reference to `vtable for osgEarth::MVT::MVTFeatureSourceOptions'
/usr/bin/ld: osgearth_mvtindex.cpp:(.text._ZN8osgEarth3MVT23MVTFeatureSourceOptionsC2Ev[_ZN8osgEarth3MVT23MVTFeatureSourceOptionsC5Ev]+0x50): undefined reference to `osgEarth::MVT::MVTFeatureSourceOptions::fromConfig(osgEarth::Config const&)'
/usr/bin/ld: CMakeFiles/application_osgearth_mvtindex.dir/osgearth_mvtindex.cpp.o: in function `osgEarth::MVTFeatureSource::MVTFeatureSource()':
osgearth_mvtindex.cpp:(.text._ZN8osgEarth16MVTFeatureSourceC2Ev[_ZN8osgEarth16MVTFeatureSourceC5Ev]+0x2e): undefined reference to `vtable for osgEarth::MVTFeatureSource'
/usr/bin/ld: osgearth_mvtindex.cpp:(.text._ZN8osgEarth16MVTFeatureSourceC2Ev[_ZN8osgEarth16MVTFeatureSourceC5Ev]+0x8d): undefined reference to `osgEarth::MVTFeatureSource::init()'
/usr/bin/ld: CMakeFiles/application_osgearth_mvtindex.dir/osgearth_mvtindex.cpp.o: in function `osgEarth::MVT::MVTFeatureSourceOptions::~MVTFeatureSourceOptions()':
osgearth_mvtindex.cpp:(.text._ZN8osgEarth3MVT23MVTFeatureSourceOptionsD2Ev[_ZN8osgEarth3MVT23MVTFeatureSourceOptionsD5Ev]+0x13): undefined reference to `vtable for osgEarth::MVT::MVTFeatureSourceOptions'
collect2: error: ld returned 1 exit status
make[2]: *** [src/applications/osgearth_mvtindex/CMakeFiles/application_osgearth_mvtindex.dir/build.make:119: bin/osgearth_mvtindex] Error 1
make[1]: *** [CMakeFiles/Makefile2:3530: src/applications/osgearth_mvtindex/CMakeFiles/application_osgearth_mvtindex.dir/all] Error 2
make: *** [Makefile:136: all] Error 2

We see undefined reference in osgearth_mvtindex.cpp to osgEarth::MVTFeatureSource

it seems that a library is missing, yet the cmake has nothing to say, does anyone have an idea, please?

**Comment by LexSheyn** [comment]
Hello. Have you resolved the issue?
