### ISSUE TITLE
3.2 fails to compile if protobuf not found

### ISSUE THREAD

**Issue by Displacer** [gwaldron/osgearth#1735]
with error:

osgearth-3.2/src/osgEarth/ArcGISTilePackage.cpp:195:19: error: ‘osgEarth::MVT’ has not been declared

MVT defined in header under condition OSGEARTH_HAVE_MVT which not enabled if Protobuf not found in CMakeList.txt

**Comment by ASxa86** [comment]
Is there a recommended workaround to this. I'm dealing with some static memory problems caused by the protobuf dependency. I'd like to not compile osgEarth with protobuf.

**Comment by plevy** [comment]
Sorry, let me take a look at it

**Comment by ASxa86** [comment]
> Sorry, let me take a look at it

I realized after my comment that the code on master just gets wrapped in an #ifdef. That's good enough for my use case I believe. I should be able to do the same thing on my machine.

**Comment by plevy** [comment]
Even better
