### ISSUE TITLE
GLES - building 3.2 fails

### ISSUE THREAD

**Issue by Displacer** [gwaldron/osgearth#1736]
osgEarth/GLUtils.cpp:821:5: error: ‘glGetTexImage’ was not declared in this scope

**Comment by Displacer** [comment]
It seems there is no glGetTexImage in OpenGL ES

**Comment by Displacer** [comment]
The same applies to TileRasterizer

**Comment by Displacer** [comment]
At least for TileRasterizer glReadPixels could be used as mentioned in comment as slower variant.

**Comment by gwaldron** [comment]
We don't actively maintain osgEarth for GLES but if you want to submit a PR we will be happy to take a look.

**Comment by Displacer** [comment]
> We don't actively maintain osgEarth for GLES but if you want to submit a PR we will be happy to take a look.

It seems working with GLES is a subject of porting some terrain engine to GLES. If I undestand correctly there are two such engines - engine_rex and engine_mp. To produce a PR to submit id like to understand is it possible to use older GLSL with version 100 or 101 (look at issue #1737 ) or I should try to fix legacy engine_mp driver? Or it is impossible without complete rewrite.

**Comment by gwaldron** [comment]
Getting OE to work with GLES is probably no small task, you are right. The last time it worked, it definitely required GLES2. It would likely be easier to support mp (since it is a much simpler implementation) but mp is no longer developed or maintained.

What is your target platform?

**Comment by Displacer** [comment]
Target platform is ARM mali, some code is already working and producing a log file attached to issue #1737

**Comment by Displacer** [comment]
GLES2 available on that platform. Unfortunately GLES2 asume GLSL version 101 while current minimum requirements are 330.

**Comment by gwaldron** [comment]
Yes that is true. It may be too much work to be worthwhile.

**Comment by HerryJessica** [comment]
> osgEarth/GLUtils.cpp:821:5: error: ‘glGetTexImage’ was not declared in this scope

I have the same problem as you, how did you solve it?

**Comment by Displacer** [comment]
> > osgEarth/GLUtils.cpp:821:5: error: ‘glGetTexImage’ was not declared in this scope
> 
> I have the same problem as you, how did you solve it?

No, it seems too complicated at least for GLES2. GLES3 is another case and it is probably possible.

**Comment by HerryJessica** [comment]
It doesn't seem to work in gles3 either, I try to use gles3 and comment out glGetTexImage but the earth can't be displayed when I run
