### ISSUE TITLE
GLES2 - runtime errors

### ISSUE THREAD

**Issue by Displacer** [gwaldron/osgearth#1737]
It seems there are some GLSL version and precision problems for engine_rex with GLES2.

Log file attached with OSG_NOTIFY_LEVEL=INFO enabled

[output_3.2.txt](https://github.com/gwaldron/osgearth/files/6768777/output_3.2.txt)

**Comment by gwaldron** [comment]
We are not actively supporting GLES2 at this time but will entertain PRs if you want to address any build issues.

**Comment by fanstep** [comment]
can we build OE with GLCORE on platform of Mali？
But Mali just support OpenGLES*
