### ISSUE TITLE
MBTiles driver leaves database open indefinitely

### ISSUE THREAD

**Issue by jasonbeverage** [gwaldron/osgearth#1738]
http://forum.osgearth.org/MBTILES-Layers-not-released-td7593942.html

**Comment by emminizer** [comment]
There's also a not-insignificant leak associated with this when loading multiple terrain files. PR submitted that fixes this.

**Comment by jasonbeverage** [comment]
Fixed in b63c08e810bcc9ef71f1fb22acaaeae33a83bfda
