### ISSUE TITLE
glsl.earth shader error

### ISSUE THREAD

**Issue by plevy** [gwaldron/osgearth#1745]
I get this error:  

FRAGMENT glCompileShader "gammaCorrection" FAILED
FRAGMENT Shader "gammaCorrection" infolog:
0(7) : error C7548: '%' requires "#extension GL_EXT_gpu_shader4 : enable" before use

glLinkProgram 0000028E42998DE0"VisibleLayer" FAILED
Program "VisibleLayer" infolog:
Fragment info
-------------
0(7) : error C7548: '%' requires "#extension GL_EXT_gpu_shader4 : enable" before use
(0) : error C2003: incompatible options for link

**Comment by gwaldron** [comment]
Shaders needs a `#version 330` at the top

**Comment by plevy** [comment]
added #version 330
