### ISSUE TITLE
wms_nexrad.earth state features do not draw with image layers enabled

### ISSUE THREAD

**Issue by plevy** [gwaldron/osgearth#1748]

**Comment by gwaldron** [comment]
`<style>` block not allowed at the top level, must be inside a `<styles>` block

**Comment by gwaldron** [comment]
Also, some of the image layers are drawn with a positive `<altitude>` which will cause the FeatureModel layer to render behind them.
Prob better to use a FeatureImage and draw it before the altitude layers.
