### ISSUE TITLE
ImGui: Support OSG threading models other than SingleThreaded

### ISSUE THREAD

**Issue by gwaldron** [gwaldron/osgearth#1756]
Some of the ImGui components do not work unless OSG is in SingleThreaded mode. SingleThreaded mode impacts performance; you can measure by running `osgearth_viewer --novsync --SingleThreaded` and checking the relative frame rates.

Task: Identify and update the non-working ImGui components so they work in DrawThreadPerContext et al.

**Comment by jasonbeverage** [comment]
I think we can separate the pre draw imgui stuff and put it in an update traversal but leave the actual render call where it is.
