### ISSUE TITLE
REX terrain engine performance and rendering issue

### ISSUE THREAD

**Issue by farz4d** [gwaldron/osgearth#1757]
As you can see in the picture there are more than 6000 network requests for this viewpoint.
This map consists of two local layers, 1 imagery and 1 elevation layer. Most of network requests belong to elevation layer. It takes 3 minutes to complete all requests!
Also at bottom-left corner there are some cracks in terrain (blue areas).

The same scenario loads very fast (under 5 seconds) in version 2.9 using MP terrain engine without visual artifacts.

System Specs: Ubuntu 18.04 LTS - NVIDIA GTX 1060 Driver 460.80 - CPU Intel Core i7 4790

![Screenshot_20210717_130151](https://user-images.githubusercontent.com/1389198/126031242-8dc57d88-c7e2-4ea4-93f1-d9b945baf59b.png)

**Comment by gwaldron** [comment]
Please include an earth file with a Viewpoint. Thanks.

**Comment by farz4d** [comment]
Earth file and related maps are attached.
3 map layers included. One imagery and two elevation layer.s Both elevation layers use the same data in TIF file.
TMS elevation layer is generated in this way:

osgearth_conv --extents 42 46 43 47 --in driver gdal --in interpolation bilinear --in N042E046_AVE_DSM.tif --out driver tms --out url elv/tms.xml --out format tif --elevation

TMS elevation data loads slowly and does lots of network requests compared to osgEarth 2.9 using MP engine.

I've found out that visual artifacts are related to morph_terrain="false" terrain option, if i enable this options there are no more cracks in terrain.

[data.zip](https://github.com/gwaldron/osgearth/files/6873778/data.zip)
