### ISSUE TITLE
ThreeDTilesLayer configKey same as ModelLayer

### ISSUE THREAD

**Issue by RhythmOfTension** [gwaldron/osgearth#1760]
Because of this I have wrong serialization.
Perhaps META_Layer macro for ThreeDTilesLayer should contain something different as last argument?
REGISTER_OSGEARTH_LAYER contains threedtiles, so maybe something like ThreeDTiles?

**Comment by gwaldron** [comment]
Thanks, good find. Fixed in ede8a7915

**Comment by RhythmOfTension** [comment]
CesiumIonImageLayer probably have the same issue, but I don't use it so can't test it now.
