### ISSUE TITLE
Feature Request: render point features with FeatureImageLayer

### ISSUE THREAD

**Issue by GISerliang** [gwaldron/osgearth#1764]
I rendered one shapefile file of point type and I created a PointSymbol for it, but it did not show in the map.
Then I found the 'renderFeaturesForStyle' Function in FeatureImageLayer only support 'LineSymbol', 'PolygonSymbol' and 'CoverageSymbol' like this:

```bool

FeatureImageLayer::renderFeaturesForStyle(Session*           session,
                                          const Style&       style,
                                          const FeatureList& features,
                                          const GeoExtent&   imageExtent,
                                          osg::Image*        image) const
{
    OE_DEBUG << LC << "Rendering " << features.size() << " features for " << imageExtent.toString() << "\n";

    // A processing context to use with the filters:
    FilterContext context(session);
    context.setProfile(getFeatureSource()->getFeatureProfile());

    const LineSymbol*    masterLine = style.getSymbol<LineSymbol>();
    const PolygonSymbol* masterPoly = style.getSymbol<PolygonSymbol>();
    const CoverageSymbol* masterCov = style.getSymbol<CoverageSymbol>();
...
```

I wanted to know how to render the point features with FeatureImageLayer. Please help me.
I only wanted this map like this after rendered.
![image](https://user-images.githubusercontent.com/11342604/127472849-7d0e0e7f-abf5-4f09-ad75-1c3c565ea365.png)

osgEarth: 3.1

**Comment by gwaldron** [comment]
Thank you for catching this; I have tagged it for feature development.
Feel free to tackle it if you want to submit a PR; otherwise it is in the queue for 3.3.

**Comment by gwaldron** [comment]
Commit 17756d53f
