### ISSUE TITLE
earth manipulator throwing doesn't work with ObjectID picker

### ISSUE THREAD

**Issue by keince** [gwaldron/osgearth#1772]
This bug can be duplicated doing the following modifications to the osgearth_pick.cpp file...

Replace line 278 given by:

app.viewer.setCameraManipulator( new EarthManipulator() );

With the lines:

EarthManipulator* em = new EarthManipulator();
em->getSettings()->setThrowingEnabled(true);
app.viewer.setCameraManipulator( em );

When running the osgearth_pick example, throwing in the earth manipulator has no effect.

Disabling the ObjectID picker by commenting out the following lines in osgearth_pick.cpp:

//app.picker->setView(&app.viewer);  // which view to pick?
//app.picker->setGraph(app.mapNode); // which graph to pick?
//app.mapNode->addChild(app.picker); // put it anywhere in the graph

The throwing action in earth manipulator works as expected.

**Comment by gwaldron** [comment]
Fixed in 4c93fbf
