### ISSUE TITLE
Regression: Artifacts in draped geometry

### ISSUE THREAD

**Issue by gwaldron** [gwaldron/osgearth#1779]
246ce0f14a71ea18b89d50e203cdd78b260b8e07 introduced rendering artifacts in `feature_draped_polygons.earth`.

Before:
![image](https://user-images.githubusercontent.com/326618/131525665-ca4b3782-d24f-4f1e-b3fc-c8f985aee619.png)

After:
![image](https://user-images.githubusercontent.com/326618/131525537-878b3c17-5434-410d-9ae8-931b01f5bcee.png)

**Comment by jasonbeverage** [comment]
I've reverted this change in 98a5c1674a8a97da0bd17c96da0b1e643192d1be and added some discussion of tessellation at https://github.com/gwaldron/osgearth/issues/1781
