### ISSUE TITLE
(REGRESSION) BBoxSymbol doesn't have any effect on text

### ISSUE THREAD

**Issue by RhythmOfTension** [gwaldron/osgearth#1802]
Looks like BBoxSymbol doesn't have any effect now (probably since 1fe4d0214eb07afc117280ee1327fd915aec36a4 commit?).

I can even reproduce it with annotation.earth (labels "Label" and "Label with offsets" don't have bounding box, but they have options text-bbox-

Tried on osgearth 3.1 + osg 3.6.5.

And even if it does work and problem is on my side, looks like it's has limited functionality based on this commit. The only options that are used are fill color?

**Comment by gwaldron** [comment]
Verified. Thanks - we will look into it.
