### ISSUE TITLE
In the rex engine, the color component a is set to 0, which is invalid?

### ISSUE THREAD

**Issue by Rendtime** [gwaldron/osgearth#1807]
The previously used version 2.10, this time I changed to version 3.2, I found that the transparency in the color does not work, I want to make the place without image transparent

<map name="OpenStreetMap Projected Map">
    <options>
        <type>projected</type>
        <terrain>
            <color>#000000**00**</color>
        </terrain>
    </options>
    <XYZImage name="osm_mapnik">
        <url>http://xxxxxxxx/{z}/{x}/{y}.png</url>
    </XYZImage>
</map>

**Comment by Rendtime** [comment]
`<map name="OpenStreetMap Projected Map">

    <options>
        <type>projected</type>
        <terrain color="#ffffff00"/>
    </options>
    <XYZImage name="osm_mapnik">
        <url>http://xxx/{z}/{x}/{y}.png</url>
        <profile>spherical-mercator</profile>
        <cache_policy usage="none"/>
    </XYZImage>
</map>`

**Comment by gwaldron** [comment]
Try setting the blending property like so:
```xml
<terrain color="#ffffff00" blending="false"/>
```

**Comment by Rendtime** [comment]
Thanks, it works perfectly
