### ISSUE TITLE
OpenGL errors when running osgearth_windows.exe application

### ISSUE THREAD

**Issue by gwaldron** [gwaldron/osgearth#1817]
### Discussed in https://github.com/gwaldron/osgearth/discussions/1816

<div type='discussions-op-text'>

<sup>Originally posted by **keince** October  4, 2021</sup>
When I run the osgearth_windows.exe application in the osgEarth build, I'm seeing the following OpenGL errors when I create and delete Views...

Warning: detected OpenGL error 'invalid operation' at start of State::apply()
Warning: detected OpenGL error 'invalid operation' after applying GLMode 0xde1
Warning: detected OpenGL error 'invalid operation' after applying attribute Texture2D 0000021A6978AC00
Warning: detected OpenGL error 'invalid operation' after applying GLMode 0xb10
Warning: detected OpenGL error 'invalid operation' after applying GLMode 0xb24
Warning: detected OpenGL error 'invalid operation' after applying GLMode 0xb50
Warning: detected OpenGL error 'invalid operation' after applying GLMode 0xb71
Warning: detected OpenGL error 'invalid operation' after applying GLMode 0x4000
Warning: detected OpenGL error 'invalid operation' after applying attribute MaterialGL3 0000021A68438C50
Warning: detected OpenGL error 'invalid operation' after applying attribute Point 0000021A68C10D10
Warning: detected OpenGL error 'invalid operation' after applying attribute LineWidth 0000021A6871BD90
Warning: detected OpenGL error 'invalid operation' after applying attribute LineStipple 0000021A6871CB10
Warning: detected OpenGL error 'invalid operation' after applying attribute LightModel 0000021A68C10090
Warning: detected OpenGL error 'invalid operation' after applying attribute BlendFunc 0000021A6871BBE0
Warning: detected OpenGL error 'invalid operation' after applying attribute ColorMask 0000021A6871C7B0
Warning: detected OpenGL error 'invalid operation' after applying attribute Viewport 0000021A68C11850
Warning: detected OpenGL error 'invalid operation' after applying attribute VirtualProgram 0000021A68099800
Warning: detected OpenGL error 'invalid operation' at end of State::apply()
Warning: detected OpenGL error 'invalid operation' at end of SceneView::draw()

Is there something I can do to alleviate these errors? I bring this up because we're seeing the same errors in our osgEarth application in multiwindow mode using CompositeViewer when we create/delete windows.

We're using osgEarth 3.1 on Windows x64

Thanks for any help in advance...</div>

**Comment by jasonbeverage** [comment]
I just pushed some fixes to osgearth for this.  One is a bug fix for the terrain engine that was causing a crash when contexts were reused 89e3cb7fa69a44f0e4a154c43e58a6583b9aa37b.  The other is a change to osgearth_windows to set the scene data to null on the view before it is finally destroyed to prevent osg from calling releaseGLObjects with a null state.  I was seeing the same kind of gl errors that you are seeing without that change, although it wasn't crashing or anything, just spewing messages.
