### ISSUE TITLE
ImGui.cpp not included in vcpkg builds

### ISSUE THREAD

**Issue by aliaksei135** [gwaldron/osgearth#1820]
OsgEarth 3.2 from vcpkg

It seems like `ImGui.cpp` is not included in the build as the implementations inside aren't being linked:

```
error LNK2019: unresolved external symbol "public: __cdecl osgEarth::GUI::OsgImGuiHandler::OsgImGuiHandler(void)" (??0OsgImGuiHandler@GUI@osgEarth@@QEAA@XZ) referenced in function "public: __cdecl osgEarth::GUI::ApplicationGUI::ApplicationGUI(bool)" (??0ApplicationGUI@GUI@osgEarth@@QEAA@_N@Z)
error LNK2001: unresolved external symbol "public: virtual bool __cdecl osgEarth::GUI::OsgImGuiHandler::handle(class osgGA::GUIEventAdapter const &,class osgGA::GUIActionAdapter &)" (?handle@OsgImGuiHandler@GUI@osgEarth@@UEAA_NAEBVGUIEventAdapter@osgGA@@AEAVGUIActionAdapter@5@@Z)
error LNK2019: unresolved external symbol "class osg::Node * __cdecl osgEarth::GUI::getSelectedNode(void)" (?getSelectedNode@GUI@osgEarth@@YAPEAVNode@osg@@XZ) referenced in function "public: virtual void __cdecl osgEarth::GUI::SceneGraphGUI::SceneHierarchyVisitor::apply(class osg::Group &)" (?apply@SceneHierarchyVisitor@SceneGraphGUI@GUI@osgEarth@@UEAAXAEAVGroup@osg@@@Z)
error LNK2019: unresolved external symbol "class std::vector<class osg::ref_ptr<class osg::Node>,class std::allocator<class osg::ref_ptr<class osg::Node> > > const & __cdecl osgEarth::GUI::getSelectedNodePath(void)" (?getSelectedNodePath@GUI@osgEarth@@YAAEBV?$vector@V?$ref_ptr@VNode@osg@@@osg@@V?$allocator@V?$ref_ptr@VNode@osg@@@osg@@@std@@@std@@XZ) referenced in function "public: bool __cdecl osgEarth::GUI::SceneGraphGUI::SceneHierarchyVisitor::isInSelectedNodePath(class osg::Node *)" (?isInSelectedNodePath@SceneHierarchyVisitor@SceneGraphGUI@GUI@osgEarth@@QEAA_NPEAVNode@osg@@@Z)
error LNK2019: unresolved external symbol "void __cdecl osgEarth::GUI::setSelectedNodePath(class std::vector<class osg::Node *,class std::allocator<class osg::Node *> > const &)" (?setSelectedNodePath@GUI@osgEarth@@YAXAEBV?$vector@PEAVNode@osg@@V?$allocator@PEAVNode@osg@@@std@@@std@@@Z) referenced in function "public: virtual void __cdecl osgEarth::GUI::SceneGraphGUI::SceneHierarchyVisitor::apply(class osg::Group &)" (?apply@SceneHierarchyVisitor@SceneGraphGUI@GUI@osgEarth@@UEAAXAEAVGroup@osg@@@Z)
fatal error LNK1120: 5 unresolved externals
```

**Comment by plevy** [comment]
I am not sure what is happening, do you see it in here: osgearth\src\third_party\imgui ?

Are you simply using vcpkg install osgearth:x64-windows or building osgearth and just using vcpkg dependencies?  

Which platform are you using?

Thank you

**Comment by coderc264** [comment]
Hello, i have a similiar problem:

on file "ImGui" (<VCPKG install dir>/installed\x64-windows\include\osgEarth\ImGui) i have a compiler error "C2653" on this row: " ImGui::Image((void*)(intptr_t)textureObject->_id, ImVec2(w, h), ImVec2(0, flip ? 0 : 1), ImVec2(1, flip ? 1 : 0), ImVec4(1, 1, 1, 1), ImVec4(1, 1, 0, 1));"

there is a workaround to build?

**Comment by plevy** [comment]
vcpkg build downloads the imgui source so perhaps that failed.  Are you installing with the "tools" option?  
vcpkg install osgearth[tools]:x64-windows?

**Comment by coderc264** [comment]
i ran these commands:

./vcpkg install osg:x64-windows
./vcpkg install osgearth:x64-windows

so without the [tools] option

**Comment by coderc264** [comment]
Hello after the 3.4 version the problem it's still present, and it's worse because the workaround of include in my project a version of imgui don't work anymore

**Comment by plevy** [comment]
What do mean by doesn't work? Doesn't build or your application doesn't work?  

vcpkg has always been a convenience rather than a dependency.  If you would like to use 3rd party packages, you can go that route by manually setting paths in cmake.  That is how we started and Openscenegraph had 3rd party binary packages for dependencies maintained by volunteers.  vcpkg is more convenient than waiting for someone else to update their binary packages.  On linux, it is easier to use packages from the repos than vcpkg.

**Comment by coderc264** [comment]
It's a libker error, i need to include the osgearth::Imagui code in my application to compile it without linker errors
