### ISSUE TITLE
New Proj errors

### ISSUE THREAD

**Issue by plevy** [gwaldron/osgearth#1876]
ERROR 1: PROJ: webmerc: Invalid latitude
ERROR 1: Invalid coordinate
ERROR 1: PROJ: webmerc: Invalid latitude
ERROR 1: Invalid coordinate

when running osgearth_viewer arcgisonline.earth.
Probably related to an update to proj or jpeg lib
https://www.mail-archive.com/gdal-dev@lists.osgeo.org/msg36060.html

Still works, just throws lots of messages to the console

**Comment by gwaldron** [comment]
CNR
