### ISSUE TITLE
macosx 10.15:osgEarth 3.2+osg3.6.5 Shader problem

### ISSUE THREAD

**Issue by tangxiaodao** [gwaldron/osgearth#1879]
Complier:osgEarth3.2 latest + osg3.6.5,no Errors.
Run Examples:glsl ver 330 not support.
Debug:osgEarth version detected openGL version:2.1,but GLView detected openGL version:4.1.
from osgEarth->Capabilities.cpp:
![$0FSWA8QKK`LEYK6ZO~_TGR](https://user-images.githubusercontent.com/12289997/143394463-9865d459-5f76-4a26-8abe-89fc8e86b37f.jpg)
From GLView tool:
![442$2I1AL$WMDJE44YWZQ9T](https://user-images.githubusercontent.com/12289997/143394254-d1cc1a10-52c9-4baa-9886-68580731de85.jpg)

Test With XCode:add Glew && Glfw3,detected openGL :4.1.
![K0OG@HIYV}655$6R@L8H6E9](https://user-images.githubusercontent.com/12289997/143394302-8771991d-4ef8-4a68-82c6-028695673245.png)

**Comment by remoe** [comment]
How do you build OpenSceneGraph? Which CMake settings do you have enabled? No compile errors does not mean it works :)

**Comment by tangxiaodao** [comment]
@remoe I have set osg GL1\2\3 Avaliable checked.
What else do I need to pay attention to？

![Q000006](https://user-images.githubusercontent.com/12289997/143536643-5084907b-6b66-403c-80f1-ef82020ed77f.png)

**Comment by remoe** [comment]
Why you need GL1 and GL2? Try only the following:

-DOSG_WINDOWING_SYSTEM=Cocoa
-DOPENGL_PROFILE=GLCORE

**Comment by tangxiaodao** [comment]
@remoe thx.I'll test it.

**Comment by remoe** [comment]
When this issue is solved you can close it?
