### ISSUE TITLE
Plugins compile errors:osgEarth-master=>GLTFReader,B3DMReader,Lerc

### ISSUE THREAD

**Issue by tangxiaodao** [gwaldron/osgearth#1880]
1.GLTFReader,B3DMReader:not exsits tinygltf::options.
2.Lerc:not match functions:lerc_decode,lerc_encode,lerc_computeCompressedSize.

**Comment by remoe** [comment]
Which version of osgEarth, platform, compiler and compile settings?

**Comment by tangxiaodao** [comment]
Version:osgEarth-master latest version && osg3.6.5
Platform:MacOS Monterey 12.0.1.
Compile:Build osgEarth for GLCORE from http://docs.osgearth.org/en/latest/build.html

**Comment by tangxiaodao** [comment]
and another issue at https://github.com/gwaldron/osgearth/issues/1703 for Globe ,the same above settings.

**Comment by remoe** [comment]
MacOS compile is not official supported. One can look at https://github.com/gwaldron/osgearth/blob/master/.github/workflows/macos.yml . This configuration compiles. Or you can try to make a PR to fix it?

**Comment by tangxiaodao** [comment]
Thank you, I have fixed it locally, but I can't push to rep. Sorry, what does PR mean?

**Comment by remoe** [comment]
I mean a pull request on github ( https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/about-pull-requests )
