### ISSUE TITLE
nationalmap.earth higher LODs not working

### ISSUE THREAD

**Issue by plevy** [gwaldron/osgearth#1883]
Maybe the url has changed..don't think it is an osgEarth problem
ERROR 4: `/vsicurl/https://prd-tnm.s3.amazonaws.com/StagedProducts/Elevation/13/TIFF/n38w123/USGS_13_n38w123.tif' does not exist in the file system, and is not recognized as a supported dataset name.
ERROR 4: `/vsicurl/https://prd-tnm.s3.amazonaws.com/StagedProducts/Elevation/13/TIFF/n38w123/USGS_13_n38w123.tif' does not exist in the file system, and is not recognized as a supported dataset name.

**Comment by gwaldron** [comment]
works for me :)

**Comment by plevy** [comment]
yes, local change was the problem
