### ISSUE TITLE
osgearth_sequencecontrol wms-t_nexrad_animated.earth no sequence

### ISSUE THREAD

**Issue by plevy** [gwaldron/osgearth#1886]
Finds the 8 times
[osgEarth]  [TileLayer] Layer "nexrad45min" [srs=WGS84, min=-180,-90 max=180,90 ar=2:1 vdatum=geodetic] [no cache]
[osgEarth]  [WMS] WMS-T: found 8 times.

but 
[osgEarth]* osgearth_SEQUENCECONTROL.exe: Your earth file does not contain any sequenced layers...bye!

**Comment by gwaldron** [comment]
SequenceControls is obselete and no longer works. The new approach is to query Layer::getDateTimeExtent() and then to set a time on the viewer. There's no example for this yet but we should add one to osgearth_imgui.cpp.
