### ISSUE TITLE
how to use overlaynode on this osgearth 2.10.0?

### ISSUE THREAD

**Issue by mirro187** [gwaldron/osgearth#1890]

**Comment by mirro187** [comment]
How do you get CoordinateSystemNode?  

osgSim::OverlayNode::OverlayTechnique technique
       = osgSim::OverlayNode::OBJECT_DEPENDENT_WITH_ORTHOGRAPHIC_OVERLAY;
osgSim::OverlayNode* overlayNode = new osgSim::OverlayNode(technique);
overlayNode->getOrCreateStateSet()->setTextureAttribute(1, new osg::TexEnv(osg::TexEnv::ADD));
overlayNode->setOverlaySubgraph(geode);
overlayNode->setContinuousUpdate(true);
overlayNode->setOverlayTextureSizeHint(1024);
overlayNode->setOverlayTextureUnit(1);

// insert the OverlayNode between the coordinate system node and its children.
for(unsigned int i=0; i<root->getNumChildren(); ++i)
{
        overlayNode->addChild( root->getChild(i) );
}
root->removeChildren(0, root->getNumChildren());
root->addChild(overlayNode);

**Comment by gwaldron** [comment]
I do not understand your question. Is this related to https://github.com/gwaldron/osgearth/discussions/1888 ?

**Comment by mirro187** [comment]
> How do you get CoordinateSystemNode?



> I do not understand your question. Is this related to #1888 ?

Is this the right way to get osg::CoordinateSystemNode on osgearth 2.10.0 for osgSim::OverlayNode function?

osg::ref_ptr<MapNode> mapNode;
const SpatialReference* geoSRS = _mapNode->getMapSRS()->getGeograhicsSRS();
osg::CoordinateSystemNode* pCoord = geoSRS->createCoordinateSystemNode();

**Comment by gwaldron** [comment]
osgSim::OverlayNode does not work with osgEarth. Try using osgEarth::ImageOverlay to project an image, or DrapeableNode for arbitrary geometry.
