### ISSUE TITLE
Texture Coordinates broken on splat

### ISSUE THREAD

**Issue by rmk177** [gwaldron/osgearth#1910]
Good day!
I pulled today master branch and have got no texture coordinates on splat layers. Now It looks like shaded terrain.
Here is Boston area with ESA_globcover
[https://drive.google.com/file/d/1r9Co10O-otUl2pLQ6thfsKuuFZHaNjiI/view?usp=sharing](url)

**Comment by rmk177** [comment]
Good day! I tested master today and under --gl4 option It doesn't show at all. Under gl3 path the same situation. Maybe there is and example how make splatting under osgEarthProcedural? Sorry for noob question, but I can't make it.

**Comment by gwaldron** [comment]
The procedural nodekit is very much still a work in progress. We have not made any test datasets available yet. If and when this happens we'll include the information in the docs.
