### ISSUE TITLE
Why does the  osg::camera frame buffertexture show black on osgEarth::Annotation::ImageOverlay?

### ISSUE THREAD

**Issue by mirro187** [gwaldron/osgearth#1912]
env is osg3.6.4&osgearth 2.10.0.

`
#include <osgViewer/Viewer>
#include <osgDB/FileNameUtils>
#include <osgDB/ReadFile>
#include <osgUtil/Optimizer>
#include <osg/PositionAttitudeTransform>
#include <osg/Switch>
#include <osg/Types>
#include <osgText/Text>
#include <osgViewer/Viewer>
#include <osgViewer/CompositeViewer>
#include <osgViewer/ViewerEventHandlers>
#include <osgGA/StateSetManipulator>
#include <osgGA/TrackballManipulator>
#include <osgGA/Device>
using namespace osg;

#include <osgEarthUtil/ExampleResources>
#include <osgEarthUtil/EarthManipulator>
#include <osgEarthUtil/Controls>
#include <osgEarth/NodeUtils>
#include <osgEarth/GeoTransform>
#include <osgEarth/ModelLayer>
#include <osgEarth/Map>
#include <osgEarth/MapNode>
#include <osgEarth/ImageLayer>
#include <osgEarth/ElevationLayer>
#include <osgEarthAnnotation/EllipseNode>
#include <osgEarthAnnotation/PlaceNode>
#include <osgEarthAnnotation/LabelNode>
#include <osgEarthAnnotation/LocalGeometryNode>
#include <osgEarthAnnotation/FeatureNode>
#include <osgEarthUtil/AutoClipPlaneHandler>
#include <osgEarthUtil/Sky>
#include <osgEarthDrivers/sky_simple/SimpleSkyOptions>
#include <osgEarth/Registry>
#include <osgEarthDrivers/gdal/GDALOptions>
#include <osgEarthUtil/EarthManipulator>
#include <osgEarthDrivers/tms/TMSOptions>
#include <osgEarthDrivers/gdal/GDALOptions>
#include <osgEarthDrivers/model_feature_geom/FeatureGeomModelOptions>
#include <osgEarthDrivers/feature_ogr/OGRFeatureOptions>
#include <osgEarthAnnotation/ImageOverlay>
using namespace osgEarth;
using namespace osgEarth::Drivers;
using namespace osgEarth::Util;
using namespace osgEarth::Features;
using namespace osgEarth::Util::Controls;

// class to handle events with a pick
class PickHandler : public osgGA::GUIEventHandler {
public:

	PickHandler() {}
	~PickHandler() {}
	//
	bool handle(const osgGA::GUIEventAdapter& ea, osgGA::GUIActionAdapter& aa)
	{
		switch (ea.getEventType())
		{
		case(osgGA::GUIEventAdapter::KEYDOWN):
		{
			if (ea.getKey() == 229) //'c'
			{
				osgViewer::View* view = dynamic_cast<osgViewer::View*>(&aa);
				if (view)
				{
					osgEarth::Util::EarthManipulator* pEarthManipulator = dynamic_cast<osgEarth::Util::EarthManipulator*>(view->getCameraManipulator());
					if (pEarthManipulator)
					{
						pEarthManipulator->setViewpoint(osgEarth::Viewpoint("", 116.54065842999999, 36.661912309999998, 67.614429810000004, 0, -90, 800), 0.5);
					}
				}
			}
			return false;
		}
		default:
			return false;
		}
	}
};

void setGaussianBlurShader(osg::ref_ptr<osg::StateSet> outStateSet, osg::ref_ptr<osg::Image> hotspot)
{
	osg::Texture2D * texture1 = new osg::Texture2D;
	texture1->setDataVariance(osg::Object::DYNAMIC); // protect from being optimized away as static state.												
	texture1->setTextureSize(hotspot->s(), hotspot->t());
	texture1->setFilter(osg::Texture2D::MIN_FILTER, osg::Texture::LINEAR_MIPMAP_LINEAR);
	texture1->setFilter(osg::Texture2D::MAG_FILTER, osg::Texture::LINEAR);
	texture1->setWrap(osg::Texture2D::WRAP_S, osg::Texture2D::REPEAT);
	texture1->setWrap(osg::Texture2D::WRAP_T, osg::Texture2D::REPEAT);
	texture1->setResizeNonPowerOfTwoHint(true);
	texture1->setImage(hotspot);
	outStateSet->setTextureAttributeAndModes(0, texture1, osg::StateAttribute::ON);
}

void createHudGeo(osg::ref_ptr<osg::Geometry> geom, const Vec3& corner, const Vec3& widthVec, const Vec3& heightVec, float l = 0, float b = 0, float r = 1, float t = 1)
{
	if (geom.valid())
	{
		Vec3Array* coords = new Vec3Array(4);
		(*coords)[0] = corner + heightVec;
		(*coords)[1] = corner;
		(*coords)[2] = corner + widthVec;
		(*coords)[3] = corner + widthVec + heightVec;
		geom->setVertexArray(coords);

		Vec2Array* tcoords = new Vec2Array(4);
		(*tcoords)[0].set(l, t);
		(*tcoords)[1].set(l, b);
		(*tcoords)[2].set(r, b);
		(*tcoords)[3].set(r, t);
		geom->setTexCoordArray(0, tcoords);

		osg::Vec3Array* normals = new osg::Vec3Array(1);
		(*normals)[0] = widthVec^heightVec;
		(*normals)[0].normalize();
		geom->setNormalArray(normals, osg::Array::BIND_OVERALL);

		DrawElementsUByte* elems = new DrawElementsUByte(PrimitiveSet::TRIANGLES);
		elems->push_back(0);
		elems->push_back(1);
		elems->push_back(2);

		elems->push_back(2);
		elems->push_back(3);
		elems->push_back(0);
		geom->addPrimitiveSet(elems);
	}
}

osg::ref_ptr<osg::Geode> genGaussianBlur(const std::vector<osg::Vec3d>& drawPts, osg::ref_ptr<osg::Image> pSrcImage)
{
	osg::ref_ptr<osg::Geode> quad_geode = new osg::Geode;
	if (drawPts.size() == 4)
	{
		int imageWidth  = osg::absolute(drawPts.at(2).x() - drawPts.at(0).x());
		int imageHeight = osg::absolute(drawPts.at(2).y() - drawPts.at(0).y());
		osg::Vec3 center(-imageWidth, -imageHeight, 0), widthVec(imageWidth * 2, 0.0f, 0.0f), heightVec(0.0f, imageHeight * 2, 0.0f);
		float l = 0, b = 0, r = 1, t = 1;
		//
		osg::ref_ptr<osg::Geometry> geom = new osg::Geometry();
		createHudGeo(geom, center, widthVec, heightVec);
		quad_geode->addDrawable(geom);
		//
		osg::StateSet *stateSet = quad_geode->getOrCreateStateSet();
		stateSet->setMode(GL_BLEND, osg::StateAttribute::ON);
		stateSet->setRenderingHint(osg::StateSet::TRANSPARENT_BIN);
		//
		stateSet->setMode(GL_LIGHTING, osg::StateAttribute::OFF);
		stateSet->setMode(GL_DEPTH_TEST, osg::StateAttribute::OFF);
		//
		setGaussianBlurShader(stateSet, pSrcImage);
	}
	return quad_geode;
}

osg::Vec3d WorldConvertLonLatCoord(osg::ref_ptr<osgEarth::Map> pMap, const osg::Vec3d& worldCoor)
{
	osg::Vec3d lonlat(0, 0, 0);
	const osgEarth::SpatialReference* latLong = pMap->getSRS()->getGeographicSRS();
	latLong->transformFromWorld(worldCoor, lonlat);
	return lonlat;
}
//
int main(int argc, char** argv)
{
	// create a viewer:
	osg::ref_ptr<osgViewer::Viewer> pView = new osgViewer::Viewer;
	if (pView.valid())
	{
		// Tell the database pager to not modify the unref settings
		pView->getDatabasePager()->setUnrefImageDataAfterApplyPolicy(true, false);

		// install our default manipulator (do this before calling load)
		pView->setCameraManipulator(new osgEarth::Util::EarthManipulator());
		pView->addEventHandler(new PickHandler());
		//
		//pView->getCamera()->setNearFarRatio(0.00002);
		pView->getCamera()->setSmallFeatureCullingPixelSize(-1.0f);
		//
		osg::ref_ptr<osgEarth::Map> map = new osgEarth::Map();
		{
			osgEarth::Drivers::TMSOptions layOpt;
			layOpt.url() = osgEarth::URI("E:/workplace/platform-standard-5007/trunk/master/X64/bin/Debug/data/BasicImage/wenhualou/tms.xml");

			osg::ref_ptr<osgEarth::ImageLayer> image = new osgEarth::ImageLayer("tms", layOpt);

			map->addLayer(image);
		}
		//
		{
			osgEarth::Drivers::TMSOptions tms;
			tms.url() = osgEarth::URI("E:/workplace/platform-standard-5007/trunk/master/X64/bin/Debug/data/BasicImage/Dem2/tms.xml");
			osgEarth::ElevationLayerOptions elvOpt("", tms);
			//
			osg::ref_ptr<osgEarth::ElevationLayer> elevationLayer = new osgEarth::ElevationLayer(elvOpt);

			map->addLayer(elevationLayer);
		}
		//
		osg::Group* root = new osg::Group();
		//make the map scene graph:
		osgEarth::MapNode* mapNode = new osgEarth::MapNode(map);
		root->addChild(mapNode);
		{
			osg::ref_ptr<osg::MatrixTransform> nodeMt = new osg::MatrixTransform;
			//
			osg::Matrixd drawMat,invertDrawMat;
			std::vector<osg::Vec3d> drawPts;
			//
			osgEarth::GeoPoint mapPoint(mapNode->getMap()->getSRS()->getGeographicSRS(), 116.54065842999999, 36.661912309999998, 67.614429810000004, ALTMODE_RELATIVE);
			//
			mapPoint.createLocalToWorld(drawMat);
			invertDrawMat = drawMat.inverse(drawMat);
			//
			drawPts.push_back(osg::Vec3d(0, 0, 0));
			drawPts.push_back(osg::Vec3d(78.020536770112813, 0, 0));
			drawPts.push_back(osg::Vec3d(78.020536770112813, 64.098223568871617, 0));
			drawPts.push_back(osg::Vec3d(0, 64.098223568871617, 0));
			//
			osg::ref_ptr<osg::Image> pSrcImage = osgDB::readRefImageFile("E:/right.jpg");
			osg::ref_ptr<osg::Geode> pGeode = genGaussianBlur(drawPts, pSrcImage);		
			//
			int imageWidth  = osg::absolute(drawPts.at(2).x() - drawPts.at(0).x());
			int imageHeight = osg::absolute(drawPts.at(2).y() - drawPts.at(0).y());
			//
			osg::ref_ptr<osg::Texture2D> texture2D = new osg::Texture2D;
			texture2D->setTextureSize(imageWidth, imageHeight);
			texture2D->setInternalFormat(GL_RGBA32F_ARB);
			texture2D->setSourceFormat(GL_RGBA);
			texture2D->setSourceType(GL_FLOAT);
			texture2D->setFilter(osg::Texture2D::MIN_FILTER, osg::Texture2D::LINEAR);
			texture2D->setFilter(osg::Texture2D::MAG_FILTER, osg::Texture2D::LINEAR);
			//
			osg::Camera* camera = new osg::Camera;
			// set up the background color and clear mask.
			{
				camera->setClearColor(osg::Vec4(0.f, 0.f, 1.f, 1.f));
				camera->setClearMask(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);
				//
				const osg::BoundingSphere& bs = pGeode->getBound();
				//
				float znear = 1.0f*bs.radius();
				float zfar  = 3.0f*bs.radius();
				// 2:1 aspect ratio as per flag geometry below.
				float projTop   = 0.25f*znear;
				float projRight = projTop * ((double)imageWidth / (double)imageHeight);
			
				znear *= 0.9f;
				zfar *= 1.1f;
			
				// set up projection.
				camera->setProjectionMatrixAsFrustum(-projRight, projRight, -projTop, projTop, znear, zfar);
				// setup view
				camera->setReferenceFrame(osg::Transform::ABSOLUTE_RF);
			
				camera->setViewMatrixAsLookAt(bs.center() - osg::Vec3(0.0f, 2.0f, 0.0f)*bs.radius(),
					bs.center(),
					osg::Vec3(0.0f, 0.0f, 1.0f));
				// set viewport
				camera->setViewport(0, 0, imageWidth, imageHeight);
			
				// set the camera to render before the main camera.
				camera->setRenderOrder(osg::Camera::POST_RENDER);
			
				camera->setRenderTargetImplementation(osg::Camera::FRAME_BUFFER_OBJECT);
			
				camera->attach(osg::Camera::COLOR_BUFFER, texture2D.get());
			
				camera->setClearColor(osg::Vec4(1.f, 1.f, 1.f, 1.f));
			
				camera->addChild(pGeode);	
				//
			}
			root->addChild(camera);
			//
			nodeMt->addChild(pGeode);
			nodeMt->setMatrix(osg::Matrixd::translate(0,250,0)*drawMat);
			root->addChild(nodeMt);
			//general Image
			osg::ref_ptr<osgEarth::Annotation::ImageOverlay> pOverlay = new osgEarth::Annotation::ImageOverlay(mapNode, texture2D->getImage());
			if (pOverlay.valid())
			{
				pOverlay->setMapNode(mapNode);
				//
				mapNode->addChild(pOverlay);
				//
				osg::Vec3d lb = WorldConvertLonLatCoord(mapNode->getMap(), drawPts.at(0)*drawMat);
				osg::Vec3d rb = WorldConvertLonLatCoord(mapNode->getMap(), drawPts.at(1)*drawMat);
				osg::Vec3d ru = WorldConvertLonLatCoord(mapNode->getMap(), drawPts.at(2)*drawMat);
				osg::Vec3d lu = WorldConvertLonLatCoord(mapNode->getMap(), drawPts.at(3)*drawMat);
			
				pOverlay->setCorners(osg::Vec2(lb.x(), lb.y()), osg::Vec2(rb.x(), rb.y()), osg::Vec2(lu.x(), lu.y()), osg::Vec2(ru.x(), ru.y()));
			}
			//
			pView->setSceneData(root);
			//
			osgEarth::Util::EarthManipulator* pEarthManipulator = dynamic_cast<osgEarth::Util::EarthManipulator*>(pView->getCameraManipulator());
			if (pEarthManipulator)
			{
				pEarthManipulator->setHomeViewpoint(osgEarth::Viewpoint("", 116.54065842999999, 36.661912309999998, 67.614429810000004, 0, -90, 800), 0.5);
			}
		}
		return pView->run();
	}
}`

**Comment by gwaldron** [comment]
Sorry, but we're not able to support osgEarth 2.10 code any longer - please consider upgrading to version 3.2.
