### ISSUE TITLE
Triton ocean display defect osgEarth v3.1

### ISSUE THREAD

**Issue by quentinBdr** [gwaldron/osgearth#1920]
Hi,

I'm running osgEarth v3.1 with osg v3.6.5 and triton 4.43 (on win10 with nvidia GPU, VS2019).
I've setup the Triton resources path correctly and moved both of the provided shaders to the Triton resources path for log2depth buffer use.

But i've still got the following error :
![image](https://user-images.githubusercontent.com/15386075/148104146-6a85cce4-5df0-490b-b1d4-d760b9cc40ab.png)

Still the program goes on but the ocean does not display as expected :
![image](https://user-images.githubusercontent.com/15386075/148104293-9f869e46-86ac-4cfa-be5d-b9c01280a90c.png)
It displays roughly the same thing whether I turn HeightMap to true or false. I did not touch the Triton.config file either.

I'm using the following earth file :
```
<map name="defaultmap" type="geocentric" version="2">

  <options>
	<proxy/>
	<cache>
	  <driver>filesystem</driver>
	  <path>XXX/cache</path>
	</cache>
	<cache_policy>
	  <usage>read_write</usage>
	</cache_policy>
	
	<terrain>
	  <driver>rex</driver>
	</terrain>
  </options>

  <xi:include href="imagery/satellite_franceSW_z18.xml"/>
  
  <xi:include href="elevation/dted_france.xml"/>
  
  <Triton>
    <user>A</user>
    <license_code>A</license_code>
    <resource_path>XXX/resources/triton</resource_path>
    <use_height_map>true</use_height_map>
    <max_altitude>1000000</max_altitude>
    <mask_layer>SAT_france_SW_z18</mask_layer>
  </Triton>

</map>
```

What am I missing here ?

Thanks

**Comment by gwaldron** [comment]
Are you able to provide access to the data files so we can test it here?

(Also, ignore the shader error, that is likely a non-issue in this case.)

**Comment by quentinBdr** [comment]
Thanks for the reply.
You will be able to fetch the imagery and elevation data under that link : [https://drive.google.com/drive/folders/1NBdsHmB9Lz7KWVOPTZMH5aoqB7oER85p?usp=sharing](https://drive.google.com/drive/folders/1NBdsHmB9Lz7KWVOPTZMH5aoqB7oER85p?usp=sharing)

Though I can tell as you might have seen, it is dted1 tile format that I've transformed to a .tif with GDAL, and I'm using the GDALElevation tag in earth file for the .tif. 
```
<GDALElevation name="dted_france_elevation">
  <url>path_to/franceElevation.tif</url>
</GDALElevation>
```

Thanks for the help.
`

**Comment by quentinBdr** [comment]
Hi,

I've tried the osgearth_triton application provided in the source to give you an example without any data.
This is what I've got : 
![osgearth_triton](https://user-images.githubusercontent.com/15386075/151797333-a99beb04-aba7-4ade-a23a-8cdf44627cee.PNG)

The ocean displays correctly but as a narrow patch. When I tilt the camera, the patch gets closer or nearer, no matter where I pan the camera, the patch stays at the same coord on the screen. When the camera's pitch is 90° the ocean disapear completely.

The earth file is now minimalist ...
```
<map name="defaultmap" type="geocentric" version="2">
</map>
```

I've tried on different Nvidia GPUs and got the same result ... 

What am I doing wrong ?

Thanks

**Comment by gwaldron** [comment]
Do you have bathymetry data? The ocean only works correctly if you have elevation data for the ocean floor. The ReadyMap example elevation data (in readymap.earth) is an example.

**Comment by gwaldron** [comment]
Most likely explanation is either an incorrect cmd line, or that the custom shaders are not installed properly.

Here is the correct command line:
`osgearth_triton readymap.earth --logdepth2`

And it should look like this:
![image](https://user-images.githubusercontent.com/326618/152842188-685f1843-3e86-4f0e-b7da-de4c27ba6673.png)

As for your data, if it does not include underwater elevation (bathymetry) the ocean rendering will not work no matter what.

**Comment by quentinBdr** [comment]
Indeed I forgot the logdepth2 option. Seems to be ok now.
I was not aware bathymetry data was mandatory for ocean rendering.

Thanks a lot for the help it's all good for me now !

**Comment by FuXiii** [comment]
@quentinBdr I still had this issue.

1. Set use `--logdepth2`:
![image](https://user-images.githubusercontent.com/40132375/233027203-4b32d3c0-844d-4ce1-a390-611f665d46f6.png)

2. Add ElevationLayer:
![image](https://user-images.githubusercontent.com/40132375/233027411-a64012b4-be50-4959-a0fc-de3d1dd2e3ad.png)

3. Add TritonLayer:
![image](https://user-images.githubusercontent.com/40132375/233028241-d4b60a6d-1e92-4f92-ae0f-fd51351b25c6.png)

The result:
![image](https://user-images.githubusercontent.com/40132375/233029181-51201543-b949-4109-8648-77fc44039335.png)

**Comment by quentinBdr** [comment]
Have you installed the custom shader provided by osgearth in the triton resources ? 
From memory it is necessary for log depth 2 support.

Note : you've let your user name and licence code into your source code comment

**Comment by FuXiii** [comment]
Thanks for your note. (●'◡'●)ﾉ♥
After I changed the `user-functions.glsl` and `user-vert-functions.glsl` the ocean become:
![Ocean](https://user-images.githubusercontent.com/40132375/233264065-5a2e1cfb-ec7b-43e1-8537-c3c7c1730636.gif)

**Comment by quentinBdr** [comment]
You're welcome :v:
Well it seems you have the same thing I had shown in my original post. Are you sure your elevation layer input has bathymetry data ?

**Comment by FuXiii** [comment]
I think the major problem is the ocean become completely transparent:
![Ocean1](https://user-images.githubusercontent.com/40132375/233268916-741c8b52-f2e7-472a-a1e1-52c045452a75.gif)

**Comment by quentinBdr** [comment]
I'm afraid I can't reproduce your behavior with transparant waves.
But I can reproduce the waves pattern by removing the bathymetry data. As gwaldron mentionned, "_The ocean only works correctly if you have elevation data for the ocean floor_".

**Comment by FuXiii** [comment]
Yes, you are right. Where I can find bathymetry data? I only had the heigh map data file on the land. (◞‸◟ )

**Comment by quentinBdr** [comment]
You'll find bathymetry at https://www.gebco.net/

**Comment by FuXiii** [comment]
Thanks!
