### ISSUE TITLE
FeatureNode In scenes Incorrect display

### ISSUE THREAD

**Issue by HerryJessica** [gwaldron/osgearth#1921]
There is a set of data about 300,000 points, combine this set of data into FeatureNode(PolyGon),then add scenes Incorrect display.
Correct display
<img width="695" alt="62DF6DE63BD411273A5B1184034E7859" src="https://user-images.githubusercontent.com/44019088/148359324-60502789-186c-4b9d-910d-85447708d490.png">

but in my scenes
<img width="394" alt="2A23C65C41D7E7016BF08DB7A01F1ED7" src="https://user-images.githubusercontent.com/44019088/148359500-21f13036-ea10-4910-8f56-5eeee4acba4c.png">
 
my version osgEarth2.10 In Android opengles 3.0

 Why the line is not displayed completely？ pelease help me!!!
@gwaldron

**Comment by gwaldron** [comment]
If you provide access to the shapefile, we can test it locally.

**Comment by HerryJessica** [comment]
I provided the shapefile and also the kml
[https://github.com/HerryJessica/test/archive/refs/heads/main.zip](url)

**Comment by HerryJessica** [comment]
Version：osg 3.6  osgearth 2.10 
Platform: android use Opengles 3.0
This problem has troubled me for a long time but I still can't solve it

**Comment by gwaldron** [comment]
Sorry - did not notice this. The link is bad, can you try again?

**Comment by HerryJessica** [comment]
That's ok @gwaldron 
 https://github.com/HerryJessica/test.git

**Comment by gwaldron** [comment]
I am able to render this correctly in osgEarth 3.2 on Win64. It also might be that a newer version of GDAL or GEOS could help you. Sorry I can't be of more help - we do not have an OES build, and version 2.10 is over 3 years old now. 
![image](https://user-images.githubusercontent.com/326618/153872468-fb2a49d5-b037-409f-986f-83c633a9fd79.png)

**Comment by HerryJessica** [comment]
Thanks ！ I also tried win64 and it works, so I suspect that Opengles is not fully supported
