### ISSUE TITLE
glsl es not support Interface Blocks

### ISSUE THREAD

**Issue by hankern** [gwaldron/osgearth#1950]
It will add Interface Blocks VP_PerVertex in ShaderFactory when create mains, but glsl es not support Interface Blocks. I think it's necessary to modify ShaderFactory file to support glsl es situation.

**Comment by gwaldron** [comment]
This is correct - osgEarth does not suppor GLES at this time.

**Comment by hankern** [comment]
my sugesstion is(i have verified) :
in vert glsl
`#pragma vp_name VP Vertex Shader Main
// Vertex stage globals:
// Vertex stage outputs:
//out VP_PerVertex { 
out  float oe_layer_rangeOpacity_inout; 
out  float oe_rex_morphFactor_inout; 
out  vec2 oe_normalMapCoords_inout; 
out  vec3 oe_UpVectorView_inout; 
out  vec3 oe_normalMapBinormal_inout; 
out  vec3 vp_Normal_inout; 
out  vec4 oe_layer_texc_inout; 
out  vec4 oe_layer_texcParent_inout; 
out  vec4 oe_layer_tilec_inout; 
out  vec4 vp_Color_inout; 
out  vec4 vp_Vertex_inout; 
//} vp_out; 
// Function declarations:
void main(void) 
{ 
    vp_Vertex = gl_Vertex; 
    vp_Normal = gl_Normal; 
    vp_Color  = gl_Color; 
    oe_rexEngine_vert(vp_Vertex); 
    oe_rexEngine_morph(vp_Vertex); 
    oe_rexEngine_elevation(vp_Vertex); 
    vp_Vertex = osg_ModelViewMatrix * vp_Vertex; 
    vp_Normal = normalize(osg_NormalMatrix * vp_Normal); 
    oe_rex_elevateVertexAndSetTexCoords(vp_Vertex); 
    oe_normalMapVertex(vp_Vertex); 
    gl_Position = osg_ProjectionMatrix * vp_Vertex; 
    oe_layer_rangeOpacity_inout = oe_layer_rangeOpacity; 
    oe_rex_morphFactor_inout = oe_rex_morphFactor; 
    oe_normalMapCoords_inout = oe_normalMapCoords; 
    oe_UpVectorView_inout = oe_UpVectorView; 
    oe_normalMapBinormal_inout = oe_normalMapBinormal; 
    vp_Normal_inout = vp_Normal; 
    oe_layer_texc_inout = oe_layer_texc; 
    oe_layer_texcParent_inout = oe_layer_texcParent; 
    oe_layer_tilec_inout = oe_layer_tilec; 
    vp_Color_inout = vp_Color; 
    vp_Vertex_inout = vp_Vertex; 
} `

in frag glsl
`#pragma vp_name VP Fragment Shader Main
// Fragment output
// Fragment stage inputs:
//in VP_PerVertex { 
in  float oe_layer_rangeOpacity_inout; 
in  float oe_rex_morphFactor_inout; 
in  vec2 oe_normalMapCoords_inout; 
in  vec3 oe_UpVectorView_inout; 
in  vec3 oe_normalMapBinormal_inout; 
in  vec3 vp_Normal_inout; 
in  vec4 oe_layer_texc_inout; 
in  vec4 oe_layer_texcParent_inout; 
in  vec4 oe_layer_tilec_inout; 
in  vec4 vp_Color_inout; 
in  vec4 vp_Vertex_inout; 
//} vp_in; 
// Fragment stage globals:
// Function declarations:
void main(void) 
{ 
    oe_layer_rangeOpacity = oe_layer_rangeOpacity_inout; 
    oe_rex_morphFactor = oe_rex_morphFactor_inout; 
    oe_normalMapCoords = oe_normalMapCoords_inout; 
    oe_UpVectorView = oe_UpVectorView_inout; 
    oe_normalMapBinormal = oe_normalMapBinormal_inout; 
    vp_Normal = vp_Normal_inout; 
    oe_layer_texc = oe_layer_texc_inout; 
    oe_layer_texcParent = oe_layer_texcParent_inout; 
    oe_layer_tilec = oe_layer_tilec_inout; 
    vp_Color = vp_Color_inout; 
    vp_Vertex = vp_Vertex_inout; 
    vp_Normal = normalize(vp_Normal); 
    oe_normalMapFragment( vp_Color ); 
    oe_rexEngine_frag( vp_Color ); 
    elevation_last_frag( vp_Color ); 
    vp_FragColor = vp_Color;
}`

**Comment by gwaldron** [comment]
This will not work with multiple shader stages (like GS, TCS, TES), which is the main reason we went with interface blocks in the first place. You can refer to the `ShaderFactory.cpp` code for details.
