### ISSUE TITLE
[3.2] Colored boxes instead of text in osgearth_viewer and osgearth_toc

### ISSUE THREAD

**Issue by sibskull** [gwaldron/osgearth#1967]
After upgrade from osgearth from 2.10.2 to 3.2 there are colored boxes instead of text in osgearth_viewer and osgearth_toc. osgearch_imgui shows text correctly.
![osgEarth_toc_after_task](https://user-images.githubusercontent.com/577967/152369333-eb91f653-da82-4c85-a2ae-72334be44a9b.png)

**Comment by gwaldron** [comment]
Don't know - I cannot reproduce the issue here.
In any case the old "Controls" library that draws those is basically deprecated now in favor of ImGui, so no further development will occur on it.
