### ISSUE TITLE
Vegetation perfomance

### ISSUE THREAD

**Issue by rmk177** [gwaldron/osgearth#1971]
Good day! Because of OsgEarthSplat doesn't work in master I tried to work with new Vegetation based on bindlessNV, but have huge perfomance drop on today master.
![Screenshot_20220208_130552](https://user-images.githubusercontent.com/6746226/152985937-fc86becd-5079-4ba7-bda8-6f5a3749ab4b.png)
my biomes.xml and earth files in attachment
[work.tar.gz](https://github.com/gwaldron/osgearth/files/8023753/work.tar.gz)

**Comment by gwaldron** [comment]
It is still a work in progress.
osgEarthSplat should work on master -- please try again.
