### ISSUE TITLE
ImGui InputText Backspace and arrow keys deos not work

### ISSUE THREAD

**Issue by nebsar** [gwaldron/osgearth#1974]
While I try to delete inputtext content with backspace, it does not delete the text and also arrow keys does not work to move the input cursor. What can be the cause?
Edit: Mouse Left Button Double click is not fully functional as well with imgui. Input Handler of osg/osgearth my have interference with imgui input handler.

**Comment by gwaldron** [comment]
You posted this question in Discussions. Please don't double-post.
