### ISSUE TITLE
Tile images become fuzzy when zooming in or on a big screen

### ISSUE THREAD

**Issue by Robert-Earth** [gwaldron/osgearth#1976]
@gwaldron 
Osgearth's tile images will become fuzzy when zooming in, that's because the tile grid on screent is bigger than 256*256. Could you tell me how to keep the resolution(or to a limited range) of tile images on screen, when zooming in or on a big screen. Thank you very much.

**Comment by gwaldron** [comment]
Try the "pixel size" range mode. This will cause tiles to transition to a higher level of details based on their screen-space extent rather than their range from the camera.
```xml
<map>
    <options>
        <terrain range_mode="PIXEL_SIZE_ON_SCREEN"/>
    </options>
   ...
```

**Comment by Robert-Earth** [comment]
Thank you very much, gwaldron.  That's amazing!! Tile images are Much much clear. But that cause another problem which crash down the computer or slow the computer seriously since too many tiles needed to be downloaded at the same time. Could the multithreads and cache   make the speed fast?

**Comment by Robert-Earth** [comment]
@gwaldron 
Thank you very much for guiding me alot. Tile images look very clear, but the imagery refreshing speed really need to be improved. The multithread and cache  can improve the performance, but it still looks lag. Is there any other methods to improve the tile refreshing?
Thanks again
