### ISSUE TITLE
Outline of the Circle Does not seem to be rendered When Earth File is Loaded Programmatically

### ISSUE THREAD

**Issue by nebsar** [gwaldron/osgearth#2008]
I tried this a lot even on esgearth_annotation example. But lines or outlines of the shapes are not rendered on earth, when the earth file is loaded programmatically. But when arguments are used, they are rendered.

**Comment by gwaldron** [comment]
You'll need to provide more information (what exactly did you try and what are you expecting?)

**Comment by nebsar** [comment]
Hi Glenn,

I solved to problem by adding the following line:
osgEarth::GLUtils::setGlobalDefaults(getCamera()->getOrCreateStateSet());

Sorry for disturbing.
