### ISSUE TITLE
packager: bad seams when tiling multiple source files

### ISSUE THREAD

**Issue by gwaldron** [gwaldron/osgearth#201]
Reference:
http://forum.osgearth.org/problems-of-edges-with-adjacent-terrain-DEM-td7579093.html

Also may be the same issue:
http://forum.osgearth.org/help-about-the-gap-when-zoom-in-td7388499.html#a7579128

**Comment by remoe** [comment]
I still see this issue with a version around 10/14/2014

**Comment by olavobelloc** [comment]
Hello everybody,

I have just tracked this bug down to the GDAL VRT rasterizer (v1.11.2, latest version at the time of this writing). After fixing their rasterizer, the black lines just disappeared. I have submitted a bug report on their bug tracker:

http://trac.osgeo.org/gdal/ticket/5874

If you are in a hurry, like me, you can just apply the patch your own.

Olavo Belloc.

**Comment by jasonbeverage** [comment]
Wow, glad to finally have some resolution on that issue.  Remo can you test
your dataset against this and see if it works?

**Comment by remoe** [comment]
@jasonbeverage sorry, we have solved this with two separate files ... but i didn't know the details.

**Comment by jasonbeverage** [comment]
Works for me.  I'm going to close this issue finally then :)
