### ISSUE TITLE
(issue #1783 revisit) ObjectID picker exhibits sloppy behavior on annotations with large display windows

### ISSUE THREAD

**Issue by keince** [gwaldron/osgearth#2023]
I know there was an attempt to fix this in issue #1783 but trying out the fix that was supposed to remedy the problem, I'm still seeing sloppiness in the pick accuracy with my buffer set to the minimum setBuffer(1) and using a large (1920x1200 or larger) window.

To me, it appears that there is an undersampling issue going on with the small 256x256 off screen memory that is used for the pick operation when using it on an actual display window that is much larger. TrackNodes and PlaceNodes are still quite sloppy and unacceptable for our application that demands precise picking.

To collaborate my theory, I reduced the size of my display window to more closely match the size of the viewport the pick camera is using. As a result, the pick operation gets more accurate. If I manually increase the size of the _rttSize variable to something that matches the display window, the pick accuracy improves very well for TrackNodes but is still sloppy for PlaceNodes. Not sure what to make of the latter.

I'm hoping this feedback will result in a resolution (no pun intended) to this picking accuracy problem...

Shayne

**Comment by gwaldron** [comment]
Hopefully you can use #2023 to address this by increasing the picker camera size.
