### ISSUE TITLE
VRT on mbtiles is not loaded using GDALImage

### ISSUE THREAD

**Issue by MCA4213** [gwaldron/osgearth#2030]
Hi, I created an application that load differents image formats that I load them as a vrt to play on bands order, but recently my application is not working for vrt created on an mbtiles file.
Here are some tests that  I did:

1) Using a world image (example/Global_work)
* Loading the mbtiles directly using MBtilesImage: work.
* Loading the mbtiles using GDALImage: work.
* Loading the vrt of the mbtiles using GDALImage: work.

2) Using a north africa image (example/NorthAfrica_notWorking)
* Loading the mbtiles directly using MBtilesImage: work.
* Loading the mbtiles using GDALImage: NOT WORKING.
* Loading the vrt of the mbtiles using GDALImage: NOT WORKING.

Earth files and files that I use them in my tests:  [Examples](https://www.mediafire.com/file/acf844wr56bv8tv/Examples.rar/file) or in attached file [Examples.zip](https://github.com/gwaldron/osgearth/files/8365553/Examples.zip)

The application is still working when the mbtiles cover the hole world (example 1), but nothing is loaded using the GDAL driver when the image is smaller, except the layer extent (I can zoom to layer, but no tiles are loaded).

I need to load my files using the GDAL driver as I was doing before to use my vrt (cannot find when it has been broken).
Any explnantions, please?

**Comment by jasonbeverage** [comment]
Thanks for the test data, it helps tremendously when we can reproduce a bug quickly.  The issue was down to a bug in the new data extents rtree index I added.  I pushed a fix for it in the master and it should work now
