### ISSUE TITLE
Strange transformation in FeatureModel layers with gltf models

### ISSUE THREAD

**Issue by RhythmOfTension** [gwaldron/osgearth#2031]
Seems like there is strange transformation applied to nodes, builded from model symbols containing gltf models inside FeatureModel layers.

![image](https://user-images.githubusercontent.com/80849292/160474670-385d5d92-4580-4c1f-8b8d-ca2b84edc906.png)

To replicate that, you can use boston.earth test example and change tree4.osgb to some gltf model (even converted from tree4.osgb via osgconv).

Maybe `osg::MatrixTransform` causing this? OBJ plugin have something similar with axis rotation, but it's not using MatrixTransform for it.
https://github.com/gwaldron/osgearth/blob/d9afdc35100394509335c10c1ece10059b1aa432/src/osgEarthDrivers/gltf/GLTFReader.h#L278

Also, this model looks fine if i load it with `readNodeFile` and place it on scene.

**Comment by gwaldron** [comment]
Can you try running with the command line option `--osg-options gltfZUp` and see if it works?

**Comment by RhythmOfTension** [comment]
I tried this too, it's look like this:
![image](https://user-images.githubusercontent.com/80849292/161596402-95ef818e-37e4-44ba-9f68-ba521a864239.png)

So it's now only local transformation problem, instead of transformation of whole group.
This model in blender (looks like it's zUp):
![image](https://user-images.githubusercontent.com/80849292/161598091-1837776d-5fee-4126-a184-383edc072397.png)

Also, this is how tree4.glb converted from tree4.osgb (via osgconv -e gltf tree4.osgb tree4.glb) looks like in blender:
![image](https://user-images.githubusercontent.com/80849292/161598812-07d2fafc-c232-4613-b828-00f171cb82e4.png)

And in map:
![image](https://user-images.githubusercontent.com/80849292/161599176-45e7ab72-4c21-46ad-9c30-8051eebd35b1.png)

With gltfZUp:
![image](https://user-images.githubusercontent.com/80849292/161599265-949775c5-9bde-4ab3-867b-1033ebc369c7.png)

**Comment by gwaldron** [comment]
Try the latest master, and add this to your FeatureModel layer:
`<instancing>false</instancing>`
There is some issue with top-level matrices and the instance manager. We'll look at this in the future but hopefully this is a workaround for now.

**Comment by RhythmOfTension** [comment]
Thanks, `instancing = false` did the trick.
