### ISSUE TITLE
BUG fatal error C1083: 无法打开包括文件: “glyphs.pb.h”: No such file or directory

### ISSUE THREAD

**Issue by SpaceView** [gwaldron/osgearth#2034]
I'm trying to compile osgearth following this link, with VS2019, 
http://docs.osgearth.org/en/latest/build.html#building-with-vcpkg
and I got the folliwng errors when compiling core project osgearth, 
已启动生成…
1>------ 已启动生成: 项目: osgEarth, 配置: RelWithDebInfo x64 ------
1>MapboxGLImageLayer.cpp
1>MapboxGLGlyphManager.cpp
1>D:\osgprj\osgearth\src\osgEarth\MapboxGLGlyphManager.cpp(25,10): fatal error C1083: 无法打开包括文件: “glyphs.pb.h”: No such file or directory
1>D:\osgprj\osgearth\src\osgEarth\MapboxGLImageLayer.cpp(258,27): error C2065: “MVTFeatureSource”: 未声明的标识符
1>D:\osgprj\osgearth\src\osgEarth\MapboxGLImageLayer.cpp(258,18): error C2923: “osg::ref_ptr”: 对于参数“T”，“MVTFeatureSource”不是有效的 模板 类型变量
1>D:\osgprj\osgearth\src\osgEarth\MapboxGLImageLayer.cpp(258): message : 参见“MVTFeatureSource”的声明
1>D:\osgprj\osgearth\src\osgEarth\MapboxGLImageLayer.cpp(258,66): error C2061: 语法错误: 标识符“MVTFeatureSource”
1>D:\osgprj\osgearth\src\osgEarth\MapboxGLImageLayer.cpp(258,60): error C2512: “osg::ref_ptr”: 没有合适的默认构造函数可用
1>D:\vs3D\vcpkg\installed\x64-windows\include\osg/ref_ptr(32,1): message : 参见“osg::ref_ptr”的声明 (编译源文件 D:\osgprj\osgearth\src\osgEarth\MapboxGLImageLayer.cpp)
1>D:\osgprj\osgearth\src\osgEarth\MapboxGLImageLayer.cpp(259,26): error C2678: 二进制“->”: 没有找到接受“osg::ref_ptr”类型的左操作数的运算符(或没有可接受的转换)
1>D:\vs3D\vcpkg\installed\x64-windows\include\osg/ref_ptr(106,12): message : 可能是“T *osg::ref_ptr<T>::operator ->(void) const” (编译源文件 D:\osgprj\osgearth\src\osgEarth\MapboxGLImageLayer.cpp)
1>D:\osgprj\osgearth\src\osgEarth\MapboxGLImageLayer.cpp(259,26): message : 尝试匹配参数列表“(osg::ref_ptr)”时
1>D:\osgprj\osgearth\src\osgEarth\MapboxGLImageLayer.cpp(259,28): error C2039: "setReadOptions": 不是 "osg::ref_ptr" 的成员
1>D:\vs3D\vcpkg\installed\x64-windows\include\osg/ref_ptr(32): message : 参见“osg::ref_ptr”的声明
1>D:\osgprj\osgearth\src\osgEarth\MapboxGLImageLayer.cpp(260,26): error C2678: 二进制“->”: 没有找到接受“osg::ref_ptr”类型的左操作数的运算符(或没有可接受的转换)
1>D:\vs3D\vcpkg\installed\x64-windows\include\osg/ref_ptr(106,12): message : 可能是“T *osg::ref_ptr<T>::operator ->(void) const” (编译源文件 D:\osgprj\osgearth\src\osgEarth\MapboxGLImageLayer.cpp)
1>D:\osgprj\osgearth\src\osgEarth\MapboxGLImageLayer.cpp(260,26): message : 尝试匹配参数列表“(osg::ref_ptr)”时
1>D:\osgprj\osgearth\src\osgEarth\MapboxGLImageLayer.cpp(260,28): error C2039: "setURL": 不是 "osg::ref_ptr" 的成员
1>D:\vs3D\vcpkg\installed\x64-windows\include\osg/ref_ptr(32): message : 参见“osg::ref_ptr”的声明
1>D:\osgprj\osgearth\src\osgEarth\MapboxGLImageLayer.cpp(261,26): error C2678: 二进制“->”: 没有找到接受“osg::ref_ptr”类型的左操作数的运算符(或没有可接受的转换)
1>D:\vs3D\vcpkg\installed\x64-windows\include\osg/ref_ptr(106,12): message : 可能是“T *osg::ref_ptr<T>::operator ->(void) const” (编译源文件 D:\osgprj\osgearth\src\osgEarth\MapboxGLImageLayer.cpp)
1>D:\osgprj\osgearth\src\osgEarth\MapboxGLImageLayer.cpp(261,26): message : 尝试匹配参数列表“(osg::ref_ptr)”时
1>D:\osgprj\osgearth\src\osgEarth\MapboxGLImageLayer.cpp(261,28): error C2039: "open": 不是 "osg::ref_ptr" 的成员
1>D:\vs3D\vcpkg\installed\x64-windows\include\osg/ref_ptr(32): message : 参见“osg::ref_ptr”的声明
1>D:\osgprj\osgearth\src\osgEarth\MapboxGLImageLayer.cpp(262,48): error C2662: “T *osg::ref_ptr<T>::get(void) const”: 不能将“this”指针从“osg::ref_ptr”转换为“const osg::ref_ptr<T> &”
1>D:\osgprj\osgearth\src\osgEarth\MapboxGLImageLayer.cpp(262,48): message : 原因如下: 无法从“osg::ref_ptr”转换为“const osg::ref_ptr<T>”
1>D:\osgprj\osgearth\src\osgEarth\MapboxGLImageLayer.cpp(262,30): message : 转换要求第二个用户定义的转换运算符或构造函数
1>D:\vs3D\vcpkg\installed\x64-windows\include\osg/ref_ptr(117,12): message : 参见“osg::ref_ptr<T>::get”的声明 (编译源文件 D:\osgprj\osgearth\src\osgEarth\MapboxGLImageLayer.cpp)
1>D:\osgprj\osgearth\src\osgEarth\MapboxGLImageLayer.cpp(1274,48): warning C4018: “>=”: 有符号/无符号不匹配
1>D:\osgprj\osgearth\src\osgEarth\MapboxGLImageLayer.cpp(1274,73): warning C4018: “>=”: 有符号/无符号不匹配
1>已完成生成项目“osgEarth.vcxproj”的操作 - 失败。
========== 生成: 成功 0 个，失败 1 个，最新 1 个，跳过 0 个 ==========
what can I do to overcome this problem?

**Comment by SpaceView** [comment]
I figured out by myself, 
(1) use protoc.exe
protoc --proto_path=D:/osgprj/temp --cpp_out=D:/osgprj/temp D:/osgprj/temp/glyphs.proto
protoc --proto_path=D:/osgprj/temp --cpp_out=D:/osgprj/temp D:/osgprj/temp/vector_tile.proto
to generate the following 4 files,
glyphs.pb.h,  glyphs.pb.cpp，vector_tile.pb.h, vector_tile.pb.cpp
combine these 4 files into the project.
(2) use precompile definition OSGEARTH_HAVE_MVT for the MVT feature issue.

**Comment by jasonbeverage** [comment]
Did you install protobuf:x64-windows via vcpkg?  What is the value of Protobuf_PROTOC_EXECUTABLE in your CMake once you run the configure setup?  For example mine is found at:  D:/dev/vcpkg/installed/x64-windows/tools/protobuf/protoc.exe
