### ISSUE TITLE
Build errors (MapboxGLGlyphManager related)

### ISSUE THREAD

**Issue by gwaldron** [gwaldron/osgearth#2042]
### Discussed in https://github.com/gwaldron/osgearth/discussions/2007

<div type='discussions-op-text'>

<sup>Originally posted by **MarkusMoss** March  3, 2022</sup>
Hi, I have tried  to build latest osgearth code  (try linking it  against latest OSG). 

For me, building osgearth (under latest ubuntu),  stops here with these  error messages:

"osgearth/src/osgEarth/MapboxGLGlyphManager.cpp:25:10: fatal error: glyphs.pb.h: Fila eller mappa finnes ikke " (file not found)

and

"osgearth/src/osgEarth/MapboxGLImageLayer.cpp:243:27: error: ‘MVTFeatureSource’ was not declared in this scope; did you mean ‘featureSource’?
  243 |             osg::ref_ptr< MVTFeatureSource > featureSource = new MVTFeatureSource();"

Do I need to install some "Mapbox" 3rdparty to get it built ? 

Thanks for info ! regards, Markus</div>

**Comment by jasonbeverage** [comment]
I've added better support in MapboxGLImageLayer for checking if osgEarth is built with sqlite and protobuf (mvt) in d0cc3040c4fda4fab441280d05cfb7d47b1fb00f.
