### ISSUE TITLE
GL3 built has problems with loading 3DModels and osg particle system

### ISSUE THREAD

**Issue by nebsar** [gwaldron/osgearth#2046]
When I try to load 3D models such as .obj, 3ds, and when I use particle system, I get the following warning repeatedly:

Warning: PolygonMode::apply(State&) - only GL_FRONT_AND_BACK is supported.

Is this because GL3 build does not support materials and other stuff? What can be the solution to this?

**Comment by nebsar** [comment]
I applied the recommended method, but it did not work. As follows:
osg::ref_ptr<osg::Node> model3d = osgDB::readRefNodeFile("model.obj");
ShaderGenerator gen;
gen.apply(*model3d);

**Comment by gwaldron** [comment]
Please explain "did not work."

**Comment by nebsar** [comment]
Same messages are still dumped

**Comment by nebsar** [comment]
I also tried : osgEarth::Registry::shaderGenerator().run(model3d); But same result.

**Comment by gwaldron** [comment]
Read the docs on [PolygonMode](https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glPolygonMode.xhtml).

> Must be GL_FRONT_AND_BACK for front- and back-facing polygons.

**Comment by nebsar** [comment]
Ok, I am sorry. Now it worked. I was using outline for the model. And that was causing the message dump. When I removed the outline it started working.

**Comment by nebsar** [comment]
But this time I do not have my model outline anymore.  :(I know that you are too busy. But just in case I shared my model outline code. Thanks for the help, Glenn. Much appreciated.

[ShOutline.zip](https://github.com/gwaldron/osgearth/files/8531266/ShOutline.zip)

**Comment by nebsar** [comment]
Ok never mind. I am still trying to learn. I read the document you shared and adjusted the code. I have my outline again. Most probably, if do the same modification for the particle system, it will work. Thanks Glenn.

**Comment by gwaldron** [comment]
Glad you got it working :)

**Comment by nebsar** [comment]
By the way, I rebuilt the OSG removing the codes that includes materials from the Particle System. Then I used osgEarth's shader generator. Particle system worked well and no dumped messages to console from OSG. Here is the image.

![image](https://user-images.githubusercontent.com/5169314/164539542-94c84207-2c6f-4d05-a922-4459a12b47fc.png)

**Comment by gwaldron** [comment]
amazing!
