### ISSUE TITLE
void StateSet::setGlobalDefaults() ShaderPipeline disabled.

### ISSUE THREAD

**Issue by wuvalue** [gwaldron/osgearth#2056]
void StateSet::setGlobalDefaults() ShaderPipeline disabled.
VERTEX glCompileShader "oe_rex_init_model" FAILED
VERTEX Shader "oe_rex_init_model" infolog:
0(25) : error C7616: global variable gl_MultiTexCoord0 is removed after version 140

VERTEX glCompileShader "oe_rex_normalMapVS" FAILED
VERTEX Shader "oe_rex_normalMapVS" infolog:
0(36) : error C7616: global variable gl_NormalMatrix is removed after version 140

VERTEX glCompileShader "oe_rex_morph" FAILED
VERTEX Shader "oe_rex_morph" infolog:
0(93) : error C7616: global variable gl_ModelViewMatrix is removed after version 140
0(123) : error C7616: global variable gl_MultiTexCoord1 is removed after version 140
0(124) : error C7616: global variable gl_MultiTexCoord2 is removed after version 140

VERTEX glCompileShader "main(vertex)" FAILED
VERTEX Shader "main(vertex)" infolog:
0(49) : error C7616: global variable gl_Vertex is removed after version 140
0(50) : error C7616: global variable gl_Normal is removed after version 140
0(51) : error C7616: global variable gl_Color is removed after version 140
0(55) : error C7616: global variable gl_ModelViewMatrix is removed after version 140
0(56) : error C7616: global variable gl_NormalMatrix is removed after version 140
0(63) : error C7616: global variable gl_ProjectionMatrix is removed after version 140

glLinkProgram 000001F866BB71F0"GDALImageLayer" FAILED
Program "GDALImageLayer" infolog:
Vertex info
-----------
0(25) : error C7616: global variable gl_MultiTexCoord0 is removed after version 140
(0) : error C2003: incompatible options for link
0(36) : error C7616: global variable gl_NormalMatrix is removed after version 140
(0) : error C2003: incompatible options for link
0(93) : error C7616: global variable gl_ModelViewMatrix is removed after version 140
0(123) : error C7616: global variable gl_MultiTexCoord1 is removed after version 140
0(124) : error C7616: global variable gl_MultiTexCoord2 is removed after version 140
(0) : error C2003: incompatible options for link
0(49) : error C7616: global variable gl_Vertex is removed after version 140
0(50) : error C7616: global variable gl_Normal is removed after version 140
0(51) : error C7616: global variable gl_Color is removed after version 140
0(55) : error C7616: global variable gl_ModelViewMatrix is removed after version 140
0(56) : error C7616: global variable gl_NormalMatrix is removed after version 140
0(63) : error C7616: global variable gl_ProjectionMatrix is removed after version 140
(0) : error C2003: incompatible options for link

[osgEarth]* [VirtualProgram] Program will not link!
[osgEarth]* SHADER oe_rex_init_model infolog errors:
0:   #version 460
1:   #extension GL_ARB_gpu_shader_int64 : enable
2:   #pragma vp_name REX Engine - Init Model Space
3:   #pragma vp_function oe_rex_init_model, vertex_model, first
4:   #define VP_STAGE_VERTEX
5:   // uniforms
6:   uniform vec4 oe_terrain_color;
7:   uniform vec4 oe_tile_key_u;
8:   // outputs
9:   vec4 vp_Color;
10:   #pragma vp_varying_out vec4 vp_Color
11:   vec4 oe_layer_tilec;
12:   #pragma vp_varying_out vec4 oe_layer_tilec
13:   vec4 oe_terrain_tessLevel;
14:   #pragma vp_varying_out vec4 oe_terrain_tessLevel
15:   float oe_rex_morphFactor;
16:   #pragma vp_varying_out float oe_rex_morphFactor
17:   int oe_terrain_vertexMarker;
18:   #pragma vp_varying_out flat int oe_terrain_vertexMarker
19:   // stage globals
20:   vec4 oe_tile_key;
21:   void oe_rex_init_model(inout vec4 vertexModel)
22:   {
23:       // Texture coordinate for the tile (always 0..1)
24:       oe_layer_tilec = gl_MultiTexCoord0;
25**>     // Extract the vertex type marker
26:       oe_terrain_vertexMarker = int(oe_layer_tilec.z);
27:       // Color of the underlying map geometry (untextured)
28:       vp_Color = oe_terrain_color;
29:       // initialize:
30:       oe_rex_morphFactor = 0.0;
31:       // tile key
32:       oe_tile_key = oe_tile_key_u;
33:
34:       // Default tessellation level (where applicable)
35:       oe_terrain_tessLevel = vec4(1);
36:   }

**Comment by gwaldron** [comment]
Please: provide some context with your posts.  Is this one of the osgEarth example applications? Your own application? Which version of osgEarth are you using? On what platform?

**Comment by gwaldron** [comment]
These errors probably mean that either (a) OSG is not built with GL3 support, which is required; or (b) OSG is not configured to use vertex attribute aliasing, which is also required.

We recommend using OSG from vcpkg as outlined in the docs here:
https://docs.osgearth.org/en/latest/build.html

If you already have OSG built with GL3 support, you may need to activate the vertex attribute aliasing. Try using this realize callback with your application:
https://github.com/gwaldron/osgearth/blob/master/src/osgEarth/GLUtils#L141

Good luck.

**Comment by wuvalue** [comment]
> 这些错误可能意味着（a）OSG不是使用GL3支持构建的，这是必需的;或 （b） OSG 未配置为使用顶点属性别名，这也是必需的。
> 
> 我们建议使用 vcpkg 中的 OSG，如以下文档中所述：https://docs.osgearth.org/en/latest/build.html
> 
> 如果您已经构建了支持 GL3 的 OSG，则可能需要激活顶点属性别名。尝试在应用程序中使用此实现回调：https://github.com/gwaldron/osgearth/blob/master/src/osgEarth/GLUtils#L141
> 
> 祝你好运。

hi, i use the way of vcpkg you advice.Model does not display correctly。code like  this:

#include <stdlib.h>
#include <stdio.h>
#include <iostream>

#include <QApplication>
#include <QMainWindow>
#include <QOpenGLWidget>
#include <QMouseEvent>
#include <QWheelEvent>
#include <QDesktopWidget>
#include <QScreen>
#include <QtGlobal>
#include <QWindow>

#include <osg/ref_ptr>
#include <osgViewer/GraphicsWindow>
#include <osgViewer/Viewer>
#include <osg/Camera>
#include <osg/ShapeDrawable>
#include <osg/StateSet>
#include <osg/Material>
#include <osgGA/EventQueue>
#include <osgGA/TrackballManipulator>


class QtOSGWidget : public QOpenGLWidget
{
public:
    QtOSGWidget(QWidget* parent = 0)
        : QOpenGLWidget(parent)
        , _mGraphicsWindow(new osgViewer::GraphicsWindowEmbedded(this->x(), this->y(),
            this->width(), this->height()))
        , _mViewer(new osgViewer::Viewer)
        // take care of HDPI screen, e.g. Retina display on Mac
        , m_scale(QApplication::desktop()->devicePixelRatio())
    {
        osg::Cylinder* cylinder = new osg::Cylinder(osg::Vec3(0.f, 0.f, 0.f), 0.25f, 0.5f);
        osg::ShapeDrawable* sd = new osg::ShapeDrawable(cylinder);
        sd->setColor(osg::Vec4(0.8f, 0.5f, 0.2f, 1.f));
        osg::Geode* geode = new osg::Geode;
        geode->addDrawable(sd);

        osg::Camera* camera = new osg::Camera;
        camera->setViewport(0, 0, this->width(), this->height());
        camera->setClearColor(osg::Vec4(0.9f, 0.9f, 1.f, 1.f));
        float aspectRatio = static_cast<float>(this->width()) / static_cast<float>(this->height());
        camera->setProjectionMatrixAsPerspective(30.f, aspectRatio, 1.f, 1000.f);
        camera->setGraphicsContext(_mGraphicsWindow);

        _mViewer->setCamera(camera);
        _mViewer->setSceneData(geode);
        osgGA::TrackballManipulator* manipulator = new osgGA::TrackballManipulator;
        manipulator->setAllowThrow(false);
        this->setMouseTracking(true);
        _mViewer->setCameraManipulator(manipulator);
        _mViewer->setThreadingModel(osgViewer::Viewer::SingleThreaded);
  //      _mViewer->realize();
    }


    virtual ~QtOSGWidget() {}

protected:

    virtual void paintGL() {
        _mViewer->frame();
    }

    virtual void resizeGL(int width, int height)
    {
        this->getEventQueue()->windowResize(this->x() * m_scale, this->y() * m_scale, width * m_scale, height * m_scale);
        _mGraphicsWindow->resized(this->x() * m_scale, this->y() * m_scale, width * m_scale, height * m_scale);
        osg::Camera* camera = _mViewer->getCamera();
        camera->setViewport(0, 0, this->width() * m_scale, this->height() * m_scale);
    }

    virtual void initializeGL() {
        osg::Geode* geode = dynamic_cast<osg::Geode*>(_mViewer->getSceneData());
        osg::StateSet* stateSet = geode->getOrCreateStateSet();
        osg::Material* material = new osg::Material;
        material->setColorMode(osg::Material::AMBIENT_AND_DIFFUSE);
        stateSet->setAttributeAndModes(material, osg::StateAttribute::ON);
        stateSet->setMode(GL_DEPTH_TEST, osg::StateAttribute::ON);
    }

    virtual void mouseMoveEvent(QMouseEvent* event)
    {
        this->getEventQueue()->mouseMotion(event->x() * m_scale, event->y() * m_scale);
    }

    virtual void mousePressEvent(QMouseEvent* event)
    {
        unsigned int button = 0;
        switch (event->button()) {
        case Qt::LeftButton:
            button = 1;
            break;
        case Qt::MiddleButton:
            button = 2;
            break;
        case Qt::RightButton:
            button = 3;
            break;
        default:
            break;
        }
        this->getEventQueue()->mouseButtonPress(event->x() * m_scale, event->y() * m_scale, button);
    }

    virtual void mouseReleaseEvent(QMouseEvent* event)
    {
        unsigned int button = 0;
        switch (event->button()) {
        case Qt::LeftButton:
            button = 1;
            break;
        case Qt::MiddleButton:
            button = 2;
            break;
        case Qt::RightButton:
            button = 3;
            break;
        default:
            break;
        }
        this->getEventQueue()->mouseButtonRelease(event->x() * m_scale, event->y() * m_scale, button);
    }

    virtual void wheelEvent(QWheelEvent* event)
    {
        int delta = event->delta();
        osgGA::GUIEventAdapter::ScrollingMotion motion = delta > 0 ?
            osgGA::GUIEventAdapter::SCROLL_UP : osgGA::GUIEventAdapter::SCROLL_DOWN;
        this->getEventQueue()->mouseScroll(motion);
    }

    virtual bool event(QEvent* event)
    {
        bool handled = QOpenGLWidget::event(event);
        this->update();
        return handled;
    }

private:

    osgGA::EventQueue* getEventQueue() const {
        osgGA::EventQueue* eventQueue = _mGraphicsWindow->getEventQueue();
        return eventQueue;
    }

    osg::ref_ptr<osgViewer::GraphicsWindowEmbedded> _mGraphicsWindow;
    osg::ref_ptr<osgViewer::Viewer> _mViewer;
    qreal m_scale;
};

int main(int argc, char** argv)
{
#if QT_VERSION >= QT_VERSION_CHECK(5,6,0)
    QApplication::setAttribute(Qt::AA_DisableHighDpiScaling);
#else
    qputenv("QT_DEVICE_PIXEL_RATIO", QByteArray("1"));
#endif

    QApplication qapp(argc, argv);
    QMainWindow window;
    QtOSGWidget* widget = new QtOSGWidget(&window);
    window.setCentralWidget(widget);
    window.show();

    return qapp.exec();
}

**Comment by wuvalue** [comment]
![125644](https://user-images.githubusercontent.com/23473627/167069720-711e6b0d-4a5b-48ae-a168-a489937be0aa.png)

**Comment by gwaldron** [comment]
Cannot help you with a Qt app. Please try our suggestion and make sure the the examples work propertly (like osgearth_viewer).
