### ISSUE TITLE
cesiumion error

### ISSUE THREAD

**Issue by vishwanath377** [gwaldron/osgearth#2066]
[osgEarth]* [EarthSerializer2] class osgEarth::CesiumIonImageLayer "Bing Maps Aerial With Labels" : Configuration error : CesiumIon API key is required
[osgEarth]* [EarthSerializer2] class osgEarth::CesiumIon3DTilesLayer "Melbourne" : Configuration error : CesiumIon API key is required

this is the error I am getting when running the cesiumion.earth file

**Comment by gwaldron** [comment]
Please go to this site to register for a Cesium Ion authorization key.
https://cesium.com/ion/signup/
