### ISSUE TITLE
class osgEarth::CesiumIonImageLayer "Bing Maps Aerial With Labels" : Configuration error : Failed to get metadata from asset endpoint [osgEarth]* [EarthSerializer2] class osgEarth::CesiumIon3DTilesLayer "Melbourne" : Resource unavailable : Error loading tileset:

### ISSUE THREAD

**Issue by vishwanath377** [gwaldron/osgearth#2067]
class osgEarth::CesiumIonImageLayer "Bing Maps Aerial With Labels" : Configuration error : Failed to get metadata from asset endpoint
[osgEarth]* [EarthSerializer2] class osgEarth::CesiumIon3DTilesLayer "Melbourne" : Resource unavailable : Error loading tileset:

getting this error while running cesiumion.earth file

**Comment by jasonbeverage** [comment]
You need to sign up for a CesiumIon account and then provide your account's token either by adding a <token>YOUR-TOKEN-HERE</token> attribute to the layer or by setting the OSGEARTH_CESIUMION_KEY environment variable to your account token.

**Comment by vishwanath377** [comment]
how can  I get buidlings and stuff all which you uploaded in the u tube. Can u upload the source code.
