### ISSUE TITLE
error

### ISSUE THREAD

**Issue by vishwanath377** [gwaldron/osgearth#2071]
C:\dev\cpp\vcpkg\build\osgearth\tests>osgearth_viewer feature_extrude.earth
[osgEarth]* XML parsing error in "feature_extrude.earth"
[osgEarth]* Error reading Attributes. (row 9, col 38)
[osgEarth]*  1          
[osgEarth]*  4
[osgEarth]*  5          <map name="Extrusion Demo">
[osgEarth]*  6          <xi:include href="readymap_imagery.xml"/>
[osgEarth]*  7              <xi:include href="readymap_elevation.xml/>
[osgEarth]*  8
[osgEarth]*  9 *            <OGRFeatures name="buildings-data">
[osgEarth]*  10                 <url>../data/buildings.shp</url>
[osgEarth]*  11                 <build_spatial_index>true</build_spatial_index>
[osgEarth]*  12             </OGRFeatures>
[osgEarth]*  13
[osgEarth]*  14             <FeatureModel name="building" features="buildings-data">
Error reading file feature_extrude.earth: read error

this the error I am i got while I tried to run this program Can U please fix it.

This is the program:
<map name="Extrusion Demo">
<xi:include href="readymap_imagery.xml"/>
    <xi:include href="readymap_elevation.xml/>
      
    <OGRFeatures name="buildings-data">
        <url>../data/buildings.shp</url>
        <build_spatial_index>true</build_spatial_index>
    </OGRFeatures>
	         
    <FeatureModel name="building" features="buildings-data">
        <styles>
            <style type="text/css">
                buildings {
                    fill:              #ff7f2f;
                    stroke:            #cf5f00;
                    extrusion-height:  20;
                    extrusion-flatten: true;
                    altitude-clamping: terrain;
                }
            </style>
        </styles>
    </FeatureModel>
    
    
    <viewpoints>
   <viewpoint name="Hyderabad, India">
    <label>Sample Viewpoint 1</label>
    <description>Description of the view.</description>
    <x>78.4867</x>
    <y>17.3850</y>
    
    <heading>-30.1011</heading>
<pitch>-34.79540299384382</pitch>
        <range>78142.53643278375</range>
</viewpoint>
</viewpoints>
    
  
</map>

**Comment by jasonbeverage** [comment]
Are you using the feature_extrude.earth demo directly from the osgearth
repo or did you try to download it from the GitHub web interface?  It looks
like you line numbers in your xml.   If you're getting it from GitHub make
sure you use the  View Raw option or download the file instead of copying
it from the web page.

**Comment by vishwanath377** [comment]
No I have used my own shape file which I have downloaded and replaced with the shape file which is alrdy there. I have also changed the coordinates.

**Comment by jasonbeverage** [comment]
Can you attach the earth file you're using so I can look at it?

**Comment by vishwanath377** [comment]
`<map name="Extrusion Demo">

    
      
    <OGRFeatures name="buildings-data">
        <url>../data/buildings.shp</url>
        <build_spatial_index>true</build_spatial_index>
    </OGRFeatures>
	         
    <FeatureModel name="building" features="buildings-data">
        <styles>
            <style type="text/css">
                buildings {
                    fill:              #ff7f2f;
                    stroke:            #cf5f00;
                    extrusion-height:  20;
                    extrusion-flatten: true;
                    altitude-clamping: terrain;
                }
            </style>
        </styles>
    </FeatureModel>
<xi:include href="readymap_imagery.xml"/>
    
    
    <viewpoints>
   <viewpoint name="Hyderabad, India">
    <label>Sample Viewpoint 1</label>
    <description>Description of the view.</description>
    <x>78.4867</x>
    <y>17.3850</y>
    
    <heading>-30.1011</heading>
<pitch>-34.79540299384382</pitch>
        <range>78142.53643278375</range>
</viewpoint>
</viewpoints>
    
  
</map>`

**Comment by vishwanath377** [comment]
<map name="Extrusion Demo">

    
      
    <OGRFeatures name="buildings-data">
        <url>../data/buildings.shp</url>
        <build_spatial_index>true</build_spatial_index>
    </OGRFeatures>
	         
    <FeatureModel name="building" features="buildings-data">
        <styles>
            <style type="text/css">
                buildings {
                    fill:              #ff7f2f;
                    stroke:            #cf5f00;
                    extrusion-height:  20;
                    extrusion-flatten: true;
                    altitude-clamping: terrain;
                }
            </style>
        </styles>
    </FeatureModel>
<xi:include href="readymap_imagery.xml"/>
    
    
    <viewpoints>
   <viewpoint name="Hyderabad, India">
    <label>Sample Viewpoint 1</label>
    <description>Description of the view.</description>
    <x>78.4867</x>
    <y>17.3850</y>
    
    <heading>-30.1011</heading>
<pitch>-34.79540299384382</pitch>
        <range>78142.53643278375</range>
</viewpoint>
</viewpoints>
    
  
</map>
