### ISSUE TITLE
cull callback for featureNode doesn't work.

### ISSUE THREAD

**Issue by keince** [gwaldron/osgearth#2074]
Adding a cull callback via the call `addCullCallback()` to a FeatureNode doesn't appear to work with view frustum culling. When I pan away from the FeatureNode on the map so that the FeatureNode is outside of the field of view, the cull callback continues to execute which it shouldn't.

I added the call `setCullingActive(true)` to the FeatureNode which has no effect. 

I also noticed that a similar issue #989 addressed something similar in where it was stated that it was fixed. My FeatureNode is also using GPU clamping.

Is there something more that needs to be done so that the cull callback works?

I'm using osgEarth 3.1 on Windows 10 x64.

-Shayne

**Comment by gwaldron** [comment]
Strange. Is that line in your code?

**Comment by keince** [comment]
Well...it was, until I commented it out to get my cull callback to work.

**Comment by keince** [comment]
Once I get my computer back online, I will double check. I may have copied it wrong since the code is on another computer that has no access to the internet.

**Comment by keince** [comment]
Here's the actual code...

`AltitudeSymbol* alt = _feature->style()->getOrCreate<AltltudeSymbol>();`
`alt->clamping() = alt->CLAMP_TO_TERRAIN;`
`alt->technique() = alt->TECHNIQUE_GPU;`

If I comment out the 3rd line `alt->technique() = alt->TECHNIQUE_GPU;`, the cull callback set on the featureNode begins to work as expected. If I leave the line uncommented, the cull callback always gets executed even though the featureNode is completely culled away by the view frustum.

**Comment by gwaldron** [comment]
OK, I see what you are saying now.
The thing about GPU clamping is that a shader will move the geometry to a new location at render time. OSG has no way of knowing where the final location will be, so we have to disable the standard OSG bounding-sphere-based culling. This happens in `ClampableNode`. This means that OSG will always invoke your cull callback since it has to assume the node is potentially visible.

**Comment by keince** [comment]
That makes sense. I'll just leave GPU clamping disabled for now...

Thanks for the detailed feedback.
