### ISSUE TITLE
Draping - draped 3D model has incorrect bounds

### ISSUE THREAD

**Issue by quentinBdr** [gwaldron/osgearth#2090]
I'm using osgearth v3.3 on windows 10, GL3 profile. My application is build under a Qt QOpenGLWidget and features also ImGui.
Here is the capabilities :
![image](https://user-images.githubusercontent.com/15386075/176847442-3bb1b57a-095c-4dd6-9ac7-ca15503cf33d.png)

The problem is I have an object that is a LocalGeometryNode (also tried w/ FeatureNode) and when wanting to drape the underlying geometry on the surface through an AltitudeSymbol w/ TECHNIQUE_DRAPE, I get no error but everything disapear on screen.
I've tried w/ TECHNIQUE_MAP and TECHNIQUE_SCENE but the geometry does not clamp. Only w/ TECHNIQUE_DRAPE and TECHNIQUE_GPU I get the defect.
Still, after everything disapear, when I zoom or pan I see osgearth log that it is loading tiles, just like it is working fine, but no display.

I get these log before everything goes away :
![image](https://user-images.githubusercontent.com/15386075/176848405-688c854b-3fe9-4509-9970-331c78727e6c.png)

Before draping :
![image](https://user-images.githubusercontent.com/15386075/176849006-842cc56d-f12b-480d-b2b7-66844aa2bbaa.png)

After Draping :
![image](https://user-images.githubusercontent.com/15386075/176849130-c7c7b65e-fbfe-40f2-a592-5fa941a4a206.png)

Have any clue on what's happening ? :)

**Comment by gwaldron** [comment]
Can you provide an earth file that reproduces the issue?

**Comment by quentinBdr** [comment]
Normally I do drape from the API, but I get the same result with a model used in the earth file provided :

```xml
<map name="Default map" type="geocentric" version="2">

  <options>
    <!-- Setup the spatial reference system. -->
    <profile/>
	<!-- Setup the network proxy for remote access. -->
	<proxy/>
	<!-- Setup the cache method. -->
	<cache>
	  <driver>filesystem</driver>
	  <path>G:/EARTH/cache</path>
	</cache>
	<!-- Setup cache policy. -->
	<cache_policy>
	  <usage>read_write</usage>
	</cache_policy>
	<!-- Setup terrain. -->
	<terrain>
	  <driver>rex</driver>
	  <gpu_tessellation>false</gpu_tessellation>
	  <range_mode>PIXEL_SIZE_ON_SCREEN</range_mode>
	  <min_tile_range_factor>10</min_tile_range_factor>
	</terrain>
  </options>

  <Annotations>
    <Model>
        <position srs="wgs84" lat="43" long="0"/>
        <style>
            model: "G:/EARTH/data/3dmodel/platforms/rafale.osgb";
            model-scale: 20;
            altitude-clamping:  terrain-drape;
        </style>
    </Model>
  </Annotations>
  
</map>
```

**Comment by gwaldron** [comment]
You problem may have to do with `QOpenGLWidget` which uses an FBO that OpenSceneGraph doesn't know about.
Try setting you main camera's default FBO like so (from your Qt paint function)... from memory:
```c++
void MyQOpenGLWidget::paintGL()
{
   viewer->getCamera()->getGraphicsContext()->setDefaultFboId(defaultFramebufferObject());
   ...
```

**Comment by quentinBdr** [comment]
Nice it does the trick thanks ! 
Although the model appears a bit croped somehow : 
![image](https://user-images.githubusercontent.com/15386075/181191736-778c256e-3daa-479c-9c25-e41790fc174b.png)
![image](https://user-images.githubusercontent.com/15386075/181191843-a419bfcf-fbcc-4df6-9355-44273aa819ee.png)

Any idea on that behavior ?

**Comment by gwaldron** [comment]
I noticed that as well. The idea of draping a 3D model is a little odd, so the use case has not really been tested much.
I will mark this as a defect and we can look into it.

**Comment by gwaldron** [comment]
Closing as stale - if someone wants to post sample code to reproduce, we'll look at it anew.
