### ISSUE TITLE
gl1 combine gl2 or gl3, which run faster?

### ISSUE THREAD

**Issue by hollypa** [gwaldron/osgearth#2091]
I compiled OsGearth using VCPKG, configured as GL3, and found that it was a bit slower than my previous compilation using GL2. GL2's frame rate was a bit more stable when dragging the earth in the OSgearth_Viewer, between 50 and 60 FPS. GL3's frame rate dropped down to around 30 FPS when dragging the earth, and around 60 FPS when not dragging

**Comment by gwaldron** [comment]
Not sure what to tell you. osgEarth requires a GL3-enabled build of OSG at this point. If you find a reason behind a slowdown, be sure to let us know!
