### ISSUE TITLE
Window Creation Failure - No interfaces available - Ubuntu 20.04

### ISSUE THREAD

**Issue by cbrl** [gwaldron/osgearth#2099]
I am attempting to use osgEarth on an x64 system running Ubuntu 20.04. I have installed osgEarth and its dependencies through the latest vcpkg port, using the default OpenGL profile of GL3.

Running any of the osgEarth tools which create a window will result in the following errors:
```
Warning: GraphicsContext::WindowingSystemInterfaces::getWindowingSystemInterface() failed, no interfaces available.
[osgEarth]* [Capabilities] Failed to create graphic window too.
```

Though the GraphicsContext is an osg component, the osgstaticviewer application (from the OpenSceneGraph examples) does not encounter any errors, which leads me to believe this is a problem with osgEarth instead.

**Comment by jasonbeverage** [comment]
osgEarth does try to create a temporary graphic context on startup to try to figure out the graphics capabilities of the system up front and it sounds like that is failing.

Is this a static build of OSG?  Can you run osgearth_version --caps and post the output?

**Comment by cbrl** [comment]
The x64-linux triplet in vcpkg uses static library linkage. osgearth_version outputs `osgEarth 3.3.0 build 135` normally, but with the --caps option I get the same errors as before:

```
[osgEarth]  [Registry] Note: GDAL_DATA environment variable is not set
Warning: GraphicsContext::WindowingSystemInterfaces::getWindowingSystemInterface() failed, no interfaces available.
[osgEarth]* [Capabilities] Failed to create graphic window too.
```

**Comment by cbrl** [comment]
I did just notice the usage of a `USE_GRAPHICSWINDOW()` macro in the osgstaticviewer source code (also present in osgslice, osgdeferred, and present3D) that might be related to the issue:
https://github.com/openscenegraph/OpenSceneGraph/blob/683403244a489fe3e71f1533580c22e099774a36/examples/osgstaticviewer/osgstaticviewer.cpp#L73

The macro is defined here: https://github.com/openscenegraph/OpenSceneGraph/blob/34a1d8bc9bba5c415c4ff590b3ea5229fa876ba8/include/osgViewer/GraphicsWindow#L286

In the case of a Linux system, it creates a static `osgViewer::GraphicsWindowFunctionProxy` variable and passes it a pointer to the `graphicswindow_X11` function, which the function proxy class will invoke upon creation.

I can't track down the definition of this `graphicswindow_X11` function, but the function is also referenced in the call to the `REGISTER_WINDOWINGSYSTEMINTERFACE2` macro here:
https://github.com/openscenegraph/OpenSceneGraph/blob/34a1d8bc9bba5c415c4ff590b3ea5229fa876ba8/src/osgViewer/GraphicsWindowX11.cpp#L2280

The `REGISTER_WINDOWINGSYSTEMINTERFACE2` is defined here:
https://github.com/openscenegraph/OpenSceneGraph/blob/683403244a489fe3e71f1533580c22e099774a36/include/osg/GraphicsContext#L603

This macro also creates a static `osg::WindowingSystemInterfaceProxy<X11WindowingSystemInterface>` variable, which will add the `X11WindowingSystemInterface` to the static list of `WindowingSystemInterface`s. I imagine the call to `graphicswindow_X11()` in osgstaticviewer is what will ultimately allow the interface to be discovered.

It may be that this `USE_GRAPHICSWINDOW()` invocation is required in static builds. I'll look into it further.

**Comment by jasonbeverage** [comment]
osgEarth does support static linkage and static osg, but our example apps aren't setup to run in that mode.  You do have to manually include every plugin you might want to use with USE_OSGPLUGIN and all those other hoops you just mentioned, but that's up to the main application take care of in their build.

**Comment by cbrl** [comment]
Good to know. Is there any documentation for these steps? I didn't notice anything about them in the references for osg or osgEarth.

**Comment by cbrl** [comment]
Closing this issue since the windowing error is resolved. Properly including the static libraries fixes the issue, though users may benefit from clarification on the static linking process.
