### ISSUE TITLE
mingw32(qt) build osgearth2.9 with osg3.4.0 so many link redefined or ambiguous

### ISSUE THREAD

**Issue by dragonwl737** [gwaldron/osgearth#2101]
FlatteningLayer.cpp:93:46: error: reference to 'Polygon' is ambiguous
     osg::Vec3d inline getInternalPoint(const Polygon* p)
  
i686-w64-mingw32/include/wingdi.h:3353:28: note: candidates are: WINBOOL Polygon(HDC, const POINT*, int)
   WINGDIAPI WINBOOL WINAPI Polygon(HDC hdc,CONST POINT *apt,int cpt);

FlatteningLayer.cpp:96:34: error: request for member 'getBounds' in '* p', which is of non-class type 'const int

**Comment by gwaldron** [comment]
First things first: osgEarth requires OpenSceneGraph 3.6 or newer.

**Comment by wlwanlong** [comment]
> First things first: osgEarth requires OpenSceneGraph 3.6 or newer.

Is the same for osgearth 2.9, it depends on osg3.6.0 and above?

**Comment by gwaldron** [comment]
Oh, I did not see that you are using 2.9, sorry.
We have no experience with mingw so I'm afraid I don't have any ideas.

**Comment by dragonwl737** [comment]
Oh, and maybe my inclusion path isn't quite right， @gwaldron thanks.
