### ISSUE TITLE
osgearth_viewer.exe show blank maps

### ISSUE THREAD

**Issue by dragonwl737** [gwaldron/osgearth#2109]
I use mingw32 to cross compile (version 2.9), osg3.6.5 (plugin3.7.0), gdal 2.1.2, and allow gl3, but always prompt an error message: [osgEarth] [VirtualProgram] Program link failure! Can anyone help me find it the reason?is there some library file I'm missing?
![image](https://user-images.githubusercontent.com/109955305/182529247-f1c23274-6fed-47dc-a162-61687c72e928.png)
![image](https://user-images.githubusercontent.com/109955305/182529871-868079c1-dd9d-4bc8-a51b-4a13aa4177ca.png)

**Comment by dragonwl737** [comment]
And OSG found the following three-party libraries:
* Freetype
  * Jasper
  * GDAL
  * CURL
  * OpenGL
  * GIFLIB
  *JPEG
  * ZLIB
  *PNG
  *TIFF
  * Threads

**Comment by dragonwl737** [comment]
[out.txt](https://github.com/gwaldron/osgearth/files/9258018/out.txt)
This is my debug info, can anyone help me, thanks!!!

**Comment by gwaldron** [comment]
I highly recommend you try the latest version of osgEarth (3.3 at the time of this comment). There is not much we can do to support and old 2.10 application, especially compiling on mingw and vmware.

**Comment by dragonwl737** [comment]
> I highly recommend you try the latest version of osgEarth (3.3 at the time of this comment). There is not much we can do to support and old 2.10 application, especially compiling on mingw and vmware.
