### ISSUE TITLE
Run osgearth_skyview crash

### ISSUE THREAD

**Issue by KaiTang2** [gwaldron/osgearth#2114]
Hellow everyone,
 I use the branch of 3.3,the osg version is 3.6.5,when I run this example , it will crash.How should I do
this is my earth file:
![image](https://user-images.githubusercontent.com/33851010/183585782-9036a93c-9ff6-4c00-bcb3-3ff177ac01cd.png)

This is a screenshot of the program crash:
![image](https://user-images.githubusercontent.com/33851010/183583881-822c3f49-d9a7-40c7-84b5-2f8166113e5e.png)

**Comment by gwaldron** [comment]
Unable to reproduce the crash. Are you running `osgearth_skyview` ?

**Comment by KaiTang2** [comment]
@gwaldron  This problem is not only this example. As long as the earth file is loaded, even if there is no label in the file, just want to display a white earth, this crash will occur。So I guess，Is there a problem with my cmake configuration, or is the cmake configuration of OSG missing any configuration，this is mine:
osgearth:
![image](https://user-images.githubusercontent.com/33851010/185524866-bdea1e50-0273-427a-afd5-7c66d2d45951.png)
![image](https://user-images.githubusercontent.com/33851010/185524899-a6db2a26-2e10-4b92-a969-63507e763165.png)
![image](https://user-images.githubusercontent.com/33851010/185524926-817460b9-0ef4-49b0-8c05-be28d3cab22b.png)
![image](https://user-images.githubusercontent.com/33851010/185524945-60324c6f-7e19-4169-8df1-81c613edd7fd.png)
osg:
![image](https://user-images.githubusercontent.com/33851010/185525052-6b5be72d-e5a8-4d3f-8bbe-01ad050aeb04.png)
![image](https://user-images.githubusercontent.com/33851010/185525083-89147263-d82f-4752-91f4-1c19e138f5ef.png)
![image](https://user-images.githubusercontent.com/33851010/185525108-056c7e6b-bbd5-4f6d-859c-a5c9ea5d8b01.png)
![image](https://user-images.githubusercontent.com/33851010/185525131-569d7a74-89f1-45c2-8715-2d7024ffdc73.png)
![image](https://user-images.githubusercontent.com/33851010/185525147-225631ed-99ab-42b4-9a65-0021d7fd3865.png)
![image](https://user-images.githubusercontent.com/33851010/185525201-9df68ac1-ae21-4794-aa7b-dd1180045b56.png)
![image](https://user-images.githubusercontent.com/33851010/185525239-b9d5a01b-19be-4f4a-b45e-25adbe7fe982.png)
![image](https://user-images.githubusercontent.com/33851010/185525301-11dcf399-86ac-407c-a52e-622580395924.png)
![image](https://user-images.githubusercontent.com/33851010/185525325-3842e6c9-bf05-4a48-a14a-019e927c8433.png)
![image](https://user-images.githubusercontent.com/33851010/185525417-49f0c0ae-f504-4285-8578-cf9bcb6c5e1d.png)
![image](https://user-images.githubusercontent.com/33851010/185525493-90b53b33-336e-48c6-b11e-74f550ab7b86.png)
![image](https://user-images.githubusercontent.com/33851010/185525610-eda4405d-df0f-4e23-a78b-8e085fb5710c.png)
![image](https://user-images.githubusercontent.com/33851010/185525649-9af73b44-2841-40bb-aaa8-5f3f44fe5823.png)
![image](https://user-images.githubusercontent.com/33851010/185525672-4f6cd650-e53f-41da-b99c-94c2df8729f4.png)
