### ISSUE TITLE
about FeatureRasterizer

### ISSUE THREAD

**Issue by HerryJessica** [gwaldron/osgearth#2121]
hi 
version : osgearth3.2
i want use FeatureRasterizer  to Rasterizer text!
there is a question that how to draw Text use of  FeatureRasterizer ! i find this class is not support draw text is it?  or i don't konw how to use it. can you give me solution! thanks very very very very much!!!@gwaldron

**Comment by jasonbeverage** [comment]
osgEarth 3.2 doesn't have support to render text using the FeatureRasterizer.  osgEarth 3.3 can render text (experimentally) based on feature data using if you build osgEarth with support for Blend2D.  You should be able to use the same type of text styling as shown [here](https://github.com/gwaldron/osgearth/blob/master/tests/feature_labels.earth#L28-L33) to wire up the text styling.
