### ISSUE TITLE
how confige the osg   with cmake for GL3?

### ISSUE THREAD

**Issue by wuvalue** [gwaldron/osgearth#2122]
![屏幕截图 2022-08-18 204251](https://user-images.githubusercontent.com/23473627/185398352-0d841d4a-760b-45ec-b8b6-acb8a7a147fb.jpg)
![屏幕截图 2022-08-18 204307](https://user-images.githubusercontent.com/23473627/185398371-9f196498-65fe-4758-a8be-175a494320d9.jpg)
![屏幕截图 2022-08-18 204320](https://user-images.githubusercontent.com/23473627/185398387-643475bf-8233-4bae-b9d6-b5d27b725233.jpg)

**Comment by gwaldron** [comment]
We recommend using the `vcpkg` installation for OpenSceneGraph (see http://docs.osgearth.org/en/latest/build.html).

If you must build it manually, you can try these settings:

Set the following variables ON:
     OSG_GL3_AVAILABLE
   
Set the following variables OFF:
     OSG_GL1_AVAILABLE
     OSG_GL2_AVAILABLE
     OSG_GLES1_AVAILABLE
     OSG_GLES2_AVAILABLE
     OSG_GL_DISPLAYLISTS_AVAILABLE
     OSG_GL_FIXED_FUNCTION_AVAILABLE
     OSG_GL_MATRICES_AVAILABLE
     OSG_GL_VERTEX_ARRAY_FUNCS_AVAILABLE
     OSG_GL_VERTEX_FUNCS_AVAILABLE

**Comment by wuvalue** [comment]
> We recommend using the `vcpkg` installation for OpenSceneGraph (see http://docs.osgearth.org/en/latest/build.html).
> 
> If you must build it manually, you can try these settings:
> 
> Set the following variables ON: OSG_GL3_AVAILABLE
> 
> Set the following variables OFF: OSG_GL1_AVAILABLE OSG_GL2_AVAILABLE OSG_GLES1_AVAILABLE OSG_GLES2_AVAILABLE OSG_GL_DISPLAYLISTS_AVAILABLE OSG_GL_FIXED_FUNCTION_AVAILABLE OSG_GL_MATRICES_AVAILABLE OSG_GL_VERTEX_ARRAY_FUNCS_AVAILABLE OSG_GL_VERTEX_FUNCS_AVAILABLE

thanks

**Comment by wuvalue** [comment]
> We recommend using the `vcpkg` installation for OpenSceneGraph (see http://docs.osgearth.org/en/latest/build.html).
> 
> If you must build it manually, you can try these settings:
> 
> Set the following variables ON: OSG_GL3_AVAILABLE
> 
> Set the following variables OFF: OSG_GL1_AVAILABLE OSG_GL2_AVAILABLE OSG_GLES1_AVAILABLE OSG_GLES2_AVAILABLE OSG_GL_DISPLAYLISTS_AVAILABLE OSG_GL_FIXED_FUNCTION_AVAILABLE OSG_GL_MATRICES_AVAILABLE OSG_GL_VERTEX_ARRAY_FUNCS_AVAILABLE OSG_GL_VERTEX_FUNCS_AVAILABLE

hi,when i use osgearth that set GL3, encountered a problem
![image](https://user-images.githubusercontent.com/23473627/186654649-94982585-2834-4823-9e02-0d4c8c5f03ae.png)

**Comment by gwaldron** [comment]
The `Material::apply` errors are "normal" as GL3/no-FFP does not support FFP (fixed-function pipeline) GL, and OSG will dump errors like this when it encounters FFP usage. Not sure about the `invalid enumerant` though -- we would need more information on what you are loading to consider this.
