### ISSUE TITLE
Performance issue with XYZImageLayer

### ISSUE THREAD

**Issue by wuvalue** [gwaldron/osgearth#2123]
![image](https://user-images.githubusercontent.com/23473627/185735165-7d8f3fb9-dd8e-4b60-b2c9-4ac0dcea0912.png)
when I use google image ,the load speed is slow ,if i not set osgearth cache in osgearth 3.

**Comment by gwaldron** [comment]
A couple things you can try when you first create your `MapNode`...
You can try adding more tile loading threads:
```c++
mapNode->getTerrainOptions().setConcurrency(16);
```
You could also try progressive mode, which forces the tiles to load in resolution order:
```c++
mapNode->getTerrainOptions().setProgressive(true);
```
You can also try running `osgearth_imgui` and opening the Network Monitor to see if you are network-limited.
Good luck.
