### ISSUE TITLE
Building with GEOS

### ISSUE THREAD

**Issue by RhythmOfTension** [gwaldron/osgearth#2134]
Looks like current FindGEOS.cmake trying to find c++ geos includes, but osgearth itself uses C geos interface. Should it look for geos_c.h instead?

**Comment by gwaldron** [comment]
Perhaps so, though I believe they are all packaged together anyway. Are you having a build issue?

**Comment by RhythmOfTension** [comment]
At least on Debian there is 2 separate dev packages (libgeos-dev and libgeos++-dev), and it's possible to install c api without c++ api (but not other way around though).

**Comment by gwaldron** [comment]
I updated the FindGEOS module to look for geos_c.h Thanks.
