### ISSUE TITLE
Triton ocean range changed with camera moving.

### ISSUE THREAD

**Issue by korela1985** [gwaldron/osgearth#2137]
Hello,

I'm using osgEarth v2.10.2 and triton sdk 4.46.
more detail development envrionment is like that, osg 3.6.4, visual studio 2013 vc12, windows 10 x64.
and sample code based on "Sample osgearth_triton", "osgEarthTriton" projects and sample earth based on "triton.earth".

My problem is triton ocean range or location had followed to camera moving or rotating.

From initial position just zoom in or zoom out was not problem.
![image](https://user-images.githubusercontent.com/110900235/190342186-fd88ac3b-86bf-4736-816c-b195dce5d983.png)

But when i beginning move or rotate camera trtion ocean did't cover all sea area.
![image](https://user-images.githubusercontent.com/110900235/190342297-9dc24e2e-3b2d-48b2-bce2-d491d9986715.png)
![image](https://user-images.githubusercontent.com/110900235/190342380-3c9532fe-03bf-4ca0-b092-ac1f3208a3e7.png)

I't look like has cylindrical boundary or something circle surface.
![image](https://user-images.githubusercontent.com/110900235/190342475-433ef92f-a534-4950-9f75-09174bcc74f9.png)
![image](https://user-images.githubusercontent.com/110900235/190342552-fc72eb32-aa08-4d34-bbf7-cc74dce69100.png)
![image](https://user-images.githubusercontent.com/110900235/190342577-aa5973f7-3ac3-4836-905f-378375241eeb.png)

Would you know that  what happen to me?

Thank you!

**Comment by gwaldron** [comment]
closing as stale - was never able to repro with newest versions
