### ISSUE TITLE
Dynamic library not found

### ISSUE THREAD

**Issue by conanlee88** [gwaldron/osgearth#2140]
i built osgearth for android, and i load a map but it failed.

`dlopen failed: library "libosgdb_osgearth_image.so" not found`
i found this message as above in log.

i can not found this libosgdb_osgearth_image.so in my osgearth build result.
so i want to know, how to build this library.

**Comment by conanlee88** [comment]
if this library won't build, why load it?

**Comment by gwaldron** [comment]
Sorry - we missed this post!
Did you resolve this issue? It's possible you were attempting to load an older-style earth file.

**Comment by conanlee88** [comment]
Not yet.
The file can be displayed normally on the Ubuntu，so it is certain that the file is not the problem. It did not work out on Android.

**Comment by gwaldron** [comment]
Closing as stale - feel free to reopen if there's new information
