### ISSUE TITLE
Problems encountered using Vertical Scale?

### ISSUE THREAD

**Issue by oOoBinoOo** [gwaldron/osgearth#2142]
Hello, when using VerticalScale, when the coefficient becomes larger, the earth will be enlarged, and there will be a vacancy around it.  May I ask how to solve this problem?
![image](https://user-images.githubusercontent.com/61222190/191459332-222fe6cc-fbc0-4d16-a7cd-10cda9f93880.png)

**Comment by oOoBinoOo** [comment]
The content of the code you write.
     <terrainshader>
        <uniform name="scale" value="20.0"/>
        <code>
            <![CDATA[
                   #pragma vp_entryPoint applyScale
                   #pragma vp_location vertex_view

                   uniform float scale;
                   vec4 oe_layer_tilec;
                   vec3 oe_UpVectorView;
                   float oe_terrain_getElevation(in vec2);

                   void applyScale(inout vec4 vertexView)
                   {
                       float e = oe_terrain_getElevation(oe_layer_tilec);
                       vertexView.xyz += oe_UpVectorView*e*(scale-1.0);
                   }
                 ]]>
        </code>
    </terrainshader>

**Comment by oOoBinoOo** [comment]
<terrainshader>
        <uniform name="scale" value="20.0"/>
        <code>
            <![CDATA[
                   #pragma vp_entryPoint applyScale
                   #pragma vp_location vertex_view

                   uniform float scale;
                   vec4 oe_layer_tilec;
                   vec3 oe_UpVectorView;
                   float oe_terrain_getElevation(in vec2);

                   void applyScale(inout vec4 vertexView)
                   {
                       float e = oe_terrain_getElevation(oe_layer_tilec);
                       vertexView.xyz += oe_UpVectorView*e*(scale-1.0);
                   }
                 ]]>
        </code>
    </terrainshader>

**Comment by gwaldron** [comment]
This happens because the view frustum is computed on the CPU from the original geometry. But then, you are moving the vertices on the GPU in a shader. The CPU has no knowledge of this so it connect account for the shader's changes. There is nothing to address this in OpenSceneGraph or osgEarth.

**Comment by horrzs** [comment]
Can I implement this function in the source code? I want to dynamically adjust the scale of vertical scaling when oegearth is running. Osgearth 3.5   @gwaldron @oOoBinoOo
