### ISSUE TITLE
Incompatibility between GL3 and Material (.obj file)

### ISSUE THREAD

**Issue by marcoma9023** [gwaldron/osgearth#2148]
Hi, I have the following problem migrating code from 2.1 to 3.3 version: I need to generate a model reading .obj file. 

The problem, as you know, is that I'm not able to handle the material, because each model obj it's a model composed of material and texture. 

Then, now with GL3 I have compatibility problem to read and handle this characteristics. 

I tried to make a simple test, reading a simple cube.obj and putting an osgEarth::MaterialGL3 with color characteristics, but I don't know why, but the color of the cube it's varying between red and black, according to the camera position.

(I did this text because I thought that osgearth had worked on some object that hid the problem of incompatibility between GL3 and materials .... I don't know, maybe implementing a shader ...)

Then, 

1) Is it possible to avoid to create shader to read material from obj file? 

2) Does OSGEarth expose some object to do that? 

Can you help me to solve the problem? Thanks

**Comment by gwaldron** [comment]
OSGEarth requires a shader to render the object. How are you adding your object to the scene?
To generate the shader code, you can try loading your file with the "osgearth_shadergen" extension (like myfile.obj.osgearth_shadergen).

**Comment by marcoma9023** [comment]
Thanks for the reply Glenn,

The object is readed by  `osg::ref_ptr<osg::Node> node =osgDB::readRefNodeFile("C:/ProgramData/ELMAN/resources/3D/ModelResized/test.obj.1000.scale.osgearth_shadergen");`

and added to the mapNode `osgEarth::GeoPoint wgsPoint10(mapNode->getMapSRS()->getGeographicSRS(), 13.719437, 45.548689, 10);

	osgEarth::GeoTransform* xform = new osgEarth::GeoTransform();
	xform->setPosition(wgsPoint10);

	xform->addChild(cubo);

	mapNode->addChild(xform);`

Then, adding the "osgearth_shadergen" extension to the .obj file, I don't have the OpneGL warning, but the behaviour it's strange and you can see it in the following video.

Uploading jKgWdHhF4E.mp4…

Where the model it's a simple cube colored in purple.

**Comment by plevy** [comment]
I was not able to reproduce the color shifting, but generally, material colors are going to be harder to use at this point.  You can see it work using the old phong lighting model using osgearth_viewer --sky-low  
and I just used your model in feature_models.earth to quick test.

Otherwise, I would use a different coloring method like face colors or textures if you want to use the more advanced lighting models.  I'd also consider using osg format rather than obj.  You can use osgconv to convert from obj to osg
