### ISSUE TITLE
hide the global

### ISSUE THREAD

**Issue by xuncanzhe** [gwaldron/osgearth#2149]
how can i disable(hide) the global model？

**Comment by gwaldron** [comment]
Try setting the MapNode's node mask to zero.
```c++
mapNode->getNodeMask(0);
```

**Comment by xuncanzhe** [comment]
> 尝试将 MapNode 的节点掩码设置为零。
> 
> ```c++
> mapNode->getNodeMask(0);
> ```

thanks for your reply. Actually I want to hide only the terrain globe.  looks like it will hide all layer data if using mapNode->setNodeMask(0), including modellayer. Which interface should I use to hide only the terrain globe?

**Comment by xuncanzhe** [comment]
> Maybe try this:
> 
> ```c++
> mapnode->getTerrainEngine()->getNode()->setNodeMask(0);
> ```

thanks very much. mapnode->getTerrainEngine()->setNodeMask(0); is working
