### ISSUE TITLE
[osgearth_conv] Error initializing output: No plugin found to load format "tif"

### ISSUE THREAD

**Issue by Eric-Sunjian** [gwaldron/osgearth#2156]
when i Execute the code "osgearth_conv --in driver GDALElevation --in url DEM_WGS84.tif --out driver MBTilesElevation --out filename myData.mbtiles --out format tif" ,That error appeard.

**Comment by gwaldron** [comment]
Did you build OpenSceneGraph yourself? Is it possible you built it without support for the tiff plugin?
