### ISSUE TITLE
Crash when using async layers

### ISSUE THREAD

**Issue by HerryJessica** [gwaldron/osgearth#2157]
I have two Imagelayers both added to the map and one of them is slow to access which is causing my other layer to block!
How can I make them not affect each other

osgEarth::XYZImageLayer* layer1= new osgEarth::XYZImageLayer();
layer1->setURL("http://c.tile.opencyclemap.org/cycle/{z}/{x}/{y}.png");//
 layer1->setProfile(osgEarth::Profile::create("spherical-mercator"));
 m_map->addLayer(layer1)

 osgEarth::XYZImageLayer* layer2= new osgEarth::XYZImageLayer();
layer2->setURL("***************************");
layer2->setProfile(osgEarth::Profile::create("spherical-mercator"));
m_map->addLayer(layer2)

If layer1 access is slow, layer2 access is slow

**Comment by gwaldron** [comment]
You can try using the experimental `async` property to make layers load asynchronously with respect to each other. Like I say, it's experimental.
```c++
layer->setAsyncLoading(true);
```

**Comment by HerryJessica** [comment]
I tried this method but it doesn't seem to work

**Comment by HerryJessica** [comment]
When I set "layer->setAsyncLoading(true);" to these two layers, an exception occurred. It seems that it is caused by thread mutual exclusion. I don't know if you have such a situation. @gwaldron

**Comment by gwaldron** [comment]
Are you using osgEarth 3.3?
Do you have a stack trace?

**Comment by HerryJessica** [comment]
the version is osgEarth3.2
When I load two layers asynchronously at the same time, I find the following _sourceUID  @gwaldron 
![image](https://user-images.githubusercontent.com/44019088/200221739-8027bc98-3c3e-47f5-8822-b1dcb804e760.png)
![image](https://user-images.githubusercontent.com/44019088/200221767-dcb86c1d-2f95-4a17-836c-7ecd40ea2a2d.png)

**Comment by HerryJessica** [comment]
At the same time, I also found that when I only async on one layer, it works normally
