### ISSUE TITLE
strange behavior using highlight_shader from osgearth_pick app

### ISSUE THREAD

**Issue by quentinBdr** [gwaldron/osgearth#2177]
I'm using osgearh v3.3 build with GL3 profile. Here's the capabilities :
![oe_cap](https://user-images.githubusercontent.com/15386075/199669088-9153e330-8fc1-4c10-89ca-9a7cca0b2028.png)

In my app I have several nodes that tag themselves through the Registry like so :
`osgEarth::Registry::objectIndex()->tagNode`

I have a custom mouse "picker" that interact with the nodes that are tagged, and it got the same shader that is available in osgearth_pick application.

The problem I have is : when I have all the node in the frustum, it's all OK. But when certain nodes are not visible, then the shader does not hightlight the right node. Even hough the indexes are still correct. I've got the same behavior if I orient the camera certain ways. Sometimes it hightlights multiple nodes.

I struggle to find explanation for this behavior, maybe you can ?

Thanks

**Comment by gwaldron** [comment]
Closing as stale - if you want to re-open with sample code please do.
