### ISSUE TITLE
https WMS maps on Windows

### ISSUE THREAD

**Issue by Thomas-Lerman** [gwaldron/osgearth#2212]
We recently have been running into more need to get WMS maps through https on Windows. I remembered we need to have cURL compiled with SSL support. osgEarth still was not getting the data. So, using the "curl -g" command in the command-line where the libcurl.dll is located, I tried getting a few files on different websites. I keep getting the same issue unless I use the "-k" command-line option. I have tried asking several people about it and nobody seems to know the answer. Do we need to put in a certificate in the same directory and a specific name? Do we need to distribute the certificate with our software and do we need to install it? If there some configuration or something else that I am missing. We are able to get https pages through Qt and do not think it has a certificate, but could be wrong?

`curl: (60) SSL certificate problem: unable to get local issuer certificate
More details here: http://curl.haxx.se/docs/sslcerts.html

curl performs SSL certificate verification by default, using a "bundle" of Certificate Authority (CA) public keys (CA certs). If the default bundle file isn't adequate, you can specify an alternate file using the --cacert option.
If this HTTPS server uses a certificate signed by a CA represented in the bundle, the certificate verification probably failed due to a problem with the certificate (it might be expired, or the name might not match the domain name in the URL).
If you'd like to turn off curl's verification of the certificate, use the -k (or --insecure) option.`

**Comment by gwaldron** [comment]
Since version 3.0, osgEarth disables self-signed peer authentication (just like the --insecure option). Which version are you using?

**Comment by Thomas-Lerman** [comment]
Yes, we are unfortunately on an older version. However, I am still seeing
curl_easy_setopt( _curl_handle, CURLOPT_SSL_VERIFYPEER, (void*)0 );
which I believe is the same as --insecure or -k. Am I missing something or incorrect? I tried finding the commit, but probably did not go back far enough.

**Comment by gwaldron** [comment]
Is the WMS server publicly accessible and if so can you share the link?

Otherwise, if you are on Windows, you can try building osgEarth with the CMAKE option `OSGEARTH_ENABLE_WININET_FOR_HTTP` set to `ON` and see if that works for you. This uses WinInet instead of CURL.

**Comment by Thomas-Lerman** [comment]
I believe I got that part working, but could be wrong. I believe the next issue is that the URL needs a token to be able to get the maps, in other words, the URL needs to have some query fields that I do not see how to specify a couple of fields (token required, not sure about ignoreillegallayers):
https://api.dataforsyningen.dk/orto_foraar_DAF?ignoreillegallayers=TRUE&token=<token-goes-here>
imagery.srs() = "epsg:4326";
imagery.format() = "png";
imagery.layers() = "orto_foraar";
imagery.style() = "";
imagery.transparent() = true;
imagery.tileSize() = 256;

**Comment by Thomas-Lerman** [comment]
I found that the parameters left in the url() stay there and it all works. Not sure if this is good enough or if we would consider token() as an enhancement in the future. For me, this is probably good enough at least for now. If you wish to close, that is fine.
