### ISSUE TITLE
WMS GetCapabilities

### ISSUE THREAD

**Issue by Thomas-Lerman** [gwaldron/osgearth#2213]
I may have missed something simple on this. I have tried a few things to get the capabilities file using osgEarth::Drivers::WMSOptions, but unsuccessful. I have even tried to get the URL through overlay.capabilitiesUrl().value(). and again nothing. Any help would be appreciated.

**Comment by gwaldron** [comment]
To get the WMS Capabilities manually, you can use the `osgEarth::WMS::CapabilitiesReader` class in `<osgEarth/WMS>`.
