### ISSUE TITLE
ObjectIDPicker woks for OSG?

### ISSUE THREAD

**Issue by Robert-Earth** [gwaldron/osgearth#2214]
@ gwaldron 
ObjectIDPicker works for osgearth very effenciently, I try to use it in OSG for picking objects, but it fails. I am just wondering  such a good tool is suitable for OSG scence.

 Appreciate all the helps

**Comment by gwaldron** [comment]
Are you saying you tried to use it outside of osgEarth? It is tied to osgEarth's VirtualProgram shader-based rendering framework, so it probably will not function outside an osgEarth context.

**Comment by Robert-Earth** [comment]
yes, I hope to use it outside of osgEarth, actually in osg, since its method is more effencient and more accurated in selecting objects.

**Comment by gwaldron** [comment]
No one has attempted to port it to a pure OSG application. You will have to port the shaders to work outside of the VirtualProgram framework. GOod luck!
