### ISSUE TITLE
Zip driver build issue

### ISSUE THREAD

**Issue by RhythmOfTension** [gwaldron/osgearth#2219]
Currently, there are several issues with osgearth's zip driver
1) libzip package searched as follows:
```
if(OSGEARTH_BUILD_ZIP_PLUGIN)
    find_package(LIBZIP)
endif()
```
But script itself in CMakeModules called FindLibZip.cmake, and i think find_package is case sensitive.

2) There is probably typo in CMakeLists.txt for zip driver, `OSGEARTH_BUILD_ZIP_PLUGIN` option called here `BUILD_OSGEARTH_ZIP_PLUGIN`

3) If 1 and 2 is fixed, looks like produced library name will be the same as OpenSceneGraph's zip plugin (which is probably also optional, but anyway). Is it intended? Even if they didn't have the same name, which plugin will be used for zipped files?

**Comment by gwaldron** [comment]
Thanks -- I pushed fixes for (1) and (2).

The osgEarth ZIP plugin is a replacement for the OSG plugin; you only need one or the other.
The only difference is that the osgEarth ZIP plugin supports ZIP archives greater than 2GB in size.
