### ISSUE TITLE
OSG can't find plugins

### ISSUE THREAD

**Issue by OlaRune** [gwaldron/osgearth#2223]
Hi! I'm new to both OSG and OSG Earth, so the solution to this issue is likely trivial.

I have installed OSG Earth and all dependencies using vcpkg as recommended in the documentation, and used `vcpkg integrate install` for simple integration with Visual Studio, as recommended in the vcpkg documentation.

Now I'm trying to write a minimal first program to load the `simple.earth` file included with OSG Earth.

Doing
`osg::ref_ptr<osg::Node> node = osgDB::readNodeFile("simple.earth");`
gives me the following output
`Error reading file simple.earth: file not handled`

From looking at the OSG documentation I am under the impression that I would get a "file not found" error if that was the problem. I've tried changing `"simple.earth"` to something like `"asdasdasdasdasd.earth"`, that doesn't exist, and I still get the same "file not handled" error, which makes me believe that OSG can't find the plugin. I also tried `"asdasdasd.osg"`, but this changes nothing, so I guess OSG can't even find its own plugins.

Looking at my vcpkg directory I can see that the plugins are placed in `vcpkg\installed\x64-windows\plugins\osgPlugins-3.6.5\ `and there seems to be both OSG and OSG Earth files there.

Does anyone know what I need to do to help OSG find the plugins?

**Comment by gwaldron** [comment]
Hello and welcome to osgEarth :)

Make sure you have both `vcpkg\installed\x64-windows\bin` and `vcpkg\installed\x64-windows\plugins` in your path.

**Comment by OlaRune** [comment]
> Hello and welcome to osgEarth :)
> 
> Make sure you have both `vcpkg\installed\x64-windows\bin` and `vcpkg\installed\x64-windows\plugins` in your path.

Thank you! I have them in my path, but that doesn't make a difference, any other ideas?

Just a quick sanity check, if the `simple.earth` file and the referenced `world.tif` file are in the same directory as my compiled .exe it should be discoverable by just loading the filename without its full path, right?

**Comment by gwaldron** [comment]
It will find `simple.earth` in the current folder. The location of `world.tif` is in the earth file, relative to the location of the earth file.

You can set the environment variable `OSG_NOTIFY_LEVEL=DEBUG` and it will print out gobs of information of where it's looking for plugins.

**Comment by OlaRune** [comment]
> It will find `simple.earth` in the current folder. The location of `world.tif` is in the earth file, relative to the location of the earth file.
> 
> You can set the environment variable `OSG_NOTIFY_LEVEL=DEBUG` and it will print out gobs of information of where it's looking for plugins.

Thanks again, now I've progressed a bit by turning on debug output with the environment variable and seeing that it fails loading a few dll files. `osgdb_serializers_osgd.dll` , `osgdb_osgd.dll`, `osgdb_earthd.dll`, `osgdb_zipd.dll`, `osgdb_freetyped.dll`.

After searching for the files I found them in `vcpkg\installed\x64-windows\debug\plugins`, after adding that to the path I no longer get the `file not handled` error.

However, now it fails when loading `osgdb_osgearth_gdalimaged.dll` and `osgEarthGdalimaged.dll`. I have tried searching for these files as well and I can't find them anywhere on my system.

Am I supposed to have those?

**Comment by gwaldron** [comment]
No; there are no such DLLs.
Are you able to run `osgearth_version --caps` and post the output?

**Comment by OlaRune** [comment]
I got it to work despite the warnings about missing GDAL-files mentioned above,.

I would also prefer not using the files under `installed/x64-windows/debug`, but they seem to only have been built for the debug target. Is `vcpkg install osgearth:x64-windows` supposed to build them for release? Do I have to build osgearth manually to get them?

**Comment by OlaRune** [comment]
Okay, I've figured this out now, and I feel kinda stupid for not realizing this immediately. Putting it here if someone else fins this in the future.

When compiling your application for debug you need to put `installed/x64-windows/debug/bin` and `installed/x64-windows/debug/plugins` in your path.

When compiling your application for release you need to put `installed/x64-windows/bin` and `installed/x64-windows/plugins` in your path.

@gwaldron I'm closing this issue, thanks for your help.

**Comment by OlaRune** [comment]
Okay, I've figured this out now, and I feel kinda stupid for not realizing this immediately. Putting it here if someone else finds this in the future.

When compiling your application for debug you need to put `installed/x64-windows/debug/bin` and `installed/x64-windows/debug/plugins` in your path.

When compiling your application for release you need to put `installed/x64-windows/bin` and `installed/x64-windows/plugins` in your path.

@gwaldron Closing this issue, thanks for your help.

**Comment by gwaldron** [comment]
It's not you; the setup of those vcpkg file location is kind of weird. Anyway, I'm glad you got it working. Again I recommend not using DEBUG mode for osg or osgEarth apps ... RelWithDebInfo is much better and still gives you decent debugging info. Cheers.

**Comment by element207** [comment]
> Hello and welcome to osgEarth :)
> 
> Make sure you have both `vcpkg\installed\x64-windows\bin` and `vcpkg\installed\x64-windows\plugins` in your path.

thank you very much, I've tried all solutions, this way did work! wow, I could cry I think!!!!!

**Comment by element207** [comment]
> Hello and welcome to osgEarth :)
> 
> Make sure you have both `vcpkg\installed\x64-windows\bin` and `vcpkg\installed\x64-windows\plugins` in your path.

thank you very much, I've tried all sulotions, your way
