### ISSUE TITLE
How do I pass options to GDAL

### ISSUE THREAD

**Issue by OlaRune** [gwaldron/osgearth#2227]
Hello!

I'm trying to use GDAL to load a geotiff, and I get the following error:
`[osgEarth]  [GDAL] The definition of projected CRS EPSG:3006 got from GeoTIFF keys is not the same as the one from the EPSG registry, which may cause issues during reprojection operations. Set GTIFF_SRS_SOURCE configuration option to EPSG to use official parameters (overriding the ones from GeoTIFF keys), or to GEOKEYS to use custom values from GeoTIFF keys and drop the EPSG code. (error 1)`

Is there a way to set `GTIFF_SRS_SOURCE=GEOKEYS` in the earth file?

**Comment by leadcoder** [comment]
Have you defined the gdal_data and proj_lib environment variables?

**Comment by gwaldron** [comment]
You cannot set them in the earth file. You can try calling `CPLSetConfigOption()` from your code, or use one of the methods described [here](https://gdal.org/user/configoptions.html).

**Comment by OlaRune** [comment]
> Have you defined the gdal_data and proj_lib environment variables?

It turned out that by proj_lib variable was set to the wrong directory. After fixing this GDAL doesn't complain anymore. Thanks!

**Comment by chl916185** [comment]
> > Have you defined the gdal_data and proj_lib environment variables?
> 
> It turned out that by proj_lib variable was set to the wrong directory. After fixing this GDAL doesn't complain anymore. Thanks!

@OlaRune 
how to do it?
