### ISSUE TITLE
"PickerGUI" No such file and directory

### ISSUE THREAD

**Issue by ScienceGeekxx** [gwaldron/osgearth#2229]
![image](https://user-images.githubusercontent.com/13169194/221118664-d0b05f15-a035-4a70-91d5-9a3ec7cf5e27.png)

hi,
here, if miss "ImGui/PickerGUI" ？i‘m not sure, maybe you can check it.
when i install a RELEASE and included in my project, i get "PickerGUI" No such file and directory.

**Comment by gwaldron** [comment]
Thanks. I have added this to the CMakeLists.txt.
FYI - I don't think that PickerGUI actually works - but at least you will not get the error now.
