### ISSUE TITLE
the outline color is not right when osgFX::outline in Qt 

### ISSUE THREAD

**Issue by lqzer** [gwaldron/osgearth#2233]
I want use osgFX::Outline to heighlight model in my Qt Application,but the outline color is not right color. I load cow model and a Box ,I set outline color is yellow.

         osg::ref_ptr<osg::Node> node = new osg::ShapeDrawable(new osg::Box(osg::Vec3(0, 0, 0), 30, 30, 30));
	//osgDB::readNodeFile("F:/ComputeGraph/VS2019/GLFixed/osg/OpenSceneGraph-Data/cow.osg");
	osg::ref_ptr<osgFX::Outline> outline = new osgFX::Outline();
	outline->addChild(node);
	outline->setWidth(10.0f);
	outline->setColor(osg::Vec4(1.0, 1.0, 0.0, 1.0f));
	osgEarth::Registry::instance()->shaderGenerator().run(outline);
	osg::ref_ptr<osgEarth::GeoPositionNode> positionNode = new osgEarth::GeoPositionNode();
	osgEarth::GeoPoint geoPoint(m_mapNode->getMap()->getSRS()->getGeographicSRS(), osg::Vec3(120.0, 30.0,200));
	osgEarth::Viewpoint viewPoint;
	viewPoint.focalPoint() = geoPoint;
	viewPoint.heading() = osgEarth::Angle(0, osgEarth::Units::DEGREES);
	viewPoint.pitch() = osgEarth::Angle(-90, osgEarth::Units::DEGREES);
	viewPoint.range() = osgEarth::Distance(100, osgEarth::Units::METERS);
	m_earthManipulator->setViewpoint(viewPoint);
	osg::Matrix matrix;
	geoPoint.createLocalToWorld(matrix);
	positionNode->getGeoTransform()->setMatrix(matrix);
	positionNode->getPositionAttitudeTransform()->addChild(outline);
	m_mapNode->addChild(positionNode);
![box](https://user-images.githubusercontent.com/11313461/222898431-350b9686-bb0d-44ac-950b-9a19c7f42fcf.png)
![cow](https://user-images.githubusercontent.com/11313461/222898438-ffc4145b-8154-4daa-a349-6794deff9ed5.png)

and I have set camera stencil buffer and clean stencil buffer.
        osg::DisplaySettings::instance()->setMinimumNumStencilBits(1);
	m_viewer->getCamera()->setClearMask(m_viewer->getCamera()->getClearMask() | GL_STENCIL_BUFFER_BIT);
	m_viewer->getCamera()->setClearStencil(0);

F:\ComputeGraph\VS2019\GLFixed\osgEarth\bin>osgearth_version.exe --caps
[osgEarth]  [Capabilities] Capabilities:
[osgEarth]  [Capabilities]   osgEarth Version:  3.2.0 build 113
[osgEarth]  [Capabilities]   OSG Version:       3.6.5
[osgEarth]  [Capabilities]   GDAL Version:      2.4.4
[osgEarth]  [Capabilities]   GEOS Version:      3.5.2
[osgEarth]  [Capabilities]   GPU Vendor:        NVIDIA Corporation
[osgEarth]  [Capabilities]   GPU Renderer:      NVIDIA GeForce GTX 1660 SUPER/PCIe/SSE2
[osgEarth]  [Capabilities]   GL/Driver Version: 4.6.0 NVIDIA 496.13
[osgEarth]  [Capabilities]   GL Core Profile:   no

**Comment by gwaldron** [comment]
The osgFX outline probably does not work within osgEarth's shader-based framework. 
You might try adding your model/outline outside of the MapNode, and removing the shader generation step.

Also, your use of the GeoPositionNode is overly complicated. You can just say
```c++
auto xform = new GeoTransform();
xform->setPosition(GeoPoint(...));
xform->addChild(model);
```
