### ISSUE TITLE
 Could not find a package configuration file provided by "git" 

### ISSUE THREAD

**Issue by leelongcrazy** [gwaldron/osgearth#2249]
when I execute this command `cmake ..`
occuered this bellow: 
```
-- Submodule update
-- Found libzip: /usr/lib/x86_64-linux-gnu/libzip.so
-- Found GDAL 3.4.1
-- Found OSG version 3.7.0
-- Creating /xxx/osgearth/build/build_include/osgEarth/BuildConfig.h
CMake Warning at src/osgEarth/CMakeLists.txt:514 (find_package):
  By not providing "Findgit.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "git", but
  CMake did not find one.

  Could not find a package configuration file provided by "git" with any of
  the following names:

    gitConfig.cmake
    git-config.cmake

  Add the installation prefix of "git" to CMAKE_PREFIX_PATH or set "git_DIR"
  to a directory containing one of the above files.  If "git" provides a
  separate development package or SDK, be sure it has been installed.


-- Building osgEarth as a SHARED library
-- INCDIR: /usr/local/include
-- Configuring done
-- Generating done
-- Build files have been written to: /xxx/osgearth/build
```

**Comment by regous** [comment]
maybe cuz vcpkg.json, remove it temporary

**Comment by leelongcrazy** [comment]
> 

I tried this ,but it doesn't work.

**Comment by plevy** [comment]
Ah ok, maybe we have different versions of cmake, here is my version:

-- Creating M:/osgearth/build/build_include/osgEarth/BuildConfig.h
CMake Warning (dev) at C:/Program Files/CMake/share/cmake-3.19/Modules/FindPackageHandleStandardArgs.cmake:426 (message):
  The package name passed to `find_package_handle_standard_args` (Git) does
  not match the name of the calling package (git).  This can lead to problems
  in calling code that expects `find_package` result variables (e.g.,
  `_FOUND`) to follow a certain pattern.
Call Stack (most recent call first):
  C:/Program Files/CMake/share/cmake-3.19/Modules/FindGit.cmake:96 (find_package_handle_standard_args)
  M:/osgearth/vcpkg/scripts/buildsystems/vcpkg.cmake:852 (_find_package)
  src/osgEarth/CMakeLists.txt:514 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

I am still thinking that was just a warning on yours, config and generate should have worked

**Comment by plevy** [comment]
Sorry, I should halve looked closer at which CMakelists, fixed it
