### ISSUE TITLE
Line with text label sometimes does not render

### ISSUE THREAD

**Issue by gwaldron** [gwaldron/osgearth#2251]
### Discussed in https://github.com/gwaldron/osgearth/discussions/2250

<div type='discussions-op-text'>

<sup>Originally posted by **OlaRune** March 30, 2023</sup>
Hello!

I'm trying to draw lines between points that the user clicks with the mouse. I had this working fully as intended, but after adding a `TextSymbol` to the style, the line sometimes doesn't render. It renders about 90% of the times, but sometimes I get the following error:

```
glLinkProgram 000001BDEC03C1B0"osgEarth::LineDrawable" FAILED
Program "osgEarth::LineDrawable" infolog:
Attached vertex shader is not compiled.

[osgEarth]  [ScreenSpaceLayout] Decluttering VP installed
[osgEarth]* [VirtualProgram] Program will not link!
```

Sometimes I get this error instead (maybe depends on zoom level):

```
glLinkProgram 000001BDEDE0ED70"osgEarth::LineDrawable" FAILED
Program "osgEarth::LineDrawable" infolog:
Attached fragment shader is not compiled.

[osgEarth]* [VirtualProgram] Program will not link!
```

What does this mean, why does it only happen 10% of the times? How do I fix it?</div>

**Comment by gwaldron** [comment]
It sounds like a shader error -- could you provide a minimal .cpp we can use to reproduce the problem?
Is this in the master branch?
(converted this to an Issue for tracking.)

**Comment by OlaRune** [comment]
Okay, I've fixed the problem in an incredibly ugly way.

This is what I did to cause it (indirectly):
- Every time the mouse moves I remove a line from my layer, calculate a new line, and add it again.
- The calling of `viewer->frame()` was done from another thread.

This is what I did to fix it, at least temporarily (forgive me...):
- Sleep for one millisecond between removing the old line and adding the new.

Maybe this has to do with the removal and the addition of a line happening within a single viewer frame, or maybe in two different frames. I don't know.

@gwaldron My specific problem is fixed, if you want to close this issue it's okay by me. If you think something needs to be fixed in OSG Earth you can keep it for tracking purposes.

**Comment by OlaRune** [comment]
I slowed down calling `viewer-frame()` from ASAP to about 60 Hz and removed the sleep period mentioned above. And that also solves the problem,.

I think the shader error is caused by removing/adding lines during a frame update, so I guess it could still happen if I'm unlucky.

**Comment by gwaldron** [comment]
Gotcha. A cardinal rule of any OpenSceneGraph application is that updates to the scene graph must be synchronous with respect to the frame loop. IOW you cannot alter the scene graph from another thread without careful locking.
The "best practice" is to make such changes during OSG's update traversal; you can either queue an Update operation to the Viewer's update operation queue, or you can install an update callback on a node.

**Comment by OlaRune** [comment]
> Gotcha. A cardinal rule of any OpenSceneGraph application is that updates to the scene graph must be synchronous with respect to the frame loop. IOW you cannot alter the scene graph from another thread without careful locking.
> The "best practice" is to make such changes during OSG's update traversal; you can either queue an Update operation to the Viewer's update operation queue, or you can install an update callback on a node.
> 

Oh, I see. I didn't know it was a problem. I'll handle it with semaphores or mutex then. Thanks!

**Comment by OlaRune** [comment]
I'm not so sure about this anymore. I'm doing my updates based on user actions caught in an GUIEventHandler that I've added to the viewer. Shouldn't these already be a part of the update traversal initiated by calling `viewer->frame()`?

**Comment by gwaldron** [comment]
oops, this fell through the cracks..
The answer is, the events are processed during the Event traversal, which allows overlap with the previous frame's draw. You could try running your program in SingleThreaded mode (--SingleThreaded) and see if that resolves the issue.
