### ISSUE TITLE
getWorldCoordsUnderMouse() returns true while giving invalid coordinates

### ISSUE THREAD

**Issue by OlaRune** [gwaldron/osgearth#2252]
If the mouse is outside the terrain (but still in the viewer window) the function
```
bool osgEarth::Terrain::getWorldCoordsUnderMouse(
            osg::View*  view,
            float       mx,
            float       my,
            osg::Vec3d& out_world ) const;
```
returns `true` along with `out_world` being `{0, 0, 0}`.

In my opinion it should return `false` if it couldn't find valid coordinates at the mouse point.

**Comment by gwaldron** [comment]
Version? Could not reproduce in the master branch.
