### ISSUE TITLE
Skynode weird image

### ISSUE THREAD

**Issue by coderc264** [gwaldron/osgearth#2253]
Hello, i'm trying to port an old osgearth (v2.8) application to a recent vcpkg osgearth release. 
I have a problem with SkyNode i've both tried to attach a SkyNode and an Sky simple extension to a viewer but unfortunately I get an image with nothing in the first case and an image with a very intense light and without moon and sun in the second case.

VCPKG version: 2023-03-29-664f8bb619b752430368d0f30a8289b761f5caba
Windows 11
Visual Studio 2022 v17.5.3

First case:

`SkyOptions skyOptions;
       
        skyOptions.coordinateSystem() = SkyOptions::COORDSYS_ECI;

        SkyNode* sky = SkyNode::create(skyOptions);

        cout << "Support GLSL: " << std::boolalpha << Registry::capabilities().supportsGLSL() << "\n";

        sky->setAtmosphereVisible(true);
        sky->setSunVisible(true);
        sky->setStarsVisible(true)`

Second one:

`Extension *skyExtension = Extension::create("sky_simple", osgEarth::ConfigOptions());
ConfigOptions opts = skyExtension->getConfigOptions();
mapNode->addExtension(skyExtension);`
![skynode](https://user-images.githubusercontent.com/38565114/229343281-1b9b9b57-e246-43f5-af90-ef356d5813b3.png)
![extension](https://user-images.githubusercontent.com/38565114/229342974-d772870f-a2dc-4243-9b35-4618d9dd743a.png)

**Comment by gwaldron** [comment]
Try version 3.5, where we tweaked the lighting model to have a proper exposure value.
