### ISSUE TITLE
ImGui con't resolve symbol

### ISSUE THREAD

**Issue by YiXiaoKezz** [gwaldron/osgearth#2255]
I'm using ObjectIDPicker according to osgearth_pick.cpp, and encounter this, I can't find its declaration.

**Comment by YiXiaoKezz** [comment]
![image](https://user-images.githubusercontent.com/28296259/230320233-053b26cd-8209-47b7-94f6-12ab9baaa521.png)

**Comment by gwaldron** [comment]
Encounter what?

**Comment by YiXiaoKezz** [comment]
> Encounter what?
ImGui con't resolve symbol
