### ISSUE TITLE
RTTPicker dont work in OE3.2.0

### ISSUE THREAD

**Issue by YiXiaoKezz** [gwaldron/osgearth#2258]
When I change my environment from oe2.10.1 to oe3.2.0, RTTPicker dont work. 
Some of my code:
```C++
struct PlaceNodePickerCallback : public osgEarth::Util::RTTPicker::Callback
{
	PlaceNodePickerCallback() = default;
	void onHit(osgEarth::ObjectID id)	
	{
		osg::ref_ptr<osgEarth::PlaceNode> placeNode = osgEarth::Registry::objectIndex()->get<osgEarth::PlaceNode>(id).get();
...
       }
	bool accept(const osgGA::GUIEventAdapter& ea, const osgGA::GUIActionAdapter& aa) 
	{
		if ((ea.getEventType() == osgGA::GUIEventAdapter::PUSH) && (ea.getButtonMask() == osgGA::GUIEventAdapter::RIGHT_MOUSE_BUTTON))
             {
             }
      }
}
```
 When I add placeNode, I register it by this:
osgEarth::Registry::objectIndex()->tagNode(node, node);

At last, add RTTPicker:

		viewer->stopThreading();
		auto picker = new osgEarth::Util::RTTPicker();
		picker->addChild(myViewerWidget->getOsgFrame()->getRoot());
		picker->setDefaultCallback(new PlaceNodePickerCallback());
		viewer->addEventHandler(picker);
		viewer->startThreading();

but my callback just cant work, it worked with oe2.10.1

**Comment by gwaldron** [comment]
RTTPicker was replaced with ObjectIDPicker a while back. Please look at the example osgearth_picker.cpp for an example.
