### ISSUE TITLE
IMGUI SceneGraphGUI doesn't compile with c++ 11 on XCode 14.2

### ISSUE THREAD

**Issue by gwaldron** [gwaldron/osgearth#2272]
### Discussed in https://github.com/gwaldron/osgearth/discussions/2271

<div type='discussions-op-text'>

<sup>Originally posted by **remoe** April 21, 2023</sup>
When one add:

```CMAKE_CXX_STANDARD:STRING=11```

to build osgearth/master with XCode 14.2 it throws a build error on imgui/scenegraphgui.

to fix this, one can add the following to SceneGraphGUI.cpp file:

```c++
#if __cplusplus < 201402L
namespace std {
    template <> struct hash<osg::Drawable::AttributeTypes> {
        size_t operator() (const osg::Drawable::AttributeTypes& t) const { return size_t(t); }
    };
}
#endif
```

But when one add:

```CMAKE_CXX_STANDARD:STRING=14```

Then the code build without this patch. </div>

**Comment by remoe** [comment]
The XCode build is solved by https://github.com/gwaldron/osgearth/pull/2275.

But osgEarth doesn't have a c++ 14 requirement?

**Comment by gwaldron** [comment]
You are correct - osgEarth does not have a C++14 requirement.
I patched SceneGraphGUI so it uses a `std::map` instead of a `std::unordered_map`; this should resolve the issue.
