### ISSUE TITLE
Why not support NVGL

### ISSUE THREAD

**Issue by Robert-Earth** [gwaldron/osgearth#2277]
I'm using an RTX 3090 graphics card, but why does my application show that it's using GL3.3 LayerDrawableGL3?
Trace: GL2->glVersion=3.3

E:\vcpkg-master\osgearth-master\lib\Release>osgearth_version --caps
[osgEarth]  [Registry] Note: GDAL_DATA environment variable is not set
[osgEarth]  [Capabilities] Capabilities:
[osgEarth]  [Capabilities]   osgEarth Version:  3.3.0 build 136
[osgEarth]  [Capabilities]   OSG Version:       3.6.5
[osgEarth]  [Capabilities]   GDAL Version:      3.4.3
[osgEarth]  [Capabilities]   GEOS Version:      3.10.2
[osgEarth]  [Capabilities]   GPU Vendor:        NVIDIA Corporation
[osgEarth]  [Capabilities]   GPU Renderer:      NVIDIA GeForce RTX 3090/PCIe/SSE2
[osgEarth]  [Capabilities]   GL/Driver Version: 4.6.0 NVIDIA 512.15 (460)
[osgEarth]  [Capabilities]   GL Core Profile:   yes

**Comment by gwaldron** [comment]
You must activate NVGL by either
- Using `--nvgl` on the command line; or
- Setting the environment variable `OSGEARTH_USE_NVGL`; or
- Calling `GLUtils::useNVGL(true);` in your code.

**Comment by Robert-Earth** [comment]
> You must activate NVGL by either
> 
> * Using `--nvgl` on the command line; or
> * Setting the environment variable `OSGEARTH_USE_NVGL`; or
> * Calling `GLUtils::useNVGL(true);` in your code.

Regardless of the method used, the system always uses GL3. The reason for this is that "const osg::GL2Extensions* GL2 = osg::GL2Extensions::Get( id, true )" retrieves "GL2->glVersion=2.999995", which causes "_supportsNVGL" to be false.

So, I guess the system get a wrong GL2->glVersion?

**Comment by Robert-Earth** [comment]
use glGetString(GL_VERSION) get machine openGL 4.6.0, why osgearth get GL2->glVersion=3.29999995
