### ISSUE TITLE
Can not display when try to draw path FeatureNode in osgearth3.3

### ISSUE THREAD

**Issue by FuXiii** [gwaldron/osgearth#2285]
The code:

![image](https://github.com/gwaldron/osgearth/assets/40132375/e131a4bc-066c-4461-9644-96c918963c7c)

The result:
![image](https://github.com/gwaldron/osgearth/assets/40132375/c3250641-570e-4988-a5ff-f321952ed1d2)

Display nothing only the text lable.

**Comment by gwaldron** [comment]
Are you running the `osgearth_annotation` example app? Or is this your own code?

**Comment by FuXiii** [comment]
This code copy from `osgearth_annotation`. If I only run `osgearth_annotation` with `simple.earth`:
![image](https://github.com/gwaldron/osgearth/assets/40132375/d7934570-ff6d-4889-92b2-9428255a2cfa)
![image](https://github.com/gwaldron/osgearth/assets/40132375/06a288ae-c591-43c8-8279-0d363887d3a9)

**Comment by gwaldron** [comment]
Created a new issue for the osgearth_annotation problem. #2288

**Comment by FuXiii** [comment]
Sorry. I forgot to call `GLUtils::setGlobalDefaults(camera->getOrCreateStateSet());` , after that it worked well.
This `Can not display when try to draw path FeatureNode` issue had been fixed. But [osgearth_annotation - exits on startup](https://github.com/gwaldron/osgearth/issues/2288) issue still have.
