### ISSUE TITLE
Osgearth with Intel uhd graphics 630

### ISSUE THREAD

**Issue by winter2011y** [gwaldron/osgearth#2290]
Hello, all
I'm using intel uhd graphics 630 and tried to compile, run osgearth 3.4 with osg 3.7 (master branch as 20 May 2023). I also tried compile and run with others version osgearth (3.3) and osg 3.6.5. I compile osg (3.7 and 3.6.5) with gl3, and also gl1+gl2. When i run osgearth_toc with 1 file (*.tif), it's okey. But when i run osgearth_toc with map file and elevation file, i received flashing scene like as

https://github.com/gwaldron/osgearth/assets/56222342/e3020a39-1555-42e6-8d23-45af6323320d
Please, help me...

**Comment by gwaldron** [comment]
This looks like a problem with the driver. Sorry we can't be of more help.
