### ISSUE TITLE
Nullify elevation in GDALImageLayer

### ISSUE THREAD

**Issue by raghulsekar** [gwaldron/osgearth#2291]
I need to display an image or a raster file at a specific height using osgEarth without the elevation affecting the imageLayer eventhough the elevation layer is present. 

![Screenshot 5](https://github.com/gwaldron/osgearth/assets/27352710/8ca51b6d-ce7b-46c3-a369-6635c8f2d0b0)
![Screenshot 6](https://github.com/gwaldron/osgearth/assets/27352710/88d3c1b5-6fa8-4a4e-a255-7e34713e1369)

First image is GDALElevationLayer and second is GDALImageLayer so what i need is , is there a possibility to neglect the elevation  for the imagelayer in osgEarth

**Comment by gwaldron** [comment]
There is no "built-in" way to do it, but you can do with with a little shader hack. It does require 2 image layers - in this example I use a ContourMap layer for the ground, and a normal TMS layer for the "floating" data.
```xml
<map>
    <ContourMap/>
    <TMSImage name="Floating imagery" opacity="0.5" altitude="25000">
        <url>http://readymap.org/readymap/tiles/1.0.0/7/</url>
        <shader>
          <![CDATA[
            #pragma vp_function func1, vertex_view, 0.0
            vec3 save;
            void func1(inout vec4 vertex) {
              save = vertex.xyz;
            }
            [break]
            #pragma vp_function func2, vertex_view, 1.0
            vec3 save;
            vec3 oe_UpVectorView;
            uniform float oe_terrain_altitude;
            void func2(inout vec4 vertex) {
              vertex.xyz = save + oe_UpVectorView * oe_terrain_altitude;
            }            
          ]]>
        </shader>
    </TMSImage>
    <TMSElevation name="ReadyMap 90m Elevation">
        <url>http://readymap.org/readymap/tiles/1.0.0/116/</url>
        <vdatum>egm96</vdatum>
    </TMSElevation>
</map>
```

**Comment by raghulsekar** [comment]
Tried the above shaders but still the elevation appears to be the same 
![Screenshot (1)](https://github.com/gwaldron/osgearth/assets/27352710/0c4c29dc-1807-4777-b898-a1ae55387845)
