### ISSUE TITLE
[osgEarth]* [Capabilities] Warning, OpenSceneGraph does not define OSG_GL3_AVAILABLE; the application may not function properly

### ISSUE THREAD

**Issue by DaXiaWei** [gwaldron/osgearth#2295]
[osgEarth]* [Capabilities] Warning, OpenSceneGraph does not define OSG_GL3_AVAILABLE; the application may not function properly
[osgEarth]* WARNING:  Call osgEarth::initialize() before realizing any graphics windows.  There are currently 1 graphics contexts.
Windows Error #2000: Win32WindowingSystem::OpenGLContext() - Unable to restore current OpenGL rendering context. Reason: 无效的像素格式。

PS C:\vcpkg> .\vcpkg.exe install osg:x64-windows
Computing installation plan...
The following packages are already installed:
    osg[core,default-features,fontconfig,freetype,nvtt,openexr,plugins]:x64-windows -> 3.6.5#19
osg:x64-windows is already installed
Restored 0 package(s) from C:\Users\win10\AppData\Local\vcpkg\archives in 70.5 us. Use --debug to see more details.
Total install time: 991 us
The package osg can be configured to use different OpenGL profiles via a custom triplet file.
Possible values are GLCORE, GL2, GL3, GLES1, GLES2, GLES3 and GLES2+GLES3.
The default value is GL2. If you want use other profiles, please add the following
code to a custom triplet file.
set(osg_OPENGL_PROFILE GL3)

PS C:\vcpkg>

**Comment by coderc264** [comment]
Hello, i have a similiar issue, with a simple test program too (Sample main.cpp included in the documentation). After this warning: [osgEarth]* [Capabilities] Warning, OpenSceneGraph does not define OSG_GL3_AVAILABLE; the application may not function properly the program starts but not showing a map

**Comment by gwaldron** [comment]
Someone reverted the OSG vcpkg build to default to GL2. This is unfortunate. We are looking into it.

**Comment by plevy** [comment]
Basically, this happened:
https://github.com/microsoft/vcpkg/issues/25705

They assumed the change broke something but that is just standard for GL3. Let me take a look in the morning.  The old way to do this in vcpkg was to manually set the Cmake flag OSG_GL3_AVAILABLE to ON which set the other necessary flags.  I am just not sure that still works as it has been a long time.

**Comment by plevy** [comment]
The custom triplet code is still there, but the default value was set to GL2.  So for GL3, you will need to look in your triplets folder, copy the one you use, I use x64-windows.cmake so copy that to a file called x64-windows-gl3.cmake.
In that file, mine looks like this:
```
set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)
```
You are going to add the GL3 profile so it looks like this:
```
set(VCPKG_TARGET_ARCHITECTURE x64)
set(VCPKG_CRT_LINKAGE dynamic)
set(VCPKG_LIBRARY_LINKAGE dynamic)
set(osg_OPENGL_PROFILE GL3)
```
Mine is still building but that is the basic idea so installing osg will now be
vcpkg install osg:x64-windows-gl3

**Comment by DaXiaWei** [comment]
Thank you very much for your help. This is a spacecraft simulation project based on osg + osgearth+osgqt. The reason for the problem is that when I built the environment in March, the vcpkg used by default was gl3. At that time, the hardware was a 12th generation Intel notebook with integrated graphics. Later, I tried to move it to a VMware virtual machine and compile and install it using vcpkg again. Then this problem occurred. After consulting materials and everyone’s help and comparing with the previous project, I found that osg did not enable the compilation options related to gl3. I finally used set(osg_OPENGL_PROFILE GL3) option in x64-windows.cmake file to solve the problem and everything runs normally. I tried both set(osg_OPENGL_PROFILE GL3) and set(osg_OPENGL_PROFILE “GL3”) and they both work normally. Thank you all for your help. @gwaldron @jasonbeverage @plevy @coderc264

**Comment by mondayboy1** [comment]
> [osgEarth]* [Capabilities] Warning, OpenSceneGraph does not define OSG_GL3_AVAILABLE; the application may not function properly [osgEarth]* WARNING: Call osgEarth::initialize() before realizing any graphics windows. There are currently 1 graphics contexts. Windows Error #2000: Win32WindowingSystem::OpenGLContext() - Unable to restore current OpenGL rendering context. Reason: 无效的像素格式。
> 
> PS C:\vcpkg> .\vcpkg.exe install osg:x64-windows Computing installation plan... The following packages are already installed: osg[core,default-features,fontconfig,freetype,nvtt,openexr,plugins]:x64-windows -> 3.6.5#19 osg:x64-windows is already installed Restored 0 package(s) from C:\Users\win10\AppData\Local\vcpkg\archives in 70.5 us. Use --debug to see more details. Total install time: 991 us The package osg can be configured to use different OpenGL profiles via a custom triplet file. Possible values are GLCORE, GL2, GL3, GLES1, GLES2, GLES3 and GLES2+GLES3. The default value is GL2. If you want use other profiles, please add the following code to a custom triplet file. set(osg_OPENGL_PROFILE GL3)
> 
> PS C:\vcpkg>

您好，想向您请教下参考文档的那个Sample main.cpp您跑通了吗，我一跑程序就崩溃

**Comment by DaXiaWei** [comment]
你是怎么安装的，也是使用vcpkg吗？

**Comment by DaXiaWei** [comment]
你是怎么安装的 @mondayboy1

**Comment by mondayboy1** [comment]
我是按官网的那个教程，vcpkg install osgearth:x64-windows，但是装完之后Sample main.cpp跑不通

**Comment by mondayboy1** [comment]
> 你是怎么安装的 @mondayboy1

我是按官网的那个教程，vcpkg install osgearth:x64-windows，但是装完之后Sample main.cpp跑不通

**Comment by RDCH106** [comment]
> Someone reverted the OSG vcpkg build to default to GL2. This is unfortunate. We are looking into it.
 
@gwaldron It is not a mistake. You can read the reason here: https://github.com/microsoft/vcpkg/issues/25705#issuecomment-1559702140

**Comment by gwaldron** [comment]
@RDCH106 I know it was intentional. What is unfortunate is that the vcpkg team is unwilling to consider a GL3 or GLCORE variation of the OSG package (or so I was told).

**Comment by RDCH106** [comment]
> @RDCH106 I know it was intentional. What is unfortunate is that the vcpkg team is unwilling to consider a GL3 or GLCORE variation of the OSG package (or so I was told).

I think that you can choose that.: https://vcpkg.roundtrip.dev/ports/osg

Try to specify values available as triplets for different builds. Take a look at the usage section of the above link 👆
(I must say that I didn't try it but the documentation says that you can do it)
