### ISSUE TITLE
Can not get the model by add a ModelLayer

### ISSUE THREAD

**Issue by x1244** [gwaldron/osgearth#2298]
When adding a model using a .earth file, everything is OK.
```
    <Model name="axes in sea" paged="true" max_rang="50000">
        <url>axes.osgt.10000.scale.osgearth_shadergen</url>
        <location lat="-2.3717" long="-85.018" alt="200.2"/>
    </Model>
```
But when I add a model using ModelLayer in the program, the model is not added to the correct latitude and longitude, but is placed in the center of the earth. Here I have set up the correct SRS.
```
void addModel(osg::Node* model, osgEarth::Map* themap)
{
   using namespace osgEarth;
   osg::ref_ptr<ModelLayer> mp = new ModelLayer;
   const SpatialReference* srs = themap->getSRS();
   GeoPoint gp(srs, -90.8, 0.33);
   mp->setLocation(gp);
   mp->setNode(model);
   themap->addLayer(mp);
}
```
![model_src](https://github.com/gwaldron/osgearth/assets/63945717/cb85942c-6706-4946-94b5-e66f497980c2)

What is the reason, and how do we get the model to the correct latitude and longitude?

About the SRS
```
    srs->getName(): "WGS84"
    srs->getWKT(): "GEOGCS["unknown",DATUM["WGS_1984",SPHEROID["WGS 84",6378137,298.257223563,AUTHORITY["EPSG","7030"]],AUTHORITY["EPSG","6326"]],PRIMEM["Greenwich",0,AUTHORITY["EPSG","8901"]],UNIT["degree",0.0174532925199433,AUTHORITY["EPSG","9122"]],AXIS["Longitude",EAST],AXIS["Latitude",NORTH]]"
```

**Comment by x1244** [comment]
when use setURL() method，get the model displayed.
```
#if 0
    mp->setNode(model);
#else
    mp->setURL("axes.osgt.1000000.scale");
#endif
```

**Comment by x1244** [comment]
When I put the model under the GeoTransform node and make the location, the model is displayed in the specified location.
At the same time, whether or not the setLocation() of the ModelLayer is set, it does not affect the display position of the model under the GeoTransform node.
```
    //this is OK
    GeoPoint gp(srs, -90.8, 0.33);
    GeoTransform* gt = new GeoTransform;
    gt->setPosition(gp);
    gt->addChild(model);
    mp->setNode(gt);
    mp->setLocation(GeoPoint(srs, -100.0, 5.0)); //has no effect
```
The model set via setURL() is affected by setLocation() and adjusts position. Is this the result of the design, or is it a bug?

**Comment by gwaldron** [comment]
Sounds like a bug - I will tag it and we'll take a look when we get a chance.
Thanks.

**Comment by x1244** [comment]
And the methord setOrientation() has no effect either.
```
    mp->setLocation(GeoPoint(srs, -100.0, 5.0));
    mp->setOrientation(osg::Vec3(120.0, 22.0, 48.0));
```
The .earth file config by orientation also has no effect.
```
	<Model name="axes in sea" paged="true" max_rang="50000">
        <url>axes.osgt.1000.scale.osgearth_shadergen</url>
        <location lat="-2.3717" long="-85.018" alt="200.2"/>
	<orientation>78.0, 35.6, 163.2</orientation>
    </Model>
```

**Comment by gwaldron** [comment]
Bottom line, this layer needs a re-design. The original purpose was only to load models from an earth file. The set/get functions will configure the options, but they do nothing at runtime.
After 3.5 we will look at reworking this layer entirely. For now I will close this issue and open a new feature issue.
