### ISSUE TITLE
Update FeatureModelLayer on the fly failed

### ISSUE THREAD

**Issue by x1244** [gwaldron/osgearth#2310]
I have a `FeatureModelLayer` and want to dynamically update the PointSet in it, and when I use `osgEarth version 3.4` (commit ed410ee952a9ec9f32a414d8179c3a75f62b0a6c), the dynamic update fails without any point output
![2023-07-16-15-32-37-image](https://github.com/gwaldron/osgearth/assets/63945717/5fd53c65-741c-456b-916d-c660882411c2)
And always prompt
```shell
[osgEarth]* ASSERTION FAILURE (redraw @ FeatureModelGraph.cpp:2089) node.valid() ...
[osgEarth]* ASSERTION FAILURE (redraw @ FeatureModelGraph.cpp:2089) node.valid() ...
```
What is the reason for this?

If disable dynamically updated, the initial setting point is displayed, which has output and does not report any errors.
![2023-07-16-15-33-33-image](https://github.com/gwaldron/osgearth/assets/63945717/9d1a7eba-9eef-4d61-82d6-1b9d3e342121)

When I use `osgEarth version 3.3` (commit a4a03147f90fb3be43e10a0b76903179a1e9ae8a), the dynamic update is successful.
![2023-07-16-15-35-18-image](https://github.com/gwaldron/osgearth/assets/63945717/92d99ec9-1c71-49cb-ac49-74dc23c12f98)

I didn't test this intermediate version, but I see that `FeatureModelGraph.cpp` should not have changed.
Part of the code is as follows, first create `FeatureModelLayer`
```cpp
struct FeatureElem{
osgEarth::FeatureModelLayer* fml;
osgEarth::PointSet* pts;
};
FeatureElem createFeatureModelLayer()
{
    using namespace osgEarth;
    osg::ref_ptr<FeatureModelLayer> layer = new FeatureModelLayer;
    osg::ref_ptr<OGRFeatureSource> src = new OGRFeatureSource;
    osg::ref_ptr<PointSet> g = new PointSet; 
    g->push_back(osg::Vec3d(-90.0, 0.0, 0.0));
    src->setGeometry(g);
    layer->setFeatureSource(src);

    Style style;
    PointSymbol* ps = style.getOrCreateSymbol<PointSymbol>();
    ps->size() = 10.0f;
    ps->fill()->color() = Color(osg::Vec4f(0.8, 0.2, 0.8, 0.8));
    ps->smooth() = true;
    osg::ref_ptr<StyleSheet> ss = new StyleSheet;
    ss->addStyle(style);
    layer->setStyleSheet(ss);

    return FeatureElem{layer.release(), g};
}
```
Then define an `Event Handler`
```cpp
class FeatureHandler : public osgGA::GUIEventHandler{
public:
FeatureHandler(FeatureElem f)
  : feature_(f){ }
bool handle (const osgGA::GUIEventAdapter &ea, osgGA::GUIActionAdapter &aa, osg::Object *, osg::NodeVisitor *) override{
    static double lat = 0.0;
    if(ea.getEventType() == osgGA::GUIEventAdapter::FRAME){
        feature_.pts->push_back(osg::Vec3d(-90., lat, 0.0));
        lat += 0.01;
        feature_.fml->dirty();
    }
    return false;
}
private:
FeatureElem feature_;
};
```
add to `Layer`

```cpp
    auto node = MapNodeHelper().load(arguments, &viewer);
    osgEarth::MapNode* mapnode = osgEarth::MapNode::get(node);
    FeatureElem elem = createFeatureModelLayer();
    mapnode->getMap()->addLayer(elem.fml);
    viewer.addEventHandler(new FeatureHandler(elem));
```
## envs
`version 3.4`

```cpp
> osgearth_version --caps
[osgEarth]  [Registry] Note: GDAL_DATA environment variable is not set
[osgEarth]  [Capabilities] Capabilities:
[osgEarth]  [Capabilities]   osgEarth Version:  3.4.0 build 148
[osgEarth]  [Capabilities]   OSG Version:       3.7.0
[osgEarth]  [Capabilities]   GDAL Version:      3.7.0dev-7a4abb688f
[osgEarth]  [Capabilities]   GEOS Version:      3.12.0dev
[osgEarth]  [Capabilities]   GPU Vendor:        NVIDIA Corporation
[osgEarth]  [Capabilities]   GPU Renderer:      NVIDIA GeForce RTX 2070 SUPER/PCIe/SSE2
[osgEarth]  [Capabilities]   GL/Driver Version: 3.3.0 NVIDIA 531.79 (330)
[osgEarth]  [Capabilities]   GL Core Profile:   yes
```

`version 3.3`

```shell
> osgearth_version --caps
[osgEarth]  [Registry] Note: GDAL_DATA environment variable is not set
[osgEarth]  [Capabilities] Capabilities:
[osgEarth]  [Capabilities]   osgEarth Version:  3.3.0 build 147
[osgEarth]  [Capabilities]   OSG Version:       3.7.0
[osgEarth]  [Capabilities]   GDAL Version:      3.7.0dev-7a4abb688f
[osgEarth]  [Capabilities]   GEOS Version:      3.12.0dev
[osgEarth]  [Capabilities]   GPU Vendor:        NVIDIA Corporation
[osgEarth]  [Capabilities]   GPU Renderer:      NVIDIA GeForce RTX 2070 SUPER/PCIe/SSE2
[osgEarth]  [Capabilities]   GL/Driver Version: 3.3.0 NVIDIA 531.79 (330)
[osgEarth]  [Capabilities]   GL Core Profile:   yes
```
How do I do this, or how to dynamically update the source in `ModelFeatureLayer`?

source file
[main.zip](https://github.com/gwaldron/osgearth/files/12063489/main.zip)

**Comment by adithyahk46** [comment]
void MainWindow::on_actionVector_Layer_triggered()
{
    QStringList filePaths = QFileDialog::getOpenFileNames(
        this,
        "Open File",
        "",        // Initial directory
        "vector Files (*.shp );;All Files (*.*)"
    );

    // Iterate over each selected file path
    for (const QString& filePath : filePaths)
    {
        if (filePath.isEmpty() || !mapNode)
            return;

        QDebug("CAme inside SHP");

        QFileInfo finfo(filePath);
        QString MapName = finfo.baseName().toStdString().c_str();
        QString fileExt = finfo.suffix().toStdString().c_str();  // Get the file extension

        QString fileName_1 = finfo.absoluteFilePath();

        // Add vector layer
            osgEarth::OGRFeatureSource* features = new osgEarth::OGRFeatureSource();
            features->setName("border-data");
            features->setURL(fileName_1.toStdString());
            //map->addLayer(features);

            // Configure style using border/width attributes
            osgEarth::Style style;
            osgEarth::LineSymbol* ls = style.getOrCreateSymbol<osgEarth::LineSymbol>();

            // Attribute-driven styling
            ls->stroke().mutable_value().color() = osgEarth::Color::Black;
            ls->stroke().mutable_value().width() = osgEarth::Distance(1.0, osgEarth::Units::PIXELS);
            ls->tessellationSize() = osgEarth::Distance(100, osgEarth::Units::KILOMETERS);

            // Create feature layer
            osgEarth::FeatureModelLayer* Borderlayer = new osgEarth::FeatureModelLayer();
            Borderlayer->setFeatureSource(features);

            osgEarth::StyleSheet* styleSheet = new osgEarth::StyleSheet();
            styleSheet->addStyle(style);
            Borderlayer->setStyleSheet(styleSheet);

            mapNode->getMap()->addLayer(Borderlayer);

    }
}



12:13:19: Starting D:\Qt_projects\OSG_EARTH_QT_APP_ADI\release\OSG_EARTH_QT_APP_ADI.exe...
[osgEarth]* ASSERTION FAILURE (redraw @ FeatureModelGraph.cpp:2056) node.valid() ...



I compiled osg , osgQT, osgEarth through vcpkg , Im facing above issue when i try to open shp file,
