### ISSUE TITLE
Crashed when trying to get multiview of the earth

### ISSUE THREAD

**Issue by iamzheng00** [gwaldron/osgearth#2321]
I tried using  `slave camera` to achieve muiltiview of the earth scene, it worked well in osgEarth3.2, but crashed in osgEarth3.4. And I also tried  `CompositeViewer`  as osgearth example did, but in 3.4 version of osgearth, the osgearth_windows example also got crashed...
Is that a little bug in 3.4version or need some additional configuration options? 

result of `running osgearth_version.exe --caps` :
[osgEarth]  [Capabilities] Capabilities:
[osgEarth]  [Capabilities]   osgEarth Version:  3.4.0 build 148
[osgEarth]  [Capabilities]   OSG Version:       3.6.5
[osgEarth]  [Capabilities]   GDAL Version:      2.4.4
[osgEarth]  [Capabilities]   GEOS Version:      3.5.2
[osgEarth]  [Capabilities]   GPU Vendor:        NVIDIA Corporation
[osgEarth]  [Capabilities]   GPU Renderer:      NVIDIA GeForce RTX 2080 Ti/PCIe/SSE2
[osgEarth]  [Capabilities]   GL/Driver Version: 3.3.0 NVIDIA 535.98 (330)
[osgEarth]  [Capabilities]   GL Core Profile:   yes

here is my test code of slave cameras:
```
#include <osgViewer/Viewer>

#include <osgEarth/MapNode>
#include <osgEarth/ModelLayer>
#include <osgEarth/GeoTransform>
#include <osgEarth/Registry>
#include <osgEarth/ShaderGenerator>
#include <osgEarth/Lighting>
#include <osgEarth/Sky>
#include <osgEarthDrivers/sky_simple/SimpleSkyOptions>
#include <osgEarth/EarthManipulator>

#include <osgDB/ReadFile>
#include <osgGA/StateSetManipulator>
#include <osgGA/TrackballManipulator>
#include <osgViewer/ViewerEventHandlers>
#include <stdio.h>
#include <istream>

#include <osg/GraphicsContext>
#include <osgViewer/GraphicsWindow>
#include <osgViewer/api/Win32/GraphicsWindowWin32>

using namespace osgEarth;
using namespace osg;
using namespace osgEarth::Util;
using namespace std;


void CreateMultiView(int width, int height, osgViewer::Viewer* viewer)
{

    int _wnd_width = width;
    int _wnd_height = height;

    osg::ref_ptr<osg::GraphicsContext::Traits> traits = new osg::GraphicsContext::Traits;
    traits->x = 100;
    traits->y = 100;
    traits->width = width * 3;
    traits->height = height * 3;
    traits->windowDecoration = true;
    traits->doubleBuffer = true;
    traits->sharedContext = 0;
    //traits->samples = 8;
    //traits->sampleBuffers = 1;
    //traits->readDISPLAY();
    //traits->setUndefinedScreenDetailsToDefaultScreen();
    
    osg::ref_ptr<GraphicsContext> graphWindow = GraphicsContext::createGraphicsContext(traits.get());

    for (int i = 0; i < 9; i++)
    {
        osg::ref_ptr<osg::Camera> slaveCamera = new osg::Camera;
        slaveCamera->setGraphicsContext(graphWindow.get());
        slaveCamera->setViewport(new osg::Viewport((i % 3) * traits->width / 3.0f, traits->height - traits->height / 3.0f * (int)((i) / 3 + 1), traits->width / 3.0f, traits->height / 3.0f));
        viewer->addSlave(slaveCamera.get());
    }

    viewer->updateSlaves();
}

/**
 * How to create a simple osgEarth map and display it.
 */
int
main(int argc, char** argv)
{
    osgEarth::initialize();
    osgViewer::Viewer* viewer = new osgViewer::Viewer();
    // create the empty map.
    Map* map = new Map();

    MapNode* mapnode = new MapNode(map);
    SkyNode* sky = SkyNode::create();
    sky->attach(viewer->asView());
    Ephemeris* eph = new Ephemeris();
    sky->setEphemeris(eph);
    DateTime dt = DateTime(2022, 3, 8, 5);
    sky->setDateTime(dt);
    sky->setLighting(true);
    sky->setAtmosphereVisible(true);
    sky->addChild(mapnode);
    auto manip = new EarthManipulator();
    viewer->setCameraManipulator(manip);
    viewer->setSceneData(sky);

    // add some stock OSG handlers:
    //MapNodeHelper().configureView(viewer);
    viewer->addEventHandler(new osgViewer::StatsHandler());
    viewer->addEventHandler(new osgGA::StateSetManipulator(viewer->getCamera()->getOrCreateStateSet()));
    viewer->addEventHandler(new osgViewer::ThreadingHandler);
    viewer->addEventHandler(new osgViewer::RecordCameraPathHandler);
    viewer->addEventHandler(new osgViewer::LODScaleHandler);
    viewer->addEventHandler(new osgViewer::ScreenCaptureHandler);

    // load a model
    std::string filepath = R"(D:\test data\redball.obj)";
    auto loadedModel3 = osgDB::readRefNodeFile(filepath);
    Registry::shaderGenerator().run(loadedModel3);
    GeoTransform* gtrans = new GeoTransform();
    GeoPoint geoOrigin(mapnode->getMapSRS(), Vec3d(88, 18, 88));
    gtrans->setTerrain(mapnode->getTerrain());
    gtrans->setPosition(geoOrigin);
    gtrans->addChild(loadedModel3);
    mapnode->addChild(gtrans);

    // set HomeViewpoint
    Viewpoint vp;
    vp.focalPoint() = geoOrigin;
    Angle* a_pitch = new Angle((double)(0 - 90), Units::DEGREES);
    osgEarth::Distance* distrange = new osgEarth::Distance(10000, Units::METERS);
    vp.setPitch(*a_pitch);
    vp.setRange(*distrange);
    auto mp = (osgEarth::EarthManipulator*)viewer->getCameraManipulator();
    mp->setHomeViewpoint(vp, 3);

    viewer->setUpViewInWindow(200, 200, 800, 600);

    // using slave cameras to create a window which splitted into 9 parts
    CreateMultiView(400, 300, viewer);

    viewer->run();

    return 1;
}

```

**Comment by gwaldron** [comment]
Do you have a stack trace? I ran this code in the master branch and it didn't crash. It only spit out a GL error.

**Comment by iamzheng00** [comment]
Thanks for your reply Glenn! I'll upload a screenshot tomorrow. By the way, I'm using osgearth 3.4 release, and I haven't used the master version yet, and I'll try it tomorrow.

**Comment by iamzheng00** [comment]
I have run the code many times, and met 3 situations:
![VPVO6J9@%0XLJ8Q4O00 PXJ](https://github.com/gwaldron/osgearth/assets/50063535/6e0f50f7-f400-48c8-8758-9bc5e0f348c7)

Sometimes met the following error :
![K)}TC58QX)Q MOU Q141( M](https://github.com/gwaldron/osgearth/assets/50063535/4b167549-4f7c-44c3-ba5e-6c66ed3dfcf5)

And sometimes crashed like this:
![2C79}3L4A}_26QUI27UJWL](https://github.com/gwaldron/osgearth/assets/50063535/43cca765-9e31-4dc1-867b-ecb4f0e00198)
if click ignore:
![X3ZJP VLX1}S_6)@F2X9WFQ](https://github.com/gwaldron/osgearth/assets/50063535/b9726b38-800e-418a-9f46-63dafdcefb9e)

**Comment by iamzheng00** [comment]
I have build the master branch and ran my code , got the same result. The osgearth_windowsd.exe crashed as before. @gwaldron 
![1](https://github.com/gwaldron/osgearth/assets/50063535/731317f3-1586-419d-8c5a-948fe14337f0)

**Comment by gwaldron** [comment]
Can you check whether the CMAKE flag "OSGEARTH_ASSUME_SINGLE_GL_CONTEXT" is set?
This was set to ON by mistake (fixed in latest master) and should be OFF.
(When it's on, multiple windows do not work propertly.)

**Comment by iamzheng00** [comment]
Thanks Glenn ! I'll check that flag and try again



---Original---
From: ***@***.***&gt;
Date: Fri, Oct 20, 2023 23:14 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [gwaldron/osgearth] Crashed when trying to get multiview of theearth (Issue #2321)




 
Can you check whether the CMAKE flag "OSGEARTH_ASSUME_SINGLE_GL_CONTEXT" is set?
 This was set to ON by mistake (fixed in latest master) and should be OFF.
 (When it's on, multiple windows do not work propertly.)

**Comment by iamzheng00** [comment]
I turned off the&nbsp; flag,&nbsp; and it solved the problem! Thanks so much , Glenn!





---Original---
From: ***@***.***&gt;
Date: Fri, Oct 20, 2023 23:14 PM
To: ***@***.***&gt;;
Cc: ***@***.******@***.***&gt;;
Subject: Re: [gwaldron/osgearth] Crashed when trying to get multiview of theearth (Issue #2321)




 
Can you check whether the CMAKE flag "OSGEARTH_ASSUME_SINGLE_GL_CONTEXT" is set?
 This was set to ON by mistake (fixed in latest master) and should be OFF.
 (When it's on, multiple windows do not work propertly.)

**Comment by gwaldron** [comment]
Great. This flag is now off by default in version 3.5.
