### ISSUE TITLE
use osgdb_ webp plugin failed to load the grayscale image

### ISSUE THREAD

**Issue by newpeople123** [gwaldron/osgearth#2324]
When I use osgdb_ The webp plugin failed to load the grayscale image.It uses function of WebPPictureImportRGBX.And after executing function of WebPEncode,variable picture's error_code is VP8_ENC_ERROR_NULL_PARAMETER.

**Comment by newpeople123** [comment]
![Gas Tank_Mixed_AO](https://github.com/gwaldron/osgearth/assets/65968233/6a58325b-f6b9-46db-9d99-48416ffd8f2c)
this is the error image

**Comment by jasonbeverage** [comment]
It looks like the image attached is a PNG and not a WEBP, do you have the original image  you're having issues with?

**Comment by newpeople123** [comment]
Yes, this image is a png, but loading this png in osgEarth and then exporting it to webp format fails.In other words, the write method of the webp plug-in does not support grayscale images well.

**Comment by jasonbeverage** [comment]
Gotcha.  I don't believe webp supports single band grayscale at all anyway so this isn't something we're going to fix.  The [spec](https://developers.google.com/speed/webp/docs/webp_lossless_bitstream_specification) says "WebP lossless is an image format for lossless compression of ARGB images."

**Comment by newpeople123** [comment]
Thanks
