### ISSUE TITLE
osgearth_graticule issues

### ISSUE THREAD

**Issue by devil-darkside** [gwaldron/osgearth#2326]
MouseCoordsTool in osgearth_graticule cause crash.
MGRS graticule is not working and GARS graticule has wrong representation

**Comment by gwaldron** [comment]
Try `osgearth_imgui graticules.earth` instead.
Unfortunately `osgearth_graticule` is an old demo and has not been maintained -- we will remove it.

**Comment by devil-darkside** [comment]
I'll try... but I would like to add the graticules from my code on demand (handler, udp, etc...)
