### ISSUE TITLE
ShaderGenerator not working

### ISSUE THREAD

**Issue by devil-darkside** [gwaldron/osgearth#2328]
ShaderGenerator is not applying shader to 3D models.
3D Models are rendered black.
Only the pseudoloader is working.
See -> Include textured models #2304

**Comment by devil-darkside** [comment]
Attached the osgearth_version --caps

![osgearth_version](https://github.com/gwaldron/osgearth/assets/140507513/2bf5a4e1-8e4b-4149-aa93-24a6f4774141)

Below the osgearth_viewer.cpp code modified.

`/* -*-c++-*- */
/* osgEarth - Geospatial SDK for OpenSceneGraph
* Copyright 2020 Pelican Mapping
* http://osgearth.org
*
* osgEarth is free software; you can redistribute it and/or modify
* it under the terms of the GNU Lesser General Public License as published by
* the Free Software Foundation; either version 2 of the License, or
* (at your option) any later version.
*
* THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
* IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
* FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
* AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
* LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
* FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
* IN THE SOFTWARE.
*
* You should have received a copy of the GNU Lesser General Public License
* along with this program.  If not, see <http://www.gnu.org/licenses/>
*/

#include <osgViewer/Viewer>
#include <osgEarth/Notify>
#include <osgEarth/EarthManipulator>
#include <osgEarth/ExampleResources>
#include <osgEarth/MapNode>
#include <osgEarth/Threading>
#include <osgEarth/ShaderGenerator>
#include <osgDB/ReadFile>
#include <osgGA/TrackballManipulator>
#include <osgUtil/Optimizer>
#include <iostream>
#include <windows.h>

#include <osgEarth/Metrics>

#include <osgViewer/CompositeViewer>
#include <osgViewer/ViewerEventHandlers>
#include <osgEarth/PhongLightingEffect>
#include <osgGA/StateSetManipulator>
#include <osg/PositionAttitudeTransform>
#include <osgEarth/GeoTransform>

#define LC "[viewer] "

using namespace osgEarth;
using namespace osgEarth::Util;

int
usage(const char* name)
{
    OE_NOTICE
        << "\nUsage: " << name << " file.earth" << std::endl
        << MapNodeHelper().usage() << std::endl;

    return 0;
}


int
main(int argc, char** argv)
{
    osgEarth::initialize();

    osg::GraphicsContext::Traits *traits = new osg::GraphicsContext::Traits;

    // added for remove some error in OpenGL FFP and set the correct GL version -> 3.3
    // with 3.0 the stars were not visible
    traits->glContextVersion = osg::DisplaySettings::instance()->getGLContextVersion();
    traits->glContextProfileMask = osg::DisplaySettings::instance()->getGLContextProfileMask();

    traits->x = 0;
    traits->y = 0;
    traits->width = 800;
    traits->height = 600;
    traits->windowName = "TEST";
    traits->windowDecoration = true;
    traits->supportsResize = true;
    traits->red = 8;
    traits->blue = 8;
    traits->green = 8;
    traits->alpha = 8;
    traits->depth = 24;
    traits->stencil = 8;
    traits->samples = 4;
    //traits->sampleBuffers = 2;
    //traits->quadBufferStereo = false;
    traits->doubleBuffer = true;
    traits->vsync = true;
    traits->useCursor = true;

    traits->setScreenIdentifier("HELLO");

    traits->sharedContext = 0;
    osg::GraphicsContext *gc = osg::GraphicsContext::createGraphicsContext(traits);
    gc->setClearColor(osg::Vec4f(0.2f, 0.2f, 0.6f, 1.0f));
    gc->setClearMask(GL_COLOR_BUFFER_BIT | GL_DEPTH_BUFFER_BIT);

    osgViewer::CompositeViewer* cv = new osgViewer::CompositeViewer;

    // thread-safe initialization of the OSG wrapper manager. Calling this here
    // prevents the "unsupported wrapper" messages from OSG
    osgDB::Registry::instance()->getObjectWrapperManager()->findWrapper("osg::Image");

    // setup OSG View for this Channel
    osgViewer::View *view = new osgViewer::View;
    view->addEventHandler(new osgGA::StateSetManipulator(view->getCamera()->getOrCreateStateSet()));
    view->addEventHandler(new osgViewer::StatsHandler);
    view->getDatabasePager()->setUnrefImageDataAfterApplyPolicy(true, false);
    view->getDatabasePager()->setDoPreCompile(true);
    view->getDatabasePager()->setDrawablePolicy(osgDB::DatabasePager::USE_DISPLAY_LISTS);
    // Tell the database pager to not modify the unref settings
    view->getDatabasePager()->setUnrefImageDataAfterApplyPolicy(true, false);

    osgEarth::EarthManipulator* em = new osgEarth::EarthManipulator;
    view->setCameraManipulator(em);
    //view->setCameraManipulator(new osgGA::TrackballManipulator);

    cv->addView(view);
    view->getCamera()->setGraphicsContext(gc);
    view->getCamera()->setViewport(new osg::Viewport(0, 0, 800, 600));
    view->getCamera()->setProjectionMatrixAsPerspective(60, 1.0, 1.0, 100.0);

    // setup local OSG scene for this Channel
    osg::Group *scene = new osg::Group;

    osgEarth::SkyOptions skyOptions;
    skyOptions.coordinateSystem() = osgEarth::SkyOptions::COORDSYS_ECEF;
    skyOptions.set_quality(osgEarth::SkyOptions::QUALITY_BEST);
    osgEarth::SkyNode *sky = osgEarth::SkyNode::create(skyOptions);
    sky->setAtmosphereVisible(true);
    sky->setMoonVisible(true);
    sky->setSunVisible(true);
    sky->setStarsVisible(true);
    sky->getSunLight()->setAmbient(osg::Vec4(0.1, 0.1, 0.1, 1.0));
    sky->setSimulationTimeTracksDateTime(false);
    sky->setDateTime(osgEarth::DateTime(2023, 07, 01, 12.0));

    // setup skydome
    sky->attach(view);

    // Add phong lighting.
    osgEarth::Util::PhongLightingEffect* phong = new osgEarth::Util::PhongLightingEffect();
    phong->attach(scene->getOrCreateStateSet());

    //Sleep(10000);

    osg::ArgumentParser arguments(&argc, argv);

    auto earth = MapNodeHelper().load(arguments, cv);
    MapNode* mapNode = MapNode::get(earth);

    //osg::Node* node = osgDB::readNodeFile("cow.osg.osgearth_shadergen"); // working
    osg::Node* node = osgDB::readNodeFile("cow.osg"); // not working

    osgUtil::Optimizer opt;
    opt.optimize(node, osgUtil::Optimizer::INDEX_MESH);

    osgEarth::GeoTransform *geo = new osgEarth::GeoTransform();
    geo->addChild(node);

    GeoPoint* gp = new GeoPoint(mapNode->getMapSRS(), 0.0, 0.0, 5000.0);
    geo->setPosition(*gp);

    scene->addChild(mapNode);

    osgEarth::Viewpoint vp;
    vp.setNode(geo);
    vp.heading()->set(0.0, Units::DEGREES);
    vp.pitch()->set(-20.0, Units::DEGREES);
    vp.range()->set(node->getBound().radius() * 10.0, Units::METERS);
    em->setViewpoint(vp);
    em->setHomeViewpoint(vp);
    
    scene->addChild(sky);
    scene->addChild(geo);

    view->setSceneData(scene);

    cv->realize();

    while (!cv->done())
    {
        auto time = cv->getFrameStamp()->getReferenceTime();

        cv->advance(time);
        cv->eventTraversal();
        cv->updateTraversal();

        cv->renderingTraversals();
    }

    //osg::ArgumentParser arguments(&argc,argv);

    //// help?
    //if ( arguments.read("--help") )
    //    return usage(argv[0]);

    //// create a viewer:
    //osgViewer::Viewer viewer(arguments);
    //// This is normally called by Viewer::run but we are running our frame loop manually so we need to call it here.
    //viewer.setReleaseContextAtEndOfFrameHint(false);

    //// Tell the database pager to not modify the unref settings
    //viewer.getDatabasePager()->setUnrefImageDataAfterApplyPolicy( true, false );

    //// thread-safe initialization of the OSG wrapper manager. Calling this here
    //// prevents the "unsupported wrapper" messages from OSG
    //osgDB::Registry::instance()->getObjectWrapperManager()->findWrapper("osg::Image");

    //// install our default manipulator (do this before calling load)
    //viewer.setCameraManipulator( new EarthManipulator(arguments) );

    //// disable the small-feature culling
    //viewer.getCamera()->setSmallFeatureCullingPixelSize(-1.0f);

    //// load an earth file, and support all or our example command-line options
    //auto node = MapNodeHelper().load(arguments, &viewer);
    //if (node.valid())
    //{
    //    viewer.setSceneData( node );
    //    
    //    if (!MapNode::get(node))
    //    {
    //        // not an earth file? Just view as a normal OSG node or image
    //        viewer.setCameraManipulator(new osgGA::TrackballManipulator);
    //        osgUtil::Optimizer opt;
    //        opt.optimize(node, osgUtil::Optimizer::INDEX_MESH);
    //        ShaderGenerator gen;
    //        node->accept(gen);
    //    }

    //    return Metrics::run(viewer);
    //}

    //return usage(argv[0]);

    return 0;
}`

**Comment by gwaldron** [comment]
Instead of `node->accept(gen)` try this instead:
```c++
ShaderGenerator gen;
gen.run(node);
```

**Comment by devil-darkside** [comment]
It works. Great!
I've copied the code from the osgearth_viewer example, I thought it was something related to my viewer creation.
