### ISSUE TITLE
Using CLAMP_TO_TERRAIN will result in a black screen when resizing the window

### ISSUE THREAD

**Issue by HerryJessica** [gwaldron/osgearth#2329]
When drawing a polygon
 AltitudeSymbol * altSymbol = geomStyle.getOrCreate<AltitudeSymbol>();
    altSymbol->clamping() = AltitudeSymbol::CLAMP_TO_TERRAIN;
    altSymbol->technique() = AltitudeSymbol::TECHNIQUE_DRAPE;
 Then resizing the window results in a black screen

osgearth  version:  2.10.1
Opensceengraph version: 3.6.5
GPU:  M1
Opengles: 3.1
platform： linux

**Comment by gwaldron** [comment]
I'm afraid we have no way to test or assist with that particular hardware configuration - sorry!
osgEarth requires OpenGL 3.3. I also recommend updating to the latest released version -- 2.10 is quite old.
