### ISSUE TITLE
Weird ModelNode texture color

### ISSUE THREAD

**Issue by elbarto1980** [gwaldron/osgearth#2332]
Good morning,
I am playing around, for the first time, with a fbx file that has all the textures included and I am experiencing some difficulties with rendering it properly.
I downloaded the fbx file from [here](https://sketchfab.com/3d-models/army-soldier-character-cc995450452744ec8f852d8bf5f335d6) and, at first, I used osgviewer to render it. The model is rendered correctly, but osgviewer prints (many times) the error: `An update callback has no name, it means it could link only with "" named Target, often an error, discard`.
Since I read that this problem might be related to the model animation (and I do not need it), I imported the fbx file in Blender and exported it again, without the animation.

Opening the new file with osgviewer, the model is rendered correctly and there are no more errors
![screen_shot_0_1](https://github.com/gwaldron/osgearth/assets/36400622/c3eb6db7-7324-4ce8-9c0e-8e0f4016886f)

but when I load it inside an osgEarth::ModelNode, the jacket has a completely different color, mixed with the texture
![modelNode](https://github.com/gwaldron/osgearth/assets/36400622/28bb80fb-0f29-4057-9d2f-3bbbc08dd725)

**I have the very same result (blue jacket) if I run osgviewer with the Intel graphic card instead of the NVidia one.**

I also tried appending `.osgearth_shadergen` to the filename when I load the file using `osgDB::readNodeFile` but, in that case, the model is not even shown on the terrain. 

Any ideas about what am I missing in my code? Or maybe when I export it from Blender?
Might it be related to this other issue #2328?
It is really strange that all the other textures of the model (skin, pants, etc.) are not affected...

My current software setup is Ubuntu 20.04 with the following caps:
```
[osgEarth]  [Registry] Note: GDAL_DATA environment variable is not set
[osgEarth]  [Capabilities] Capabilities: 
[osgEarth]  [Capabilities]   osgEarth Version:  3.2.0 build 113
[osgEarth]  [Capabilities]   OSG Version:       3.6.5
[osgEarth]  [Capabilities]   GDAL Version:      3.0.4
[osgEarth]  [Capabilities]   GEOS Version:      3.8.0
[osgEarth]  [Capabilities]   GPU Vendor:        NVIDIA Corporation
[osgEarth]  [Capabilities]   GPU Renderer:      NVIDIA GeForce RTX 3070 Laptop GPU/PCIe/SSE2
[osgEarth]  [Capabilities]   GL/Driver Version: 4.6.0 NVIDIA 535.86.05
[osgEarth]  [Capabilities]   GL Core Profile:   no
```

Thank you so much for your help

**Comment by elbarto1980** [comment]
Hi,
I have just solved the issue (in Blender). The problem was related to the Normal/Map color block that was applied to the jacket.
![nmap](https://github.com/gwaldron/osgearth/assets/36400622/9017f7fa-b3b0-4380-977b-821caacb681a)

For future reference, I just had to remove the whole `file7` block and export to fbx file again.

**Comment by gwaldron** [comment]
Glad you figured this out. I'm guessing that the FBX model once loaded had the normal map in one of the secondary texture image units, and the osgEarth shader generator interpreted this as another color texture. It doesn't really know the difference; the stock shader generator does not have support for normal maps anyway.
