### ISSUE TITLE
Extruded building roofs flickering - bad texture coordinates

### ISSUE THREAD

**Issue by devil-darkside** [gwaldron/osgearth#2350]
The roofs are flickering on extrusion with building shapefiles using wgs84 proj.
Using utm projection roofs are ok.

**Comment by gwaldron** [comment]
Can we see your earth files? And possible your shapefile files to reproduce?

**Comment by devil-darkside** [comment]
[vector.zip](https://github.com/gwaldron/osgearth/files/12932169/vector.zip)
[00_test.zip](https://github.com/gwaldron/osgearth/files/12932236/00_test.zip)

Attached simple buildings and earth file.

**Comment by gwaldron** [comment]
Your buildings are over 1km wide, so the roof is intersecting the terrain (just like it would in real life).

**Comment by devil-darkside** [comment]
I know... it is just a test... 
But if you go very near to the roofs, you can see the flickering when doing pan on earth.

**Comment by devil-darkside** [comment]
[buildings_extract.zip](https://github.com/gwaldron/osgearth/files/13050954/buildings_extract.zip)
[00_test.zip](https://github.com/gwaldron/osgearth/files/13050960/00_test.zip)
Try with this sample.

**Comment by gwaldron** [comment]
Fixed in  18fcc5051
