### ISSUE TITLE
Plain terrain on mountains/hills

### ISSUE THREAD

**Issue by devil-darkside** [gwaldron/osgearth#2356]
When near to the ground the terrain orography seems simplified with plain terrain.
Tested also with gdaldem.earth

**Comment by gwaldron** [comment]
Screenshot please?

**Comment by devil-darkside** [comment]
![gdaldem_grandcanyon_zone](https://github.com/gwaldron/osgearth/assets/140507513/482634b5-2f1d-4ce9-a9fe-6fb1ef832cce)
![gdaldem_nepal_zone](https://github.com/gwaldron/osgearth/assets/140507513/057fabc8-9ffc-4b3f-a779-555f783d46a1)
Same behaviour with dted and other elevation data.

**Comment by gwaldron** [comment]
Are you sure that isn't just the maximum resolution of the terrain data?
