### ISSUE TITLE
GeoPositionNodeAutoScaler: Issue with Truncated Circle Representation

### ISSUE THREAD

**Issue by muby** [gwaldron/osgearth#2361]
Context : Osgearth 3.2 + Patch (From Conan)
Maybe it's something fixed in 3.4 

I conducted some tests as I wanted to create a circle with a consistent diameter using GeoPositionNodeAutoScaler. 

While it works reasonably well, there's an issue where, when the camera is close to the circle, it maintains the correct size, but when zoomed out too much, it appears as a square (it gets truncated), and at a certain point, it reduces to just 1 pixel. 

Additionally, when dealing with two circles, the 'truncation' behavior is somewhat different. Below is the code and a short video demonstrating these observations.

` 

    int nbCircle = 2;
    for (int i = 0; i < nbCircle ; i++)
    {
        osg::ref_ptr<osg::Group> group = new osg::Group ();GeoPositionNodeAutoScaler

        osg::ref_ptr<osgEarth::CircleNode> _circleCenter = new osgEarth::CircleNode ();
        _circleCenter->setName ("HackCircle");
        _circleCenter->setRadius (osgEarth::Distance (100, osgEarth::Units::METERS));
        _circleCenter->setPosition (osgEarth::GeoPoint (geoSRS, -122+i*0.01, 45,150, osgEarth::ALTMODE_RELATIVE));

        _circleCenter->setCullingActive (true);
        _circleCenter->setCullCallback (new osgEarth::GeoPositionNodeAutoScaler ());
        //_circleCenter.get ()->setCullCallback (new osg::NodeCallback());

        group->addChild (_circleCenter.get ());
        annoGroup->addChild (group.get ());

        osgEarth::Style circleStyle;

        circleStyle.getOrCreate<osgEarth::PolygonSymbol> ()->fill ()->color ()         = osgEarth::Color (osg::Vec4f (1, 0, 0, 0.8));
        circleStyle.getOrCreate<osgEarth::AltitudeSymbol> ()->technique ()             = osgEarth::AltitudeSymbol::TECHNIQUE_DRAPE;
        circleStyle.getOrCreate<osgEarth::AltitudeSymbol> ()->clamping ()              = osgEarth::AltitudeSymbol::CLAMP_TO_TERRAIN;
        circleStyle.getOrCreate<osgEarth::RenderSymbol> ()->depthOffset ()->enabled () = true;
        circleStyle.getOrCreate<RenderSymbol> ()->lighting ()                          = false;
        _circleCenter->setStyle (circleStyle);
    }`

[Video Rendering](https://easyupload.io/links?id=https://easyupload.io/57zuh5)

**Comment by gwaldron** [comment]
What exactly are you trying to do? What does it mean to plot a circle with a 100m radius, and then have it auto-scale?

**Comment by muby** [comment]
Indeed, it's quite strange but I just want a circle clamp on ground with fixe radius but ideally in pixel.
