### ISSUE TITLE
GL3 core profile Segmentation FAULT

### ISSUE THREAD

**Issue by JudyDve** [gwaldron/osgearth#2425]
I get a segfault when running **_osgearth_viewer simple.earth_** in GL3 core profile, but runs fine in GL compatibility PROFILE.  I switch the mp Egine as default. The debugging shows that the error location is in _glDrawElements_.  I will continue to troubleshoot this issue.

![Screenshot from 2024-01-18 16-12-51](https://github.com/gwaldron/osgearth/assets/50954821/87b2f03c-9e21-4724-a80f-32c4928fe033)

OS:           Ubuntu22.04
Graphics:  llvmpipe (LLVM 15.0.6, 256 bits) / Mesa Intel® Graphics (ADL GT2)
OSG:        3.6.5
OSGEARTH: 2.10.2

**Comment by JudyDve** [comment]
![Uploading Screenshot from 2024-01-18 16-12-51.png…]()

**Comment by gwaldron** [comment]
osgEarth 2.10 is many years old; I really recommend you move up to a modern version if possible.
GL3 and GLCORE support are much better in the latest versions.
You may also want to [read this](https://docs.osgearth.org/en/latest/build.html#tips-for-vmware-users) since you are using Mesa.
Good luck!

**Comment by JudyDve** [comment]
Thank you for your suggestion. 
Later on, I will also deeply use the higher version content.
I understand that the version(2.10) is no longer maintained, but I think I may have found the issue above(segfault). 
It seems to be related to the OE‘s shaders . If I set resetVertexAttribute(false), the display is normal, But I haven't been able to pinpoint which shader it is yet causing the issue.

**Comment by gwaldron** [comment]
If you look at this custom [GL3RealizeOperation](https://github.com/gwaldron/osgearth/blob/master/src/osgEarth/GLUtils.cpp#L486) it does various things that you need for a successful GL3/GLCORE context.
I don't recall whether this was in 2.10, but maybe the code will help you.

Good luck!
