### ISSUE TITLE
model height issue in earth file

### ISSUE THREAD

**Issue by nitinsdg** [gwaldron/osgearth#2426]
Hello community,

earlier in earth file we can define model elevation through below xml tag

```
<model name = "modelname" driver="simple">
	    <url>model.IVE.4,4,4.scale</url>
	    <location>71.067 20.735 3549.65</location>
</model>
```

but in new it is not working, it is only accepting lat long not _height_, see below

```
<model name = "modelname" >
	    <url>model.IVE.4,4,4.scale</url>
<location lat="30.735" long="79.067"   **??????** />
</model>

```
Please let me know what to do to add elevation on 3d model

**Comment by nitinsdg** [comment]
I got the attribute, it is **'alt'**, but i want to know where is the documentation to know all this for osgeath 3.x ???? please share link if it is available ?

**Comment by gwaldron** [comment]
There is none, just the examples in the `tests` folder. `annotation.earth` has a bunch of examples for annotation objects.
Good luck and feel free to ask if you get stuck!!
