### ISSUE TITLE
Which tag of cesium-native can be used to compile osgEarthCesium successfully?

### ISSUE THREAD

**Issue by liangyuxuly** [gwaldron/osgearth#2430]
When I use the cesium-native tag of v0.30.0 and v0.31.0, syntax errors will be reported.
<img width="860" alt="1705682438459" src="https://github.com/gwaldron/osgearth/assets/101852238/ffcda08b-b022-4806-935b-fe1bfdefe303">

**Comment by virtuozo007** [comment]
我用的最新的osgearth的master版本+cesium-native的最新master版本，可以编译通过。就是注意有一个cpp文件要另存为UTF-8 with BOM，具体哪个文件我忘了，反正有个提示编码问题的错误，记得改一下。

**Comment by liangyuxuly** [comment]
感谢，我试试

**Comment by liangyuxuly** [comment]
Thanks, I have compiled it, using the master branch of osgEarth and the main branch of cesium-native. At the same time, I have also compiled it using the osgEarth-3.5 tag of osgEarth and the v0.25.0 tag of cesium-native.

**Comment by gwaldron** [comment]
Glad you got it working :)

**Comment by xiahai** [comment]
> Thanks, I have compiled it, using the master branch of osgEarth and the main branch of cesium-native. At the same time, I have also compiled it using the osgEarth-3.5 tag of osgEarth and the v0.25.0 tag of cesium-native.
怎么编译的呢，用vcpkg嘛

**Comment by xiahai** [comment]
> 我用的最新的osgearth的master版本+cesium-native的最新master版本，可以编译通过。就是注意有一个cpp文件要另存为UTF-8 with BOM，具体哪个文件我忘了，反正有个提示编码问题的错误，记得改一下。
怎么编译的呢，配置怎么设置，用的是vcpkg嘛
