### ISSUE TITLE
How can I know the osgEarth version if I installed it by vcpkg?

### ISSUE THREAD

**Issue by shaozhihua** [gwaldron/osgearth#2454]
We know,if we install the osg&osgEarth by vcpkg,it will be very convenient and high efficiency,but in this way, we will missing some .exe files. and we only got a lot of .lib and .dll files,so I can not know accurately what version of the osgEarth which I installed...
That is my question.
I hope some relevant person can help me answer questions, thank you very much!

**Comment by gwaldron** [comment]
The osgEarth tool are separate in vcpkg. You can install osgearth[tools] to get them.
Otherwise you can check the header file `osgEarth/Version` in your vcpkg install folder. Hope this helps.

**Comment by shaozhihua** [comment]
@gwaldron thanks,I read the Version file,and I figure it out.
![version](https://github.com/gwaldron/osgearth/assets/18071679/7740e3ba-83ab-4297-9bca-243355fc031b)
and I wonder how can I install the osgEarth tools except compile src... if you are free,I want to consult you.

**Comment by gwaldron** [comment]
`vcpkg install osgearth[tools]:x64-windows` should do it.

**Comment by shaozhihua** [comment]
tnanks sir,thank you so much!
