### ISSUE TITLE
BUG - OSG version is not retrieved

### ISSUE THREAD

**Issue by AhmedAredah** [gwaldron/osgearth#2464]
**Describe the bug**
Building the library on windows does not get the OSG version number.

**To Reproduce**
1. Build the library on Win 11 64 bit.
command:

`cmake -G "Visual Studio 16 2019" -A x64 .. -DGEOS_LIBRARY_DEBUG:FILEPATH="C:/Program Files/GEOS/lib/geos_cd.lib" -DOSGSHADOW_LIBRARY_DEBUG:FILEPATH="C:/Program Files/OSG/lib/osgShadowd.lib" -DOSGUTIL_LIBRARY
_DEBUG:FILEPATH="C:/Program Files/OSG/lib/osgUtild.lib" -DOSGSIM_LIBRARY_DEBUG:FILEPATH="C:/Program Files/OSG/lib/osgSimd.lib" -DOSGVIEWER_LIBRARY:FILEPATH="C:/Program Files/OSG/lib/osgViewer.lib" -DOSGSIM_LIBRA
RY:FILEPATH="C:/Program Files/OSG/lib/osgSim.lib" -DCMAKE_INSTALL_PREFIX:PATH="C:/Program Files/OSGEARTH" -DOSGTEXT_LIBRARY:FILEPATH="C:/Program Files/OSG/lib/osgText.lib" -DOSG_DIR:PATH="C:/Program Files/OSG" -
DOSGVIEWER_LIBRARY_DEBUG:FILEPATH="C:/Program Files/OSG/lib/osgViewerd.lib" -DOSGGA_LIBRARY:FILEPATH="C:/Program Files/OSG/lib/osgGA.lib" -DOSG_GEN_INCLUDE_DIR:PATH="C:/Program Files/OSG/include" -DOSGTEXT_LIBRA
RY_DEBUG:FILEPATH="C:/Program Files/OSG/lib/osgTextd.lib" -DOSGUTIL_LIBRARY:FILEPATH="C:/Program Files/OSG/lib/osgUtil.lib" -DOSGMANIPULATOR_LIBRARY_DEBUG:FILEPATH="C:/Program Files/OSG/lib/osgManipulatord.lib"
-DOSGDB_LIBRARY_DEBUG:FILEPATH="C:/Program Files/OSG/lib/osgDBd.lib" -DOSG_LIBRARY:FILEPATH="C:/Program Files/OSG/lib/osg.lib"  -DOPENTHREADS_LIBRARY_DEBUG:FILEPATH="C:/Program Files/OSG/lib/OpenThreadsd.lib" -D
OSGMANIPULATOR_LIBRARY:FILEPATH="C:/Program Files/OSG/lib/osgManipulator.lib" -DOSG_INCLUDE_DIR:PATH="C:/ProgramFiles/OSG/include" -DOSG_LIBRARY_DEBUG:FILEPATH="C:/Program Files/OSG/lib/osgd.lib" -DOPENTHREADS_L
IBRARY:FILEPATH="C:/Program Files/OSG/lib/OpenThreads.lib"  -DOSGDB_LIBRARY:FILEPATH="C:/Program Files/OSG/lib/osgDB.lib" -DOSGSHADOW_LIBRARY:FILEPATH="C:/Program Files/OSG/lib/osgShadow.lib" -DGDAL_INCLUDE_DIR=
"C:/Program Files/gdal/include" -DGDAL_LIBRARY="C:/Program Files/gdal/lib/gdal.lib" -DCMAKE_BUILD_TYPE=Release`

3. the cmakeCache has the value of OPENSCENEGRAPH_VERSION = ..

**Expected behavior**
It should get the OSG version. I am using OSG version 3.6.5 [here](https://github.com/openscenegraph/OpenSceneGraph/tree/OpenSceneGraph-3.6.5)

**Screenshots**
![image](https://github.com/gwaldron/osgearth/assets/77444744/fc7e4892-b8fe-41c2-821f-3c376f2e43a6)

**Desktop (please complete the following information):**
 - OS: Win 11 x64
 - Version osgearth-3.5

**Comment by AhmedAredah** [comment]
I manually defined the version, does it have any impact?


` set(OPENSCENEGRAPH_MAJOR_VERSION 3)

 set(OPENSCENEGRAPH_MINOR_VERSION 6)

 set(OPENSCENEGRAPH_PATCH_VERSION 5)`

**Comment by gwaldron** [comment]
If might be broken because of
`-DOSG_INCLUDE_DIR:PATH="C:/ProgramFiles/OSG/include"`
instead of
`-DOSG_INCLUDE_DIR:PATH="C:/Program Files/OSG/include"`

**Comment by AhmedAredah** [comment]
@gwaldron oh thank you for noticing it
