### ISSUE TITLE
How to prevent the map from being dragged outside the view?

### ISSUE THREAD

**Issue by shaozhihua** [gwaldron/osgearth#2468]
I changed the projection of the map through this interface,then I got a 2D map in the viewer;
But I found that I can drag the map to any position in the scene,even outside the viewer,which I dont expect.
![1](https://github.com/gwaldron/osgearth/assets/18071679/121de1bd-852c-411e-a9b5-36ff911e8d22)
![2](https://github.com/gwaldron/osgearth/assets/18071679/0afccdc3-2695-414c-bee4-765baea9685a)
we can see the map is outsize from the viewer.
so which class should I restrict the map drag...
expecting the someone's help, I will appreciate you so much.

**Comment by gwaldron** [comment]
The map manipulation is controlled by the [EarthManipulator](https://github.com/gwaldron/osgearth/blob/master/src/osgEarth/EarthManipulator.cpp) class.
There is no API function to do what you want - you will need to tackle it yourself. Good luck!

**Comment by shaozhihua** [comment]
Ok，thanks for your reply,I will try to read the source code of osg/oe,yeah,good luck to me.
