### ISSUE TITLE
Draping: using depth-offset with draping causes artifacts

### ISSUE THREAD

**Issue by YHLpuyu** [gwaldron/osgearth#2473]
When drawing a polygon, and set `CLAMP_TO_TERRAIN`, `TECHNIQUE_DRAPE`, the polygon is not absolutly clamp to terrain. I use the newest version of osgearth.
When look around, the polygon has offset relavite to terrain.
``` c++
Polygon* geom = new Polygon();
// put some coords

Style polyStyle;
PolygonSymbol* poly = polyStyle.getOrCreate<PolygonSymbol>();
poly->fill()->color() = Color(Color::Yellow, 0.4);
LineSymbol* line = polyStyle.getOrCreate<LineSymbol>();
line->stroke()->color() = Color::White;
line->stroke()->width() = 2;
AltitudeSymbol* alt = polyStyle.getOrCreate<AltitudeSymbol>();
alt->clamping() = alt->CLAMP_TO_TERRAIN;
alt->technique() = alt->TECHNIQUE_DRAPE;
RenderSymbol* rs = polyStyle.getOrCreate<RenderSymbol>();
rs->depthOffset()->enabled() = true;

Feature* f = new Feature(geom, _mapNode->getMapSRS());
_fn = new FeatureNode(f, polyStyle);
_fn->setMapNode(_mapNode);
_mapNode->addChild(_fn);

```
![clamp](https://github.com/gwaldron/osgearth/assets/8923933/9dffcd01-2e07-4339-8545-8fcb0d25d031)

**Comment by YHLpuyu** [comment]
the boundary is moving when camera moving. Is there some option, that I don't set?

**Comment by YHLpuyu** [comment]
if set `depthoffset` to false, it looks normal

**Comment by gwaldron** [comment]
Draping uses projective texturing to draw the geometry on the terrain.
I'm surprised that depth offsetting affects it; we will re-open this ticket and take a look. Thanks for finding this.
