### ISSUE TITLE
Version 3.5 not available through vcpkg

### ISSUE THREAD

**Issue by OlaRune** [gwaldron/osgearth#2475]
$ ./vcpkg.exe search osgearth
osgearth                 3.4#1            osgEarth - Dynamic map generation toolkit for OpenSceneGraph Copyright 202...

[https://github.com/microsoft/vcpkg/blob/master/ports/osgearth/vcpkg.json](https://github.com/microsoft/vcpkg/blob/master/ports/osgearth/vcpkg.json)

**Comment by gwaldron** [comment]
We are working on this. Standby for updates.

**Comment by OlaRune** [comment]
> We are working on this. Standby for updates.

Any update on this issue? :)

**Comment by gwaldron** [comment]
Yeah, the short answer is, we are going to release version 3.6 and push that to vcpkg instead. 3.6 includes a full CMake refactor that will meet all the vcpkg requirements, clean things up considerably, and get past the issues we're having with 3.5.

Don't have an exact timeframe but we hope to get this going within the next 30 days.
