### ISSUE TITLE
detected OpenGL error invalid operation at after renderBin::draw(..)

### ISSUE THREAD

**Issue by jz336697** [gwaldron/osgearth#2480]
Osgearth runs in the QT window. When I use Polygon, once the size of the window changes, OpenGL prompts the content: Detected OpenGL ERRORID Operation atraction: Draw (..), the interface will all turn black. This will also occur when using ImageOverlay, but it is no problem after using Setdraped (false).

**Comment by gwaldron** [comment]
Next time please fill out the Bug Report template properly.

[Maybe try this.](https://docs.osgearth.org/en/latest/faq.html#rendering-problems-when-using-the-qt-qopenglwidget)

**Comment by jz336697** [comment]
Thank you so much! My problem was solved. Next time I will use the bug report template to fill in.
