### ISSUE TITLE
osgearth_conv command that worked in 3.5 failing with segfault on tip

### ISSUE THREAD

**Issue by michaelgtodd** [gwaldron/osgearth#2481]
**Describe the bug**
An osgearth_conv command that worked in 3.5 now produces a segfault on the latest.

**To Reproduce**
1. Install osgearth
2. Run the below command (with a valid token):
```
osgearth_conv --in driver arcgisserverelevation \
              --in url https://services.arcgisonline.com/arcgis/rest/services/WorldElevation3D/Terrain3D/ImageServer \
              --in token <token omitted!!> \
              --out driver tmselevation \
              --out url output_geo/tms.xml \
              --out format tif \
              --min-level 10 \
              --max-level 10 \
              --extents -90 -180 90 180 \
              --profile global-geodetic \
              --no-overwrite \
              --threads 8
```

**Expected behavior**
osgearth_conv begins downloading tiles

**Desktop (please complete the following information):**
 - Fedora 29 Docker Container on RHEL 8 host OS

**Comment by plevy** [comment]
Michael, are you saying it doesn't work with a token but does without? Or neither work for you?

Thank you

**Comment by plevy** [comment]
Also around that time, there was segfault on RH that was later fixed.  Have you tried grabbing the latest master?

**Comment by gwaldron** [comment]
Fixed a bug in osgearth_conv.
