### ISSUE TITLE
A question about node or feature's edit

### ISSUE THREAD

**Issue by shaozhihua** [gwaldron/osgearth#2499]
I have browsed the official application of OSGEARTH and some projects from others.
I found that everyone use "CircleNodeEditor" or "osgEarth::Annotation::FeatureEditor" class to implment the editing of shapes or features.
but my osgearth is very new,the version is 3.6.5,and I can't find these two classes,
when I read the application tests,file : osgearth_annotation.cpp
![screenshot](https://github.com/gwaldron/osgearth/assets/18071679/8dcf7e78-d1e7-4e55-a719-310da237639c)
which is deleted the CircleNodeEditor,
so my question is how can I add editor to the node like CircleNode 、 ellipseNode、RectangleNode e.g;
expect for some replies ,thanks very much!

**Comment by gwaldron** [comment]
You are right, they were deprecated and removed. You are welcome to grab the old code and use it in your own projects. Good luck!

**Comment by shaozhihua** [comment]
so I can't add editable node to them by the latest osgearth code?
isn't any solution?

**Comment by gwaldron** [comment]
The solution is to take the old editors and update them to use in your own application. There are no annotation editor classes in the current osgEarth.

**Comment by shaozhihua** [comment]
Ok，I will find the "XXXeditor" classes code in early osgearth version,and put them into my project.
thank you very much! Gwaldron. good luck to me.I hope it works.
