### ISSUE TITLE
load local 3dtiles file error

### ISSUE THREAD

**Issue by wangdemon** [gwaldron/osgearth#2505]
**Describe the bug**
I use osgearth_viewerd.exe to load a 3dtiles json file

The osgearth_viewer program crashes directly

**Screenshots**

the earth file

![1](https://github.com/gwaldron/osgearth/assets/20681339/bb8d1540-9e97-44fe-9595-396aa6dc3871)

When crashing, prompt screenshot

![2](https://github.com/gwaldron/osgearth/assets/20681339/f41b4476-d7fb-472b-b8bc-9fd211ec91a6)

**Desktop (please complete the following information):**
 - OS: [Wins]
 - Version [e.g. osgearth35]

**Additional context**
I didn't do anything, just used the mouse wheel to locate the area where 3dtiles were located, and then the program crashed

**Comment by gwaldron** [comment]
Are you able to show us a stack trace from the debugger?
Or post your 3D tiles file so we can try to reproduce the crash?

**Comment by wangdemon** [comment]
> Are you able to show us a stack trace from the debugger? Or post your 3D tiles file so we can try to reproduce the crash?

Please take a look at the screenshot and video below

![img](https://github.com/gwaldron/osgearth/assets/20681339/55cebf3a-378d-473e-ac1f-a75a7546708f)




https://github.com/gwaldron/osgearth/assets/20681339/73994da9-54c5-4f31-b96f-3d8b1dcf19d7


This 3dtile file is 3GB in size, I don't know how to send it to you
![img2](https://github.com/gwaldron/osgearth/assets/20681339/b8f09085-179d-44e0-8c06-eadd8f0a96f0)

**Comment by wangdemon** [comment]
Okay, the screenshot is below

![1](https://github.com/gwaldron/osgearth/assets/20681339/44c7a08d-d835-4140-a9db-ed1749edaf5d)

**Comment by jasonbeverage** [comment]
I've pushed a hopeful fix for this in 12586ed.  Grab the master and give it a shot!
