### ISSUE TITLE
Error message when loading an mbtiles file that isn't created from osgearth

### ISSUE THREAD

**Issue by jasonbeverage** [gwaldron/osgearth#2509]
When you load an earth file with an mbtiles layer with a non-osgearth layer you get a complaint like:
```
osgEarth]* JSON decoding error: * Line 1, Column 1
  Syntax error: value, object or array expected.
```
This might be from trying to load the profile and there not being one in the mbtiles.

**Comment by gwaldron** [comment]
We should prob assume it's spherical-mercator per the mbtiles spec?

**Comment by jasonbeverage** [comment]
Added a check to see if the profileStr might be JSON before attempting to parse it.
