### ISSUE TITLE
Very high hardware resource consumption

### ISSUE THREAD

**Issue by wangdemon** [gwaldron/osgearth#2519]
osgEarth Version (required):3.5

I am using the latest version of osgEarth to load 3dtiles files, which consume a lot of memory and graphics card resources

Look at the screenshot below

The resource usage of osgEarth and cesium web

![1](https://github.com/gwaldron/osgearth/assets/20681339/ff4c8402-58ec-4b8f-8afb-d4056e2f9a2c)

![2](https://github.com/gwaldron/osgearth/assets/20681339/8cf9cdbd-5081-47c7-bff4-6fec7819e49c)

The 3dtiles file, only 800MB
![3](https://github.com/gwaldron/osgearth/assets/20681339/13055478-0129-41e7-aacb-1e988e1eed6e)

**Comment by gwaldron** [comment]
Thank you, if you find any more information feel free to re-open and report.
