### ISSUE TITLE
Is there any a website or doc where can refer to .earth file's configuration?

### ISSUE THREAD

**Issue by shaozhihua** [gwaldron/osgearth#2521]
as we know, we can use xxx.earth file to show a map in the earth 3D model.
but is there any a website or registry to illustrate how to config this file?
Its format is very similar to an XML file,I want a doc that can guide me to create a .earth file.
I know I can read a lot example.earth file and find the  pattern and learn it,but it is a little inefficiency.

expecting everyone's reply and thank you very much!sincerely!

**Comment by shaozhihua** [comment]
actually，My confusion is :
I have some elevation tiles,they are some .tif pictures file.
I guess I need to add their local path(because the tif picture file is in my PC) to a custome .earth file.
but i have no the solution about it.

**Comment by shaozhihua** [comment]
first，thanks for your reply and advice,Gwaldron.
You're an excellent and responsible manager!
but my tif file is not a single file,they are many files in a folder.
so should I add more "<url>xxx.tif</url>" code in the <GDALElevation> tag?

**Comment by gwaldron** [comment]
This might be the best approach:
https://docs.osgearth.org/en/latest/data.html#loading-a-directory-of-files

**Comment by shaozhihua** [comment]
@gwaldron Thanks a lot Glenn,the approach you provided solved my problem successfully.I have been able to sleep well for so many days now.
By the way,The early gdal compiled gdalbuildvrt.exe may not support regular expressions. At least this version 2.1.3 doesn't work.
so I found a newer version then it worked.
