### ISSUE TITLE
Error: 'resib' was not declared in this scope in file CompressedArray.cpp

### ISSUE THREAD

**Issue by ComradeMashkov** [gwaldron/osgearth#2522]
osgEarth Version (required): Version 3.5

Error: 'resib' was not declared in this scope
![image](https://www.upload.ee/image/16604305/328459250-079e327f-d2e2-4813-93c4-1f8b7f39370b.png)

So there is no 'resib' variable in the CompressedArray.cpp file. Where is it defined and how can i fix this? I would really appreciate your help!

Build toolchain: mingw64 (MinGW Makefiles)

**Comment by jasonbeverage** [comment]
I've pushed a fix for this, thanks for reporting the issue!
