### ISSUE TITLE
Build Issues with protobuf when building version 3.5

### ISSUE THREAD

**Issue by gfyrtuwcv** [gwaldron/osgearth#2529]
I encountered a glyphs.pu.h error when building the latest osgearth,like this:
![image](https://github.com/gwaldron/osgearth/assets/107821427/372da88d-b63f-4eaa-b17f-5dd98c753271)
I don't want to use protobuf, but it will fail：
MapboxGLGlyphManager.cpp(28,10): error C1083: Failed to open the include file: "glyphs.pb.h" : No such file or directory
I fell back to osgearth3.4 without using protobuf to build successfully，and I would like to ask osgearth3.5 must use protobuf? Or is there any way to fix the error I encounter?

**Comment by luoxiaozhu** [comment]
try to remove the protobuf category in your cmake gui，then configure and generate

**Comment by gfyrtuwcv** [comment]
Unfortunately, this doesn't work, so it looks like I'll have to use osg3.4 until I find a solution

**Comment by gfyrtuwcv** [comment]
I removed the vcpkg installation of protobuf and used an older version of protobuf, which enabled osgearth3.5 to compile successfully, thanks for your advice!

**Comment by ComradeMashkov** [comment]
> I removed the vcpkg installation of protobuf and used an older version of protobuf, which enabled osgearth3.5 to compile successfully, thanks for your advice!

Hey, which version of protobuf did you use?

**Comment by gfyrtuwcv** [comment]
> Hey, which version of protobuf did you use?


The version of protobuf I used was very old, 3.7.0

**Comment by ComradeMashkov** [comment]
> > Hey, which version of protobuf did you use?
> 
> The version of protobuf I used was very old, 3.7.0

I see. I built protobuf v3.21.10 and it worked. I don't know why, but new versions of protobuf don't contain logger class, which was the reason for linker to crash.
