### ISSUE TITLE
Textures are not loading in the sample code

### ISSUE THREAD

**Issue by ComradeMashkov** [gwaldron/osgearth#2534]
osgEarth Version (required): [3fc9686](https://github.com/gwaldron/osgearth/commit/3fc9686bf956e91640e215e9aae7048cd0f0ee72) master

**What is the problem?** 

I have successfully built the osgEarth library. However, when I try to run sample from [docs](https://docs.osgearth.org/en/latest/install.html), I get this output in console:

<details>
<summary>Console output</summary>

```
[osgearth warning] ASSERTION FAILURE (createMains @ C:\Users\ilya.mashkov\Desktop\osgearth\src\osgEarth\ShaderFactory.cpp:170) state.getUseVertexAttributeAliasing() ...OpenSceneGraph vertex attribute aliasing must be enabled. Consider installing the GL3RealizeOperation in your viewer.
[osgearth warning] ASSERTION FAILURE (createMains @ C:\Users\ilya.mashkov\Desktop\osgearth\src\osgEarth\ShaderFactory.cpp:173) state.getUseModelViewAndProjectionUniforms() ...OpenSceneGraph matrix uniforms must be enabled. Consider installing the GL3RealizeOperation in your viewer.
[osgearth warning] [VirtualProgram] Program will not link!
[osgearth warning] ASSERTION FAILURE (createMains @ C:\Users\ilya.mashkov\Desktop\osgearth\src\osgEarth\ShaderFactory.cpp:170) state.getUseVertexAttributeAliasing() ...OpenSceneGraph vertex attribute aliasing must be enabled. Consider installing the GL3RealizeOperation in your viewer.
[osgearth warning] ASSERTION FAILURE (createMains @ C:\Users\ilya.mashkov\Desktop\osgearth\src\osgEarth\ShaderFactory.cpp:173) state.getUseModelViewAndProjectionUniforms() ...OpenSceneGraph matrix uniforms must be enabled. Consider installing the GL3RealizeOperation in your viewer.
[osgearth warning] [VirtualProgram] Program will not link!
```

</details>

And the image is like:

<details>
<summary>Image</summary>

![image](https://github.com/gwaldron/osgearth/assets/117441107/ca98ec51-50bd-47da-849b-112add7ffee4)

</details>

Then I googled the problem a bit and found out, that I built the library with OpenGL 2 profile (by default). That is why I have to insert this:
```cpp
viewer.setRealizeOperation(new osgEarth::GL3RealizeOperation());
```

I did this trick but it didn't help. The output in console is clear, but textures are still missing (the sphere is white).

<details>
<summary>Image</summary>

![image](https://github.com/gwaldron/osgearth/assets/117441107/b416bdab-302b-4f16-bc96-49ec93a54612)

</details>

How can I solve this problem? I am glad that I found your library and you guys did the great work. But I suspect that I am stuck in my misunderstanding of the problem. I feel that I built library the wrong way, but I'm not sure. I would really appreciate your help! Thanks!

**UPD**: I guess the problem is in my location. I can't reach readymap site without VPN so the example is not working :(

**Comment by jasonbeverage** [comment]
We have certain countries blocked on our ReadyMap server so you won't be able to access it from those locations.  Check out some of the other examples that use different data sources or use some local geospatial data via the GDALImage/GDALElevation driver.
