### ISSUE TITLE
Call function dirty() of my custom imagelayer which inherit from imageLayer didn't make createImageImplementation re-execute

### ISSUE THREAD

**Issue by luoxiaozhu** [gwaldron/osgearth#2535]
osgEarth Version (required):
3.5
What is the problem?
Hi ,I made my custom imageLayer which inherite from Imagelayer,and  reimplement  createImageImplementation  to use the parameters of tilekey to query the elements in the local database, and the visibility of these elements change according to the user operations, So after I modify the visibility of certain elements I need createImageImplementation method can perform again, so I changed elements in visibility called after the layer of dirty method and set the layer of caching policy to NO_CACHE in advance,but 
 function createImageImplementation didn't re-execute as i wish , I don't know what to do, hope to get your advice,thank you.

**Comment by gwaldron** [comment]
Try calling one of the `mapNode->getTerrainEngine()->invalidateRegion(...)` functions.

**Comment by luoxiaozhu** [comment]
hi gwaldron，thank you so much，it works！
