### ISSUE TITLE
ObjectWrapperManager::addWrapper(): '' already exists.

### ISSUE THREAD

**Issue by ComradeMashkov** [gwaldron/osgearth#2541]
osgEarth Version (required): [3fc9686](https://github.com/gwaldron/osgearth/commit/3fc9686bf956e91640e215e9aae7048cd0f0ee72) 

**What is the problem?** 
When trying to include `<osgEarth/MapNode>` I get this error (multiple lines):
```bash
$ ./Debug/myApp.exe
ObjectWrapperManager::addWrapper(): '' already exists.
ObjectWrapperManager::addWrapper(): '' already exists.
ObjectWrapperManager::addWrapper(): '' already exists.
ObjectWrapperManager::addWrapper(): '' already exists.
ObjectWrapperManager::addWrapper(): '' already exists.
```

I built osgEarth with Cesium Native and GL3 Profile using Visual Studio 17 2022 generator.

**Comment by gwaldron** [comment]
Recommend consulting the OpenSceneGraph support group about this issue.
