### ISSUE TITLE
i used those example programs ，but i'm having some issues （i built the project using vcpkg）

### ISSUE THREAD

**Issue by kiikor** [gwaldron/osgearth#2556]
PS E:\work\build\src\applications\osgearth_simple\RelWithDebInfo> ./osgearth_simple simple.earth
Fontconfig error: Cannot load default config file: No such file: (null)
Error reading file C:/Users/RiuShin/AppData/Local/Microsoft/Windows/Fonts\CascadiaCode.ttf: file not handled
Error reading file simple.earth: file not handled
Error: File not found
Usage: E:\work\build\src\applications\osgearth_simple\RelWithDebInfo\osgearth_simple.exe file.earth

i need some help，please，

**Comment by gwaldron** [comment]
Make sure the osgEarth and dependency DLLs are in your system path.
