### ISSUE TITLE
The close() and open() methods of layers  crash

### ISSUE THREAD

**Issue by DogMan624586** [gwaldron/osgearth#2570]
osgEarth Version (required):
3.1

What is the problem?
When I load a service using XYZImageLayer, I frequently call {XYZImageLayer ->close(), XYZImageLayer ->open()} with a timer, which causes a random crash phenomenon

How have you tried to resolve it?
Attempted to resolve but failed

Help US help YOU: include a screenshot, code block, or data file that we can use to reproduce the issue!

**Comment by gwaldron** [comment]
Did you try reproducing the problem in the latest version of osgEarth?
If so, do you have a .cpp that will help us reproduce the bug?

**Comment by gwaldron** [comment]
Closing due to lack of feedback; re-open if you have more to add.
