### ISSUE TITLE
no matching function for call to ‘CesiumIonClient::Connection::Connection(CesiumAsync::AsyncSystem&, std::shared_ptr<osgEarth::Cesium::AssetAccessor>&, std::string)'

### ISSUE THREAD

**Issue by virtuozo007** [gwaldron/osgearth#2573]
osgEarth Version (required):    the latest master version.

compiling with the latest Cesium-native lib.

From version 0.35.0, a parameter called "CesiumIonClient::ApplicationData&" was added in the constructor function of  "Connection" in the "CesiumIonClient" module.

So, the "CesiumIon::refresh()" funtion in CesiumIon.cpp may need a modify as bellow,   i guess:
`Connection connection(Context::instance().asyncSystem, Context::instance().assetAccessor, getCesiumIonKey(), CesiumIonClient::ApplicationData());`

**Comment by gwaldron** [comment]
osgEarth 3.5/3.6 builds against Cesium Native 0.31.0.
