### ISSUE TITLE
Dependencies problems

### ISSUE THREAD

**Issue by devil-darkside** [gwaldron/osgearth#2588]
osgEarth Version (required): **3.6**

What is the problem?
How have you tried to resolve it?
Missing library dependencies (osgEarthProcedural.lib and osgEarthImGui.lib) for new ImGui implementation on osgearth_windows and osgearth_collecttriangles.
Include reference too.

In addition to #2585.

**Comment by gwaldron** [comment]
Thanks.
Workaround will be to disable OSGEARTH_BUILD_TESTS in Cmake (which I think is the default)

**Comment by devil-darkside** [comment]
I know... Thanks

**Comment by gwaldron** [comment]
Fixed
