### ISSUE TITLE
Error reading file tests\nodata.earth: file not handled

### ISSUE THREAD

**Issue by ianleework** [gwaldron/osgearth#2602]
osgEarth Version (required): osgEarth 3.4.0 build 148

i installed osgearth from vcpkg, when i run osgearth_viewer *.earth , it always show these:
D:\vcpkg\installed\x64-windows\tools\osgearth>osgearth_viewer.exe tests\nodata.earth
[osgEarth]* [Capabilities] Warning, OpenSceneGraph does not define OSG_GL3_AVAILABLE; the application may not function properly
Error reading file tests\nodata.earth: file not handled
 it cannot handle earth file, i added osg and osgearth folder to environment variables, and copy fontconfig file and osg plugins folder to the viewer folder,   it still has this problem, could someone help me?

**Comment by gwaldron** [comment]
Usually this means your path is not set up properly. Make sure both these folders are in your path:
```
vcpkg_installed\x64-windows\bin
vcpkg_installed\x64-windows\plugins
```
(You can usually safely ignore the GL3 warning.)

**Comment by sergei** [comment]
Getting the same problem, set the paths as follow:

`$ echo $PATH
/opt/homebrew/osgearth/lib64/osgPlugins-3.6.5:/opt/homebrew/osgearth/bin/:
`

The output is as follow:
`$ osgearth_viewer readymap.earth
Error reading file readymap.earth: file not handled
[osgEarth]* [MapNodeHelper] No earth file loaded
View an earth file: osgearth_viewer file.earth
`
Any suggestions how to proceed?

**Comment by feishengfei** [comment]
> Getting the same problem, set the paths as follow:
> 
> ```
> $ echo $PATH
> /opt/homebrew/osgearth/lib64/osgPlugins-3.6.5:/opt/homebrew/osgearth/bin/:
> ```
> 
> The output is as follow:
> 
> ```
> $ osgearth_viewer readymap.earth
> Error reading file readymap.earth: file not handled
> [osgEarth]* [MapNodeHelper] No earth file loaded
> View an earth file: osgearth_viewer file.earth
> ```
> 
> Any suggestions how to proceed?

I guess you need to check whether there is a 'osgdb_earth.so' under '../osgearth/lib64/osgPlugins-3.6.5'

In my case, there're no osgdb_earth.so either.

**Comment by feishengfei** [comment]
@sergei My issue :
```
Error reading file ./boston.earth: file not handled
[osgEarth]* [MapNodeHelper] No valid earth file loaded - aborting
[osgEarth]  Hello, world.
[osgEarth]  [Registry] Note: GDAL_DATA environment variable is not set 
[osgEarth]  [Capabilities] Realized graphics window for OpenGL operations.
[osgEarth]  [Capabilities] osgEarth Version:  3.5.0 build 149 
[osgEarth]  [Capabilities] OSG Version:       3.6.5
[osgEarth]  [Capabilities] GDAL Version:      3.8.4
[osgEarth]  [Capabilities] GPU Vendor:        Intel
[osgEarth]  [Capabilities] GPU Renderer:      Mesa Intel(R) UHD Graphics 630 (CML GT2)
[osgEarth]  [Capabilities] GL/Driver Version: 4.6 (Core Profile) Mesa 24.0.9-0ubuntu0.3 (460)
[osgEarth]  [Capabilities] GL Core Profile:   yes 
[osgEarth]  [Capabilities] Max GPU texture units = 32
[osgEarth]  [Capabilities] Max varyings = 0 
[osgEarth]  [Capabilities] Max texture size = 16384
[osgEarth]  [Capabilities] GLSL Version = 460 
[osgEarth]  [Capabilities] draw instanced = yes 
[osgEarth]  [Capabilities] Compression = S3 RG
[osgEarth]  [GLUtils] Disabling NVIDIA GL4 extensions
[osgEarth]  
Usage: osgearth_viewer file.earth
  --sky                         : add a sky model
  --kml <file.kml>              : load a KML or KMZ file
  --kmlui                       : display a UI for toggling nodes loaded with --kml
  --coords                      : display map coords under mouse
  --ortho                       : use an orthographic camera
  --logdepth                    : activates the logarithmic depth buffer
  --logdepth2                   : activates logarithmic depth buffer with per-fragment interpolation
  --shadows                     : activates model layer shadows
  --out-earth [file]            : write the loaded map to an earth file
  --uniform [name] [min] [max]  : create a uniform controller with min/max values
  --define [name]               : install a shader #define
  --path [file]                 : load and playback an animation path
  --extension [name]            : loads a named extension
  --ocean                       : add a simple ocean model (requires bathymetry)

[osgEarth]  [StateSetCache] Pruned 0 attributes, 0 statesets
[osgEarth]  [Registry] Registry shutting down...
[osgEarth]  [Registry] Registry shutdown complete.
[osgEarth]  [StateSetCache] Pruned 0 attributes, 0 statesets
```
was related that I forgot to install 'osgdb_xxxx.so' under debian/tmp/usr/lib/osgPlugins-3.6.5/
I'm adding debian support for integration. 
After install the necessary  'osgdb_xxxxx.so' into '/usr/lib/osgPlugins-3.6.5/', 'xxx.earth' file can be peacefully loaded and the correct map shown up.
