### ISSUE TITLE
A question about rotation of the earth

### ISSUE THREAD

**Issue by jeekjie** [gwaldron/osgearth#2603]
Hi,I have a problem with the rotation of the earth.I use a osg::MatrixTransform and a osg::NodeCallback to rotate the earth,but I found that the earth didn't rotate as expected.When I replace the earth with other osg Models,the code works fine.Could anyone help me?Thanks!
My Environment:
**OSG:3.6.5
OSGEarth:3.5.0**
IDE:Visual Studio 2017
OS:Windows 10
![caps](https://github.com/user-attachments/assets/d59973b6-141e-4bd4-ad3c-74b14c2721ad)
[main.zip](https://github.com/user-attachments/files/16536557/main.zip)

**Comment by gwaldron** [comment]
The `EarthManipulator` keeps your camera pointed at the same location.
So the earth is rotating, but your camera is rotating along with it.

**Comment by jeekjie** [comment]
> The `EarthManipulator` keeps your camera pointed at the same location. So the earth is rotating, but your camera is rotating along with it.

I find that the code works fine with **OSG3.4.0** and **OSGEarth2.8**,so anything different in newer version?

**Comment by jeekjie** [comment]
> The `EarthManipulator` keeps your camera pointed at the same location. So the earth is rotating, but your camera is rotating along with it.
you could try  to run the code from the main.cpp with  OSG3.4.0 and OSGEarth2.8, and the earth will rotate normally.

**Comment by jeekjie** [comment]
> The `EarthManipulator` keeps your camera pointed at the same location. So the earth is rotating, but your camera is rotating along with it.

Problem solved,thanks!
