### ISSUE TITLE
Can't build current master with GLCore / VS

### ISSUE THREAD

**Issue by remoe** [gwaldron/osgearth#2610]
The CMake variable ```DOSGEARTH_GLCORE_INCLUDE_DIR``` has been removed in the current master branch, and ```FindGLCORE.cmake``` has also been removed. I don't use vcpkg to build osgEarth. What is required to build osgEarth (VisualStudio/Windows) with the GLCore profile without vcpkg?

**Comment by emminizer** [comment]
We build osgEarth outside of vcpkg as well. This won't help you, but just as a data point, we add `include/GL/glcorearb.h` to our OpenSceneGraph install since it's kind of required with anything OSG in these cases.

**Comment by remoe** [comment]
Thanks, @emminizer. Yes, this is possible, but my goal was to separate OSG from GLCore and use it as a library.

**Comment by gwaldron** [comment]
You have to build OSG with the CMake option `OPENGL_PROFILE=GLCORE`.

There is no special GLCORE setup in osgEarth itself. It just includes `<osg/GL>` and uses whatever is in there. When you use the GLCORE profile, <osg/GL> will reference glcorearb.h.

**Comment by remoe** [comment]
@gwaldron yes, but when the include path to <GL/...> is not defined, then cmake doesn't find this header file. One need to include GLCore as a header library.

**Comment by gwaldron** [comment]
I see. So all you need then is to add the location of `GL/glcorearb.h` to the include directories, correct?

**Comment by remoe** [comment]
yes, in the past it was ```-DOSGEARTH_GLCORE_INCLUDE_DIR``` and https://github.com/gwaldron/osgearth/blob/osgearth-3.5/CMakeModules/FindGLCORE.cmake . But I'm not sure FindGLCore is needed.

**Comment by gwaldron** [comment]
That is what I am thinking. We don't really need FindGLCORE since you still have to tell it where to look.
Can we just add that back as a simple CMake variable that you can set?

**Comment by gwaldron** [comment]
@remoe I reinstated the `OSGEARTH_GLCORE_INCLUDE_DIR` cmake variable. There's no Find script, just set it like you did before.
