### ISSUE TITLE
Add support for Cesium Ion self hosted

### ISSUE THREAD

**Issue by jasonbeverage** [gwaldron/osgearth#2613]
We need to change some of the options in cesium native to support self hosted Cesium Ion so we can have per layer api tokens and server urls.

### Discussed in https://github.com/gwaldron/osgearth/discussions/2612

<div type='discussions-op-text'>

<sup>Originally posted by **remoe** August 26, 2024</sup>
Does support cesium-nodekit a self hosted Cesium ION with asset id's? It needs accessToken per layer and a server configuration entry for the cesium api server in the earth file?

In CesiumJS (javascript) one can add it as follow:

```js
const resource = await IonResource.fromAssetId(assetID, {
  accessToken: '<TOKEN>',
  server: 'https://example.ion'
});

const terrainProvider = CesiumTerrainProvider.fromUrl(resource);

```</div>

**Comment by remoe** [comment]
@jasonbeverage I've done a first implementation. I've tested it with a single-user mode self-hosted ION mixed with default ION.
