### ISSUE TITLE
How can I add many ImageLayers with large data (600MB) to the map fast？

### ISSUE THREAD

**Issue by ZzWDlyy** [gwaldron/osgearth#2620]
If I want to add many ImageLayers with large data (600MB) to the map, how can I make them load and render faster? Can I use osgearth_cache, and how do I use it in osgearth 3.5?
please help me.

**Comment by plevy** [comment]
Yes, overviews and then keep scrolling down on that page for tilesets.  Overviews should help alot.

**Comment by ZzWDlyy** [comment]
Ok,I will try.thanks for your help.
