### ISSUE TITLE
the VERTICAL_INTERLACE stereo mode seems error,but ANAGLYPHIC mode and HORIZONTAL_SPLIT is right

### ISSUE THREAD

**Issue by myhawk557** [gwaldron/osgearth#2631]
I want to show the earth in stereo mode, I write a console program,the ANAGLYPHIC 、VERTICAL_SPLIT、
![screenshot-20240920-201432](https://github.com/user-attachments/assets/7763fe54-44ea-4bfa-a89e-f27f8bf9b427)
![screenshot-20240920-201611](https://github.com/user-attachments/assets/6b548a69-7305-4900-a479-74ee8ac9dceb)
![screenshot-20240920-201309](https://github.com/user-attachments/assets/51a9f2ef-2108-44d7-893e-f7e588014ac6) mode is right，but HORIZONTAL_INTERLACE、VERTICAL_INTERLACE is wrong。

Here is the code :
    osg::ArgumentParser arguments(&argc1, (char**)argvv);

    // start up osgEarth
    osgEarth::initialize();

    // create a simple view
    osgViewer::Viewer viewer(arguments);
    viewer.setUpViewInWindow(x, y, width, height);

    // install our default manipulator (do this before calling load)
    viewer.setCameraManipulator(new EarthManipulator(arguments));

    // disable the small-feature culling; necessary for some feature rendering
    viewer.getCamera()->setSmallFeatureCullingPixelSize(-1.0f);

    viewer.setKeyEventSetsDone(0);
    osg::DisplaySettings* disp = osg::DisplaySettings::instance();
    if (stereo >= 0) {
        disp->setStereo(true);
        disp->setStereoMode(osg::DisplaySettings::VERTICAL_INTERLACE);                
        disp->setScreenWidth(width);
        disp->setScreenHeight(height);
    }

    osg::Group* root = new osg::Group;
    // load an earth file, and support all or our example command-line options
    auto node = MapNodeHelper().load(arguments, &viewer);
    if (node.valid())
    {
        if (MapNode::get(node))
        {
            //地图配置：设置缓存目录
            osgEarth::ProfileOptions profileOpts;
            osgEarth::Drivers::FileSystemCacheOptions cacheOpts;
            std::string cacheDir = "/tmp";
            cacheOpts.rootPath() = cacheDir;

            osgDB::Options* op = new osgDB::Options(cacheDir);
            osgEarth::Map::Options mapOpts;
            mapOpts.cache() = cacheOpts;
            mapOpts.profile() = profileOpts;
            //创建地图节点
            //osg::ref_ptr<osgEarth::Map> pMap = new osgEarth::Map(mapOpts);
            osg::ref_ptr<osgEarth::Map> pMap = new osgEarth::Map(op);
            osg::ref_ptr<osgEarth::MapNode> pMapNode = new osgEarth::MapNode(pMap);

            // 添加倾斜摄影数据
            std::string fileDir = "F:\\e_bak\\data\\xuchang1\\Data";
            std::string outputLodFile = fileDir + "/Data.osgb";

            //OSG直接读取
            std::string filePath = outputLodFile;
            ReaderWriterS3C* reader = new ReaderWriterS3C();
            osgDB::ReaderWriter::ReadResult g = reader->readNode(oblique, NULL);
            AddModelEx(g.getNode(), pMap, pMapNode);
            root->addChild(pMapNode);

            root->addChild(node);
            viewer.setSceneData(root);

            ShaderGenerator gen;
            gen.run(root);
            return viewer.run();
        }
    }

**Comment by gwaldron** [comment]
I this is outside the scope of osgEarth -- I recommend you ask about it on the OpenSceneGraph page:
https://github.com/openscenegraph/OpenSceneGraph/issues

Good luck.
