### ISSUE TITLE
ElevationLayer Async?

### ISSUE THREAD

**Issue by HerryJessica** [gwaldron/osgearth#2661]
How to make ElevationLayer async？
I found that the ElevationLayerr may cause the Imagelayer to be blocked,Can provide a function like Imagelayer setAsyncLoading?

**Comment by gwaldron** [comment]
No, there is no way to load an elevation layer asynchronously.
What type of elevation data are you using? Can you pre-tile it?

**Comment by HerryJessica** [comment]
My data comes from the Internet and it will be blocked if the network is not good

**Comment by HerryJessica** [comment]
My data comes from the Internet and if the server request is slow, it will be blocked

**Comment by gwaldron** [comment]
Gotcha.
We do not have any plans for an asynchronous elevation layer at this time.
