### ISSUE TITLE
osgearth_minimap not working

### ISSUE THREAD

**Issue by devil-darkside** [gwaldron/osgearth#2668]
osgEarth Version (required): 3.7.1 build 164

Description of the problem: minimap is not shown. I'm just trying the example in order to integrate the minimap in my main application.

What you have tried: launch the example with simple.earth

**Comment by gwaldron** [comment]
I cannot reproduce the issue. I see the minimap in the lower-left corner of the view.
Can you post a screenshot?
Can you set `OSGEARTH_NOTIFY_LEVEL=INFO` and post any console output?

**Comment by devil-darkside** [comment]
I've compiled again the osgearth and now it works.
I've also updated osgearth to the last commit and it works.
I've found an error in the FeatureTest.cpp "splitAcrossDateLine" that Washington replaced by the "splitAcrossAntiMeridian".

**Comment by gwaldron** [comment]
Thanks.
This too should be patched up in the latest push.
