### ISSUE TITLE
How to specify the basic authentication parameters when creating an XYZImageLayer?

### ISSUE THREAD

**Issue by Shreyansh-prog** [gwaldron/osgearth#2670]
I successfully loaded an XYZ tile map service without authentication in my osgEarth application using the URL: "[https://tile.openstreetmap.org/{z}/{x}/{y}.png."](https://tile.openstreetmap.org/%7Bz%7D/%7Bx%7D/%7By%7D.png.%22)
 
Next, I attempted to load an XYZ tile map service with basic authentication in QGIS (screen capture below), and I was able to load it successfully.
![OSG Earth Image 1](https://github.com/user-attachments/assets/6d0a5f4c-7819-415d-a1d9-6c1b755f8a11)

However, when I tried to create an osgEarth::XYZImageLayer to load an XYZ tile map service that requires basic authentication (username and password), the attempt failed. Is there a way to specify the basic authentication parameters when creating an XYZImageLayer?

**Comment by gwaldron** [comment]
HTTP Basic Authentication works by adding an HTTP request header. You can do this like so:
```c++
URIContext context;
context.addHeader("Authorization", "Basic BASE64CREDENTIALS=");

URI location("https://myserver", context);
xyzLayer->setURL(location);
```
Replace `BASE64CREDENTIALS` with your own base64-encoded credentials according to the spec.
Hope this helps.

**Comment by Shreyansh-prog** [comment]
Thanks for the prompt response. This resolved my issue.
