### ISSUE TITLE
How to create a local coordinate system in osgEarth?

### ISSUE THREAD

**Issue by Shreyansh-prog** [gwaldron/osgearth#2671]
I loaded a georeferenced GIS dataset (Shapefile with an associated projection file) into osgEarth, and it displayed correctly.

Then, I tried to load a non-georeferenced shapefile into QGIS, it loaded successfully, but the coordinate system was shown as “Invalid projection.”
![Screenshot of Invalid SRS in QGIS](https://github.com/user-attachments/assets/5d6e7c6b-c187-44f7-8ca2-0921d8c7ce76)

I then attempted to load the same non-georeferenced shapefile into osgEarth. While the shapefile loaded, no data was displayed in the viewer.

Is there a way to create a local coordinate system in osgEarth that would allow me to load and display a non-georeferenced shapefile?

**Comment by gwaldron** [comment]
No; osgEarth requires all data to be georeferenced.
You can easily give your data an a valid SRS using QGIS or ogr2ogr.

**Comment by Shreyansh-prog** [comment]
Ok, thank you for your prompt assistance with my request. Your quick response helped me a lot. I truly appreciate your support.
Best regards,
Shreyansh
