### ISSUE TITLE
Minizip build error on gentoo

### ISSUE THREAD

**Issue by chrisstankevitz** [gwaldron/osgearth#332]
Please:

1. Change the minizip searched-for-file from zip.h to unzip.h.  When searching for zip.h, cmake is finding /usr/include/zip.h vs /usr/include/minizip/zip.h

2. Add an additional directory to the minizip search path: /usr/include/minizip/ which is where gentoo puts the minizip files

Thanks,

Chris

diff --git a/CMakeModules/FindMiniZip.cmake b/CMakeModules/FindMiniZip.cmake
index c80ebbf..8dbc657 100644
--- a/CMakeModules/FindMiniZip.cmake
+++ b/CMakeModules/FindMiniZip.cmake
@@ -5,7 +5,7 @@
 # MINIZIP_INCLUDE_DIR, where to find the headers
 #
 
-FIND_PATH(MINIZIP_INCLUDE_DIR zip.h
+FIND_PATH(MINIZIP_INCLUDE_DIR unzip.h
     ${CMAKE_SOURCE_DIR}/src/3rdparty/minizip
     $ENV{MINIZIP_DIR}/include
     $ENV{MINIZIP_DIR}
@@ -16,6 +16,7 @@ FIND_PATH(MINIZIP_INCLUDE_DIR zip.h
     /Library/Frameworks
     /usr/local/include
     /usr/include
+    /usr/include/minizip # Gentoo
     /sw/include # Fink
     /opt/local/include # DarwinPorts
     /opt/csw/include # Blastwave

**Comment by gwaldron** [comment]
minizip dependency is removed.
