### ISSUE TITLE
segmentation fault from osgEarth_engine_mp::QuickReleaseGLObjects::operator()

### ISSUE THREAD

**Issue by chdohmen** [gwaldron/osgearth#437]
osgEarth_engine_mp::QuickReleaseGLObjects::operator() seg. faults with the following backrace:

#0  0xded15de4 in empty (this=0x0) at /usr/gcc-4.6.3/lib/gcc/i686-suse-linux/4.6.3/../../../../include/c++/4.6.3/bits/stl_tree.h:692
#1  empty (this=0x0) at /usr/gcc-4.6.3/lib/gcc/i686-suse-linux/4.6.3/../../../../include/c++/4.6.3/bits/stl_map.h:419
#2  osgEarth_engine_mp::TileNodeRegistry::empty (this=0x0)
    at /usr/src/packages/BUILD/gwaldron-osgearth-17a230a/src/osgEarthDrivers/engine_mp/TileNodeRegistry.cpp:184
#3  0xded014e0 in osgEarth_engine_mp::QuickReleaseGLObjects::operator() (this=0x8fb0310, renderInfo=...)
    at /usr/src/packages/BUILD/gwaldron-osgearth-17a230a/src/osgEarthDrivers/engine_mp/QuickReleaseGLObjects:79
#4  0xe5a74e66 in osgUtil::RenderStage::draw (this=0x851fb18, renderInfo=..., previous=@0xde2d2eec)
    at /usr/src/packages/BUILD/OpenSceneGraph-3.0.1/src/osgUtil/RenderStage.cpp:1269
#5  0xe5a81583 in osgUtil::SceneView::draw (this=0x851d1e0) at /usr/src/packages/BUILD/OpenSceneGraph-3.0.1/src/osgUtil/SceneView.cpp:1443
#6  0xe58f8618 in osgViewer::Renderer::draw (this=0x8519408) at /usr/src/packages/BUILD/OpenSceneGraph-3.0.1/src/osgViewer/Renderer.cpp:725
#7  0xe58f74f5 in osgViewer::Renderer::operator() (this=0x8519408, context=0x84b3710)
    at /usr/src/packages/BUILD/OpenSceneGraph-3.0.1/src/osgViewer/Renderer.cpp:892
#8  0xe5ceb8f8 in osg::GraphicsContext::runOperations (this=0x84b3710)
    at /usr/src/packages/BUILD/OpenSceneGraph-3.0.1/src/osg/GraphicsContext.cpp:756
#9  0xe5ced85b in osg::RunOperations::operator() (this=0x87ca480, context=0x84b3710)
    at /usr/src/packages/BUILD/OpenSceneGraph-3.0.1/src/osg/GraphicsThread.cpp:137
#10 0xe5ceda66 in osg::GraphicsOperation::operator() (this=0x87ca480, object=0x84b3710)
    at /usr/src/packages/BUILD/OpenSceneGraph-3.0.1/src/osg/GraphicsThread.cpp:53
#11 0xe5d3d57f in osg::OperationThread::run (this=0x8468648) at /usr/src/packages/BUILD/OpenSceneGraph-3.0.1/src/osg/OperationThread.cpp:426
#12 0xe5cedb08 in osg::GraphicsThread::run (this=0x8468648) at /usr/src/packages/BUILD/OpenSceneGraph-3.0.1/src/osg/GraphicsThread.cpp:38
#13 0xe6ef036e in OpenThreads::ThreadPrivateActions::StartThread (data=0x8468654)
    at /usr/src/packages/BUILD/OpenSceneGraph-3.0.1/src/OpenThreads/pthreads/PThread.cpp:181
#14 0xed03cb05 in start_thread () from /lib/libpthread.so.0
#15 0xecf9dd5e in clone () from /lib/libc.so.6

I'm using osg 3.0.1 and osgEarth 2.5. The seg. faulting app removes all image layers and add new image layers triggered by mouse wheel. And if this happens 'too often' or 'too quick' I get this crash.

**Comment by gwaldron** [comment]
retested; cannot reproduce.
