### ISSUE TITLE
PointSymbol can not work for point shape file

### ISSUE THREAD

**Issue by nickyxu** [gwaldron/osgearth#440]
PointSymbol works based on point(the feature must contains more than one point).
However IconSymbol works based on feature. 

They are very different under multi-point.

![capitals](https://f.cloud.github.com/assets/1539051/1710586/08edb470-6135-11e3-8d5f-4924537fa3f4.png)
![capitals_multipoint](https://f.cloud.github.com/assets/1539051/1710588/0c840e7c-6135-11e3-91e6-584de502c941.png)

I really don't how to attach file.
The above two png actually are rar file. You can just save as ... and rename them to rar.

Sorry about that.

Best Regards,
Nicky

**Comment by jasonbeverage** [comment]
If you don't specify a style at all, you will usually see "something" with osgearth.  In the case of the feature_gpx example you can't just change the layer index to 0 (points) without changing the style (which only defines a stroke for lines).  If you add a point-fill: #ffff00 to the style then it will work.
