### ISSUE TITLE
Memory Leak caused by the engine_mp QuickReleaseGLObjects callback

### ISSUE THREAD

**Issue by MPursche** [gwaldron/osgearth#462]
Hello,

I have found a memory leak in osgEarth, that is caused by the QuickReleaseGLObjects callback. This bug is only triggered when the scene graph has a specific layout:
1. The scene graph contains one or more pre or post render cameras that use a osgEarth::MapNode.
2. A osg::Switch is used to make some of these pre-renderpasses optional.
3. The first camera that wraps the osgEarth::MapNode is one of the optional cameras.

I have an application that supports some complex rendering techniques like depth peeling or shadow mapping. This techniques can be toggled on and off at run-time to improve the performance. I use a scene graph layout as described above to deactivate unnecessary pre-renderpasses.
The problem is that the osgEarth::TerrainNode of the mp engine adds the QuickReleaseGLObjects callback to the first parent camera. In my application this is an optional camera. So if the associated rendering technique is not used, this camera is not traversed and the callback is never called, with the result that removed tiles pile up in the dead tiles list and never get destroyed.

As a quick workaround I deactivated the quick release GL objects function in the earth-file, but it would be nice if I could use it in my application.
It would be nice if the callback could be attached to a camera by the application itself. But after looking at the code I can't think of a reasonable way to implement this.

Greetings

Marcel

**Comment by gwaldron** [comment]
NTS: adapt the ResourceReleaser as a replacement for the QuickReleaseGLObjects , as in rex

**Comment by gwaldron** [comment]
Done, QR replaced be ResourceReleaser
