### ISSUE TITLE
LocalizedNode  constructor call  Pure Virtual Function

### ISSUE THREAD

**Issue by friendbaby** [gwaldron/osgearth#543]
LocalizedNode::LocalizedNode(MapNode* mapNode, const Config& conf) 
call setScale( const osg::Vec3f& scale )
call  updateTransform( const GeoPoint& p, osg::Node* patch )
call  getTransform()

virtual osg::MatrixTransform* LocalizedNode::getTransform() =0;

if config has "scale" ,it will crash

**Comment by gwaldron** [comment]
fixed
