### ISSUE TITLE
Use of newest duktape (0.12) ?

### ISSUE THREAD

**Issue by remoe** [gwaldron/osgearth#552]

**Comment by remoe** [comment]
I use currently v1.1.0 of duktape and osgearth allow to use a different version. So I close this.

**Comment by gwaldron** [comment]
Thanks. Can you comment on any improvements that would make it wise to upgrade the internal version? Is it faster?

**Comment by remoe** [comment]
I haven't tested the performance. But I need to use this: http://duktape.org/guide.html#modules

**Comment by gwaldron** [comment]
That looks useful indeed. We may consider modularizing the JS API in the future..
