### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by DaxDeveloper** [gwaldron/osgearth#558]
Hi,
I have try to build the VS2013 solution and I have a lot of error like this:
Error	1	error C2664: 'bool osgEarth::Profile::isHorizEquivalentTo(const osgEarth::Profile *) const' : cannot convert argument 1 from 'const osg::ref_ptr<const osgEarth::Profile>' to 'const osgEarth::Profile *'	osgEarth.

I can solve the problem using the raw pointer but in any case which is the problem? Something is wrong in my configuration?

Regards

**Comment by beachwalker** [comment]
Hi,

I also use VS2013. Works for me. Did you succeed in the the mean time?

**Comment by DaxDeveloper** [comment]
Hi,
yes I stil the same problem :(.

Any suggestion?

**Comment by DaxDeveloper** [comment]
In attachment you can find a screenshot of my problem.
![error](https://cloud.githubusercontent.com/assets/6593113/6000046/1532bb9c-aad9-11e4-84e9-d8ce635b8a0b.jpg)

**Comment by gwaldron** [comment]
Did you compile OSG with the OSG_USE_REF_PTR_IMPLICITY_OUTPUT_CONVERSION option disabled?

**Comment by gwaldron** [comment]
Any update? If not, I will close

**Comment by remoe** [comment]
I don't have any compile error with VS2013 x64 on master and OSG 3.1.4.
