### ISSUE TITLE
osgearth_featureditor sample crashes when editing

### ISSUE THREAD

**Issue by beachwalker** [gwaldron/osgearth#559]
The feature editor sample allows adding lines but crushes when switching to edit mode.

- first add verts
- create some lines
- click the button for switching to edit mode => crush

environment: x64, windows 8, no qt

**Comment by beachwalker** [comment]
Seems to be there is a duplicate: https://github.com/gwaldron/osgearth/issues/564

**Comment by gwaldron** [comment]
yep, thanks - closed for dupe
