### ISSUE TITLE
Crash osgearth_featureeditor edit button

### ISSUE THREAD

**Issue by rooi** [gwaldron/osgearth#564]
Hi,

When I click on the edit button in the osgearth_featureeditor example, the application crashes in Group::traverse(NodeVisitor& nv).I cannot seem to find the cause of it, although when I remove s_root->addChild( c_editotor.get() ); it does not crash any longer.

Does anyone else experience the same? I'm using osg 3.2.1 and a very recent osgEarth.

Thanks,

Roy

**Comment by gwaldron** [comment]
Thanks; confirmed.

**Comment by gwaldron** [comment]
couple display issues, but the crash is patched for now
