### ISSUE TITLE
Paged features are busted with latest OSG from master

### ISSUE THREAD

**Issue by jasonbeverage** [gwaldron/osgearth#569]
Try boston.earth, the buildings crash.  If you remove the layout block so it's not paged it works fine.

**Comment by remoe** [comment]
Jason, I've tried it with release from yesterday. It doesn't crash on my system:

![image](https://cloud.githubusercontent.com/assets/804941/5682163/4a792e1c-981e-11e4-9b15-18ef10a1efaf.png)

**Comment by jasonbeverage** [comment]
Thanks remo, when did you last update OSG?  Mine is a couple of days old.

**Comment by remoe** [comment]
Jason, sorry I've had removed my post :) I've used 3.14

**Comment by jasonbeverage** [comment]
Ha, I was hoping just doing an update would fix the issue :)

**Comment by gwaldron** [comment]
Closing until OSG 3.4 comes out, at which point we will reevaluate
