### ISSUE TITLE
Annotation sample hangs

### ISSUE THREAD

**Issue by beachwalker** [gwaldron/osgearth#571]
The annotation sample has a bug and stops execution during startup and exits.

![image](https://cloud.githubusercontent.com/assets/2715897/5921496/a6042d2a-a644-11e4-90f6-13146cc7fbb7.png)

...using latest master of osgEarth with osg 3.2.1 (x64, windows)

osgearth_viewer(d) works (x86 and x64).

**Comment by jasonbeverage** [comment]
glenn fixed this in 4b127defe63cc74a13035c309204a81d91a6f9b1.  Extra :wine_glass: for him.

**Comment by gwaldron** [comment]
Like.

**Comment by beachwalker** [comment]
... works with this fix but getting warnings:

![image](https://cloud.githubusercontent.com/assets/2715897/5990325/29b4e0f6-a9ab-11e4-9310-89d6fe31ea91.png)

and no handles are drawn (if I remember right, there should be a handle for dragging):

![image](https://cloud.githubusercontent.com/assets/2715897/5990334/6aa6c7be-a9ab-11e4-9893-9d3fa5086f1e.png)

**Comment by beachwalker** [comment]
Should I report this as a separate bug?

**Comment by beachwalker** [comment]
Decided to write a separate bug instead of asking for a reopen (problem of the bug seems to be different).
