### ISSUE TITLE
Scintillation lighting issues at poles of osgearth models

### ISSUE THREAD

**Issue by KingArthur10** [gwaldron/osgearth#572]
Reproduction case:
1. Start osgearth_viewer using the lod_blending.earth example
2. Navigate to the pole of the earth
3. Alter camera altitude and move toward the earth

result: notice a scintillation pattern at the pole that flashes in and out.  Also, notice that the brightness of the tiles at the poles varies between transitions.

This is especially noticeable when using a lighting model that does not include any atmospheric scatter and no fill lighting.  This is especially bad for Nightshade NG as most non-earth bodies have no atmosphere.  It appears to be something about the normals at the poles.

You can download a video from the following link that shows the pattern:
https://onedrive.live.com/redir?resid=14E05ECE114D24C6!61432&authkey=!AGrlv3mK_b1dhX0&ithint=video%2cmp4

Using osgearth under Ubuntu Linux and an nVidia graphics card.

**Comment by gwaldron** [comment]
I can't reproduce this, and I can't see any ill effects in the video you posted.

**Comment by tlareywi** [comment]
This only reproduces when the normalize_edges terrain option is true, .e.g  <normalize_edges>true</normalize_edges>.

**Comment by gwaldron** [comment]
Thanks for the clarification tlareywi, that is helpful.

**Comment by gwaldron** [comment]
The quickest fix is you turn OFF edge normalization (set to "false" or simply remove from the earth file) and turn ON normal mapping like so:

<map>
   ....
  <extensions>
      <normalmap/>

This uses a different (and faster/better) mechanism to smooth normals across tiles, and will be the default mechanism in the future. The "normalize_edges" option will eventually go away.

Hope this helps.
