### ISSUE TITLE
osgearth_viewer crashed when loading billboard.earth

### ISSUE THREAD

**Issue by beachwalker** [gwaldron/osgearth#574]
The osgearth_viewer applications crashed after trying to load the billboard.earth from the test folder.  (Win 8.1, x64 release, OSG 3.2.1, latest osgEarth master)

![image](https://cloud.githubusercontent.com/assets/2715897/5990378/5844415c-a9ae-11e4-832a-cb3f4ee053a6.png)

(sorry, screenshot from german OS)

**Comment by gwaldron** [comment]
Don't know the problem, but "billboard" is an experimental component and not quite ready for use. More to come.
