### ISSUE TITLE
Release plan out of sync with website link

### ISSUE THREAD

**Issue by beachwalker** [gwaldron/osgearth#575]
It seems the releases documented in Github are not in sync with the website. If you download the current release from the website osgearth.org version 2.6 is linked but on Github 2.5 is documented as the latest release. What is the latest official stable release?

https://github.com/gwaldron/osgearth/releases

![image](https://cloud.githubusercontent.com/assets/2715897/5991734/28794716-aa02-11e4-901f-873a6d2eb4fb.png)

https://github.com/gwaldron/osgearth/milestones

![image](https://cloud.githubusercontent.com/assets/2715897/5991751/5e6bf4f8-aa03-11e4-8fe4-46a9272bb0e0.png)

**Comment by gwaldron** [comment]
2.6 is the latest release. I forgot to mark it as so. Done. Thanks.
