### ISSUE TITLE
Edit handles aren't visualized

### ISSUE THREAD

**Issue by beachwalker** [gwaldron/osgearth#577]
Annotation sample works again (closed issue #571), but still getting warnings and no handles are drawn (there should be some visible drag handles, if I remember right)

![image](https://cloud.githubusercontent.com/assets/2715897/5990353/8c49656a-a9ac-11e4-962d-103102bc82de.png)

![image](https://cloud.githubusercontent.com/assets/2715897/5997786/11017f4a-aac0-11e4-9b58-8f39b0f5feaf.png)

![image](https://cloud.githubusercontent.com/assets/2715897/5990325/29b4e0f6-a9ab-11e4-9310-89d6fe31ea91.png)

**Comment by gwaldron** [comment]
Fixed!
