### ISSUE TITLE
Missing 'ShaderLoader.cpp'

### ISSUE THREAD

**Issue by clmtk4** [gwaldron/osgearth#578]
Missing 'ShaderLoader.cpp'

-------------------------------------------------------------------------------------------
CMake Error at src/osgEarth/CMakeLists.txt:301 (ADD_LIBRARY):
  Cannot find source file:

    ShaderLoader.cpp

  Tried extensions .c .C .c++ .cc .cpp .cxx .m .M .mm .h .hh .h++ .hm .hpp
  .hxx .in .txx
-------------------------------------------------------------------------------------------

**Comment by gwaldron** [comment]
Pushed. Thanks.
