### ISSUE TITLE
Track sample broken when disabling declutter option

### ISSUE THREAD

**Issue by beachwalker** [gwaldron/osgearth#580]
The track sample does not work when disabling declutter.

![image](https://cloud.githubusercontent.com/assets/2715897/6226125/80dae166-b692-11e4-9469-741c5114528a.png)

... but works when running with decluttering enabled

![image](https://cloud.githubusercontent.com/assets/2715897/6226155/b2418df4-b692-11e4-96c6-0dc38992cc44.png)

**Comment by jasonbeverage** [comment]
Thomas does this happen with the master?  Glenn pushed a fix for this recently and it appears to work here.

**Comment by beachwalker** [comment]
Works with latest master... sorry, was some time behind.
