### ISSUE TITLE
Manipulator initialization crashes with specific order of commands

### ISSUE THREAD

**Issue by hwiesmann** [gwaldron/osgearth#583]
The statement sequence crashes because Manipulator::_cached_srs is still invalid within EarthManipulator::collisionDetect() (called from applySettings):

    osgEarth::Util::EarthManipulator* manipulator(new osgEarth::Util::EarthManipulator());
    osgEarth::Util::EarthManipulator::Settings* settings(manipulator->getSettings());

    settings->setMinMaxPitch(-90.0,-90.0);
    manipulator->applySettings(settings);
    manipulator->setNode(this->m_RootNodePtr.get());

Changing the statement sequence to

    osgEarth::Util::EarthManipulator* manipulator(new osgEarth::Util::EarthManipulator());
    osgEarth::Util::EarthManipulator::Settings* settings(manipulator->getSettings());

    manipulator->setNode(this->m_RootNodePtr.get());
    settings->setMinMaxPitch(-90.0,-90.0);
    manipulator->applySettings(settings);

prevents the crash.

Hardy

**Comment by gwaldron** [comment]
Thanks. Patched.

Incidentally, you don't need to call applySettings() unless you have created a branch new Settings instance. When you call manipulator->getSettings() you can getting a pointer to the settings object that's already installed.
