### ISSUE TITLE
MaxDataLevel not respected by TileSource

### ISSUE THREAD

**Issue by hwiesmann** [gwaldron/osgearth#587]
The following code should limit the LOD (maxDataLevel) to 11. But it does not:

	osgEarth::ImageLayerOptions imageLayerOptions;

	osgEarth::Drivers::XYZOptions xyzOptions;
	

	xyzOptions.maxDataLevel() = 11;
	xyzOptions.profile()      = osgEarth::Util::ProfileOptions("spherical-mercator");
	xyzOptions.url()          = "http://otile[1234].mqcdn.com/tiles/1.0.0/sat/{z}/{x}/{y}.jpg";
	imageLayerOptions.maxLevel() = 11;
	imageLayerOptions.driver()   = xyzOptions;
	this->GetMapPtr()->addImageLayer(new osgEarth::ImageLayer(k_MapQuestOAMLayerName,imageLayerOptions));

The reason is a bug in osgEarth::TileSource::hasData(const osgEarth::TileKey&) const. The order of comparisons is:

    //sematics: might have data.

    //If no data extents are provided, just return true
    if (_dataExtents.size() == 0) 
        return true;

    unsigned int lod = key.getLevelOfDetail();

    // Remap the lod to an appropriate lod if it's not in the same SRS        
    if (!key.getProfile()->isHorizEquivalentTo( getProfile() ) )
    {        
        lod = getProfile()->getEquivalentLOD( key.getProfile(), key.getLevelOfDetail() );        
    }

    // Check the explicit max data override:
    if (_options.maxDataLevel().isSet() && lod > _options.maxDataLevel().value())
        return false;

but should be:

    unsigned int lod = key.getLevelOfDetail();

    // Remap the lod to an appropriate lod if it's not in the same SRS
    if (!key.getProfile()->isHorizEquivalentTo( getProfile() ) )
    {        
        lod = getProfile()->getEquivalentLOD( key.getProfile(), key.getLevelOfDetail() );        
    }

    // Check the explicit max data override:
    if (_options.maxDataLevel().isSet() && lod > _options.maxDataLevel().value())
        return false;

    //If no data extents are provided, just return true
    if (_dataExtents.size() == 0) 
        return true;

Otherwise the data is reported to exist regardless of the LOD in case no data extents exist. This seems to be the case (no data extents) when using the xyz-loader.

Regards,
Hartwig

**Comment by gwaldron** [comment]
Thanks Hartwig. Patched and tested.
