### ISSUE TITLE
Is there a need for LIB_POSTFIX?

### ISSUE THREAD

**Issue by parched** [gwaldron/osgearth#590]
Why not just use lib instead of lib64? The Arch Linux package manger (pacman) will not allow installing files to /usr/lib64. I can easily move them to /usr/lib (which it is a symlink to), but I was wondering if this is old unneeded code that can be removed anyway.

**Comment by gwaldron** [comment]
I have no idea. We only develop on Windows here so we'll leave decisions on non-Win CMake config up to others. Much of the CMake setup was copied from old OSG/VPB CMake. Feel free to submit a pull request.

**Comment by parched** [comment]
I did some research, it is still needed for some linux distros, e.g., Fedora.
I can set it to nothing anyway so it is fine as is.

**Comment by gwaldron** [comment]
Thanks for researching this.
