### ISSUE TITLE
GDAL compile error

### ISSUE THREAD

**Issue by DaxDeveloper** [gwaldron/osgearth#606]
Hi,
I have tried to compile OSearth with VS2013 and  I'm get a linker error:

Error	2	error LNK2019: unresolved external symbol GDALGetDriverByName referenced in function "class GDALDataset * __cdecl `anonymous namespace'::createMemDS(int,int,double,double,double,double,class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?createMemDS@?A0x81de9983@@YAPEAVGDALDataset@@HHNNNNAEBV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@Z)	c:\Temp\Osg\gwaldron-osgearth-350f1a0\build\src\osgEarth\GeoData.obj	osgEarth

I have downloded this GDAL package: http://download.osgeo.org/gdal/win32/1.4.1/gdalwin32dev141.zip

Any suggestions?

Thx

**Comment by gwaldron** [comment]
GDAL 1.4.1 is 8 years old. Try a more modern version :) I recommend looking here:
http://www.gisinternals.com/release.php
