### ISSUE TITLE
Clean up CMake by being able loop over directories to add subfolders

### ISSUE THREAD

**Issue by jasonbeverage** [gwaldron/osgearth#608]
New macro:

MACRO(SUBDIRLIST result curdir)
  FILE(GLOB children RELATIVE ${curdir} ${curdir}/*)
  SET(dirlist "")
  FOREACH(child ${children})
    IF(IS_DIRECTORY ${curdir}/${child})
        LIST(APPEND dirlist ${child})
    ENDIF()
  ENDFOREACH()
  SET(${result} ${dirlist})
ENDMACRO()

Then for a directory you can run:
SUBDIRLIST(SUBDIRS ${CMAKE_CURRENT_SOURCE_DIR})
FOREACH(subdir ${SUBDIRS})
    ADD_SUBDIRECTORY(${subdir})
ENDFOREACH()

All the guards like checknig for dependencies would then go inside the CMake for the projects themselves.  For example the leveldb cache's CMakeList.txt would include a guard like:
IF(LEVELDB_FOUND)
...
ENDIF(LEVELDB_FOUND)

**Comment by gwaldron** [comment]
done right?
