### ISSUE TITLE
VPB *.iveTerrain Gaps

### ISSUE THREAD

**Issue by kinsung** [gwaldron/osgearth#609]
How to eliminate these gaps between tiles in VPB *.ive terrain?

![terrain gap](https://cloud.githubusercontent.com/assets/4880761/7695570/0fbf8d22-fe24-11e4-8f26-b842ad64aa9b.jpg)
![terrain gap2](https://cloud.githubusercontent.com/assets/4880761/7695572/1100874a-fe24-11e4-83a4-8f39b5c2c20b.jpg)
![terrain chaos](https://cloud.githubusercontent.com/assets/4880761/7695573/1152787a-fe24-11e4-89c3-ff96405d61b5.jpg)

**Comment by gwaldron** [comment]
This looks like a z-buffering problem rather than gaps. How are you setting up your camera? Are you disabling near/far compute?

**Comment by kinsung** [comment]
Yes, thank you!

**Comment by kinsung** [comment]
Yes, thank you!

**Comment by kinsung** [comment]
Yes, thank you!

**Comment by kinsung** [comment]
Yes, thank you!
