### ISSUE TITLE
UTM/MGRS Graticule doesn't work anymore

### ISSUE THREAD

**Issue by beachwalker** [gwaldron/osgearth#615]
The graticule does not work when selecting MGRS or UTM. (The geodetic grid still works.)
You can reproduce this when starting the example osgearth_graticule.

(Win7 64)

**Comment by ijk123** [comment]
The example osgearth_graticule can work under MGRS or UTM in my computer. Could you provide more descriptions, please? osgEarth version? is it blank?

**Comment by beachwalker** [comment]
It only works with Geodetic for me. The other grids are blank. Do you use the latest trunk? I do.

**Comment by beachwalker** [comment]
Is it planned to reenable this feature? I have seen the latest trunk just switches the formatter for the text output in the top left corner but not the graticule itself. This was different in previous versions. We had a real utm/mgrs graticule.

**Comment by gwaldron** [comment]
Yes, we plan to fix this. IIRC it's a depth or draw order issue.

**Comment by gwaldron** [comment]
fixed - just a render order issue.
