### ISSUE TITLE
PrimitiveIntersector doesn't work correctly on projected Map with geographic SRS

### ISSUE THREAD

**Issue by MCA4213** [gwaldron/osgearth#620]
Hi,
I used to use the Pickers class to select features, but when I set a projected Map with geographic SRS like WGS84 I get a wrong selection; BUT if I work on geocentric Map with geographic SRS or on projected Map with a projected SRS it will work fine.

In the past I used to use the old Pickers class that use the PolytopeIntersector that worked fine, BUT NOW I can't use this class because of the new ObjectIndex system.

Here is a video to demonstrate a comparison between using the Pickers class with the PolytopeIntesector and the new class that use the PrimitiveIntesector (before the version with ObjectIndex system).
https://drive.google.com/file/d/0BwUM6S4j6vlXb2ZVYm8tb0dvRzQ/view?pli=1

I hope that the new RTTPicker with PrimitiveIntesector will be corrected to support the projected Map with geographic SRS.

**Comment by MCA4213** [comment]
Hi, I want to say that now with the latest osgEarth 2.7 the selection on a projected map is working perfectly. 
I don't knew how ( perhaps because osgEarth is using now a equirectangular profile for projected map), but thank you for your amazing works.

So, please ignore my issue.

**Comment by gwaldron** [comment]
Thanks for the follow up :)
