### ISSUE TITLE
osgearth_viewer crashed when starting with multi-screen setup when using OSG 3.4.0 

### ISSUE THREAD

**Issue by beachwalker** [gwaldron/osgearth#643]
If you have a mulit-monitor setup (e.g. 2 Monitors attached) and osgEarth is compiled against latest stable release 3.4.0 of OpenSceneGraph, the application crashed at startup. (Just called osgearth_viewer with earth file parameter)

This doesn't happen if you explicitely call osgearth_viewer --screen 0 to start rendering only at one screen.

I don't know if it is still working with versions prior to 3.4.0 of OSG linked with osgEarth.

**Comment by beachwalker** [comment]
Seems like a bug in OpenSceneGraph 3.4.0 itself. I posted this issue to their mailing list, too.

**Comment by gwaldron** [comment]
OK thanks. Keep us posted.

**Comment by beachwalker** [comment]
Still occurs in 3.4.1, wanna try 3.6 next days. Is osgEarth worth to try with or are there any incompatibility issues known already?

**Comment by emminizer** [comment]
I've been building osgEarth against 3.6 here and no build problems.  Still working through some (comparatively minor) GL Core profile issues, but I do not see any compatibility mode issues.
