### ISSUE TITLE
onMiss method of FeatureQueryTool does not make tool invisible

### ISSUE THREAD

**Issue by bclay1297** [gwaldron/osgearth#649]
in addition to the  problem of onMiss not hiding the tool:
There are time where we might want to call up the tool and leave it visible while querying a number of features on the map.  during these times it seems better to keep the tool up and display a "feature not found" message  instead of hiding the tool

**Comment by gwaldron** [comment]
To be clear, the bug here is that Control::setVisible(false) is not working.

Regarding the behavior of the tool ... that's up to you. The code in the example is just that: an example. :)

**Comment by bclay1297** [comment]
Agree - to both parts

**Comment by beachwalker** [comment]
... so this should be closed?

**Comment by gwaldron** [comment]
works for me.
