### ISSUE TITLE
Draped lines are not occluded by the earth

### ISSUE THREAD

**Issue by anddyhzw** [gwaldron/osgearth#652]
I run osgearth_view.exe with feature_drapped_lines.earth being parameter with OpenSceneGraph 3.2.1. When I look at the front horizontally,It seems drawing wrongly.
![drapingerror](https://cloud.githubusercontent.com/assets/4575686/10036067/530adf6e-61d4-11e5-99cf-fb1868fafb17.png)

And the RTT picture is 
![drapingerror2](https://cloud.githubusercontent.com/assets/4575686/10036122/6d88805c-61d5-11e5-80cc-2eaf1472cfde.png)

**Comment by gwaldron** [comment]
Confirmed, thanks for the report.

**Comment by gwaldron** [comment]
fixed
