### ISSUE TITLE
Typed extensions no longer load from earth file

### ISSUE THREAD

**Issue by gwaldron** [gwaldron/osgearth#655]
If you include a "typed" plugin in the earth file (like "sky driver=simple") it now fails to load.

**Comment by jasonbeverage** [comment]
It actually does load since Sky is loaded by the ExampleResources, it's just complaining that it can't find an extension by the name osgearth_sky.  The sky does load though.  I've quietened down the warning to OE_INFO.

Fixed in  947efda51e6bcb596d34b5f5efabc5ec374f1046
