### ISSUE TITLE
relative url in <NetworkLink><Link><href>rel.kml</href></Link></NetworkLink> broken

### ISSUE THREAD

**Issue by philipdumont** [gwaldron/osgearth#683]
Please consider something like the attached patch.

As is, a relative link is looked for in the process's current working directory. It should be relative to the referrer -- the file containing the `<NetworkLink>` tag.  The patch makes it so.

[osgearth-2.7.0.patch.txt](https://github.com/gwaldron/osgearth/files/81748/osgearth-2.7.0.patch.txt)

**Comment by philipdumont** [comment]
A bit more detail...

As as, a relative link is looked for in the process's current working directory.  It should be relative to the referrer -- the file containing the <NetworkLink> tag.

**Comment by gwaldron** [comment]
Please submit code changes as a Pull Request. Thanks.

**Comment by philipdumont** [comment]
Er, how do I do that?

Note: I'm moderately conversant in mercurial.  My knowledge of git is
limited to the extent to which it resemble mercurial (and what little I
gleaned just now to get as far as I did).

I got as far as:

   - clone repo (git clone https://github.com/gwaldron/osgearth.git)
   - create a branch (cd osgearth; git branch
   pdd_NetworkLink_relative_href_fix)
   - switch to branch (git checkout pdd_NetworkLink_relative_href_fix)
   - make edits
   - commit (git add ...; git commit).

Now what?  I can't push, I can't find anything in "git help" about issuing
a pull request, I can't find anything at github about how to issue a pull
request.  (Somewhere in faq, there's a list of instructions that include
"issue a pull request", but it doesn't say how.)  I see the "Pull Request"
link on the github page, but as it's accessing the github repo, not my
clone, what good is that?

Please advise.

**Comment by philipdumont** [comment]
Pull request instructions found.  Pull request submitted.
