### ISSUE TITLE
ON_DEMAND mode is not working in master

### ISSUE THREAD

**Issue by gwaldron** [gwaldron/osgearth#691]

**Comment by remoe** [comment]
We work only with this mode. Otherwise it could be kill your PC :)

**Comment by gwaldron** [comment]
Remo, can you retest? osgearth_viewer wasn't honoring on-demand mode; now it is. There are some features in OE that disable it, but please give it another try. Thanks

**Comment by remoe** [comment]
Glenn I'm not 100% sure but the CPU is lower then 5%. So I think it works.
