### ISSUE TITLE
How to enable light for osgearth ContourMap? 

### ISSUE THREAD

**Issue by kinsung** [gwaldron/osgearth#698]
How to enable light for osgearth ContourMap? 
Please copy the link below and paste to browser's addreess bar. 
Sample picture: [http://pan.baidu.com/s/1gedWtKR](url)

**Comment by gwaldron** [comment]
osgearth_viewer coutourmap.earth --sky

**Comment by kinsung** [comment]
Thank you. Yes, It takes effect. 
But we need the dark side of earth not very dark,  so I set SkyOptions ambient() to 0.5.   Obviously, the ambient value takes effect, but also make the shadow of terrain not so dark. I want the shadow of terrain looks more darkly. How can I set the individual ambient for shadow of terrain？

**Comment by gwaldron** [comment]
You cannot configure the shadow color from the .earth file, but you can use ShadowCaster::setShadowColor to adjust it in code.

**Comment by kinsung** [comment]
I do not know how to use ShadowCaster. In my usage way,  ShadowCaster::setShadowColor just make some big black grid flickering on terrain.
