### ISSUE TITLE
changelog: 3.0 Porting issue with Annotation

### ISSUE THREAD

**Issue by remoe** [gwaldron/osgearth#701]
It would be great when we have a changelog about serious interface changes.

Annotation::LocalizedNode -> Annotation::GeoPositionNode
Annotation::OrthoNode -> Annotation::GeoPositionNode

removed:
- clearDecoration

getAttachPoint -> getPositionAttitudeTransform
set/getAnnotationData -> node->set/getUserData()

AnnotationData::setPriority -> node->setPriority

**Comment by gwaldron** [comment]
AnnotationData only exists to support KML, so was removed in the refactor and the priority property we put in AnnotationNode itself. As for Decorations most of them were broken anyway, so we are still in the process of refactoring or replacing their functionality with other things. Work in progress
