### ISSUE TITLE
feature_occlusion_culling.earth / text-occlusion-cull doesn't work with current master?

### ISSUE THREAD

**Issue by remoe** [gwaldron/osgearth#715]
It doesn't hide it behind terrain:

![image](https://cloud.githubusercontent.com/assets/804941/14740714/60692f26-0891-11e6-90c3-0f8592ace4d0.png)

**Comment by jasonbeverage** [comment]
Fixed in c329efca531e2a8bc2886efaf9a88d91bc33fa4d

**Comment by remoe** [comment]
Thanks! ;)
