### ISSUE TITLE
cracks in terrain?

### ISSUE THREAD

**Issue by remoe** [gwaldron/osgearth#716]
After updated to current master I see sometimes cracks in the terrain like:

![image](https://cloud.githubusercontent.com/assets/804941/14741033/abd6cf20-0893-11e6-94c8-8e0c0ecb66f6.png)

after zoom in it close:

![image](https://cloud.githubusercontent.com/assets/804941/14741038/ca684ff4-0893-11e6-8620-c96ff9ec8445.png)

![image](https://cloud.githubusercontent.com/assets/804941/14741348/dfb42d54-0895-11e6-887c-afeb9ffc57c9.png)

We haven't see such issues in the past.

**Comment by jasonbeverage** [comment]
Remo what elevation driver are you using?

**Comment by remoe** [comment]
TMS

**Comment by jasonbeverage** [comment]
Remo can you send me your earth file offline and I'll see if I see anything?

**Comment by remoe** [comment]
Jason, sorry the data is very large. We use this settings:

```
	terrain: {
		normalize_edges: true,
		lighting: false,
		sample_ratio: 0.125,
		min_lod: 18
	},
	elevation_tile_size: 63,
```

and

```
<map  type="geocentric" version="2">
	<elevation name = "name" driver = "gdal">
		<url>x.tif</url>
		<tile_size>256</tile_size>
    </elevation>
</map>```

Is there any deprecated?

**Comment by jasonbeverage** [comment]
So it's coming from the gdal driver, not tms.  I can't think of anything
that would be broken but I can take a look.

**Comment by remoe** [comment]
Jason, do you prefer a specific GDAL version? I use 1.10.1 .

**Comment by jasonbeverage** [comment]
I also use 1.10.  Do you have any idea when this issue crept in?  What
version were you using previously where there were no cracks?

**Comment by remoe** [comment]
Jason, yes, this:

https://github.com/gwaldron/osgearth/commit/133b7dede73bf00d31e3ffab4fd41d94db1ebf59

**Comment by remoe** [comment]
Someone with a different config with older version of osgEarth has also this issue. So I close it for now.

**Comment by remoe** [comment]
It is a GDAL_DATA issue. Some files are missed. But why this are needed for WGS84 ? :/

**Comment by jasonbeverage** [comment]
So if you set the GDAL_DATA path correctly then the problem goes away?

**Comment by remoe** [comment]
I'm not sure. I didn't understand the behavior. I've inserted the gdal files with the correct path. Then the terrain was rendered correctly. But when I remove the whole gdal directory and run it again, then the terrain is also correct. And on the release mode nothing works. I'm confused.
