### ISSUE TITLE
How to create overlayer in map

### ISSUE THREAD

**Issue by hongsonitptit** [gwaldron/osgearth#717]
Hi,
I want to create a over layout in map that can be draw on it by canvas like bellow picture.
How can I do that???
![untitled](https://cloud.githubusercontent.com/assets/5134089/14810368/d051056a-0bbc-11e6-8352-c5e781bee605.png)

**Comment by beachwalker** [comment]
What technology for map Qtquick, Qtwidgets, Wpf, pure OpenGL? This is not a issue. It is something for the forum.

**Comment by gwaldron** [comment]
That kind of overlay is commonly called a "HUD" (Heads-Up Display) and there is an [OSG example showing how to create one here](https://github.com/openscenegraph/OpenSceneGraph/blob/master/examples/osghud/osghud.cpp).

If you just need some simple text or controls, you can try the osgEarth::Util::Controls library. It's designed mainly to support the examples, but might suit your needs.
