### ISSUE TITLE
Missing example feature_stencil_line_draping.earth

### ISSUE THREAD

**Issue by rhabacker** [gwaldron/osgearth#729]
At http://docs.osgearth.org/en/latest/references/drivers/model/feature_stencil.html there is written: 

Also see:
   feature_stencil_line_draping.earth sample in the repo

This file is missing in the git repo.

**Comment by gwaldron** [comment]
rhabacker, that demo was removed, so feel free to remove it from the docs. Thanks.

**Comment by rhabacker** [comment]
Does it mean that 
1. the 'feature_stencil' driver has been removed or 
2. only the example file ?

**Comment by gwaldron** [comment]
The driver is still in the repo, but it's no longer supported. It probably doesn't even work anymore. I will mark it as deprecated.

**Comment by jasonbeverage** [comment]
Removed the docs and moved the model_feature_stencil driver to the osgEarthDriversDisabled section in dc66432ade060d5afb9243bd76a83a64081513a6.
