### ISSUE TITLE
Undocumentated attributes in earth file layout tag 

### ISSUE THREAD

**Issue by rhabacker** [gwaldron/osgearth#730]
In the boston.earth examples there is an attribute tile_size_factor used, which is not documentated in the online documentation. After looking into recent sources it turns out that additional attributes of the layout tag are not documented.

attribute/related commit
tile_size_factor
 https://github.com/gwaldron/osgearth/commit/175a8d5d9a94f4a670fa881018439406444fddf4

priority_scale 
https://github.com/gwaldron/osgearth/commit/10f4b8ff3d61c96d426c0c7bd98ee22a228e1713

crop_features
https://github.com/gwaldron/osgearth/commit/10c8a926fbbb53d9f5544a48ad7584fa1377b7f3

priority_offset
https://github.com/gwaldron/osgearth/commit/10f4b8ff3d61c96d426c0c7bd98ee22a228e1713

**Comment by hemangini1** [comment]
Hello Sir. I am new to open source contribution. Can you please tell what the issue is asking to contribute, ie, in what manner?

**Comment by jasonbeverage** [comment]
Documented in b45cb38
