### ISSUE TITLE
Requesting unneeded shader files ?

### ISSUE THREAD

**Issue by remoe** [gwaldron/osgearth#736]
osgEarth try to open this files while loading:

```
MPEngine.vert.model.glsl 
MPEngine.vert.view.glsl
MPEngine.frag.glsl 
SimpleSky.Ground.ONeil.vert.glsl 
SimpleSky.Ground.ONeil.frag.glsl 
SimpleSky.Atmosphere.vert.glsl 
SimpleSky.Atmosphere.frag.glsl 
SimpleSky.Sun.vert.glsl
SimpleSky.Sun.frag.glsl
```

From: ShaderLoader::load / findDataFile

**Comment by gwaldron** [comment]
osgEarth tries to load shader files from the OSG_FILE_PATH first, and if it doesn't find them it falls back on using the inlined internal versions. So this is expected behavior

**Comment by remoe** [comment]
But this calls are not just one. It is called many times. And File-IO could slow down a lot of things.
