### ISSUE TITLE
osgEarth/OSG search the module osgdb_osgearth_engine_mp_tiled.dll through the PATH environment variable

### ISSUE THREAD

**Issue by remoe** [gwaldron/osgearth#737]
I've traced an osgEarth application with a process monitor and I found that osg/osgEarth search the file "osgdb_osgearth_engine_mp_tiled.dll" in the whole PATH environment-variable paths!

Does anyone know how one can avoid this? I don't see this with other dll's.

**Comment by jasonbeverage** [comment]
Remo, if you put the dll in your osgPlugins-3.4.0 (or whatever version you're using) then it shouldn't do this.  Also, it should only search for the dll once anyway and never again, so this shouldn't be a performance issues.
