### ISSUE TITLE
Tesselator: does not tile properly near the poles

### ISSUE THREAD

**Issue by gwaldron** [gwaldron/osgearth#746]
Polar tesselation fails b/c the tiling doesn't work properly at that latitude. (BGF:812)
Geometry:
MULTIPOLYGON(((191.026667 87.63333,114.75 78,89.5 77.333336,81.833336 75.333336,70.683334 74.5,70.916664 73.666664,68.666664 73.666664,66.291664 71.505,57.65 71.166664,58 73.9,48.616665 73,49.198334 71.43,49.5 70.5,43.266666 68.666664,32.083332 71.5,32.083332 74,35 74,35 81,32 81,32 90,191.026667 87.63333))) 

Tiling on:
![2016-06-30_133107](https://cloud.githubusercontent.com/assets/326618/16497849/fe6a3bf0-3ec6-11e6-9961-3d4f79ff9abe.jpg)

Tiling off:
![2016-06-30_133009](https://cloud.githubusercontent.com/assets/326618/16497855/04095b86-3ec7-11e6-9155-fee3e8e3c49c.jpg)

**Comment by jasonbeverage** [comment]
Can we use this as a base?  https://github.com/virtualglobebook/OpenGlobe/blob/master/Source/Core/Polygons/EarClippingOnEllipsoid.cs

**Comment by gwaldron** [comment]
Workaround: patched the tessellator in BGF so it won't tile unless maxPolygonTilingAngle is expressly set.
