### ISSUE TITLE
 OsgEarth 2.7 and osg3.4 compile environment 

### ISSUE THREAD

**Issue by sczhaoyu** [gwaldron/osgearth#747]
My developing tool is VS2015，I want OSG3.4 win764 compile environment.
What is the third-party stable version in the 2.7 version?

**Comment by jasonbeverage** [comment]
We haven't done anything with VS 2015 yet and I'm not sure if there are prebuilt dependencies available or not.  The osg mailing list has mentions of this project https://github.com/bjornblissing/osg-3rdparty-cmake when talking about 2015 dependencies though that might be helpful
