### ISSUE TITLE
osgEarth does not display model when +a and +b are used in profile

### ISSUE THREAD

**Issue by KingArthur10** [gwaldron/osgearth#749]
Repro:

Create a .earth file where you override the options profile using both +a and +b (eg +proj=latlong +a=6378140 +b=6378140)
Open the file in osgearth_viewer
result: a blank background is displayed

open the file in osgviewer
result: triangle intersect errors spew out on the command line, but the model appears to load.

Note: replacing +b with a large +rf value seems to work.

reference discussion: http://forum.osgearth.org/Performance-issues-when-using-gdal-and-topography-using-overviews-td7589445.html#a7589455

**Comment by gwaldron** [comment]
reduced to nuisance since there is a workaround
