### ISSUE TITLE
Build failing when OSG_USE_UTF8_FILENAME is set.

### ISSUE THREAD

**Issue by SrinivasPrabhu794** [gwaldron/osgearth#752]
I have built osg with the **OSG_USE_UTF8_FILENAME**  to support utf-8 based filenames(for internationalization). But when I  try to build osgearth, the file "`FileUtils.cpp`" fails to compile.

This bug is in all versions. Please fix this issue.
To Reproduce:
Build `osg`with **OSG_USE_UTF8_FILENAME** set
Build `osgearth`pointing to this recently built osg and the build will fail

**Comment by gwaldron** [comment]
If/when you have a fix, please submit via a pull request - thank you.

**Comment by jasonbeverage** [comment]
This should be fixed in the master.
