### ISSUE TITLE
Dirty() ineffective when ModelSource is empty on first Load

### ISSUE THREAD

**Issue by JD31** [gwaldron/osgearth#759]
If a ModelLayer is empty on the first load then the call to ModelSource::Dirty() does nothing. The layer still empty.

**Comment by JD31** [comment]
Hello. Can we hope a correction for 2.8? This should be usefull to everyone who needs to fill the data source during runtime (after an empty initialisation). For the moment the work around has been to remove the layer from the map and build it again and then attach it again to the map.

**Comment by gwaldron** [comment]
Jerome what is your use case for this? I was actually considering removing the Revisioned base class altogether for ModelSource since it is unused. Do you have a custom ModelSource?

**Comment by JD31** [comment]
I don't have a custom modelsource.
My use case is:
The user lauches the application with an empty database (postgis).
The user requests the data he wants to display via the hmi then the postgis
layer is filled.
The osgearth layer is then refreshed to display the just downloaded data
(dirty method is called).
- > the map is still empty (postgis is not)

Tests have shows that if we start with a non empty table, the dirty works.
Note: all layers are loaded at application starting within an earth file.
The idea is just to call dirty when the source has been updated.

**Comment by gwaldron** [comment]
Are you saying that if you start with a non-empty table, if shows the data from that table, and then you update the table and call dirty(), and it updates the layer? Because I am looking through the code, and it seems like that would not work at all -- nothing ever checks the ModelSource dirty state.
