### ISSUE TITLE
osgearth2.5 List iterator not dereferencable!

### ISSUE THREAD

**Issue by zcwbnu** [gwaldron/osgearth#762]
hello!  I use featurenode draw a clamping line,but when zoom out ,sometimes appear bug "List iterator not dereferencable!" but I never use list,here is my code.Can you help me? 

```
LineString* line = new LineString();   
m_TrackNode =  new FeatureNode(m_mapNode, new osgEarth::Features::Feature(line, m_mapNode->getMapSRS()));
m_TrackNode->getOrCreateStateSet()->setMode(GL_LIGHTING, osg::StateAttribute::OFF);
m_TrackNode->getOrCreateStateSet()->setMode(GL_RESCALE_NORMAL,osg::StateAttribute::ON);
m_TrackNode->setDataVariance( osg::Group::DYNAMIC );
m_TrackNode->getFeature()->geoInterp() = GEOINTERP_GREAT_CIRCLE;
m_TrackNode->getFeature()->setDataVariance(osg::Object::DYNAMIC);   
m_TrackNode->getOrCreateStateSet()->setRenderBinDetails(6,"renderbin");
osgEarth::Symbology::LineSymbol* ls = m_TrackNode->getFeature()->style()->getOrCreate< osgEarth::Symbology::LineSymbol>();
ls->stroke()->color() = Color::Yellow;
ls->stroke()->width() = 5.0f;
ls->stroke()->stipple() = 255;
ls->stroke()->widthUnits() = Units::PIXELS;
ls->tessellation() = 1; 
osgEarth::Symbology::AltitudeSymbol* as = m_TrackNode->getFeature()->style()->getOrCreate<osgEarth::Symbology::AltitudeSymbol>();
as->clamping() = AltitudeSymbol::CLAMP_TO_TERRAIN;
as->technique() = AltitudeSymbol::TECHNIQUE_DRAPE;
```

![355084686470248895](https://cloud.githubusercontent.com/assets/18117662/17483806/1c041732-5dba-11e6-80b7-6b6b4692933a.jpg)

**Comment by jasonbeverage** [comment]
Where do you actually add points to your line?  Do you have a better stack
trace?

**Comment by zcwbnu** [comment]
thanks for your replay! I add points in m_TrackNode's updatecallback function,  I get point data from another thread，this is the code:

m_TrackNode->addUpdateCallback(new DynamicTrackCallback());
........
void DynamicTrackCallback::operator()(osg::Node* node,osg::NodeVisitor* nv)
{
    if(_flag == true)//if data is ready, add point
    {
         _featureNode = dynamic_cast<osgEarth::Annotation::FeatureNode*>(node);
	 if(_featureNode.get())
	 {
              _featureNode->getFeature()->getGeometry()->push_back(_lon,_lat,_alt);
	      _featureNode->init();
          }
     }
    _flag = false;
    //traverse(node,nv);
}

void DynamicTrack::addVertex(double lon,double lat,double alt)
{
      if(_flag == false)
      {
           _lon = lon;
	   _lat = lat;
           _alt = alt;
           _flag = true;
       }
}

**Comment by gwaldron** [comment]
Obselete
