### ISSUE TITLE
Deadlock in FeatureModelGraph

### ISSUE THREAD

**Issue by jasonbeverage** [gwaldron/osgearth#781]
was waiting to report this until I could try to make a simple repro case, but since the new release is coming soon...

I experienced a deadlock on the recently added _clampableMutex in FeatureModelGraph.  This occurred when adding a model layer to the map (using the C++ API, not an earth file):  the mutex is acquired in FeatureModelGraph::redraw() (called from the ctor), and from redraw, checkForGlobalStyles() is called and tries to recursively lock the mutex, but this creates a deadlock since the mutex is not re-entrant.

I was able to work around the problem by changing _clampableMutex to an OpenThreads::ReentrantMutex, but there could be a better way to distribute the locks to fix the issue since checkForGlobalStyles is a private method.

This happened with a recent build.  Not the very latest trunk, but it doesn't look like much has changed in this class.  Here's a portion of the stack trace:
#0  __lll_lock_wait ()

```
at ../nptl/sysdeps/unix/sysv/linux/x86_64/lowlevellock.S:135
```
#1  0x00007fea3aa27649 in _L_lock_909 ()

   from /lib/x86_64-linux-gnu/libpthread.so.0
#2  0x00007fea3aa27470 in __GI___pthread_mutex_lock (mutex=0x3072f78)

```
at ../nptl/pthread_mutex_lock.c:79
```
#3  0x00007fea3d0c3a9b in ScopedLock (m=..., this=<synthetic pointer>)

```
at /opt/render/render-trunk/include/OpenThreads/ScopedLock:31
```
#4  osgEarth::Features::FeatureModelGraph::checkForGlobalStyles (

```
this=this@entry=0x3070df0, style=...)
at /tmp/osgearth-trunk/src/osgEarthFeatures/FeatureModelGraph.cpp:1485
```
#5  0x00007fea3d0c3f5c in osgEarth::Features::FeatureModelGraph::getOrCreateStyleGroupFromFactory (this=this@entry=0x3070df0, style=...)

```
at /tmp/osgearth-trunk/src/osgEarthFeatures/FeatureModelGraph.cpp:1601
```

Python Exception <class 'IndexError'> list index out of range:
#6  0x00007fea3d0c43ed in osgEarth::Features::FeatureModelGraph::createStyleGroup (this=this@entry=0x3070df0, style=..., workingSet=std::list,

```
contextPrototype=..., readOptions=readOptions@entry=0x31a78f0)
at /tmp/osgearth-trunk/src/osgEarthFeatures/FeatureModelGraph.cpp:1432
```
#7  0x00007fea3d0c4632 in osgEarth::Features::FeatureModelGraph::createStyleGroup (this=this@entry=0x3070df0, style=..., query=..., index=index@entry=

```
0x3076f20, readOptions=readOptions@entry=0x31a78f0)
at /tmp/osgearth-trunk/src/osgEarthFeatures/FeatureModelGraph.cpp:1474
```
#8  0x00007fea3d0c5793 in osgEarth::Features::FeatureModelGraph::build (

```
this=this@entry=0x3070df0, defaultStyle=..., baseQuery=...,
workingExtent=..., index=index@entry=0x3076f20,
readOptions=readOptions@entry=0x31a78f0)
at /tmp/osgearth-trunk/src/osgEarthFeatures/FeatureModelGraph.cpp:1231
```
#9  0x00007fea3d0c6424 in osgEarth::Features::FeatureModelGraph::buildTile (

```
this=this@entry=0x3070df0, level=..., extent=..., key=key@entry=0x0,
readOptions=0x31a78f0)
at /tmp/osgearth-trunk/src/osgEarthFeatures/FeatureModelGraph.cpp:1051
```
#10 0x00007fea3d0c745b in osgEarth::Features::FeatureModelGraph::redraw (

```
this=this@entry=0x3070df0)
at /tmp/osgearth-trunk/src/osgEarthFeatures/FeatureModelGraph.cpp:1758
```
#11 0x00007fea3d0c871a in osgEarth::Features::FeatureModelGraph::ctor (

```
this=this@entry=0x3070df0)
at /tmp/osgearth-trunk/src/osgEarthFeatures/FeatureModelGraph.cpp:481
```

**Comment by gwaldron** [comment]
Note: clampable should really not be a global style, but we should look at refactoring it in the same manner as Drapeable

**Comment by gwaldron** [comment]
OBE.

**Comment by hpuhr** [comment]
Will there be a patch for this issue? It still persists in the downloadable version.

**Comment by gwaldron** [comment]
What downloadable version?

**Comment by hpuhr** [comment]
The one on the homepage? https://github.com/gwaldron/osgearth/zipball/osgearth-2.8
Or has this changed recently (since yesterday)? Then this would be my mistake.

**Comment by gwaldron** [comment]
That is the 2.8 download. This commit is in the master branch from 5 days ago.

**Comment by hpuhr** [comment]
Thats what I thought. So my (improved) question would be: Will this fix also be published as a patch/update for version 2.8?

**Comment by gwaldron** [comment]
Unlikely. But we are planning to create a 2.9 release by the end of 2017.

**Comment by hpuhr** [comment]
Ok, thank you so much for your (incredibly fast) support and the good work.
