### ISSUE TITLE
Tesselation failed for a given a shape file

### ISSUE THREAD

**Issue by JD31** [gwaldron/osgearth#786]
With the given shape file the tesselation fails (was OK some weeks - maybe  months - ago).
Trace is:

[osgEarth]  [FeatureCursorOGR] SQL: SELECT * FROM france_lacs_rivieres
[osgEarth]  [FeatureModelGraph] : Created style group "default"
[osgEarth]  [FeatureModelGraph] : Cropped out 0 features
[osgEarth]  [Tessellator] Tessellation failed!
[osgEarth]  [ObjectIndex] Insert 11; size = 1

[hydro.zip](https://github.com/gwaldron/osgearth/files/444707/hydro.zip)

[Ground_dbSelected-Copie.zip](https://github.com/gwaldron/osgearth/files/444710/Ground_dbSelected-Copie.zip)

**Comment by JD31** [comment]
If waiting very long time, it finally ends and display is OK.
But loading time has been dramatically increased comparing to previous weeks.

**Comment by jasonbeverage** [comment]
I think you're getting bit by the fact that we had to disable the tiling path in the BuildGeometryFilter by default.  The issue is describe in #746.  

You can get the old behavior back on your complicated polygon by explicitly setting a max_polygon_tiling_angle to your model element like this:

```
<model>
    <max_polygon_tiling_angle>5.0</max_polygon_tiling_angle>
</model>
```

**Comment by JD31** [comment]
Really not enough...
The loading time has been decreased with that patch but it takes 2min30s versus approximatively 30s before.

**Comment by gwaldron** [comment]
Jermone, try 45 instead of 5. Loads for me in 10 seconds

**Comment by jasonbeverage** [comment]
I got my defaults mixed up :)

**Comment by JD31** [comment]
It is OK with 45...
...but i wonder:
I am concern with issue 746? So, if i understand, if i set 45 the drawing near the pole will be wrong. If i let default value, it will be OK but with a very longer loading time. That's it?

**Comment by jasonbeverage** [comment]
That's correct.   In some cases polygons near the poles don't work
correctly with the cropping code.
