### ISSUE TITLE
osgEarthQt no longer built for 2.8rc1

### ISSUE THREAD

**Issue by sebastic** [gwaldron/osgearth#791]
It seems osgEarthQt was disabled for 2.8rc1. libosgEarthQt is required for the QGIS Globe plugin, see:

https://github.com/qgis/QGIS/blob/master/cmake/FindOSGEARTH.cmake#L82

Why was this disabled, and will it be re-enabled for the 2.8 final release?

**Comment by gwaldron** [comment]
You need to set the CMAKE flag

OSGEARTH_USE_QT

If you want to old legacy Qt widgets (which are deprecated), you can also enable

OSGEARTH_QT_BUILD_LEGACY_WIDGETS

Note that we might remove the Qt stuff entirely in a future version. It's not specific to osgEarth, and is just in there as a convenience.

**Comment by sebastic** [comment]
Thanks for the hint, I overlooked to for loop in which the osgEarthQt directory is included.

QGIS only uses the ViewerWidget from osgEarthQt, so the legacy widgets shouldn't be required.
