### ISSUE TITLE
Including files with xml tag <xi:include> only includes the first tag

### ISSUE THREAD

**Issue by rhabacker** [gwaldron/osgearth#800]
Loading an earth file including other files having multiple top level tags like <image> or <model> only displays the first tag. See the example:

test.earth
-------------------------------------------------------------------
```
<map name="test" type="projected" version="2">
      <xi:include href="part.xml"/>
</map>
```

-------------------------------------------------------------------
part.xml
-------------------------------------------------------------------
```
<image name="readymap_imagery" driver="tms">
      <url>http://readymap.org/readymap/tiles/1.0.0/7/</url>
</image>
<elevation name="readymap_elevation" driver="tms">
       <url>http://readymap.org/readymap/tiles/1.0.0/116/</url>
</elevation>
```
-------------------------------------------------------------------

Running 

OSGEARTH_NOTIFY_LEVEL=DEBUG osgearth_viewer test.earth 

shows that only the entry named "readymap_imagery" is included.

**Comment by jasonbeverage** [comment]
That's a known limitation of the xml include spec, and the reason we wrote the [template driver](https://github.com/gwaldron/osgearth/tree/master/src/osgEarthDrivers/template)

Check out the [readymap_template.earth](https://github.com/gwaldron/osgearth/blob/master/tests/readymap_template.earth) example instead.  

You have to append .template to the earth file when you load it to invoke the psuedoloader like this:

osgearth_viewer readymap_template.earth.template

**Comment by rhabacker** [comment]
Thanks for this hint. The irritating thing is that it works for viewpoints https://github.com/gwaldron/osgearth/blob/master/tests/viewpoints.xml, but not for other. If not available I suggest to add a <group> tag or similar to be able to group several tags together, which could then be placed into a seperate xml file. 
The additional benefit is, that this tag could have an "enabled" attribute to switch on/off the whole group similar to the "enabled" attribute of the <image> or <model> tag.

**Comment by jasonbeverage** [comment]
It works for viewpoints b/c that file is wrapped in a higher level
<viewpoints> block, it's not just a list of <viewpoint> elements.

**Comment by rhabacker** [comment]
Yes and therefore I suggested the addition of a common block like `<group>` for example 

```
<group>
  <image>
  </image>
</group>
```
or 
```
<group>
  <model>
  </model>
</group>
```

where `<group>` is optional in the main file and mandatory in the sub xml file.

**Comment by gwaldron** [comment]
I commented on this in the PR, but I will repeat here for convenience.

Semantically, a "group" implies that the contents are grouped together for any map-based operation, not just loading from XML. This is common in GIS tools. So to introduce something like this it would need to be a complete implementation of the group concept in the Map model, not just an earth file loading trick.
