### ISSUE TITLE
Invalid reserialization of xml tag <extension>

### ISSUE THREAD

**Issue by rhabacker** [gwaldron/osgearth#802]
Reserialization of test earth file readymap-bing.earth with osgearth from master branch and running 

`osgconv readymap-bing.earth test.earth`

 creates a partially different output file. The bug is that the following fragment 

```
   <extensions>
        <xi:include href="viewpoints.xml"/>
    </extensions>
```

is reserializated to 

```
  <xi:include href="viewpoints.xml" />
  <external>
    <xi:include href="viewpoints.xml" />
  </external>
```

which 
1. includes the viewpoints.xml below `<external>` while it was below `<extensions>`
2. viewpoints.xml is included second time below `<map>` resulting in having duplicated view points.

**Comment by gwaldron** [comment]
This is a bug in the backwards-compatibility code. You no longer need to put your extensions (like the viewpoints) under an "extensions" block - just put them directly under the "map" tag along with the map layers.

**Comment by rhabacker** [comment]
Thanks for this hint. About 25% of the examples from the tests subdir still uses this tag and are misleading users to use this. Is this somewhere documentated in the reference doc ?

**Comment by gwaldron** [comment]
Right; we still need to work on cleaning those up. No docs on the topic

**Comment by gwaldron** [comment]
Removed old "extensions" tags from all sample files.
