### ISSUE TITLE
Missing documentation of earth file tag <libraries>

### ISSUE THREAD

**Issue by rhabacker** [gwaldron/osgearth#804]
The earth file reference manual located at http://docs.osgearth.org/en/latest/references/earthfile.html does not include a documentation of the xml tag `<libraries>`. osgearth git master branch also does not include a related documentation.

**Comment by vschmidt94** [comment]
https://github.com/gwaldron/osgearth/commit/4f89ae5edf3dc4e712ab7c55e0155f3c62ff1d17#diff-d459efe09c0f67bd807e668a74acea6e appears to resolve this issue.
