### ISSUE TITLE
Crash at poles

### ISSUE THREAD

**Issue by jasonbeverage** [gwaldron/osgearth#809]
osgearth will continuously subdivide and crash if you use rex (or mp with a high min_lod set) and zoom into the poles.  It will continue to subdivide and eventually run out of memory.

Run osgearth_viewer readymap-rex and go zoom into the north pole to reproduce.

**Comment by jasonbeverage** [comment]
Maybe we limit how far down osgearth can subdivide based on latitude.

**Comment by gwaldron** [comment]
Fixed by changing the adaptive polar algorithm to adjust the perceived tile radius based on latitude
