### ISSUE TITLE
Docs missing for osgEarth 2.7 and 2.8 (latest)

### ISSUE THREAD

**Issue by beachwalker** [gwaldron/osgearth#817]
http://docs.osgearth.org/ points to the latest (2.8) release.

When you go down in the website to select the documentation for a specific release then osgearth-2.7 and osgearth-2.8 (which is indeed the same as latest but should be stated explicitly) are both missing. Only 2.6 and 2.5 can be selected. But there should be a difference (e.g. rex driver etc.)

![image](https://cloud.githubusercontent.com/assets/2715897/19765037/8e0bccc4-9c46-11e6-872d-717690cbb2fa.png)

**Comment by jasonbeverage** [comment]
I've added docs for 2.7 and 2.8, I had to do it manually in the ReadTheDocs settings.  I think the issue is that we aren't using semantic versioning for our tags.  We have tags like osgearth-2.8 instead of 2.8.0.  We should consider changing that in the future so things automatically get picked up.

**Comment by beachwalker** [comment]
This page for docs does not exist: [osgearth 2.8](http://docs.osgearth.org/en/osgearth-2.8/)

2.7 and below works fine.

**Comment by jasonbeverage** [comment]
The build failed for some reason the first time, it is working now.
