### ISSUE TITLE
Duplicate feature_mapnikvectortiles driver

### ISSUE THREAD

**Issue by beachwalker** [gwaldron/osgearth#820]
There is a **feature_mapnikvectortiles** in **osgEarthDriversDisabled** as well as in **osgEarthDrivers**. Seems there is something wrong... should be in only one folder. Or is there any reason I don't see?

https://github.com/gwaldron/osgearth/tree/master/src/osgEarthDriversDisabled/feature_mapnikvectortiles
https://github.com/gwaldron/osgearth/tree/master/src/osgEarthDrivers/feature_mapnikvectortiles

**Comment by jasonbeverage** [comment]
Good find, that was from when I was hacking on that driver originally and it can be removed.  It's removed in d81dd9758cabda22dc5f80e3129cc8b3124d40c8
