### ISSUE TITLE
ArrayDispatchers no longers exists in OSG

### ISSUE THREAD

**Issue by henrymohn** [gwaldron/osgearth#822]
OSG has renamed ArrayDispatchers to AttributeDispatchers.  This causes MPGeometry.cpp and TileDrawable.cpp to fail to compile when using the latest OSG.

**Comment by remoe** [comment]
This should work now:

https://github.com/gwaldron/osgearth/compare/51896d2dd2...81e3eec849

**Comment by gwaldron** [comment]
I attempted to fix this, but don't have an OSG master build handy at the moment -- please test and report back. Thanks

**Comment by remoe** [comment]
I've tested it on MacOSX with OSG 3.5.6.

**Comment by gwaldron** [comment]
thanks Remo!

**Comment by remoe** [comment]
Glenn, sorry It seems i've only tested a part of it:
http://forum.osgearth.org/Error-building-master-on-Linux-td7590027.html
