### ISSUE TITLE
render-order doesn't work with icon/text annotations

### ISSUE THREAD

**Issue by remoe** [gwaldron/osgearth#827]
Run osgearth_viewer with tests/feature_labels.earth:

![image](https://cloud.githubusercontent.com/assets/804941/20298298/642cdf6e-ab15-11e6-8f67-0e3b2a712eab.png)

after adding "render-order: 11;"

```xml
            <style type="text/css">              
                cities {
                    icon:           "../data/downarrow.png";
                    icon-placement: centroid;
                    icon-declutter: true;
                    icon-align:     center-bottom;
                    text-content:   [name];
                    text-priority:  [rank_max];
                    text-align:     center-bottom;
                    text-halo:      #3f3f3f;
                    text-size:      12+3*([rank_max]-9);
		    render-order:      11;
                }     
            </style> 
```

![image](https://cloud.githubusercontent.com/assets/804941/20298336/a0a6399a-ab15-11e6-88c8-1ad4fe1a6cf3.png)

the annotations are disappeared.

**Comment by gwaldron** [comment]
Yes, this is a conflict between the layer setting a render-order and the individual annotations activating the screen space layout. There is no easy fix. One possibility is to add a screen space layout option that sets the render bin number for all PlaceNode/LabelNodes.

**Comment by remoe** [comment]
But it also doesn't work when I set:

```
 icon-declutter: false
```

**Comment by remoe** [comment]
Fixed by: https://github.com/gwaldron/osgearth/commit/fd384fdb068b92387392fdfebe6a485744da8d6f
