### ISSUE TITLE
Replace build_vrt path in GDAL driver with "libified" version in GDAL 2.1

### ISSUE THREAD

**Issue by jasonbeverage** [gwaldron/osgearth#828]
The build_vrt code path in the GDAL driver is very fragile b/c it's basically copy and pasted from GDAL and tied to a specific version of GDAL.  Starting with GDAL 2.1 this functionality is "libified" and can be called like this:  https://github.com/OSGeo/gdal/blob/trunk/gdal/apps/gdalbuildvrt_bin.cpp#L186-L190
This is much nicer since it's actually part of GDAL.

**Comment by gwaldron** [comment]
OBE
