### ISSUE TITLE
Have option to allow interpolation of imagery when using GDAL driver after last overview has been exhausted

### ISSUE THREAD

**Issue by KingArthur10** [gwaldron/osgearth#830]
Currently, you can interpolate imagery using bilinear or average, but only if you eschew the performance enhancements of overviews.  Basically, you're stuck with two options:

Live with blocky squares when you exhaust data
or
have a separate layer that comes on at the last LOD level and uses interp_imagery and interpolation to have a smooth looking texture.

It'd be awesome if we could somehow allow the same layer to utilize the imagery in overviews and then begin performing interpolation once all native data pixels have been rendered.  Especially nice for clouds or other nebulous looking structures (eg the Milkyway in NightshadeNG).

**Comment by gwaldron** [comment]
The "rex" terrain engine will use the last available texture and just filter it on the GPU (instead of upsampling/interpolating imagery on the CPU) so you might want to try that instead.

**Comment by gwaldron** [comment]
OBE, archiving
