### ISSUE TITLE
Filters does not work with WFS

### ISSUE THREAD

**Issue by beachwalker** [gwaldron/osgearth#833]
It seems the filter function is not used for wfs driver:

      <features name="buildings" driver="wfs">
            <url>http://localhost:8080/geoserver/wfs</url>           
            <typename>rde:planet_osm_polygon</typename>
            <outputformat>json</outputformat>
            <filters>
                <script>
                 <![CDATA[
                      function filter() {
                          if ("building" in feature.properties)
						  {
                              return true;
                          }
                          return false;
                      }
                      filter();
                 ]]>
                </script>
            </filters>	
        </features>

**Comment by gwaldron** [comment]
I believe this was added a couple years ago -- need to verify against WFS server

**Comment by jasonbeverage** [comment]
Just tried it, it works fine.
