### ISSUE TITLE
osgearth_qt_simple + REX = black screen

### ISSUE THREAD

**Issue by gwaldron** [gwaldron/osgearth#853]
Repro
set OSGEARTH_TERRAIN_ENGINE=rex
osgearth_qt_simple readymap.earth

Black screen. Works under MP. Works in SIMSDK.

**Comment by filnet** [comment]
With osgearth_qt5_simple:
```
$ osgearth_qt5_simple /C/M/mingw-w64-osgearth-git/src/osgearth/tests/readymap-rex.earth
Error reading file shaders/text.vert: file not found
Error reading file shaders/text.frag: file not found
Error reading file shaders/text.vert: file not found
Error reading file shaders/text.frag: file not found
swapBuffers: Cannot find window 0x1e1390
swapBuffers: Cannot find window 0x1e1390
Segmentation fault
```

osgearth_qt5_windows
```
$ osgearth_qt5_windows /C/M/mingw-w64-osgearth-git/src/osgearth/tests/readymap-rex.earth
swapBuffers: Cannot find window 0x1a109a
QWidget::repaint: Recursive repaint detected
Segmentation fault
```

Both show black screen and segfault on exit.
This is with osg and osgEarth master, Qt 5.10.0 on msys2.

**Comment by gwaldron** [comment]
Thanks. No leads on this, but it won't hold up 2.9. We will probably end up following OSG's lead and remove QT examples from osgEarth after 2.9.

**Comment by filnet** [comment]
Ignore the previous post of mine. Was using an old version of osgQt.

I am trying to fix this issue as it happens in our Qt app where we would like to use the rex engine.
I am using osgearth_qt5_simple a test bed only...

Strange thing is that the Stats HUD is also "black" (i.e. it does not show up when pressing 's') when using osgearth_qt_simple.  But the Stats HUD is active, pressing 'S' gives some output:

```
Stats Viewer FrameNumber 399
    Event traversal begin time  12.6265
    Event traversal end time    12.6265
    Event traversal time taken  4.10524e-005
    Frame duration      0.0309367
    Frame rate  32.324
    Number of instanced Drawable        332
    Number of instanced Geode   18
    Number of instanced Geometry        18
    Number of instanced Group   433
    Number of instanced LOD     0
    Number of instanced Primitives      151844
    Number of instanced Stateset        22
    Number of instanced Switch  0
    Number of instanced Transform       298
    Number of instanced Vertices        86164
    Number of unique Drawable   332
    Number of unique Geode      18
    Number of unique Geometry   18
    Number of unique Group      433
    Number of unique LOD        0
    Number of unique Primitives 151844
    Number of unique StateSet   7
    Number of unique Switch     0
    Number of unique Transform  298
    Number of unique Vertices   86164
    Reference time      12.6265
    Rendering traversals begin time     12.6266
    Rendering traversals end time       12.6374
    Rendering traversals time taken     0.0108242
    Update traversal begin time 12.6265
    Update traversal end time   12.6266
    Update traversal time taken 2.14592e-005
    Stats Camera FrameNumber 399
        Cull traversal begin time       12.6289
        Cull traversal end time 12.6295
        Cull traversal time taken       0.000609877
        Draw traversal begin time       12.6296
        Draw traversal end time 12.6347
        Draw traversal time taken       0.00510139
        GPU draw begin time     12.6297
        GPU draw end time       12.6346
        GPU draw time taken     0.00496921
        Number of StateGraphs   5
        Number of ordered leaves        0
        Visible depth   0
        Visible number of GL_LINES      0
        Visible number of GL_LINE_LOOP  0
        Visible number of GL_LINE_STRIP 0
        Visible number of GL_POINTS     0
        Visible number of GL_POLYGON    0
        Visible number of GL_QUADS      0
        Visible number of GL_QUAD_STRIP 0
        Visible number of GL_TRIANGLES  292
        Visible number of GL_TRIANGLE_FAN       0
        Visible number of GL_TRIANGLE_STRIP     0
        Visible number of PrimitiveSets 50
        Visible number of drawables     37
        Visible number of fast drawables        18
        Visible number of impostors     0
        Visible number of lights        0
        Visible number of render bins   4
        Visible vertex count    620
```

The output shows that there is geometry.

And there is this thread : http://forum.osgearth.org/Report-The-latest-osgEarth-code-problem-td7590331.html#a7591477 where user ago says he got it working by "calling viewer.realize()", but he doesn't say where to call it from.
My understanding is that realize() is called automatically on the first frame. And our app calls realize() explicitly.

**Comment by filnet** [comment]
I got rex working with osgearth_qt5_simple.exe :

![image](https://user-images.githubusercontent.com/8101062/36351922-fc1de060-14b0-11e8-99a6-570ad73760f0.png)

I'll share later how I found the issue and the fix.

**Comment by filnet** [comment]
To track down the issue I tried to compare verbose logs of osgearth_viewer.exe and osgearth_qt5_simple.exe while displaying readymap.earth with mp or rex.
This led nowhere. 

Then using glintercept [1], I did the same with opengl call logs.
The logs showed that osgearth_qt5_simple.exe with readymap rex had a single call to glDrawBuffer(GL_NONE) and no later call to set the draw buffer to something else.
Running osgearth_qt5_simple.exe with readymap mp did not show this call.

The same behavior was exibhited by osgearth_viewer.exe, to the difference that later glDrawBuffer(GL_BACK) is called before each frame.

Anyways, the debugging session showed that the lone glDrawBuffer(GL_NONE) call originated from osgUtil::RenderStager::runCameraSetUp().
```
// If no color attachment make sure to set glDrawBuffer/glReadBuffer to none
// otherwise glCheckFramebufferStatus will fail
// It has to be done after call to glBindFramebuffer (fbo->apply)
// and before call to glCheckFramebufferStatus
if ( !colorAttached )
{
    setDrawBuffer( GL_NONE, true );
    setReadBuffer( GL_NONE, true );
    #if !defined(OSG_GLES1_AVAILABLE) && !defined(OSG_GLES2_AVAILABLE) && !defined(OSG_GLES3_AVAILABLE)
        glDrawBuffer( GL_NONE );
        glReadBuffer( GL_NONE );
    #endif
}
```
This section runs when the camera must render to an FBO and that FBO has no color buffer attached.
Seems to be there to make a specific opengl driver happy. Git history shows that this section is a minor war zone.
Commenting out the calls to glDrawBuffer and glReadBuffer was enough to get rex working with osgearth_qt5_simple.exe.

I need to check with OpenSceneGraph what to do with that.

I am also wondering why osgearth_qt5_simple.exe and osgearth_viewer.exe behave differently w/r to glDrawBuffer (double buffering ?).
And I could not find why/where rex uses an FBO but did not look very hard.


[1] https://github.com/dtrebilco/ : very simple to use to log opengl calls and more, windows only.

**Comment by filnet** [comment]
Adding the following snippet when configuring the camera (in osgEarthQt::ViewerWidget::reconfigure() for example) should workaround the issue:

```
GLenum buffer = _gc->getTraits()->doubleBuffer ? GL_BACK : GL_FRONT;
camera->setDrawBuffer(buffer);
camera->setReadBuffer(buffer);
```

**Comment by gwaldron** [comment]
Great sleuthing. Would you consider this ViewWidget update just a workaround, or the proper solution?

**Comment by filnet** [comment]
I think it is a workaround as it will have a limited scope.
It won't address OSX if it is suffering from a similar issue.

I also feel we should not mess with glDrawBuffer and not at this higher level.
The glDrawBuffer documentation [1] indicates that default setup should be fine in most cases (i.e. for single and double buffering).

Let's see what Robert has to say.

[1] https://www.khronos.org/registry/OpenGL-Refpages/gl4/html/glDrawBuffer.xhtml

**Comment by filnet** [comment]
Found another workaround.

This time it is in TileRasterizer. This camera attaches its color buffer dynamically (i.e. late...). This throws off the FBO completion test in RenderStage which triggers the issues. 

By attaching a dummy color buffer or asking RenderStage to create one for us, things fall back in order.

```
// attach dummy color buffer to workaround RenderStage's FBO completion tests
// note: what happens to it when the proper buffer is attached ? is memory properly reclaimed ?
osg::Texture2D *texture = new osg::Texture2D;
texture->setTextureSize(10, 10);
texture->setInternalFormat(GL_RGBA);
attach(COLOR_BUFFER, texture);
```
or
```
// ask RenderStage to create a color buffer for us
// note: what happens to it when the proper buffer is attached ? 
//setImplicitBufferAttachmentMask(0, 0);
setImplicitBufferAttachmentMask(IMPLICIT_COLOR_BUFFER_ATTACHMENT, 0);
```

Just this change alone fixes rex on qt. No need to have the ViewWidget one too.

Other cameras (ClampingTechnique, ...) probably have the same issue.

**Comment by gwaldron** [comment]
Good find ... still not clear why it happens but good to know. If it comes down it we can check in this workaround -- it doesn't seem to affect the operation of the TR.

**Comment by filnet** [comment]
The reason it happens is quite complex. It involves several wrongs in OSG leading to a right.
I'll submit my full analysis to OSG.

**Comment by filnet** [comment]
PS : the same issue potentially affects other osgEarth cameras.

All the cameras that call setImplicitBufferAttachmentMask(0, 0) are potentially affected.
By doing that you tell OSG not attach a color buffer for you if none is attached.
This then triggers this piece of code:
```
// If no color attachment make sure to set glDrawBuffer/glReadBuffer to none
// otherwise glCheckFramebufferStatus will fail
// It has to be done after call to glBindFramebuffer (fbo->apply)
// and before call to glCheckFramebufferStatus
if ( !colorAttached )
{
    setDrawBuffer( GL_NONE, true );
    setReadBuffer( GL_NONE, true );
    #if !defined(OSG_GLES1_AVAILABLE) && !defined(OSG_GLES2_AVAILABLE) && !defined(OSG_GLES3_AVAILABLE)
        glDrawBuffer( GL_NONE );
        glReadBuffer( GL_NONE );
    #endif
}
````
which messes up the draw buffer.

**Comment by filnet** [comment]
I have submitted my analysis of the issue to OSG. If it is accepted, I can then provide some fixes to OSG.

If these get through, we will be able to add a workaround to osgEarth that targets OSG < 3.5.10.

**Comment by filnet** [comment]
Ok. I am taking a break away from OSG and osgEarth. Don't know how to take this further.

**Comment by gwaldron** [comment]
Did you submit your analysis to OSG? Link please?

**Comment by filnet** [comment]
Yes, as a PR for sake of simplicity. Got shot down.
See "...added comment about draw buffer..." link above.
I am at a loss now and don't know how to proceed.

**Comment by filnet** [comment]
PS: the link https://github.com/filnet/OpenSceneGraph/commit/624ccadde4871673044aa101540e2bfc149ae0ab

**Comment by filnet** [comment]
And I have fix to submit too but I am afraid of having to go through a 3rd rebuttal.

**Comment by gwaldron** [comment]
Robert just posted this:
https://www.mail-archive.com/osg-users@lists.openscenegraph.org/msg76173.html

Is the answer then to add these set* calls to ViewWidget and ViewerWidget?

**Comment by filnet** [comment]
For the record and because my story started here ;

As a contributor to LibrePilot that integrates osgEarth, I wanted to test the new osgEarth rex engine on Qt.
I ran into an issue, but fortunately I'm not alone and end up here.
After quite some research and personal investment I come up with what I consider workarounds and describe them here.
Apparently the workarounds help others too.

I look more into the issue, think I found something, so open an issue on OSG's GitHub [[1]](https://github.com/openscenegraph/OpenSceneGraph/issues/486).
Issue gets closed within 24 hours with useful feedback.

I continue looking into the issue and want to share my findings as comments in the code.
So I submit a first pull request [[2]](https://github.com/openscenegraph/OpenSceneGraph/pull/489). Big mistake !
Closed within 24 hours with "words" from "openscenegraph".

Ok my bad... I continue looking into the issue and come up with some ideas for a fix.
This time, as told, I post a full length message to the forum and make proposals for a fix.
I create a second pull request with the fix proposals [[3]](url=https://github.com/openscenegraph/OpenSceneGraph/pull/493).
Again closed within 24 hours (great SLA btw) and I get shouted at. I am basically told go "fix your app".

Day after, a series of fixes similar to my proposed workaround are committed to OSG.
And an official message is posted to the forum [[4]](http://forum.openscenegraph.org/viewtopic.php?t=17132) informing all that "a user" has found an issue and describing the fix.
Why the formality ? Why the rush all of a sudden ? It is not as if the issue had any critical or life threatening implications.
Minor bug fixes never get that much honor from OSG. They usually just get committed. Puzzling...

And to finish, the killer, osgEarth then commits the official OSG fix to osgEarth.
osgEarth fully well knew the whole story as it unfolded under its eyes and regularly inquired about my progress.
Kinda bad cop / good cop situation here.

Not to mention that, the day before, osgEarth borrowed another PR of mine and committed it without due credit (the little credit I got was on my request).

Being replied to with words like "hack", "crap", "abuse" and being shouted at is not what I expect to get when contributing to an open source project.
Seems like "openscenegraph" is lacking basic courtesy and is treating its community in ways I have not seen elsewhere.

I'll continue to use OSG and osgEarth as both projects are great but will stay away from its community.

If you are a would be contributor, know that it can happen to you. I have witnessed it happen to other contributors too.

Cheers,
Philippe.

[1] https://github.com/openscenegraph/OpenSceneGraph/issues/486
[2] https://github.com/openscenegraph/OpenSceneGraph/pull/489
[3] https://github.com/openscenegraph/OpenSceneGraph/pull/493
[4] http://forum.openscenegraph.org/viewtopic.php?t=17132

**Comment by jasonbeverage** [comment]
Philippe,

Thank you for your hard work; your persistent efforts were instrumental in helping to track down this sticky issue. We greatly appreciate the contributions of time and talent to have helped make the osgEarth project successful and useful to so many people, and we regret that you've had a negative experience. It's not always easy, nor is the process always perfect, but we strive to maintain an inviting and active community for all members. We couldn't do it without you!
