### ISSUE TITLE
about sky extension 

### ISSUE THREAD

**Issue by qing222713** [gwaldron/osgearth#855]
i want to danamic add/remove sky effect 

void Map3DOptions::on_checkSky_stateChanged(int state) 
{ 
        if(m_sky == 0){ 
                m_sky = osgEarth::Extension::create("sky_simple", ConfigOptions()); 
        } 
        if(state == Qt::Checked){ 
                global->getMapNode()->addExtension(m_sky); 
        }else if(state == Qt::Unchecked){ 
                global->getMapNode()->removeExtension(m_sky); 
        } 
} 
but removeExtension not remove sky effect 
That is because the SimpleSkyExtension::disconnect method is unimplemented.

**Comment by qing222713** [comment]
thanks

**Comment by gwaldron** [comment]
Fixed
