### ISSUE TITLE
master: image layer caching (or readback) not functioning

### ISSUE THREAD

**Issue by gwaldron** [gwaldron/osgearth#856]
Repro:
enabled a cache;
run readymap.earth;
set cache only mode;
run readymap.earth

No imagery appears. Elevation may not work either; check that too.

**Comment by remoe** [comment]
Glenn, is this closed by this: https://github.com/gwaldron/osgearth/commit/618b6abd8a40c371b529be2c02eb9ed38b8ce693
?

**Comment by gwaldron** [comment]
I think it was solved before this, a long time back. Don't recall. In any case it works now.
