### ISSUE TITLE
osgdb_earth plugin does not show viewpoints

### ISSUE THREAD

**Issue by rhabacker** [gwaldron/osgearth#862]
The osgdb_earth plugin loads earth files in regular osg applications like osgviewer and other osg based viewers. Loading an earth file with with viewpoints like readymap.earth from osgearth/tests directory  with osgearth_viewer shows an ui in the left lower edge of the screen containing all viewpoints. Pressing the mentioned key or selecting an entry with the mouse jumps to the defined location. This does not works in case the mentioned earth file is loaded by the osgDB plugin system for example with osgviewer.

Looking at osgviewer source there is called  

    osg::ref_ptr<osg::Node> loadedModel = osgDB::readRefNodeFiles(arguments);

to read node files while osgearth_viewer uses 

  osg::Node* node = MapNodeHelper().load(arguments, &viewer);

Inspecting that methods shows that viewpoints are handled inside this function and not in the osgdb_earth plugin.

It would be nice to have viewpoint handling in osgdb_earth plugin to be usable with other osg based viewers. 

This issue has been also recognized with osgopenvrviewer  https://github.com/ChrisDenham/osgopenvrviewer

**Comment by remoe** [comment]
Hi, viewpoints are handled by the viewpoint extension:
https://github.com/gwaldron/osgearth/tree/master/src/osgEarthDrivers/viewpoints

**Comment by rhabacker** [comment]
sure, but the ui part of the viewpoint extension needs to be initialized by calling bool ViewpointsExtension::connect(Control* control) which is called from MapNodeHelper::parse() (see https://github.com/gwaldron/osgearth/blob/master/src/osgEarthUtil/ExampleResources.cpp#L618) in case of running osgearth_viewer, but not from ReaderWriterOsgEarth::readNode(std::istream& in, const osgDB::Options* readOptions) when loaded from the osgdb_earth plugin.

**Comment by gwaldron** [comment]
This is by design. The earth plugin loads the earth file but will not create and of the built-in UI elements that Extensions support. The ViewpointsExtension and its simple UI really only exist to support the osgEarth sample apps like osgearth_viewer. If you want to use readNode and want to invoke the sample UIs, you can just create a MapNodeHelper and call parse().

**Comment by rhabacker** [comment]
How should this work with osgviewer ? This would require to link osgviewer against osgearth and to implement a special hack to deal with earth files ? 
Do you think that this will be accepted by the osg maintainers ?

In the opposite moving the mentioned ui initialization into osgdb_earth plugin could be used by the osgearth_viewer also.

**Comment by gwaldron** [comment]
No, I am quite sure that the OSG maintainer will not accept such a contribution.

I don't quite understand why you want all this to work in osgviewer instead of just using osgearth_viewer. The whole reason that osgearth_viewer exists is to be able to use osgEarth-specific things like the UI controls, EarthManipulator, and command-line extensions.

**Comment by rhabacker** [comment]
I mentioned osgviewer as example. You can think of any additional available viewer or viewer example as there are flightgear viewer, osg openvr viewer and osg oculus rift viewer or any osg based application.

Imagine you got a HTC Vive for something like playing your prefered VR app like Google Earth or any other vr application. While being impressed by the new possibilities you recognize that it might be a good for presentation purpose to show osgearth examples with this head set and also for presentation purpose it would also be good to have viewable viewpoints in the scene.

Now you have two choices: 
1. you can implement openvr support directly into osgearth viewer which needs to be maintained by you or 
2. you can take a look if there is already such a viewer available

Fortunally there is already an osg based openvr viewer (see link above), so you simply run viewerexample readymap.earth osgopenvr build. 

But on running you do not see the viewpoints because osgopenvr viewer does not support them. 
Okay you add osgearth as dependency to osgopenvr and patch viewerexample  to use MapNodeHelper::load from osgearth library to see viewpoints. So far so good. 

Then you are contacting the osgopenvr maintainer to include your patch and osgearth dependency to have viewpoints ui support into osg vr viewer. Would that work ?

In the opposite having viewpoints UI support in osgdb_earth plugin would support the mentioned use case out of box. No need to integrate vr support in osgearth_viewer, no need to patch osgopenvr viewer; you can choose whatever client application to have usable viewpoints.
