### ISSUE TITLE
missing osgEarthUtil/DetailTexture

### ISSUE THREAD

**Issue by ningfc** [gwaldron/osgearth#864]
missing osgEarthUtil/DetailTexture
not make osgearth_detailtex and osgearth_verticalscale

**Comment by gwaldron** [comment]
osgEarth version?

**Comment by ningfc** [comment]
master branch

**Comment by gwaldron** [comment]
That file was removed; the replacement is the DetailExtension plugin. Please do a full cmake/rebuild.
