### ISSUE TITLE
Support GEOS 3.6.x

### ISSUE THREAD

**Issue by gwaldron** [gwaldron/osgearth#867]
There are compile errors with osg master and 2.8. Support the latest GEOS.

**Comment by filnet** [comment]
i submitted a PR fpr addressing this issue.

**Comment by filnet** [comment]
And a more universal PR was submitted : https://github.com/gwaldron/osgearth/pull/899

**Comment by remoe** [comment]
I've tested the latest master with GEOS 3.6.1 on MacOSX. It compiles.

**Comment by gwaldron** [comment]
Sounds like this is working
