### ISSUE TITLE
Draped polygons render issue (osgEarth master / MP only)

### ISSUE THREAD

**Issue by remoe** [gwaldron/osgearth#897]
I've tested OSG latest 3.5.6 master with osgEarth master (c80bc10f8c2d14220020e65773b9da2da19c808c) on Win64 and also with MacOSX Core Profile. I see the following issue with stock example "feature_draped_polygons.earth" https://github.com/gwaldron/osgearth/blob/master/tests/feature_draped_polygons.earth:

![image](https://cloud.githubusercontent.com/assets/804941/24495281/ea10ed30-1534-11e7-9255-7d2aa4f8e8db.png)

**Comment by remoe** [comment]
I've tested it now also with OSG 3.4. It has the same issue!

**Comment by gwaldron** [comment]
Remo, I am not able to duplicate the problem here with OSG 3.4 and osgEarth master. Are you doing a GL3 build in Windows too?

**Comment by remoe** [comment]
No, i use default settings.

**Comment by remoe** [comment]
Glenn, I use the mp-engine not rex.

**Comment by remoe** [comment]
Works on https://github.com/gwaldron/osgearth/commit/208ab3d922c6fbca5844ace4379f62d7d51b7255

**Comment by gwaldron** [comment]
Note to self - only occurs with MP - Rex is fine
