### ISSUE TITLE
GeoPoint::createLocalToorld with AltitudeMode = RELATIVE_TO_TERRAIN Error

### ISSUE THREAD

**Issue by remoe** [gwaldron/osgearth#906]
If one runs:

```
osgearth_viewer tests/feature_occlusion_culling.earth
```

It throws:

```
[osgEarth]* [GeoPoint] ILLEGAL: called GeoPoint::createLocalToorld with AltitudeMode = RELATIVE_TO_TERRAIN
``` 

Tested with MacOSX, OSG 3.5.6 and osgEarth: https://github.com/gwaldron/osgearth/commit/208ab3d922c6fbca5844ace4379f62d7d51b7255

and also on Windows x64, OSG 3.4, osgEarth Master

**Comment by gwaldron** [comment]
Patched.
