### ISSUE TITLE
osgEarthDrivers xyz

### ISSUE THREAD

**Issue by denistu** [gwaldron/osgearth#907]
message:
> DynamicLibrary::failed loading "osgPlugins-3.5.6/mingw_osgdb_106&lyrs=s&x=3&y=0&z=2.dll

the url is http://mt.google.com/vt/v=ap.106&lyrs=y&x=${x}&y=${y}&z=${z}
profile provided, <profile>spherical-mercator</profile>

environment:
windows 10
msys64
OpenSceneGraph/master
osgQt/master
osgEarth/master

PS: openstreetmap with xyz driver works fine

**Comment by denistu** [comment]
log from OSGEARTH_NOTIFY_LEVEL=DEBUG

[osgEarth]  [ImageLayer] "google_hybrid" create image for "3/4/5", ext= SW=0,-10018754.1714 NE=5009377.0857,-5009377.0857, SRS=Mercator CS
[osgEarth]  [XYZ driver] URI: http://mt.google.com/vt/v=ap.106&lyrs=y&x=4&y=5&z=3, key: 540/6d4/78
[osgEarth]  
Host name = mt.google.com
Url path = /vt/v=ap.106&lyrs=y&x=4&y=5&z=3
Port = 50
[osgEarth]  [URI] Got remote result for http://mt.google.com/vt/v=ap.106&lyrs=y&x=4&y=5&z=3
[osgEarth]  Added 3/4/5 to blacklist
[osgEarth]  [ImageLayer] "google_hybrid" 3/4/5result INVALID

**Comment by jasonbeverage** [comment]
The ampersands are screwing up the XML encoding.  You need to use CDATA in your URL definition like this
```
<url><![CDATA[http://mt.google.com/vt/v=ap.106&lyrs=y&x=${x}&y=${y}&z=${z}]]></url>
```

All that being said, please be aware of the Google Earth terms of service, you definitely can't use that layer for anything in production.

**Comment by denistu** [comment]
i have to notice that if i build osgearth with curl, not with wininet, then google maps work
so the problem seems to be in the part of osgearth which uses wininet

**Comment by gwaldron** [comment]
Please note that the WININET support is experimental and not fully implemented.
