### ISSUE TITLE
MacOSX -- dynamic_cast error.  VERTEX glCompileShader "oe_terrain_SDK_mp_VS" FAILED.

### ISSUE THREAD

**Issue by JIabao1** [gwaldron/osgearth#917]
OSG master
osgearth master
Environment: 
MacBook Pro (Retina, 13-inch, Mid 2014)
macOS Sierra 10.12.4 (16E195)

errors:

osgearth_viewerd[69855:10712897] dynamic_cast error 1: Both of the following type_info's should have public visibility.  At least one of them is hidden. NSt3__115basic_streambufIcNS_11char_traitsIcEEEE, N3osg18NotifyStreamBufferE.
Error reading file osgearth_viewer: file not handled
_forceVertexArrayObject = 0
_forceVertexBufferObject = 0
ViewerBase::configureAffinity() numProcessors=4
  databasePagers = 1
_forceVertexArrayObject = 0
_forceVertexBufferObject = 0
VERTEX glCompileShader "oe_terrain_SDK_mp_VS" FAILED
VERTEX Shader "oe_terrain_SDK_mp_VS" infolog:
ERROR: 0:1: '' :  version '330' is not supported

FRAGMENT glCompileShader "oe_terrain_SDK_mp_FS" FAILED
FRAGMENT Shader "oe_terrain_SDK_mp_FS" infolog:
ERROR: 0:1: '' :  version '330' is not supported

VERTEX glCompileShader "main(vertex)" FAILED
VERTEX Shader "main(vertex)" infolog:
ERROR: 0:1: '' :  version '330' is not supported
ERROR: 0:1: '' : syntax error: #version
WARNING: 0:3: extension 'GL_ARB_gpu_shader5' is not supported
ERROR: 0:17: ';' : syntax error: Uniform blocks may not have identifiers in GLSL 140

FRAGMENT glCompileShader "main(fragment)" FAILED
FRAGMENT Shader "main(fragment)" infolog:
ERROR: 0:1: '' :  version '330' is not supported
ERROR: 0:1: '' : syntax error: #version
WARNING: 0:3: extension 'GL_ARB_gpu_shader5' is not supported
ERROR: 0:14: ';' : syntax error: Uniform blocks may not have identifiers in GLSL 140

glLinkProgram 0x105030d40"" FAILED
Program "" infolog:
ERROR: One or more attached shaders not successfully compiled

VERTEX glCompileShader "oe_mp_vertModel" FAILED
VERTEX Shader "oe_mp_vertModel" infolog:
ERROR: 0:1: '' :  version '330' is not supported
ERROR: 0:1: '' : syntax error: #version

VERTEX glCompileShader "oe_mp_vertView" FAILED
VERTEX Shader "oe_mp_vertView" infolog:
ERROR: 0:1: '' :  version '330' is not supported
ERROR: 0:1: '' : syntax error: #version

FRAGMENT glCompileShader "oe_mp_apply_coloring" FAILED
FRAGMENT Shader "oe_mp_apply_coloring" infolog:
ERROR: 0:1: '' :  version '330' is not supported
ERROR: 0:1: '' : syntax error: #version

VERTEX glCompileShader "main(vertex)" FAILED
VERTEX Shader "main(vertex)" infolog:
ERROR: 0:1: '' :  version '330' is not supported
ERROR: 0:1: '' : syntax error: #version
WARNING: 0:3: extension 'GL_ARB_gpu_shader5' is not supported
ERROR: 0:25: ';' : syntax error: Uniform blocks may not have identifiers in GLSL 140

FRAGMENT glCompileShader "main(fragment)" FAILED
FRAGMENT Shader "main(fragment)" infolog:
ERROR: 0:1: '' :  version '330' is not supported
ERROR: 0:1: '' : syntax error: #version
WARNING: 0:3: extension 'GL_ARB_gpu_shader5' is not supported
ERROR: 0:18: ';' : syntax error: Uniform blocks may not have identifiers in GLSL 140

glLinkProgram 0x10e930750"osgEarth.engine_mp.TerrainNode" FAILED
Program "osgEarth.engine_mp.TerrainNode" infolog:
ERROR: One or more attached shaders not successfully compiled

**Comment by gwaldron** [comment]
You may have an old driver. Please post the output of
osgearth_version --caps

**Comment by JIabao1** [comment]
Run 'application_osgearth_viewer' with any of the '*.earth' in tests file, will get the error.

osg: 3.5.1 release.

'osgearth_version' is osgEarth Library 2.9.0 DEVELOPMENT。
 I got the same error when I use 'osgEarth Library 2.8.0'。

**Comment by remoe** [comment]
I don't have any such issues with Sierra MacOSX. Use newer OSG.

**Comment by JIabao1** [comment]
Thank you! I got the same error with newer OSG(3.5.3), osgearth(2.8.0). Could you please tell me your MAC , the OSG and osgearth version? 
 And I use OSG(3.4.0) ,osgearth(2.7.0),there will be no error,but when I run the tests (ocean.earth,boston_buildings.earth...) it  load image anomalies.
