### ISSUE TITLE
master: Rex engine not building with master OSG

### ISSUE THREAD

**Issue by MCA4213** [gwaldron/osgearth#920]
I have downloaded the latest OSG and osgEarth on 31 June 2017, and I have some compilation errors on the rex engine, more precisely at "TileDrawable.cpp"

`    
    f.begin(GL_TRIANGLES);
    for(int t=0; t<_tileSize-1; ++t)
    {
        for(int s=0; s<_tileSize-1; ++s)
        {
            int i00 = t*_tileSize + s;
            int i10 = i00 + 1;
            int i01 = i00 + _tileSize;
            int i11 = i01 + 1;

            f.vertex(_mesh[i00]);  f.vertex(_mesh[i10]);  f.vertex(_mesh[i01]);
            f.vertex(_mesh[i01]);  f.vertex(_mesh[i10]);  f.vertex(_mesh[i11]);
        }
    }

    f.end();`

The errors are: 
Error	C2039	'begin': is not a member of 'osg::PrimitiveFunctor'	Plugin osgearth_engine_rex		124	
Error	C2039	'vertex': is not a member of 'osg::PrimitiveFunctor'	Plugin osgearth_engine_rex		134	
Error	C2039	'vertex': is not a member of 'osg::PrimitiveFunctor'	Plugin osgearth_engine_rex		135	
Error	C2039	'end': is not a member of 'osg::PrimitiveFunctor'	Plugin osgearth_engine_rex		139	

By comparing the old "osg/PrimitiveSet" with the new ones, these virtual functions have been removed from the "PrimitiveFunctor" class.

**Comment by gwaldron** [comment]
Should be fixed now. Thanks. OSG 3.5.6 got rid of the begin/vertex/end paradigm.
