### ISSUE TITLE
How to set the scale (1:1000, 1:5000, 1:10000 etc)?

### ISSUE THREAD

**Issue by dmitriano** [gwaldron/osgearth#924]
Hello! 
It is not a bug report, but some newbie question. If anyone can answer, it will same some time for me.

There is a function in osgEarth

void osgEarth::Util::EarthManipulator::setDistance( double distance);

that sets the distance between the camera and the base of the normal to the surface of the earth (as far as I can see). Also there is a function

void osgEarth::Util::EarthManipulator::zoom(double dx, double dy);

that increments the distance by dy (as far I can guess). Obviously there is some dependence between the distance and the scale that probably is defined by 4x4 matrix, so I can change the scale changing the distance.

But it is not clear, is there a way to set the scale not in terms of the distance to the camera, but in terms of 1:1000, 1:5000, 1:10000 etc (as on usual paper charts)? (Assuming I see the Earth as 2D surface, in 3D there can be various definitions of what scale is, but for example, it can be some approximation of the nearest area of the Earth surface).

**Comment by gwaldron** [comment]
Hi, osgEarth doesn't have any code to work with map scales. You will need to calculate the conversion from map scale to distance yourself. Map scale is not usually in terms of camera distance -- it usually represents the ratio of real world space to space on your physical screen. (e.g., one mile = one centimeter).
