### ISSUE TITLE
RTTPicker and multi-view

### ISSUE THREAD

**Issue by valladis** [gwaldron/osgearth#929]
RTTPicker crashes as a result of using bad/invalidated `Pick::_context` pointer in its _picks member caused by a resize of `std::vector<PickContext>` upon a new view joining the picking. I guess that draining the _picks just before a call to `_pickContexts.push_back( PickContext() );` (at line 152) could help resolving that issue. (other option would require using different type of referencing).
In multi-view environment a need to remove the PickContext associated with the destroyed view is also quite legitimate (In such case draining _picks will also help)

**Comment by gwaldron** [comment]
Thanks, this makes sense. In your opinion, could we also resolve the issue by replacing std::vector with a container like std::list or std::set that does not invalidate iterators upon insertion?

**Comment by valladis** [comment]
That would be even better ;)
Thanks.

**Comment by gwaldron** [comment]
done; please test ;)
