### ISSUE TITLE
How can I get elevation more efficient?

### ISSUE THREAD

**Issue by JiaoJianing** [gwaldron/osgearth#932]
I tried to get elevation of a random GEO position. I used osgEarth::ElevationQuery and called getElevation. It gave me a perfect result.
  But when I execute a query each frame(I want high precision datas to improve some effects), I realized that it takes a little bit time and cause frame rate reduce.
  Any way else? Thanks!

**Comment by gwaldron** [comment]
You can try using map->getElevationPool()->getElevation. This returns a "Future" object and runs the elevation query asynchronously. You can call isAvailable() to see when the result is ready.

**Comment by JiaoJianing** [comment]
Hi,I tried that function.But the returns elevation will always be NO_DATA_VALUE.I'm sure that my elevation layer worked well and I used valid lon lat values.

**Comment by gwaldron** [comment]
ElevationPool queries at a specific LOD, and by default tries to use the highest LOD. Try a lower LOD. Querying elevation data every frame at the maximum LOD is very expensive since the terrain engine needs to fetch the data from the data source and query it.
