### ISSUE TITLE
Does osgEarth support Mercator projection?

### ISSUE THREAD

**Issue by dmitriano** [gwaldron/osgearth#934]
Hello!
Sorry for disturbing you, but I have yet another newbie question that I cannot find the answer to.
Does osgEarth support Mercator projection somehow? If not, how difficult it is to add the Mercator projection support, and what needs to be changed for this? At least I afraid that I need to write my own OpenGL shaders...
What does it mean that the source file 'osgEarth/Mercator.cpp' is completely commented out?

**Comment by jasonbeverage** [comment]
We definitely support the mercator projection.  Those are just some old
files that are no longer used.  I removed them from the repo.
