### ISSUE TITLE
feature_custom_filters.earth broken

### ISSUE THREAD

**Issue by beachwalker** [gwaldron/osgearth#940]
Feature custom filters is broken for sample: [osgEarth]* [FeatureFilterRegistry] Failed to load FeatureFilter driver "change_attribute"

The countries are not rendered.

![image](https://user-images.githubusercontent.com/2715897/28306513-d827172c-6b9f-11e7-86d1-3747e57ea525.png)

**Comment by remoe** [comment]
Other filters are rewritten to "REGISTER_OSGPLUGIN". Does "OSGEARTH_REGISTER_SIMPLE_FEATUREFILTER" not work any more?

**Comment by gwaldron** [comment]
Not a bug. You must run this example with osgearth_featurefilter.exe.
