### ISSUE TITLE
feature_xyz driver does not refresh on zoom/pan for new tiles

### ISSUE THREAD

**Issue by beachwalker** [gwaldron/osgearth#942]
I found the xyz driver for features (feature_xyz) and I was able to connect that to a GeoServer using this earth file feature:

    <model name="States" driver="feature_geom">
        <features name="states" driver="xyz">
            <url>http://141.200.19.174:8080/geoserver/gwc/service/tms/1.0.0/opengeo%3Acountries@EPSG%3A4326@geojson/{z}/{x}/{y}.geojson</url>           
			<format>json</format>
			<profile>global-geodetic</profile>
			<min_level>0</min_level>
			<max_level>14</max_level>
        </features>
        <styles>        
            <style type="text/css">
                states {
                   stroke:            #ffff00;
                   stroke-opacity:    1.0;
                   stroke-width:      3.0;
                   altitude-clamping: terrain-drape;
                }                       
            </style>
        </styles>
    </model>

Sadly, the data is not refreshed if the globe is rotated or zoomed in. So only the half globe is rendered.

![image](https://user-images.githubusercontent.com/2715897/28581779-7fe39dbe-7163-11e7-9752-7aa2c18ec25b.png)

**Comment by beachwalker** [comment]
... also tried different min/max_level settings which makes the rendered part smaller. It looks like not all tiles are rendered even though other applications (openlayers etc.) have no problems with that data.

**Comment by gwaldron** [comment]
Is this still an issue?
