### ISSUE TITLE
How to create a zoom view showing the same nodes with different scale?

### ISSUE THREAD

**Issue by dmitriano** [gwaldron/osgearth#946]
Sorry for asking newbie questions here, but I hope the answer will not take a long time.

I am working on a QT application that uses osgEarth::QtGui::ViewerWidget in its main window with the map node and some custom nodes and geometries that are shown above the map node. It creates its root node with the following code (I omitted details):
`    
    rootNode_ = new osg::Group;

    viewer_ = new osgViewer::Viewer;
    viewer_->setSceneData(rootNode_);    

    osg::ref_ptr<osg::Node> earthNode = osgDB::readNodeFile(earthFilePath.toUtf8().data());
    mapNode_ = osgEarth::MapNode::findMapNode(earthNode);
    rootNode_->addChild(earthNode.get());

    viewerWidget_ = new osgEarth::QtGui::ViewerWidget(viewer_.get());
`
For the experiment, I created another window containing ViewerWidget initialized in the same way, except that I reuse rootNode_ from the main view (or window). 

`
    viewer_ = new osgViewer::Viewer;
    viewer_->setSceneData(rootNode_);
    viewerWidget_ = new osgEarth::QtGui::ViewerWidget(viewer_.get());
`
My idea is to show the same node tree in other view (zoom view) with different projection (or at least viewpoint). Surprisingly, zoom view shown me the Earth with the custom nodes with a small distortion, but, as I expected, I crashes repeatedly in osg/src/osgText/Text.cpp:

`
   if ( !_textureGlyphQuadMap.empty() )
    {
        const GlyphQuads& glyphquad = (_textureGlyphQuadMap.begin())->second;
        if ( glyphquad._transformedCoords[contextID]->empty() )
        {
            computePositions(contextID);
        }
    }
`
and I have an impression that something is wrong with contextID, because zoom window has different OpenGL context.

The question: is this use case implied? Or probably there is a better way to create zoom view?

**Comment by gwaldron** [comment]
Try using ViewWidget and sharing the GL context.

**Comment by dmitriano** [comment]
I had some kind of success with the latest version of osgEarth, that does not crash in osg/src/osgText/Text.cpp, at least I was able to see multiple windows (QGLWindget-s) with the same nodes. Now I am trying to figure out, should I share a single map node between multiple windows, or there should be a separate map node for each window? At least at the moment, there are back holes on the map in zoom (or not main) windows with Open Street Map format, so I think that multiple map nodes is a better solution?

**Comment by gwaldron** [comment]
You can share a single MapNode among multiple Views in a osgViewer::CompositeViewer. (It's OK for each View being in a separate window.) However you cannot share a single MapNode (or any other node, really) among multiple separate osgViewer::Viewer instances. That usually results in OSG losing track of GPU resources, and the "black tiles" that you describe are a common symptom of that.

**Comment by dmitriano** [comment]
This technique with osgViewer::CompositeViewer works in OSG 3.4 and OsgEarth 2.8, at least I succeeded with showing Open Street Map in multiple windows. In OSG 3.3.9 and OsgEarth 2.7 this code crashes. Thank you for your help!
