### ISSUE TITLE
Dynamical loading of resources

### ISSUE THREAD

**Issue by JeyDee** [gwaldron/osgearth#951]
I was tasked with writing a visualizer for large 3D areas, the kind of areas that do not fit into RAM. This requires constant loading and unloading of resources, depending on where the camera is looking.

I was wondering if there are mechanisms within OSG or OSG Earth that already supports this? Or is it a thing that I would have to implement myself from scratch?

**Comment by gwaldron** [comment]
Yes, osgEarth does this automatically by way of terrain tiles. When a tile is no longer in view, it is a candidate for unloading from memory ("paging out"). So all you need to do is configure your data sources and osgEarth will take care of the rest. Hope this helps.

**Comment by JeyDee** [comment]
Thanks! I did some reading and found out about osg::PagedLOD and osgDB::DatabasePager. But how does it work if I need to reload data in a format that is not already supported out of the box?

**Comment by remoe** [comment]
You need to write a custom driver for osgEarth like: https://github.com/gwaldron/osgearth/tree/master/src/osgEarthDrivers/feature_ogr

**Comment by JeyDee** [comment]
Thanks. Can you tell me more about the context behind that? How does a Driver interact with a PagedLOD and a DatabasePager?

**Comment by remoe** [comment]
For this you need to study the source code, or someone has time to explain this :) For example:

https://github.com/gwaldron/osgearth/blob/master/src/osgEarthFeatures/FeatureModelGraph.cpp

**Comment by JeyDee** [comment]
If nearly 2000 lines of code are a starting point, I don't want to see the additional literature ;). See, my intention is to figure out how get OSG Earth to visualize large point clouds. I'm trying to get a grasp of how it may work, but it's quite hard to do so without spending weeks reading source code.

I would really appreciate if somebody would give me the hints I need to solve that task. Just point me out the way I have to go (which modules I would have to implement) to get a point cloud visualization and I would be happy to go it on my own. It's something the community could profit from if I succeed.

**Comment by remoe** [comment]
After the osgearth forum is back, you can post this question on https://forum.osgearth.org. One should only post bugs here, not questions.

**Comment by JeyDee** [comment]
So the Issue Tracker is only for bugs, not for issues ;)? I would also prefer the forum, but I don't have any clue when it comes back and I'm afraid I'm on a timetable, so posting here was a logical conclusion. I still would appreciate it very much if someone could invest 5 minutes to help me solve my problem.

**Comment by jasonbeverage** [comment]
Hi Jey!

We actually have a solution for streaming massive points clouds that we've developed here at Pelican Mapping called Juniper.  You can see it in action here:  https://youtu.be/lUeF4Y8yGNI

If you're interested in potentially using Juniper we'd be happy to chat with you about it!

Jason
