### ISSUE TITLE
ON_DEMAND mode not working on master

### ISSUE THREAD

**Issue by remoe** [gwaldron/osgearth#952]
I've tested with osgEarth (https://github.com/gwaldron/osgearth/commit/8c792176c9e68a1ece222ec75686695750c4e3bb), OSG 3.5.6, readymap.earth and adding:

`viewer.setRunFrameScheme(osgViewer::ViewerBase::ON_DEMAND);`

**Comment by gwaldron** [comment]
Are you using REX or MP? ON_DEMAND does not work with the REX engine.

**Comment by remoe** [comment]
I use MP.

**Comment by gwaldron** [comment]
A quick look reveals that the TerrainEngineNode activates an update traversal for processing callbacks. This is the likely (first) culprit and I'll take a closer look at doing this different ways when I get a moment.

**Comment by remoe** [comment]
Ok, great! It would also be great when the future terrain rendering engine REX would also support ON_DEMAND rendering because it's better the CPU runs on very low power when no background work must be done.
