### ISSUE TITLE
Geocentric SRS support

### ISSUE THREAD

**Issue by jasonbeverage** [gwaldron/osgearth#954]
osgEarth doesn't support "native" geocentric srs's (epsg:4978).  A few things need to be done for this to work:

1)  Change it so _is_ecef calls OGRIsGeocentric to get the value from gdal
2)  Change it so transformXYZPointArrays takes in a z array as well

These are pretty trivial changes but need to be handled with care to make sure nothing breaks.

**Comment by gwaldron** [comment]
wontfix
