### ISSUE TITLE
gl_LightSource[0] not accessible with openGL Core Profile

### ISSUE THREAD

**Issue by mathieu** [gwaldron/osgearth#964]
https://github.com/gwaldron/osgearth/blob/6330374fecc78d54222f8abb4397413f3ae95d65/src/osgEarthUtil/Shadowing.frag.glsl#L64

It seems the fragment shader for shadows needs some refactoring to use the same inputs as the PhongLigthingEffect in terms of use of the OE_LIGHTING #define and access to the osg_LightSource uniforms...

**Comment by gwaldron** [comment]
fixed in e72f159
