### ISSUE TITLE
[clang sanitizer] Thread data-race on osgEarth::SpatialReference

### ISSUE THREAD

**Issue by remoe** [gwaldron/osgearth#970]
In TerrainLayer::getDataExtentsUnion()

**Thread 1 write** 

_dataExtentsUnion = e;

This calls osgEarth::GeoExtent::operator=

and this calls 

```
osg::ref_ptr<osgEarth::SpatialReference const>::assign<osgEarth::SpatialReference const>(osg::ref_ptr<osgEarth::SpatialReference const> const&) 
```

**Thread 2 Read**

osgEarth::GeoExtent::isValid()

and this calls 

```
osg::ref_ptr<osgEarth::SpatialReference const>::valid()
```

This is a OSG ref_ptr issue.

Thoughts?

**Comment by remoe** [comment]
It's not a OSG issue, ref_ptr is not designed to be thread safe.  osg::Referenced is thread safe.

**Comment by gwaldron** [comment]
Are you getting a crash somewhere?

**Comment by remoe** [comment]
no

**Comment by remoe** [comment]
not an issue?
