### ISSUE TITLE
Rex: Texture sampler shader composition error

### ISSUE THREAD

**Issue by omaralvarez** [gwaldron/osgearth#978]
I am having issues with a 2D sampler in a custom fragment shader that is injected with the following:

```
#pragma vp_entryPoint  fragment
#pragma vp_location    fragment_lighting
#pragma vp_order       1.0

uniform sampler2D projectionMap;
in vec2 texCoord;

void fragment(inout vec4 color)
{

    // Get texels from 2D texture
    color =  texture2D(projectionMap, texCoord);

}
```

This shader works well with the MP engine. Here is an image of what is happening:

![rex_error](https://user-images.githubusercontent.com/5764407/30744650-52e5fd8e-9fa3-11e7-8a6e-a69dc7079093.png)

It looks like the texture is not been sampled correctly, it should not be black.

Any idea about what could be the cause of this?

**Comment by gwaldron** [comment]
Not much to go on here, but the first thing I would check is that you don't have a texture image unit conflict. How are you selecting the texture image unit to use for your projected texture? Make sure to use the MapNode::getTerrainEngine()->getResources() API to reserve one that is not in use by osgEarth.

**Comment by omaralvarez** [comment]
Thanks for the response, I was definitely not using the getResources API, so I will look into that ASAP and report my findings.

**Comment by gwaldron** [comment]
Did this resolve the issue?

**Comment by omaralvarez** [comment]
I finally had time to test this possible fix. Even when using:

```cpp
int texUnit = -1;
mapNode->getTerrainEngine()->getResources()->reserveTextureImageUnit(texUnit);

...

ss->setTextureAttributeAndModes(texUnit, texture, osg::StateAttribute::ON);
// set up tex gens
ss->setTextureMode(texUnit, GL_TEXTURE_GEN_S,
                       osg::StateAttribute::ON);
ss->setTextureMode(texUnit, GL_TEXTURE_GEN_T,
                       osg::StateAttribute::ON);

osg::Uniform* texUniform = new osg::Uniform(osg::Uniform::SAMPLER_2D, "projectionMap");
texUniform->set(texUnit);
ss->addUniform(texUniform);
```
Looks like texture is being rewritten:

![test](https://user-images.githubusercontent.com/5764407/50981651-bf47a080-14fb-11e9-9434-eda5fdf6f2bf.png)

**Comment by omaralvarez** [comment]
I found the issue:

```cpp
texUniform->set(texUnit);
```

`texUnit`is not working properly, I'm guessing it is due to `texUniform->set()` expecting an `int`. Really weird behaviour...
