### ISSUE TITLE
Error compiling OSGearth 2.7

### ISSUE THREAD

**Issue by samtux** [gwaldron/osgearth#980]
As a dependency of the Globe plugin of QGIS, it requires OSGearth v2.7, but generates an error with compilation:

https://gist.github.com/samtux/5434adf8496b002b58c9e4b2c06c3a55

The OS is Arch Linux x64. The version of GESO is v3.6.2. The instructions of compilation is:

https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=osgearth-qt4

Thanks.

**Comment by gwaldron** [comment]
You probably need to use an older version of GDAL/OGR. Which version are you using?

**Comment by samtux** [comment]
@gwaldron The GDAL/OGR version is the most recent.
```
[samtux@ultrabook ~]$ gdalinfo --version
GDAL 2.2.1, released 2017/06/23
```

Thanks

**Comment by gwaldron** [comment]
Right; I believe you may need a 1.x version of GDAL for OE 2.7.

**Comment by samtux** [comment]
Thanks @gwaldron , I will close the issue, because it is due to the version of GDAL. It is time to wait until QGIS supports the Globo plugin until the new version of OSGearth.

**Comment by landryb** [comment]
@samtux: fwiw globe plugin builds fine against osgearth master, the build failure you were seeing has been solved in https://github.com/gwaldron/osgearth/commit/6a3f724e3a19aa53ba7af40bcbce7e1e19477a8e
