### ISSUE TITLE
GDAL Driver: better error reporting for VRT problems

### ISSUE THREAD

**Issue by gwaldron** [gwaldron/osgearth#982]
The "read all files in folder" feature is not very good at reporting errors, like then files have differing projections/palettes/resolutions/etc. Need to improve that.

**Comment by jasonbeverage** [comment]
I'd prefer just removing the file of folders feature in the GDAL driver in favor of creating VRTs manually.  It would clean up the driver quite a bit and make it less error prone to GDAL versions.

**Comment by gwaldron** [comment]
Agreed - done for 3.0.
